add_ghostFromFiner – Treelm
add_ghostFromFiner Subroutine
37 statements
Source File
private recursive subroutine add_ghostFromFiner(elemID, levelDesc, minLevel, tree, updated, foundPos, stencil)
Add parentID as GhostFromFiner. Then set its BC from its children. If any children do NOT exist, recursively call this routine to add them as GhostFromFiner.
Arguments
Type Intent Optional Attributes Name
integer(kind=long_k), intent(in) :: elemID
requested treeID
type(tem_levelDesc_type), intent(inout) :: levelDesc(minLevel:)
the level descriptor to be filled
integer, intent(in) :: minLevel
minimum level fluid element in the tree
type(treelmesh_type), intent(in) :: tree
tree information
logical, intent(out) :: updated
was the current element updated in this call?
integer, intent(out) :: foundPos
type(tem_stencilHeader_type), intent(in) :: stencil
current stencil definition
Calls
Called by
Source Code
  recursive subroutine add_ghostFromFiner( elemID, levelDesc, minLevel,     &
    &                                      tree, updated, foundPos, stencil )
    ! -------------------------------------------------------------------- !
    !> requested treeID
    integer(kind=long_k), intent(in) :: elemID
    !> minimum level fluid element in the tree
    integer, intent(in) :: minLevel
    !> the level descriptor to be filled
    type(tem_levelDesc_type), intent(inout) :: levelDesc(minLevel:)
    !> tree information
    type(treelmesh_type), intent(in) :: tree
    ! position of elemID in elem%tID list
    integer, intent(out) :: foundPos
    !> was the current element updated in this call?
    logical, intent(out) :: updated
    !> current stencil definition
    type( tem_stencilHeader_type ), intent(in) :: stencil
    ! -------------------------------------------------------------------- !
    integer :: iChild, level
    integer(kind=long_k) :: children(8), property
    logical :: wasAdded, childUpdated
    integer :: childPos(8)
    type(tem_path_type) :: childPath
    ! -------------------------------------------------------------------- !
    ! Set as not updated by default
    updated = .false.
    ! Create the ghostFromFiner
    level = tem_LevelOf( elemID )
    call append( me         = levelDesc( level )%elem, &
      &          tID        = elemID,                  &
      &          eType      = eT_ghostFromFiner,       &
      &          property   = 0_long_k,                &
      &          sourceProc = tree%global%myPart+1,    &
      &          pos        = foundPos,                &
      &          wasAdded   = wasAdded                 )
    if( wasAdded ) then
      updated = .true.
      children = tem_directChildren( elemID )
      childPos = 0 ! reset child positions. non-existing children are 0
      ! reset property
      property = 0_long_k
      ! if added elemID is more than level coarser than available child treeID
      ! in original treeID list then add all children between level and
      ! neighLevel
      do iChild = 1, 8
        ! Return position in the treeIDlist
        childPath  = tem_PathOf( children( iChild ))
        childPos( iChild ) = tem_PosOfPath( childPath, tree%pathList )
        if( childPos( iChild ) < 0 ) then
           ! This child does NOT exists, recusively add it as a ghostFromFiner.
           call add_ghostFromFiner( elemID    = children( iChild ),    &
             &                      levelDesc = levelDesc,             &
             &                      minLevel  = minlevel,              &
             &                      tree      = tree,                  &
             &                      foundPos  = childPos( iChild ),    &
             &                      updated   = childUpdated,          &
             &                      stencil   = stencil                )
           ! Unify all properties of the children
           property = ieor( property,                  &
             &              levelDesc(level+1)         &
             &                %elem                    &
             &                %property                &
             &                %val( childPos(iChild) ) )
           updated = ( updated .or. childUpdated )
        else
          ! This child is a Fluid, i.e. already exists in element list
          childPos( iChild ) = PositionOfVal( &
            &   levelDesc( level+1 )%elem%tID, children(iChild) )
        end if
      end do ! iChild = 1, 8
      ! Now reconstruct current element's neighborhood
      ! based on the children's information
      call tem_find_BCs_fromFiner( childPos     = childPos,   &
        &                          sourceLevel  = level + 1,  &
        &                          targetLevel  = level,      &
        &                          targetPos    = foundPos,   &
        &                          levelDesc    = levelDesc,  &
        &                          minLevel     = minLevel,   &
        &                          stencil      = stencil     )
    else
      ! ghostFromFiner element was not added
      ! Hence, we found available information which now has to be returned
      updated = .false.
    end if
  end subroutine add_ghostFromFiner
Call graph
add_ghostfromfiner calls add_ghostfromfiner, append, positionofval, tem_directchildren, tem_find_bcs_fromfiner, tem_levelof, tem_pathof, tem_posofpath
append calls append_ga_dynlong, append_ga_dynlong_vec
positionofval calls posofval_label
tem_find_bcs_fromfiner calls append, init, stenciltochild, update_childneighborid
init calls init_ga2d_real
append_ga_dynlong calls expand
append_ga_dynlong_vec calls expand
posofval_label calls sortedposofval
update_childneighborid calls tem_parentof, tem_idofcoord
expand calls expand_ga_dynlong
sortedposofval calls sortposofval_label
tem_parentof calls tem_directparent, tem_parentatlevel
identify_local_element calls add_ghostfromfiner
identify_halo calls identify_local_element
single_process_element calls identify_local_element
identify_elements calls single_process_element, identify_elements
request_remotehalos calls identify_halo
build_levelelements calls identify_elements
communicate_elements calls request_remotehalos
create_allparentneighbors calls identify_elements
identify_additionalneigh calls identify_elements
identify_stencilneigh calls identify_elements