alloc_matrix – Treelm
alloc_matrix Subroutine
14 statements
Source File
private subroutine alloc_matrix(me, dim1, dim2)
This routine allocates matrix with given dimentions
Arguments
Type Intent Optional Attributes Name
type(tem_matrix_type) :: me
integer, intent(in) :: dim1
integer, intent(in) :: dim2
Calls
Called by
Source Code
  subroutine alloc_matrix( me, dim1, dim2 )
    ! --------------------------------------------------------------------------
    type( tem_matrix_type ) :: me
    integer, intent(in) :: dim1
    integer, intent(in) :: dim2
    ! --------------------------------------------------------------------------
    if ( dim1 > 0 .and. dim2 > 0 ) then
      me%nEntries(1) = dim1
      me%nEntries(2) = dim2
      allocate( me%A( dim1, dim2 ) )
      me%A = 0.0_rk
    else
      write( logUnit(1), "(A)" ) &
        &  'Failed to allocate matrix. Dimension is negative number.'
      call tem_abort()
    end if
  end subroutine alloc_matrix
Call graph
alloc_matrix calls tem_abort
tem_abort calls mpi_abort
build_matrixlsf_linearintp calls alloc_matrix
build_matrixlsf_quadintp calls alloc_matrix
append_intpmatrixlsf calls build_matrixlsf_linearintp, build_matrixlsf_quadintp
append calls append_intpmatrixlsf