append_arrayga2d_real – Treelm
append_arrayga2d_real Subroutine
19 statements
Source File
public subroutine append_arrayga2d_real(me, val, length, pos)
append an array of values to the growing 2d array.
Arguments
Type Intent Optional Attributes Name
type(grw_real2darray_type) :: me
array to append the value to
real(kind=rk), intent(in) :: val(:)
array of values to append
integer, intent(in), optional :: length
optional length to expand the array
integer, intent(out), optional :: pos
the position in second dimension the elements were added to
Calls
Called by
Source Code
  subroutine append_arrayga2d_real(me, val, length, pos)
    ! --------------------------------------------------------------------------
    !> array to append the value to
    type(grw_real2darray_type) :: me
    !> array of values to append
    real(kind=rk), intent(in) :: val(:)
    !> optional length to expand the array
    integer, intent(in), optional :: length
    !> the position in second dimension the elements were added to
    integer, intent(out), optional :: pos
    ! --------------------------------------------------------------------------
    integer :: newpos
    ! --------------------------------------------------------------------------
    if (me%nvals == huge(me%nvals)) then
       write(*,*) "reached end of integer range for growing array!"
       write(*,*) "aborting!!"
       stop
    end if
    newpos = me%nvals + 1
    if (newpos > me%containersize) then
      ! expand the array, if its boundary is reached
      call expand( me = me, length = length )
    end if
    me%nvals = max(newpos, me%nvals)
    me%val( : , newpos ) = val(:)
    if( present( pos ) ) pos = newpos
  end subroutine append_arrayga2d_real
Call graph
append_arrayga2d_real calls expand
expand calls expand_ga2d_real
append calls append_arrayga2d_real, append_intpmatrixlsf
append_intpmatrixlsf calls append
load_datafile calls append
tem_addface calls append
tem_build_facerecvbuffers calls append
tem_build_facesendbuffers calls append
tem_dump_stlb calls append
tem_init_surfdata calls append
tem_opvar_fill_inputindex calls append
tem_opvar_reduction_transient_init calls append
tem_opvar_setupindices calls append, tem_opvar_fill_inputindex
tem_refine_global_subtree calls append
tem_spatial_scalar_storeval calls append
tem_spatial_vector_storeval calls append
tem_unify_surfacedata calls append
tem_spatial_storeval calls tem_spatial_scalar_storeval, tem_spatial_vector_storeval
load_temporal_from_file calls load_datafile
tem_build_facebuffers calls tem_build_facerecvbuffers, tem_build_facesendbuffers
tem_get_faces calls tem_addface
tem_readandunify_surfdata calls tem_unify_surfacedata
tem_update_surfpos calls tem_init_surfdata
setup_indices_spacetime calls tem_spatial_storeval
tem_build_face_info calls tem_build_facebuffers
tem_collect_faces calls tem_get_faces
tem_load_temporal calls load_temporal_from_file