append_ga_dynlong_vec – Treelm
append_ga_dynlong_vec Subroutine
20 statements
Source File
public subroutine append_ga_dynlong_vec(me, val, length)
Arguments
Type Intent Optional Attributes Name
type(grw_dynlongarray_type) :: me
type(dyn_longarray_type), intent(in) :: val(:)
integer, intent(in), optional :: length
optional length to expand the array
Calls
Called by
Source Code
  subroutine append_ga_dynlong_vec(me, val, length)
    type(grw_dynlongarray_type) :: me !< array to append the value to
    type(dyn_longarray_type), intent(in) :: val(:) !< values to append
    !> optional length to expand the array
    integer, intent(in), optional :: length
    integer :: lb, ub, ii
    if (me%nvals == huge(me%nvals)) then
      write(*,*) "reached end of integer range for growing array!"
      write(*,*) "aborting!!"
      stop
    end if
    lb = me%nvals + 1
    ub = lb + size(val) - 1
    if (ub > me%containersize) then
      ! expand the array, if its boundary is reached
      call expand(me = me, pos = ub, length = length)
    end if
    me%nvals = max( ub, me%nvals )
    do ii = lb, ub
      me%val(ii) = val(1+ii-lb)
    end do
  end subroutine append_ga_dynlong_vec
Call graph
append_ga_dynlong_vec calls expand
expand calls expand_ga_dynlong
append calls append_ga_dynlong_vec, append_element
add_all_virtual_children calls append, add_all_virtual_children
add_ghostfromfiner calls append, add_ghostfromfiner, tem_find_bcs_fromfiner
append_element calls append
appendghostdependency calls append
create_allparentneighbors calls append, identify_elements, identify_stencilneigh
depsource_append calls append
identify_elements calls append, create_allparentneighbors, identify_elements, single_process_element, identify_stencilneigh
identify_local_element calls append, add_all_virtual_children, add_ghostfromfiner
redefine_halos calls append, tem_stencil_communicate
request_remotehalos calls append, create_allparentneighbors, identify_halo, identify_stencilneigh
single_process_element calls append, identify_local_element
tem_adapt_dump_newmesh calls append
tem_find_bcs_fromfiner calls append
tem_halo_append calls append
tem_init_elemlevels calls append
tem_stencil_communicate calls append
build_levelelements calls identify_elements, identify_additionalneigh
communicate_elements calls redefine_halos, request_remotehalos, identify_lists
identify_additionalneigh calls identify_elements
identify_halo calls identify_local_element
identify_lists calls tem_halo_append
identify_stencilneigh calls identify_elements
tem_build_verticaldependencies calls appendghostdependency
tem_create_leveldesc calls tem_init_elemlevels, tem_build_verticaldependencies
tem_dimbydim_construction calls tem_create_leveldesc
tem_find_allelements calls build_levelelements, communicate_elements, identify_additionalneigh, identify_lists