append_possible_variable – Treelm
append_possible_variable Subroutine
10 statements
Source File
public subroutine append_possible_variable(me, varName, nComponents, pos)
Arguments
Type Intent Optional Attributes Name
type(tem_possible_variable_type), intent(inout) :: me
Possible variables
character(len=*), intent(in) :: varName
variable name
integer, intent(in) :: nComponents
number of components
integer, intent(out), optional :: pos
Calls
Called by
Source Code
  subroutine append_possible_variable( me, varName, nComponents, pos )
    !---------------------------------------------------------------------------
    !> Possible variables
    type(tem_possible_variable_type), intent(inout) :: me
    !> variable name
    character(len=*), intent(in) :: varName
    !> number of components
    integer, intent(in) :: nComponents
    integer, intent(out), optional :: pos
    !---------------------------------------------------------------------------
    integer :: internal_pos
    !---------------------------------------------------------------------------
    call append( me  = me%varName,    &
      &          val = trim(varName), &
      &          pos = internal_pos   )
    call append( me  = me%nComponents, &
      &          val = nComponents     )
    if( present( pos ) ) pos = internal_pos
  end subroutine append_possible_variable
Call graph
append_possible_variable calls append
append calls append_ga_stringkeyvaluepair, append_ga_stringkeyvaluepair_vec, append_possible_variable
append_ga_stringkeyvaluepair calls expand
append_ga_stringkeyvaluepair_vec calls expand
expand calls expand_ga_stringkeyvaluepair