append_singlePnt2grwPoints – Treelm
append_singlePnt2grwPoints Subroutine
7 statements
Source File
private subroutine append_singlePnt2grwPoints(me, val)
This routine append a single point to growing array of points
Arguments
Type Intent Optional Attributes Name
type(tem_grwPoints_type), intent(inout) :: me
Growing array of points in each dimension
real(kind=rk), intent(in) :: val(3)
single point to append
Calls
Called by
Source Code
  subroutine append_singlePnt2grwPoints(me, val)
    !---------------------------------------------------------------------------
    !> Growing array of points in each dimension
    type(tem_grwPoints_type), intent(inout) :: me
    !> single point to append
    real(kind=rk), intent(in) :: val(3)
    !---------------------------------------------------------------------------
    call append(me = me%coordX, val = val(1))
    call append(me = me%coordY, val = val(2))
    call append(me = me%coordZ, val = val(3))
  end subroutine append_singlePnt2grwPoints
Call graph
append_singlepnt2grwpoints calls append
append calls append_da_label, append_da_veclabel, append_singlepnt2grwpoints
append_da_label calls expand, sortedposofval
append_da_veclabel calls expand
expand calls expand_da_label
sortedposofval calls sortposofval_label