append_vectorPnt2grwPoints – Treelm
append_vectorPnt2grwPoints Subroutine
12 statements
Source File
private subroutine append_vectorPnt2grwPoints(me, val)
This routine append a array of points to growing array of points
Arguments
Type Intent Optional Attributes Name
type(tem_grwPoints_type), intent(inout) :: me
Growing array of points in each dimension
real(kind=rk), intent(in) :: val(:,:)
Array of points to append
Calls
Called by
Source Code
  subroutine append_vectorPnt2grwPoints(me, val)
    !---------------------------------------------------------------------------
    !> Growing array of points in each dimension
    type(tem_grwPoints_type), intent(inout) :: me
    !> Array of points to append
    real(kind=rk), intent(in) :: val(:,:)
    !---------------------------------------------------------------------------
    ! Expect points in shape(n,3) if not terminate
    if (size(val,dim=2)/=3) then
      write(logUnit(1),*) 'Error: Appending array of points to 1D growing'
      write(logUnit(1),*) '       array. Expects shape (n,3)'
      call tem_abort()
    end if
    call append(me = me%coordX, val = val(:,1))
    call append(me = me%coordY, val = val(:,2))
    call append(me = me%coordZ, val = val(:,3))
  end subroutine append_vectorPnt2grwPoints
Call graph
append_vectorpnt2grwpoints calls append, tem_abort
append calls append_da_label, append_da_veclabel, append_vectorpnt2grwpoints
tem_abort calls mpi_abort
append_da_label calls expand, sortedposofval
append_da_veclabel calls expand
expand calls expand_da_label
sortedposofval calls sortposofval_label