appendGhostDependency – Treelm
appendGhostDependency Subroutine
7 statements
Source File
private subroutine appendGhostDependency(sourcePos, sourceLevel, tgtDep)
add here the dependency for interpolation between the levels For each target cell, there are one or more source cells. The source cell can be of type fluid, ghost or halo. We save the type to update the correct element position later on, when the lists have been assembled.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: sourcePos
position of the source cell in total list
integer, intent(in) :: sourceLevel
level of the source ghost cell
type(depSource_type), intent(inout) :: tgtDep
dependent source elements for this target
Calls
Called by
Source Code
  subroutine appendGhostDependency( sourcePos, sourceLevel, tgtDep )
    ! ---------------------------------------------------------------------------
    !> position of the source cell in total list
    integer, intent(in) :: sourcePos
    !> level of the source ghost cell
    integer, intent(in) :: sourceLevel
    !> dependent source elements for this target
    type(depSource_type), intent(inout) :: tgtDep
    ! ---------------------------------------------------------------------------
    tgtDep%dependencyLevel = sourceLevel
    ! append the new entry to the dependency list at the end+1
    call append( me     = tgtDep%elem, &
      &          val    = sourcePos,   &
      &          length = 8            )
  end subroutine appendGhostDependency
Call graph
appendghostdependency calls append
append calls append_ga_dynlong, append_ga_dynlong_vec
append_ga_dynlong calls expand
append_ga_dynlong_vec calls expand
expand calls expand_ga_dynlong
tem_build_verticaldependencies calls appendghostdependency
tem_create_leveldesc calls tem_build_verticaldependencies
tem_dimbydim_construction calls tem_create_leveldesc
tem_build_face_info calls tem_dimbydim_construction