append_ga_stringkeyvaluepair – Treelm
append_ga_stringkeyvaluepair Subroutine
10 statements
Source File
private subroutine append_ga_stringkeyvaluepair(me, val, length)
Arguments
Type Intent Optional Attributes Name
type(grw_stringkeyvaluepairarray_type) :: me
type(tem_stringKeyValuePair_type), intent(in) :: val
integer, intent(in), optional :: length
optional length to expand the array
Calls
Called by
Source Code
  subroutine append_ga_stringkeyvaluepair(me, val, length)
    type(grw_stringkeyvaluepairarray_type) :: me !< array to append the value to
    type(tem_stringkeyvaluepair_type), intent(in) :: val !< value to append
    !> optional length to expand the array
    integer, intent(in), optional :: length
    ! value to append is larger than all existing ones,
    ! just put it to the end of the list, this captures
    ! also the case of empty lists.
    ! in this case foundpos = me%nvals + 1 holds.
    if (me%nvals+1 > me%containersize) then
      ! expand the array, if its boundary is reached
      call expand(me = me, length = length)
    end if
    me%nvals = me%nvals+1
    me%val(me%nvals) = val
  end subroutine append_ga_stringkeyvaluepair
Call graph
append_ga_stringkeyvaluepair calls expand
expand calls expand_ga_stringkeyvaluepair
append calls append_ga_stringkeyvaluepair, append_possible_variable
append_possible_variable calls append
tem_create_varmap calls append
tem_load_bc_state calls append, tem_variable_loadmapping
tem_variable_loadmapping_single calls append
tem_variable_loadmapping calls tem_variable_loadmapping_single, tem_variable_loadmapping_vector
hvs_output_init calls tem_create_varmap
tem_init_convergence calls tem_create_varmap
tem_init_depend calls tem_create_varmap
tem_init_tracker calls tem_create_varmap, hvs_output_init
tem_opvar_reduction_transient_init calls tem_create_varmap
tem_variable_loadmapping_vector calls tem_variable_loadmapping_single