bessel_jn_derivative – Treelm
bessel_jn_derivative Function
6 statements
Source File
private function bessel_jn_derivative(n, x) result(der)
Compute derivative for Bessel function of first kind of order n.
Arguments
Type Intent Optional Attributes Name
integer :: n
The order of the function.
real(kind=rk), intent(in) :: x
The evaluation point.
Return Value real(kind=rk)
The function value.
Called by
Source Code
  function bessel_jn_derivative(n,x) result(der)
    ! --------------------------------------------------------------------------
    !> The order of the function.
    integer :: n
    !> The evaluation point.
    real(kind=rk), intent(in) :: x
    !> The function value.
    real(kind=rk) :: der
    ! --------------------------------------------------------------------------
    ! --------------------------------------------------------------------------
    ! Calculate the derivative by recursive relation
    der = 0.5_rk*(bessel_jn(n-1,x)-bessel_jn(n+1,x))
  end function bessel_jn_derivative
Call graph
tem_eval_miescatter_magnangular calls bessel_jn_derivative
tem_init_data calls bessel_jn_derivative
tem_eval_miescatter_magnx calls tem_eval_miescatter_magnangular
tem_eval_miescatter_magny calls tem_eval_miescatter_magnangular
tem_load_miescatter calls tem_init_data
tem_load_miescatter_displacementfieldz calls tem_load_miescatter
tem_load_miescatter_magneticfieldx calls tem_load_miescatter
tem_load_miescatter_magneticfieldy calls tem_load_miescatter
tem_spacetime_for_coord calls tem_eval_miescatter_magnx, tem_eval_miescatter_magny
tem_spatial_for_coord calls tem_eval_miescatter_magnx, tem_eval_miescatter_magny
tem_spacetime_for calls tem_spacetime_for_coord
tem_spatial_for calls tem_spatial_for_coord
load_spacetime_predefined calls tem_load_miescatter_displacementfieldz, tem_load_miescatter_magneticfieldx, tem_load_miescatter_magneticfieldy
load_spatial_predefined calls tem_load_miescatter_displacementfieldz, tem_load_miescatter_magneticfieldx, tem_load_miescatter_magneticfieldy
tem_spacetime_for_stcoord calls tem_spacetime_for_coord
tem_spacetime_scalar_for_index calls tem_spacetime_for_coord
tem_spatial_scalar_for_index calls tem_spatial_for_coord