cart2polar – Treelm
cart2polar Function
11 statements
Source File
private function cart2polar(x, y) result(polar)
Convert from cartesian coordinates (in the x-y plane) to polar coordinates (radius,angle)
Arguments
Type Intent Optional Attributes Name
real(kind=rk) :: x
X coordinate
real(kind=rk) :: y
Y coordinate
Return Value real(kind=rk), (2)
Polar coordinates, radius (first entry) and angle (second entry)
Called by
Source Code
  function cart2polar(x,y) result(polar)
    ! --------------------------------------------------------------------------
    !> X coordinate
    real(kind=rk) :: x
    !> Y coordinate
    real(kind=rk) :: y
    !> Polar coordinates, radius (first entry) and angle (second entry)
    real(kind=rk) :: polar(2)
    ! --------------------------------------------------------------------------
    ! --------------------------------------------------------------------------
    polar(1) = sqrt(x*x + y*y)
    ! Atan2 is not defined when both coordinates are zero. To cover this
    ! situation correctly, we define the angle to be 0.
    if(polar(1) > epsilon(1.0_rk) ) then
      polar(2) = atan2(y,x)
    else
      polar(2) = 0.0_rk
    end if
  end function cart2polar
Call graph
tem_eval_miescatter_displz calls cart2polar
tem_eval_miescatter_magnangular calls cart2polar
tem_eval_miescatter_magnradial calls cart2polar
tem_eval_miescatter_magnx calls cart2polar, tem_eval_miescatter_magnangular, tem_eval_miescatter_magnradial
tem_eval_miescatter_magny calls cart2polar, tem_eval_miescatter_magnangular, tem_eval_miescatter_magnradial
tem_spacetime_for_coord calls tem_eval_miescatter_displz, tem_eval_miescatter_magnx, tem_eval_miescatter_magny
tem_spatial_for_coord calls tem_eval_miescatter_displz, tem_eval_miescatter_magnx, tem_eval_miescatter_magny
tem_spacetime_for calls tem_spacetime_for_coord
tem_spatial_for calls tem_spatial_for_coord
tem_spacetime_for_stcoord calls tem_spacetime_for_coord
tem_spacetime_scalar_for_index calls tem_spacetime_for_coord
tem_spatial_scalar_for_index calls tem_spatial_for_coord