check_mpi_error – Treelm
check_mpi_error Subroutine
12 statements
Source File
public subroutine check_mpi_error(iError, event_string)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: iError
character(len=*), intent(in) :: event_string
Calls
Called by
Source Code
  subroutine check_mpi_error( iError, event_string )
    integer, intent(in) :: iError
    character(len=*), intent(in) :: event_string
    character(len=100) :: IOError
    integer :: resultlen = 100
    integer :: ErrErr
    if (iError /= MPI_SUCCESS) then
      call MPI_ERROR_STRING(iError, IOError, resultlen, ErrErr)
      write(logUnit(0),*) 'MPI Error when '//trim(event_string),': ' &
        &                 //trim(IOError)
      call tem_abort()
    end if
  end subroutine check_mpi_error
Call graph
check_mpi_error calls mpi_error_string, tem_abort
tem_abort calls mpi_abort
dump_tem_bc_prop calls check_mpi_error
dump_tem_bc_realarray calls check_mpi_error
dump_treelmesh calls check_mpi_error
load_tem_bc_prop calls check_mpi_error
load_tem_bc_realarray calls check_mpi_error
load_treelmesh calls check_mpi_error
tem_commbuf_int_fillindexed calls check_mpi_error
tem_commbuf_int_fintyped calls check_mpi_error
tem_commbuf_int_gatherindexed calls check_mpi_error
tem_commbuf_long_fillindexed calls check_mpi_error
tem_commbuf_long_fintyped calls check_mpi_error
tem_commbuf_long_gatherindexed calls check_mpi_error
tem_commbuf_real_fillindexed calls check_mpi_error
tem_commbuf_real_fintyped calls check_mpi_error
tem_commbuf_real_gatherindexed calls check_mpi_error
tem_dump_weights calls check_mpi_error
tem_init_restart_create_types calls check_mpi_error
tem_load_weights calls check_mpi_error
tem_restart_closeread_single calls check_mpi_error
tem_restart_closewrite calls check_mpi_error
tem_restart_dump_data calls check_mpi_error
tem_restart_finalize calls check_mpi_error
tem_restart_openread_single calls check_mpi_error
tem_restart_openwrite calls check_mpi_error
tem_restart_readdata_single calls check_mpi_error
tem_restart_writedata calls check_mpi_error