childToStencil – Treelm
childToStencil Function
5 statements
Source File
private function childToStencil(childCoord) result(stencilCoord)
Convert a child coordinate {0,1} to non-zero stencil direction {-1,1}
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: childCoord
Return Value integer
Called by
Source Code
  function childToStencil( childCoord ) result( stencilCoord)
    ! ---------------------------------------------------------------------------
    integer, intent(in) :: childCoord
    integer :: stencilCoord
    ! ---------------------------------------------------------------------------
    stencilCoord = (childCoord*2) -1
  end function childToStencil
Call graph
tem_find_bcs_fromcoarser calls childtostencil
add_all_virtual_children calls tem_find_bcs_fromcoarser, add_all_virtual_children
identify_local_element calls add_all_virtual_children
identify_halo calls identify_local_element
single_process_element calls identify_local_element