cross_product3D – Treelm
cross_product3D Function
8 statements
Source File
public pure function cross_product3D(a, b) result(cross)
This function calculate the cross product of two 3D vector
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: a(3)
input vector a
real(kind=rk), intent(in) :: b(3)
input vector b
Return Value real(kind=rk), (3)
resulting cross produkt
Called by
Source Code
  pure function cross_product3D(a, b) result( cross )
    ! ---------------------------------------------------------------------------
    !> resulting cross produkt
    real(kind=rk) :: cross(3)
    !> input vector a
    real(kind=rk), intent(in) :: a(3)
    !> input vector b
    real(kind=rk), intent(in) :: b(3)
    ! ---------------------------------------------------------------------------
    cross(1) = a(2) * b(3) - a(3) * b(2)
    cross(2) = a(3) * b(1) - a(1) * b(3)
    cross(3) = a(1) * b(2) - a(2) * b(1)
  end function cross_product3D
Call graph
axistest calls cross_product3d
intersect_raytriangle calls cross_product3d
tem_calctriaareas calls cross_product3d
tem_createplane calls cross_product3d
tem_dump_stlb calls cross_product3d
tem_triangle_normal_proximity calls cross_product3d
triboxoverlap_loc calls cross_product3d, axistest
tem_createbox calls tem_createplane
tem_load_onecanonicalnd calls tem_createplane, tem_createbox
tem_trianglecubeoverlap calls triboxoverlap_loc
tem_load_canonicalnd calls tem_load_onecanonicalnd, tem_load_canonicalnd_vec
tem_load_canonicalnd_vec calls tem_load_onecanonicalnd
tem_planecubeoverlap calls tem_trianglecubeoverlap
tem_shape_subtreefromgeominters calls tem_trianglecubeoverlap, tem_stlcubeoverlap
tem_stlcubeoverlap calls tem_trianglecubeoverlap
tem_boxcubeoverlap calls tem_planecubeoverlap
tem_cano_initsubtree calls tem_planecubeoverlap
tem_load_shape_single calls tem_load_canonicalnd
tem_shape2subtree calls tem_shape_subtreefromgeominters