deriveElemVol – Treelm
deriveElemVol Subroutine
22 statements
Source File
private recursive subroutine deriveElemVol(fun, varSys, elempos, time, tree, nElems, nDofs, res)
Get the volume of an element
Arguments
Type Intent Optional Attributes Name
class(tem_varSys_op_type), intent(in) :: fun
Description of the method to obtain the variables, here some preset values might be stored, like the space time function to use or the required variables.
type(tem_varSys_type), intent(in) :: varSys
The variable system to obtain the variable from.
integer, intent(in) :: elempos(:)
Position of the TreeID of the element to get the variable for in the global treeID list.
type(tem_time_type), intent(in) :: time
Point in time at which to evaluate the variable.
type(treelmesh_type), intent(in) :: tree
global treelm mesh info
integer, intent(in) :: nElems
Number of values to obtain for this variable (vectorized access).
integer, intent(in) :: nDofs
Number of degrees of freedom within an element.
real(kind=rk), intent(out) :: res(:)
Resulting values for the requested variable.
Linearized array dimension: (n requested entries) x (nComponents of this variable) x (nDegrees of freedom) Access: (iElem-1)fun%nComponentsnDofs + (iDof-1)*fun%nComponents + iComp
Calls
Source Code
  recursive subroutine deriveElemVol( fun, varsys, elempos, time, tree, &
    &                                 nElems, nDofs, res                )
    ! -------------------------------------------------------------------- !
    !> Description of the method to obtain the variables, here some preset
    !! values might be stored, like the space time function to use or the
    !! required variables.
    class(tem_varSys_op_type), intent(in) :: fun
    !> The variable system to obtain the variable from.
    type(tem_varSys_type), intent(in) :: varSys
    !> Position of the TreeID of the element to get the variable for in the
    !! global treeID list.
    integer, intent(in) :: elempos(:)
    !> Point in time at which to evaluate the variable.
    type(tem_time_type), intent(in)  :: time
    !> global treelm mesh info
    type(treelmesh_type), intent(in) :: tree
    !> Number of values to obtain for this variable (vectorized access).
    integer, intent(in) :: nElems
    !> Number of degrees of freedom within an element.
    integer, intent(in) :: nDofs
    !> Resulting values for the requested variable.
    !!
    !! Linearized array dimension:
    !! (n requested entries) x (nComponents of this variable)
    !! x (nDegrees of freedom)
    !! Access: (iElem-1)*fun%nComponents*nDofs +
    !!         (iDof-1)*fun%nComponents + iComp
    real(kind=rk), intent(out) :: res(:)
    ! -------------------------------------------------------------------- !
    integer :: iElem
    real(kind=rk) :: dx
    ! -------------------------------------------------------------------- !
    res = 0.0_rk
    do iElem = 1, nElems
      if ( .not. btest( tree%ElemPropertyBits( elemPos(iElem) ), &
        &               prp_solid )                              ) then
        ! calculate without qVals
        dx = tem_ElemSize( tree, tree%treeID( elemPos(iElem) ) )
        res( (iElem-1)*nDofs+1 ) = dx*dx*dx
      end if
    end do  ! iElem
    if (time%sim < 0.0_rk) then
      write(logUnit(10),*) 'Negative time for variable ', &
        &                  trim(varSys%varName%val(fun%myPos))
    end if
  end subroutine deriveElemVol
Call graph
deriveelemvol calls tem_elemsize
tem_elemsize calls tem_elemsizelevel, tem_levelof