destroy_ga_dynlong – Treelm
destroy_ga_dynlong Subroutine
6 statements
Source File
public subroutine destroy_ga_dynlong(me)
Arguments
Type Intent Optional Attributes Name
type(grw_dynlongarray_type), intent(inout) :: me
Called by
Source Code
  subroutine destroy_ga_dynlong(me)
    type(grw_dynlongarray_type), intent(inout) :: me !< dynamic array to destroy
    me%containersize = 0
    me%nvals = 0
    if( allocated( me%val ) ) deallocate(me%val)
  end subroutine destroy_ga_dynlong
Call graph
destroy calls destroy_ga_dynlong
tem_halo_destroy calls destroy
identify_lists calls tem_halo_destroy
tem_cleanupdependencyarrays calls tem_halo_destroy
communicate_elements calls identify_lists
tem_create_leveldesc calls tem_cleanupdependencyarrays
tem_find_allelements calls identify_lists, tem_cleanupdependencyarrays