destroy_da_label – Treelm
destroy_da_label Subroutine
7 statements
Source File
public subroutine destroy_da_label(me)
destruction of a dynamic array
this subroutine takes care of a proper destruction of a dynamic array, it frees the allocated memory and resets the internal counts to 0.
Arguments
Type Intent Optional Attributes Name
type(dyn_labelarray_type), intent(inout) :: me
Called by
Source Code
  subroutine destroy_da_label(me)
    type(dyn_labelarray_type), intent(inout) :: me !< dynamic array to init
    me%containersize = 0
    me%nvals         = 0
    if( allocated( me%val ) ) deallocate(me%val)
    if( allocated( me%sorted ) ) deallocate(me%sorted)
  end subroutine destroy_da_label
Call graph
destroy calls destroy_da_label
sorttruncate_da_int calls destroy
sorttruncate_da_label calls destroy
sorttruncate_da_long calls destroy
sorttruncate_da_real calls destroy
tem_comm_createbuffer calls destroy
tem_comm_destroy calls destroy
tem_commbuf_int_gatherindexed calls destroy
tem_commbuf_long_gatherindexed calls destroy
tem_commbuf_real_gatherindexed calls destroy
sorttruncate calls sorttruncate_da_long, sorttruncate_da_int, sorttruncate_da_real, sorttruncate_da_label