destroy_ga2d_real – Treelm
destroy_ga2d_real Subroutine
6 statements
Source File
public subroutine destroy_ga2d_real(me)
destroy the 2d growing array
Arguments
Type Intent Optional Attributes Name
type(grw_real2darray_type), intent(inout) :: me
dynamic array to init
Called by
Source Code
  subroutine destroy_ga2d_real(me)
    ! --------------------------------------------------------------------------
    !> dynamic array to init
    type(grw_real2darray_type), intent(inout) :: me
    ! --------------------------------------------------------------------------
    deallocate(me%val)
    me%nvals  = 0
    me%containersize = 0
  end subroutine destroy_ga2d_real
Call graph
destroy calls destroy_ga2d_real, empty_stencil, destroy_intpmatrixlsf, destroy_element, destroy_grwpoints
assemble_lists calls destroy
depsource_append calls destroy
destroy_element calls destroy
destroy_grwpoints calls destroy
destroy_intpmatrixlsf calls destroy
empty_stencil calls destroy
request_remotehalos calls destroy
tem_cleanup_arrays calls destroy
tem_cleanupdependencyarrays calls destroy
tem_create_subtree_of calls destroy
tem_dump_stlb calls destroy
tem_refine_global_subtree calls destroy
tem_unify_surfacedata calls destroy
tem_unify_vrtx calls destroy
empty calls empty_stencil
communicate_elements calls request_remotehalos
tem_calc_vrtx_coord calls tem_unify_vrtx
tem_create_leveldesc calls tem_cleanupdependencyarrays, tem_find_allelements
tem_create_subtree_of_st_funlist calls tem_create_subtree_of
tem_find_allelements calls assemble_lists, tem_cleanupdependencyarrays, communicate_elements
tem_init_convergence calls tem_create_subtree_of
tem_init_tracker_subtree calls tem_create_subtree_of
tem_readandunify_surfdata calls tem_unify_surfacedata
tem_write_debugmesh calls tem_create_subtree_of
hvs_output_init calls tem_calc_vrtx_coord
tem_dimbydim_construction calls tem_create_leveldesc