dump_tem_BC_qValHeader – Treelm
dump_tem_BC_qValHeader Subroutine
5 statements
Source File
private subroutine dump_tem_BC_qValHeader(me, headerfile)
dump qval header information to lua file
Arguments
Type Intent Optional Attributes Name
type(tem_BC_prop_type), intent(in) :: me
Boundary condition construct to load the data into
character(len=*), intent(in) :: headerfile
name of the bc header lua file
Calls
Called by
Source Code
  subroutine dump_tem_BC_qValHeader( me, headerfile )
    ! ---------------------------------------------------------------------------
    !> Boundary condition construct to load the data into
    type(tem_BC_prop_type), intent(in) :: me
    !> name of the bc header lua file
    character(len=*), intent(in) :: headerfile
    ! ---------------------------------------------------------------------------
    call dump_tem_BC_logicalHeader( headerfile, 'hasQVal', me%nBCtypes, &
      &                             me%hasQVal                          )
  end subroutine dump_tem_BC_qValHeader
Call graph
dump_tem_bc_qvalheader calls dump_tem_bc_logicalheader
dump_tem_bc_logicalheader calls aot_out_close, aot_out_close_table, aot_out_open, aot_out_open_table, aot_out_val
dump_tem_bc_qval calls dump_tem_bc_qvalheader