dump_tem_prophead – Treelm
dump_tem_prophead Subroutine
14 statements
Source File
public subroutine dump_tem_prophead(me, conf)
Subroutine to dump property header informations into a Lua file.
Arguments
Type Intent Optional Attributes Name
type(tem_prophead_type), intent(in) :: me(:)
Property to write
type(aot_out_type) :: conf
aotus lua state to write output
Calls
Called by
Source Code
  subroutine dump_tem_prophead(me, conf)
    ! -------------------------------------------------------------------- !
    !> Property to write
    type(tem_prophead_type), intent(in) :: me(:)
    !> aotus lua state to write output
    type(aot_out_type) :: conf
    ! -------------------------------------------------------------------- !
    integer :: iprop
    ! -------------------------------------------------------------------- !
    ! open property table
    call aot_out_open_table( conf, 'property' )
    do iprop=1, size(me)
      call aot_out_open_table( conf )
      call aot_out_val( put_conf = conf,                 &
        &               vname    = 'label',              &
        &               val      = trim(me(iprop)%label) )
      call aot_out_val( put_conf = conf,            &
        &               vname    = 'bitpos',        &
        &               val      = me(iprop)%bitpos )
      call aot_out_val( put_conf = conf,            &
        &               vname    = 'nElems',        &
        &               val      = me(iprop)%nElems )
      call aot_out_close_table(conf)
    end do
    call aot_out_close_table(conf)
  end subroutine dump_tem_prophead
Call graph
dump_tem_prophead calls aot_out_close_table, aot_out_open_table, aot_out_val
dump_tem_global calls dump_tem_prophead
dump_treelmesh calls dump_tem_global
tem_adapt_dump_newmesh calls dump_treelmesh
tem_dump_subtree calls dump_treelmesh
tem_restart_openwrite calls dump_treelmesh, tem_dump_subtree
hvs_output_init calls tem_dump_subtree
hvs_output_open calls tem_restart_openwrite
tem_write_debugmesh calls tem_dump_subtree