dump_tem_BC_propHeader – Treelm
dump_tem_BC_propHeader Subroutine
15 statements
Source File
public subroutine dump_tem_BC_propHeader(me, headerfile)
dump bc properties header information to lua file
Arguments
Type Intent Optional Attributes Name
type(tem_BC_prop_type), intent(in) :: me
Boundary condition construct to load the data into
character(len=*), intent(in) :: headerfile
name of the bc header lua file
Calls
Called by
Source Code
  subroutine dump_tem_BC_propHeader( me, headerfile )
    ! ---------------------------------------------------------------------------
    !> Boundary condition construct to load the data into
    type(tem_BC_prop_type), intent(in) :: me
    !> name of the bc header lua file
    character(len=*), intent(in) :: headerfile
    ! ---------------------------------------------------------------------------
    integer :: i
    type(aot_out_type) :: conf ! aotus lua state to write output
    ! ---------------------------------------------------------------------------
    call aot_out_open( conf, headerfile )
    call aot_out_val( put_conf = conf, vname = 'nSides', val = me%nSides )
    call aot_out_val( put_conf = conf, vname = 'nBCtypes', val = me%nBCtypes )
    call aot_out_open_table( conf, 'bclabel' )
    do i = 1, me%nBCtypes
      call aot_out_val( conf, val = me%BC_label(i) )
    end do
    call aot_out_close_table(conf)
    ! close the mesh header file
    call aot_out_close(conf)
  end subroutine dump_tem_BC_propHeader
Call graph
dump_tem_bc_propheader calls aot_out_close, aot_out_close_table, aot_out_open, aot_out_open_table, aot_out_val
dump_tem_bc_prop calls dump_tem_bc_propheader