dump_meshHeader – Treelm
dump_meshHeader Subroutine
30 statements
Source File
public subroutine dump_meshHeader(me)
write mesh information
Arguments
Type Intent Optional Attributes Name
type(treelmesh_type), intent(in) :: me
fluid tree from mesh
Called by
Source Code
  subroutine dump_meshHeader( me )
    ! -------------------------------------------------------------------- !
    !> fluid tree from mesh
    type( treelmesh_type ), intent(in) :: me
    ! -------------------------------------------------------------------- !
    integer :: iProp
    ! -------------------------------------------------------------------- !
    write(logunit(1),*)  'Got a mesh with following properties:'
    write(logUnit(1), "('                 Mesh name: ',A)") &
      &               trim(me%global%label)
    if (trim(me%global%predefined) /= '') then
      write(logunit(1), "(' This is a predefined mesh: ', A)") &
        &               trim(me%global%predefined)
    end if
    write(logunit(1), "('  Total number of elements: ', I0)") me%global%nElems
    write(logunit(1), "('  Local number of elements: ', I0)") me%nElems
    write(logUnit(1), "('      Number of properties: ', I0)") &
      &               me%global%nProperties
    write(logunit(1), "('      Number of partitions: ', I0)") me%global%nParts
    write(logunit(1), "('             Minimum level: ', I0)") me%global%minlevel
    write(logunit(1), "('             Maximum level: ', I0)") me%global%maxlevel
    write(logunit(1), "('       Bounding Box Origin: ', 3F10.4 )") &
      &               me%global%origin
    write(logunit(1), "('       Bounding Box Length: ', F10.4 )") &
      &               real(me%global%BoundingCubeLength)
    write(logUnit(1), "('     Coarsest element size: ', F10.4 )") &
      &               real( me%global%BoundingCubeLength /      &
      &               real( 2**me%global%minlevel, kind=rk ) )
    write(logUnit(1), "('       Finest element size: ', F10.4 )") &
      &               real( me%global%BoundingCubeLength /      &
      &               real( 2**me%global%maxlevel, kind=rk ) )
    do iProp=1,me%global%nProperties
      if ( me%global%Property(iProp)%BitPos == prp_hasBnd ) then
        write(logUnit(1), "('  Number of boundary elements: ', I0 )") &
          &               me%Property(iProp)%nElems
      end if
      if ( me%global%Property(iProp)%BitPos == prp_hasQVal ) then
        write(logUnit(1), "('      Number of qVal elements: ', I0 )") &
          &               me%Property(iProp)%nElems
      end if
      if ( me%global%Property(iProp)%BitPos == prp_hasNormal ) then
        write(logUnit(1), "('Number of elements with wall normals: ', I0 )") &
          &               me%Property(iProp)%nElems
      end if
    end do
  end subroutine dump_meshHeader
Call graph
load_tem calls dump_meshheader
tem_restart_readheader calls load_tem
tem_load_restart calls tem_restart_readheader