dump_tem_BC_normal – Treelm
dump_tem_BC_normal Subroutine
15 statements
Source File
public subroutine dump_tem_BC_normal(me, offset, nElems, basename, myPart, comm)
dump normal information
Arguments
Type Intent Optional Attributes Name
type(tem_BC_prop_type), intent(in) :: me
Boundary condition construct to load the data into
integer(kind=long_k), intent(in) :: offset
Offset of the local set of elements in the global list
integer, intent(in) :: nElems
Local number of elements with this property
character(len=*), intent(in) :: basename
Name of the file, the data is stored in, will be appended with ".lua" for the header information and ".lsb" or ".msb" for the binary data.
integer, intent(in) :: myPart
Partition to dump
integer, intent(in) :: comm
Communicator to use
Calls
Source Code
  subroutine dump_tem_BC_normal( me, offset, nElems, basename, myPart, comm )
    ! ---------------------------------------------------------------------------
    !> Boundary condition construct to load the data into
    type(tem_BC_prop_type), intent(in) :: me
    !> Offset of the local set of elements in the global list
    integer(kind=long_k), intent(in) :: offset
    !> Local number of elements with this property
    integer, intent(in) :: nElems
    !> Name of the file, the data is stored in, will be appended with
    !! ".lua" for the header information and ".lsb" or ".msb" for the
    !! binary data.
    character(len=*), intent(in) :: basename
    !> Partition to dump
    integer, intent(in) :: myPart
    !> Communicator to use
    integer, intent(in) :: comm
    ! ---------------------------------------------------------------------------
    integer, parameter :: root = 0
    character(len=256) :: headerfile
    ! ---------------------------------------------------------------------------
    headerfile = trim(basename)//'.lua'
    if (myPart == root) then
      ! Only root partition needs to write the header
      !open up the mesh header lua file to dump the stuff using aotus library
      call dump_tem_BC_NormalHeader( me, headerfile )
    end if
    call dump_tem_BC_realArray( offset   = offset,    &
      &                         arraylen = 3,         &
      &                         nElems   = nElems,    &
      &                         propdat  = me%normal, &
      &                         basename = basename,  &
      &                         comm     = comm       )
  end subroutine dump_tem_BC_normal
Call graph
dump_tem_bc_normal calls dump_tem_bc_normalheader, dump_tem_bc_realarray
dump_tem_bc_normalheader calls dump_tem_bc_logicalheader
dump_tem_bc_realarray calls mpi_file_close, mpi_file_open, mpi_file_set_view, mpi_file_write_all, mpi_type_commit, mpi_type_contiguous, mpi_type_free, mpi_type_size, check_mpi_error, tem_create_endiansuffix
check_mpi_error calls mpi_error_string, tem_abort
dump_tem_bc_logicalheader calls aot_out_close, aot_out_close_table, aot_out_open, aot_out_open_table, aot_out_val
tem_abort calls mpi_abort