equal – Treelm
equal Function
6 statements
Source File
private elemental function equal(a, b) result(res)
Relational operator to test the equality of floating point numbers.
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: a
Floating point value to be compared.
real(kind=rk), intent(in) :: b
Floating point value to be compared.
Return Value logical
The result is a logical value indicating whether the operands are equal to within numerical precision.
Called by
Call graph
operator (.feq.) calls equal, equal_array
equal_array calls equal
greaterthanorequal calls equal
lessthanorequal calls equal
notequal calls equal
operator (.fge.) calls greaterthanorequal
operator (.fle.) calls lessthanorequal
operator (.fne.) calls notequal, notequal_array
notequal_array calls equal_array