evaluate_FOAG_spacetime_scalarByTreeID – Treelm
evaluate_FOAG_spacetime_scalarByTreeID Subroutine
17 statements
Source File
public recursive subroutine evaluate_FOAG_spacetime_scalarByTreeID(fun, varSys, elempos, time, tree, nElems, nDofs, res)
This subroutine directly evaluate spacetime function for given element position in global TreeID list on 1st st_fun assuming global shape.
Arguments
Type Intent Optional Attributes Name
class(tem_varSys_op_type), intent(in) :: fun
Description of the method to obtain the variables, here some preset values might be stored, like the space time function to use or the required variables.
type(tem_varSys_type), intent(in) :: varSys
The variable system to obtain the variable from.
integer, intent(in) :: elempos(:)
Position of the TreeID of the element to get the variable for in the global treeID list.
type(tem_time_type), intent(in) :: time
Point in time at which to evaluate the variable.
type(treelmesh_type), intent(in) :: tree
global treelm mesh info
integer, intent(in) :: nElems
Number of values to obtain for this variable (vectorized access).
integer, intent(in) :: nDofs
Number of degrees of freedom within an element.
real(kind=rk), intent(out) :: res(:)
Resulting values for the requested variable.
Linearized array dimension: (n requested entries) x (nComponents of this variable) x (nDegrees of freedom) Access: (iElem-1)fun%nComponentsnDofs + (iDof-1)*fun%nComponents + iComp
Calls
Source Code
  recursive subroutine evaluate_FOAG_spacetime_scalarByTreeID( fun, varsys, &
    & elempos, time, tree, nElems, nDofs, res                               )
    !--------------------------------------------------------------------------!
    !> Description of the method to obtain the variables, here some preset
    !! values might be stored, like the space time function to use or the
    !! required variables.
    class(tem_varSys_op_type), intent(in) :: fun
    !> The variable system to obtain the variable from.
    type(tem_varSys_type), intent(in) :: varSys
    !> Position of the TreeID of the element to get the variable for in the
    !! global treeID list.
    integer, intent(in) :: elempos(:)
    !> Point in time at which to evaluate the variable.
    type(tem_time_type), intent(in)  :: time
    !> global treelm mesh info
    type(treelmesh_type), intent(in) :: tree
    !> Number of values to obtain for this variable (vectorized access).
    integer, intent(in) :: nElems
    !> Number of degrees of freedom within an element.
    integer, intent(in) :: nDofs
    !> Resulting values for the requested variable.
    !!
    !! Linearized array dimension:
    !! (n requested entries) x (nComponents of this variable)
    !! x (nDegrees of freedom)
    !! Access: (iElem-1)*fun%nComponents*nDofs +
    !!         (iDof-1)*fun%nComponents + iComp
    real(kind=rk), intent(out) :: res(:)
    !--------------------------------------------------------------------------!
    ! --------------------------------------------------------------------------
    type(tem_st_fun_listElem_type), pointer :: fPtr
    ! -------------------------------------------------------------------------!
    !call C_F_POINTER( fun%method_Data, fPtr )
    ! avoid compiler warning about unused varsys
    call C_F_POINTER( varsys%method%val(fun%mypos)%method_Data, fPtr )
    ! assuming nDofs = 1
    if (nDofs > 1) then
      write(logUnit(1),*) 'Spacetime function does not support nDofs>1'
      call tem_abort()
    end if
    res(:) = tem_spacetime_for( me      = fPtr%val(1),             &
         &                      treeIDs = tree%treeID(elemPos(:)), &
         &                      tree    = tree,                    &
         &                      time    = time,                    &
         &                      n       = nElems                   )
  end subroutine evaluate_FOAG_spacetime_scalarByTreeID
Call graph
evaluate_foag_spacetime_scalarbytreeid calls tem_spacetime_for, tem_abort
tem_spacetime_for calls tem_spacetime_for_coord, tem_spacetime_for_stcoord, tem_spacetime_for_treeids, tem_spacetime_scalar_for_index, tem_spacetime_vector_for_coord, tem_spacetime_vector_for_index, tem_spacetime_vector_for_treeids
tem_abort calls mpi_abort
tem_spacetime_for_coord calls tem_abort, tem_spacetime_lua_for, tem_spatial_for, tem_eval_acoustic_pulse, tem_eval_cylindricalwave, tem_eval_miescatter_displz, tem_eval_miescatter_magnx, tem_eval_miescatter_magny, tem_polygon_material_movement_multi, tem_polygon_material_movement_single, tem_temporal_for
tem_spacetime_for_stcoord calls tem_spacetime_for_coord
tem_spacetime_for_treeids calls tem_abort, tem_spacetime_lua_for, tem_spatial_for, tem_temporal_for
tem_spacetime_scalar_for_index calls tem_spacetime_for_coord, ids, tem_spacetime_lua_for, tem_spatial_for, posids, tem_temporal_for, tem_precice_read
tem_spacetime_vector_for_coord calls tem_abort, tem_spacetime_lua_for, tem_spatial_for, tem_temporal_for
tem_spacetime_vector_for_index calls tem_spacetime_vector_for_coord, ids, tem_spacetime_lua_for, tem_spatial_for, posids, tem_temporal_for, tem_precice_read
tem_spacetime_vector_for_treeids calls tem_abort, tem_spacetime_lua_for, tem_spatial_for, tem_temporal_for