exchange_elements – Treelm
exchange_elements Subroutine
13 statements
Source File
public subroutine exchange_elements(me, sparta)
Exchange mesh elements with other process The following data within treelmesh_type is updated in this routine: treeID, ElemPropertyBits, Part_First, Part_Last Data pathList is deallocated.
Arguments
Type Intent Optional Attributes Name
type(treelmesh_type), intent(inout) :: me
Tree Mesh type nElems and offset should be ready before this routine
type(tem_sparta_type), intent(in) :: sparta
How many elements to exchange with other processes
Calls
Called by
Source Code
  subroutine exchange_elements( me, sparta )
    ! -------------------------------------------------------------------- !
    !> Tree Mesh type
    !! nElems and offset should be ready before this routine
    type( treelmesh_type ), intent(inout) :: me
    !> How many elements to exchange with other processes
    type( tem_sparta_type ), intent(in) :: sparta
    ! -------------------------------------------------------------------- !
    integer :: iError, iProp
    ! -------------------------------------------------------------------- !
    ! Exchange treeID and propertyBits ---------------------------------
    call tem_exchange_sparta( me = sparta, &
      &                       val = me%treeID, &
      &                       nComponents = 1, &
      &                       comm = me%global%comm )
    call tem_exchange_sparta( me = sparta, &
      &                       val = me%ElemPropertyBits, &
      &                       nComponents = 1, &
      &                       comm = me%global%comm )
    ! Exchange treeID and propertyBits ---------------------------------
    ! Update Part_first and Part_Last ------------------------
    call MPI_allgather( me%treeID(1), 1, long_k_mpi,  &
      &                 me%Part_First, 1, long_k_mpi, &
      &                 me%global%comm, iError        )
    call MPI_allgather( me%treeID(me%nElems), 1, long_k_mpi, &
      &                 me%Part_Last, 1, long_k_mpi,         &
      &                 me%global%comm, iError               )
    ! Update Part_first and Part_Last ------------------------
    do iProp=1,me%global%nProperties
      call gather_Property( Property = me%Property(iProp),                     &
        &                   Header   = me%global%Property(iProp),              &
        &                   BitField = me%ElemPropertyBits,                    &
        &                   comm     = me%global%comm )
    end do
    if (allocated(me%pathList)) deallocate( me%pathList  )
  end subroutine exchange_elements
Call graph
exchange_elements calls tem_exchange_sparta, mpi_allgather, gather_property
tem_exchange_sparta calls tem_exchange_double, tem_exchange_double2, tem_exchange_long, tem_exchange_long2
gather_property calls mpi_exscan
tem_exchange_double calls mpi_alltoallv, tem_abort
tem_exchange_double2 calls mpi_alltoallv
tem_exchange_long calls mpi_alltoallv, tem_abort
tem_exchange_long2 calls mpi_alltoallv
tem_abort calls mpi_abort
load_tem calls exchange_elements
tem_restart_readheader calls load_tem
tem_load_restart calls tem_restart_readheader