get_valOfIndex_FOAG_vector_spacetime – Treelm
get_valOfIndex_FOAG_vector_spacetime Subroutine
19 statements
Source File
public recursive subroutine get_valOfIndex_FOAG_vector_spacetime(fun, varSys, time, iLevel, idx, idxLen, nVals, res)
This routine returns value at the given index. If value is pre-computed and value at given index is returned else value is computing on the points for given index.
If a variable has more than one spacetime function, then result of 1st spacetime function is returned with assumed global shape
For vectorial variable.
Arguments
Type Intent Optional Attributes Name
class(tem_varSys_op_type), intent(in) :: fun
Description of the method to obtain the variables, here some preset values might be stored, like the space time function to use or the required variables.
type(tem_varSys_type), intent(in) :: varSys
The variable system to obtain the variable from.
type(tem_time_type), intent(in) :: time
Point in time at which to evaluate the variable.
integer, intent(in) :: iLevel
Level on which values are requested
integer, intent(in) :: idx(:)
Index of points in the growing array and variable val array to return. Size: nVals
integer, intent(in), optional :: idxLen(:)
With idx as start index in contiguous memory, idxLength defines length of each contiguous memory Size: nVals
integer, intent(in) :: nVals
Number of values to obtain for this variable (vectorized access).
real(kind=rk), intent(out) :: res(:)
Resulting values for the requested variable.
Dimension: n requested entries x nComponents of this variable Access: (iElem-1)*fun%nComponents + iComp
Calls
Source Code
  recursive subroutine get_valOfIndex_FOAG_vector_spacetime( fun, varSys,  &
    &                                                        time, iLevel, &
    &                                                        idx, idxLen,  &
    &                                                        nVals, res    )
    !--------------------------------------------------------------------------!
    !> Description of the method to obtain the variables, here some preset
    !! values might be stored, like the space time function to use or the
    !! required variables.
    class(tem_varSys_op_type), intent(in) :: fun
    !> The variable system to obtain the variable from.
    type(tem_varSys_type), intent(in) :: varSys
    !> Point in time at which to evaluate the variable.
    type(tem_time_type), intent(in) :: time
    !> Level on which values are requested
    integer, intent(in) :: iLevel
    !> Index of points in the growing array and variable val array to
    !! return.
    !! Size: nVals
    integer, intent(in) :: idx(:)
    !> With idx as start index in contiguous memory,
    !! idxLength defines length of each contiguous memory
    !! Size: nVals
    integer, optional, intent(in) :: idxLen(:)
    !> Number of values to obtain for this variable (vectorized access).
    integer, intent(in) :: nVals
    !> Resulting values for the requested variable.
    !!
    !! Dimension: n requested entries x nComponents of this variable
    !! Access: (iElem-1)*fun%nComponents + iComp
    real(kind=rk), intent(out) :: res(:)
    !--------------------------------------------------------------------------!
    ! -------------------------------------------------------------------------!
    type(tem_st_fun_listElem_type), pointer :: fPtr
    integer :: iVal
    real(kind=rk) :: st_res(nVals, fun%nComponents)
    ! -------------------------------------------------------------------------!
    call C_F_POINTER( fun%method_Data, fPtr )
    ! check if number of index are the same as number of values asked for
    call tem_varSys_check_inArgs( fun, varSys, time, iLevel, idx, idxLen, &
      &    nVals, label = 'get_valOfIndex_FOAG_vector_spacetime'          )
    st_res = tem_spacetime_for( me     = fPtr%val(1),                &
      &                         grwPnt = fPtr%pntData%pntLvl(iLevel) &
      &                                      %grwPnt,                &
      &                         idx    = idx,                        &
      &                         nVals  = nVals,                      &
      &                         iLevel = ilevel,                     &
      &                         time   = time,                       &
      &                         nComps = fun%nComponents             )
    do iVal = 1, nVals
      res( (iVal-1)*fun%nComponents + 1 : iVal*fun%nComponents ) &
        & = st_res(iVal, :)
    end do
  end subroutine get_valOfIndex_FOAG_vector_spacetime
Call graph
get_valofindex_foag_vector_spacetime calls tem_spacetime_for, tem_varsys_check_inargs
tem_spacetime_for calls tem_spacetime_for_coord, tem_spacetime_for_stcoord, tem_spacetime_for_treeids, tem_spacetime_scalar_for_index, tem_spacetime_vector_for_coord, tem_spacetime_vector_for_index, tem_spacetime_vector_for_treeids
tem_spacetime_for_coord calls tem_spacetime_lua_for, tem_spatial_for, tem_abort, tem_eval_acoustic_pulse, tem_eval_cylindricalwave, tem_eval_miescatter_displz, tem_eval_miescatter_magnx, tem_eval_miescatter_magny, tem_polygon_material_movement_multi, tem_polygon_material_movement_single, tem_temporal_for
tem_spacetime_for_stcoord calls tem_spacetime_for_coord
tem_spacetime_for_treeids calls tem_spacetime_lua_for, tem_spatial_for, tem_abort, tem_temporal_for
tem_spacetime_scalar_for_index calls tem_spacetime_for_coord, ids, tem_spacetime_lua_for, tem_spatial_for, posids, tem_temporal_for, tem_precice_read
tem_spacetime_vector_for_coord calls tem_spacetime_lua_for, tem_spatial_for, tem_abort, tem_temporal_for
tem_spacetime_vector_for_index calls tem_spacetime_vector_for_coord, ids, tem_spacetime_lua_for, tem_spatial_for, posids, tem_temporal_for, tem_precice_read
tem_spacetime_vector_for_treeids calls tem_spacetime_lua_for, tem_spatial_for, tem_abort, tem_temporal_for