getElemWeight – Treelm
getElemWeight Subroutine
24 statements
Source File
private recursive subroutine getElemWeight(fun, varSys, elempos, time, tree, nElems, nDofs, res)
Get the computational weight of elements
Arguments
Type Intent Optional Attributes Name
class(tem_varSys_op_type), intent(in) :: fun
Description of the method to obtain the variables, here some preset values might be stored, like the space time function to use or the required variables.
type(tem_varSys_type), intent(in) :: varSys
The variable system to obtain the variable from.
integer, intent(in) :: elempos(:)
Position of the TreeID of the element to get the variable for in the global treeID list.
type(tem_time_type), intent(in) :: time
Point in time at which to evaluate the variable.
type(treelmesh_type), intent(in) :: tree
global treelm mesh info
integer, intent(in) :: nElems
Number of values to obtain for this variable (vectorized access).
integer, intent(in) :: nDofs
Number of degrees of freedom within an element.
real(kind=rk), intent(out) :: res(:)
Resulting values for the requested variable.
Linearized array dimension: (n requested entries) x (nComponents of this variable) x (nDegrees of freedom) Access: (iElem-1)fun%nComponentsnDofs + (iDof-1)*fun%nComponents + iComp
Calls
Source Code
  recursive subroutine getElemWeight( fun, varsys, elempos, time, tree, &
    &                                 nElems, nDofs, res                )
    ! -------------------------------------------------------------------- !
    !> Description of the method to obtain the variables, here some preset
    !! values might be stored, like the space time function to use or the
    !! required variables.
    class(tem_varSys_op_type), intent(in) :: fun
    !> The variable system to obtain the variable from.
    type(tem_varSys_type), intent(in) :: varSys
    !> Position of the TreeID of the element to get the variable for in the
    !! global treeID list.
    integer, intent(in) :: elempos(:)
    !> Point in time at which to evaluate the variable.
    type(tem_time_type), intent(in)  :: time
    !> global treelm mesh info
    type(treelmesh_type), intent(in) :: tree
    !> Number of values to obtain for this variable (vectorized access).
    integer, intent(in) :: nElems
    !> Number of degrees of freedom within an element.
    integer, intent(in) :: nDofs
    !> Resulting values for the requested variable.
    !!
    !! Linearized array dimension:
    !! (n requested entries) x (nComponents of this variable)
    !! x (nDegrees of freedom)
    !! Access: (iElem-1)*fun%nComponents*nDofs +
    !!         (iDof-1)*fun%nComponents + iComp
    real(kind=rk), intent(out) :: res(:)
    ! -------------------------------------------------------------------- !
    ! local variable
    integer :: iElem
    real(kind=rk), allocatable :: weights(:)
    logical :: has_weights
    ! -------------------------------------------------------------------- !
    allocate(weights(tree%nElems))
    call tem_load_weights( me      = tree,       &
      &                    weights = weights,    &
      &                    success = has_weights )
    res = 0.0_rk
    if (has_weights) then
      do iElem = 1, nElems
        res((iElem-1)*nDofs+1) = weights( elemPos(iElem) )
      end do  ! iElem
    end if
    if (time%sim < 0.0_rk) then
      write(logUnit(10),*) 'Negative time for variable ', &
        &                  trim(varSys%varName%val(fun%myPos))
    end if
  end subroutine getElemWeight
Call graph
getelemweight calls tem_load_weights
tem_load_weights calls mpi_bcast, mpi_file_close, mpi_file_get_size, mpi_file_open, mpi_file_read_all, mpi_file_set_view, mpi_type_commit, mpi_type_contiguous, mpi_type_free, mpi_type_size, check_mpi_error, tem_create_endiansuffix, tem_levelof
check_mpi_error calls mpi_error_string, tem_abort
tem_abort calls mpi_abort