hankel2_n – Treelm
hankel2_n Function
6 statements
Source File
private function hankel2_n(n, x) result(val)
Compute Hankel function of second kind of order n.
Arguments
Type Intent Optional Attributes Name
integer :: n
The order of the function.
real(kind=rk), intent(in) :: x
The evaluation point.
Return Value complex(kind=rk)
The function value.
Called by
Source Code
  function hankel2_n(n,x) result(val)
    ! --------------------------------------------------------------------------
    !> The order of the function.
    integer :: n
    !> The evaluation point.
    real(kind=rk), intent(in) :: x
    !> The function value.
    complex(kind=rk) :: val
    ! --------------------------------------------------------------------------
    ! --------------------------------------------------------------------------
    val = bessel_jn(n, x) - (0.0_rk, 1.0_rk)*bessel_yn(n, x)
  end function hankel2_n
Call graph
hankel2_n_derivative calls hankel2_n
tem_eval_miescatter_displz calls hankel2_n
tem_eval_miescatter_magnradial calls hankel2_n
tem_init_data calls hankel2_n, hankel2_n_derivative
tem_eval_miescatter_magnangular calls hankel2_n_derivative
tem_eval_miescatter_magnx calls tem_eval_miescatter_magnradial, tem_eval_miescatter_magnangular
tem_eval_miescatter_magny calls tem_eval_miescatter_magnradial, tem_eval_miescatter_magnangular
tem_load_miescatter calls tem_init_data
tem_spacetime_for_coord calls tem_eval_miescatter_displz, tem_eval_miescatter_magnx, tem_eval_miescatter_magny
tem_spatial_for_coord calls tem_eval_miescatter_displz, tem_eval_miescatter_magnx, tem_eval_miescatter_magny
tem_load_miescatter_displacementfieldz calls tem_load_miescatter
tem_load_miescatter_magneticfieldx calls tem_load_miescatter
tem_load_miescatter_magneticfieldy calls tem_load_miescatter
tem_spacetime_for calls tem_spacetime_for_coord
tem_spatial_for calls tem_spatial_for_coord
tem_spacetime_for_stcoord calls tem_spacetime_for_coord
tem_spacetime_scalar_for_index calls tem_spacetime_for_coord
tem_spatial_scalar_for_index calls tem_spatial_for_coord