hvs_vtk_close – Treelm
hvs_vtk_close Subroutine
7 statements
Source File
public subroutine hvs_vtk_close(vtk_file, proc)
This routine finalizes the vtu file i.e closing cellData xml and creating pvtu file to combile all parallel vtu files
Arguments
Type Intent Optional Attributes Name
type(hvs_vtk_file_type), intent(in) :: vtk_file
The file descriptor to close again.
type(tem_comm_env_type), intent(in) :: proc
Communicator for the parallel environment.
Calls
Called by
Source Code
  subroutine hvs_vtk_close( vtk_file, proc )
    !> The file descriptor to close again.
    type(hvs_vtk_file_type), intent(in) :: vtk_file
    !> Communicator for the parallel environment.
    type(tem_comm_env_type), intent(in) :: proc
    ! ----------------------------------------------------------------------!
    write(logUnit(0),*) 'Using dummy hvs_vtk_close because'
    write(logUnit(0),*) 'executable is configured with --no_vtk'
    call tem_abort()
  end subroutine hvs_vtk_close
Call graph
hvs_vtk_close calls tem_abort
tem_abort calls mpi_abort
hvs_output_close calls hvs_vtk_close
tem_tracker calls hvs_output_close