hvs_banner – Treelm
hvs_banner Subroutine
22 statements
Source File
public subroutine hvs_banner(solveHead, supportSolName)
Print harvester banner to screen
Arguments
Type Intent Optional Attributes Name
type(tem_solveHead_type) :: solveHead
character(len=*) :: supportSolName
Name of the solver which invokes this routine
Calls
Source Code
  subroutine hvs_banner( solveHead, supportSolName )
    ! ---------------------------------------------------------------------------
    type( tem_solveHead_type )  :: solveHead
    !> Name of the solver which invokes this routine
    character(len=*) :: supportSolName
    ! ---------------------------------------------------------------------------
    character(len=26) :: dat_string
    ! ---------------------------------------------------------------------------
    write(logunit(0),*)"                                                          "
    write(logunit(0),*)"        __                               __               "
    write(logunit(0),*)"       / /_  ____  ______   _____  _____/ /____  _____    "
    write(logunit(0),*)"      / __ \/ __ \/ ___/ | / / _ \/ ___/ __/ _ \/ ___/    "
    write(logunit(0),*)"     / / / / /_/ / /   | |/ /  __(__  ) /_/  __/ /        "
    write(logunit(0),*)"    /_/ /_/\____/_/    |___/\___/____/\__/\___/_"         &
      &                                                  //trim(solveHead%version)
    write(logunit(0),*)"                                                          "
    write(logunit(0),*)" (C) 2012 German Research School for Simulation Sciences  "
    write(logunit(0),*)"                                                          "
    call tem_print_execInfo()
    write(logunit(0),*)""
    write(logunit(0),*)"With "//trim(supportSolName)//" support."
    write(logunit(0),*)""
    dat_string = utc_date_string()
    write(logUnit(1),*)"Run at: "//trim(dat_string)
    write(logUnit(1),*)""
    write(logunit(0),*)"----------------------------------------------------------"
  end subroutine hvs_banner
Call graph
hvs_banner calls tem_print_execinfo, utc_date_string
tem_print_execinfo calls tem_horizontalspacer