hvs_output_close – Treelm
hvs_output_close Subroutine
14 statements
Source File
public subroutine hvs_output_close(out_file, mesh, varsys, subtree)
Close all files open for current time step.
Arguments
Type Intent Optional Attributes Name
type(hvs_output_file_type), intent(inout) :: out_file
type(treelmesh_type), intent(in) :: mesh
Mesh to write the data on.
type(tem_varSys_type), intent(in) :: varsys
Description of the available variable system to get the given varnames from.
type(tem_subTree_type), intent(in), optional :: subtree
Optional restriction of the elements to output.
Calls
Called by
Source Code
  subroutine hvs_output_close(out_file, mesh, varSys, subTree)
    ! --------------------------------------------------------------------------!
    type(hvs_output_file_type), intent(inout) :: out_file
    !> Description of the available variable system to get the given varnames
    !! from.
    type(tem_varSys_type), intent(in) :: varsys
    !> Mesh to write the data on.
    type(treelmesh_type), intent(in) :: mesh
    !> Optional restriction of the elements to output.
    type(tem_subtree_type), optional, intent(in) :: subtree
    ! --------------------------------------------------------------------------!
    select case(out_file%vis_kind)
    case(hvs_AsciiSpatial)
      call hvs_asciiSpatial_close( asciiSpatial = out_file%asciiSpatial )
    case(hvs_Internal)
      call tem_restart_closeWrite( me      = out_file%restart, &
        &                          tree    = mesh,             &
        &                          timing  = out_file%time,    &
        &                          varSys  = varSys,         &
        &                          subTree = subTree           )
    case(hvs_VTK)
      call hvs_vtk_close( vtk_file = out_file%vtk, &
        &                 proc     = out_file%proc )
    end select
  end subroutine hvs_output_close
Call graph
hvs_output_close calls hvs_asciispatial_close, hvs_vtk_close, tem_restart_closewrite
hvs_vtk_close calls tem_abort
tem_restart_closewrite calls mpi_barrier, mpi_file_close, check_mpi_error, tem_restart_writedata, tem_restart_writeheader
check_mpi_error calls tem_abort, mpi_error_string
tem_abort calls mpi_abort
tem_restart_writedata calls check_mpi_error, mpi_file_write_all
tem_restart_writeheader calls aot_out_close, aot_out_close_table, aot_out_open, aot_out_open_table, aot_out_val, tem_varsys_out, newunit, tem_mesh_out, tem_open, tem_time_out
tem_varsys_out calls tem_varsys_out_single, tem_varsys_out_vector
tem_mesh_out calls aot_out_close_table, aot_out_open_table, aot_out_val
tem_open calls tem_abort, newunit, upper_to_lower
tem_time_out calls aot_out_close_table, aot_out_open_table, aot_out_val
tem_tracker calls hvs_output_close