hvs_vtk_dump_data – Treelm
hvs_vtk_dump_data Subroutine
11 statements
Source File
public subroutine hvs_vtk_dump_data(vtk_file, varpos, varsys, mesh, time, subtree)
Dump the given data (input) with the given name in the given format (vtu) to the given unit.
Arguments
Type Intent Optional Attributes Name
type(hvs_vtk_file_type), intent(in) :: vtk_file
VTK file to write data to.
integer, intent(in) :: varpos
Position of the variable to write
type(tem_varSys_type), intent(in) :: varsys
Description of the available variable system to get the given varnames from.
type(treelmesh_type), intent(in) :: mesh
Mesh to write the data on.
type(tem_time_type), intent(in) :: time
Point in time to use for this data.
Can be important for space-time function evaluations.
type(tem_subTree_type), intent(in), optional :: subtree
Optional restriction of the elements to output.
Calls
Called by
Source Code
  subroutine hvs_vtk_dump_data( vtk_file, varpos, varSys, mesh, time, subtree )
    !> VTK file to write data to.
    type(hvs_vtk_file_type), intent(in) :: vtk_file
    !> Position of the variable to write
    integer, intent(in) :: varpos
    !> Description of the available variable system to get the given varnames
    !! from.
    type(tem_varSys_type), intent(in) :: varsys
    !> Mesh to write the data on.
    type(treelmesh_type), intent(in) :: mesh
    !> Point in time to use for this data.
    !!
    !! Can be important for space-time function evaluations.
    type(tem_time_type), intent(in) :: time
    !> Optional restriction of the elements to output.
    type(tem_subtree_type), optional, intent(in) :: subtree
    ! ----------------------------------------------------------------------!
    write(logUnit(0),*) 'Using dummy hvs_vtk_dump_data because'
    write(logUnit(0),*) 'executable is configured with --no_vtk'
    call tem_abort()
  end subroutine hvs_vtk_dump_data
Call graph
hvs_vtk_dump_data calls tem_abort
tem_abort calls mpi_abort
hvs_output_write calls hvs_vtk_dump_data
tem_tracker calls hvs_output_write