hvs_vtk_init – Treelm
hvs_vtk_init Subroutine
8 statements
Source File
public subroutine hvs_vtk_init(vtk_file, vtk_config, basename, proc)
Initialize the type for VTK format
Arguments
Type Intent Optional Attributes Name
type(hvs_vtk_file_type), intent(inout) :: vtk_file
The file description to open.
type(hvs_vtk_config_type), intent(in) :: vtk_config
User specified settings for the output
character(len=*), intent(in) :: basename
Basename for the output file, rank and suffix will be appended as needed.
type(tem_comm_env_type), intent(in) :: proc
Parallel environment to use for the output.
Calls
Called by
Source Code
  subroutine hvs_vtk_init(vtk_file, vtk_config, basename, proc)
    ! --------------------------------------------------------------------------!
    !> The file description to open.
    type(hvs_vtk_file_type), intent(inout) :: vtk_file
    !> User specified settings for the output
    type(hvs_vtk_config_type), intent(in) :: vtk_config
    !> Basename for the output file, rank and suffix will be appended as
    !! needed.
    character(len=*), intent(in) :: basename
    !> Parallel environment to use for  the output.
    type(tem_comm_env_type), intent(in) :: proc
    ! --------------------------------------------------------------------------!
    write(logUnit(0),*) 'VTK output deactivated in this executable!'
    call tem_abort()
  end subroutine hvs_vtk_init
Call graph
hvs_vtk_init calls tem_abort
tem_abort calls mpi_abort
hvs_output_init calls hvs_vtk_init
tem_init_tracker calls hvs_output_init