ic_gausspulse_for – Treelm
ic_gausspulse_for Function
12 statements
Source File
public function ic_gausspulse_for(me, coord, n) result(res)
This function defines gauss pulse
This function computes gauss pulse for given array co-ordinate points and defined gauss parameters in LUA file. Gauss function: where,
 a - pulse height,
 x - pulse center,
 c - pulse widthn,
 b - position along x
Arguments
Type Intent Optional Attributes Name
type(ic_gausspulse_type), intent(in) :: me
global gauss pulse data
real(kind=rk), intent(in) :: coord(n,3)
coordinate of an element
integer, intent(in) :: n
number of return values
Return Value real(kind=rk), (n)
return value which is sent to state variable
Called by
Source Code
  function ic_gausspulse_for(me, coord, n) result(res)
    ! ---------------------------------------------------------------------------
    !> number of return values
    integer, intent(in) :: n
    !> global gauss pulse data
    type(ic_gausspulse_type), intent(in) :: me
    !> coordinate of an element
    real(kind=rk), intent(in) :: coord(n, 3)
    !> return value which is sent to state variable
    real(kind=rk) :: res(n)
    ! ---------------------------------------------------------------------------
    real(kind=rk) :: distsquare(n)
    real(kind=rk) :: fact
    ! ---------------------------------------------------------------------------
    fact = -log(2.0_rk)/(me%halfwidth**2)
    distsquare = (coord(:,1) - me%center(1))**2                                &
      &        + (coord(:,2) - me%center(2))**2                                &
      &        + (coord(:,3) - me%center(3))**2
    distsquare = fact*distsquare
    res = me%background + (me%amplitude * exp(distsquare))
  end function ic_gausspulse_for
Call graph
tem_spatial_for_coord calls ic_gausspulse_for
tem_spatial_for calls tem_spatial_for_coord, tem_spatial_scalar_for_index
tem_spatial_scalar_for_index calls tem_spatial_for_coord
tem_spacetime_for_coord calls tem_spatial_for
tem_spacetime_for_treeids calls tem_spatial_for
tem_spacetime_scalar_for_index calls tem_spatial_for, tem_spacetime_for_coord
tem_spacetime_vector_for_coord calls tem_spatial_for
tem_spacetime_vector_for_index calls tem_spatial_for, tem_spacetime_vector_for_coord
tem_spacetime_vector_for_treeids calls tem_spatial_for
tem_spatial_scalar_storeval calls tem_spatial_for
tem_spatial_vector_storeval calls tem_spatial_for
tem_spacetime_for calls tem_spacetime_for_coord, tem_spacetime_for_treeids, tem_spacetime_scalar_for_index, tem_spacetime_vector_for_coord, tem_spacetime_vector_for_index, tem_spacetime_vector_for_treeids
tem_spatial_storeval calls tem_spatial_scalar_storeval, tem_spatial_vector_storeval
tem_spacetime_for_stcoord calls tem_spacetime_for_coord