identify_stencilNeigh – Treelm
identify_stencilNeigh Subroutine
29 statements
Source File
public recursive subroutine identify_stencilNeigh(iElem, iLevel, iStencil, tree, pathFirst, pathLast, levelDesc, proc, stencil, nesting)
Invoke the identify_elements for each neighbor of the stencil and store the positions of the encountered elements
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: iElem
element position in levelDesc to identify
integer, intent(in) :: iLevel
element level
integer, intent(in) :: iStencil
stencil within the element to act on
type(treelmesh_type), intent(in) :: tree
tree information
type(tem_path_type), intent(in) :: pathFirst(:)
first treeID path in every process
type(tem_path_type), intent(in) :: pathLast(:)
last treeID path in every process
type(tem_levelDesc_type), intent(inout) :: levelDesc(tree%global%minLevel:)
the level descriptor to be filled
type(tem_comm_env_type), intent(in) :: proc
process
type(tem_stencilHeader_type), intent(in) :: stencil
current stencil definition
integer, intent(in) :: nesting
nesting level
Calls
Called by
Source Code
  recursive subroutine identify_stencilNeigh( iElem, iLevel, iStencil, tree,  &
    &                                         pathFirst, pathLast, levelDesc, &
    &                                         proc, stencil, nesting          )
    ! -------------------------------------------------------------------- !
    !> element position in levelDesc to identify
    integer, intent(in)                      :: iElem
    !> element level
    integer, intent(in)                      :: iLevel
    !> stencil within the element to act on
    integer, intent(in)                      :: iStencil
    !> tree information
    type(treelmesh_type), intent(in)         :: tree
    !> first treeID path in every process
    type(tem_path_type), intent(in)          :: pathFirst(:)
    !> last treeID path in every process
    type(tem_path_type), intent(in)          :: pathLast(:)
    !> the level descriptor to be filled
    type(tem_levelDesc_type), intent(inout)  :: levelDesc(tree%global%minLevel:)
    !> process
    type(tem_comm_env_type), intent(in)      :: proc
    !> current stencil definition
    type(tem_stencilHeader_type), intent(in) :: stencil
    !> nesting level
    integer, intent(in)                      :: nesting
    ! -------------------------------------------------------------------- !
    integer :: iStencilElem, elemPos
    integer :: neighIDpos
    integer(kind=long_k) :: neighID
    ! -------------------------------------------------------------------- !
    ! identify all the compute neighbors of the current element
    do iStencilElem = 1, stencil%QQN
      neighIDpos = levelDesc(iLevel)%elem%stencil%val(iElem)          &
        &                           %val(iStencil)%tIDpos(iStencilElem)
      if( neighIDpos > 0 ) then
        neighID = &
          & levelDesc( iLevel )%elem%neighID%val(iElem)%val(neighIDpos)
        ! This call might add new halo elements
        if ( neighID > 0_long_k ) then
          call identify_elements( TreeID     = neighID,   &
            &                     tree       = tree,      &
            &                     pathFirst  = pathFirst, &
            &                     pathLast   = pathLast,  &
            &                     levelDesc  = levelDesc, &
            &                     elemPos    = elemPos,   &
            &                     proc       = proc,      &
            &                     stencil    = stencil,   &
            &                     nesting    = nesting    )
        else ! neighID < 0
          elemPos = 0
        end if
      else ! neighIDpos < 0
        elemPos = 0
      end if ! neighIDpos > 0
      ! And add the encountered neighbor elements to the current element's
      ! stencil neighbors
      levelDesc(iLevel)%elem%stencil%val(iElem)              &
        &              %val(iStencil)%totalPos(iStencilElem) = elemPos
    end do
  end subroutine identify_stencilNeigh
Call graph
identify_stencilneigh calls identify_elements
identify_elements calls identify_stencilneigh, identify_elements, append, init, create_allparentneighbors, single_process_element, tem_directchildren, tem_find_depproc, tem_levelof, tem_pathof, tem_tidinfo
append calls append_ga_dynlong, append_ga_dynlong_vec
init calls init_ga2d_real
create_allparentneighbors calls identify_stencilneigh, identify_elements, append, tem_parentof
single_process_element calls append, init, tem_levelof, identify_local_element, tem_abort
tem_find_depproc calls tem_find_depproc_globsearch, tem_pathcomparison
tem_tidinfo calls tem_baryofid, tem_coordofid, tem_elemsize
tem_parentof calls tem_directparent, tem_parentatlevel
append_ga_dynlong calls expand
append_ga_dynlong_vec calls expand
identify_local_element calls append, tem_levelof, tem_pathof, tem_tidinfo, positionofval, add_all_virtual_children, add_ghostfromfiner, tem_posofpath
tem_abort calls mpi_abort
tem_baryofid calls tem_coordofid, tem_elemsizelevel
tem_coordofid calls tem_levelof
tem_elemsize calls tem_levelof, tem_elemsizelevel
tem_find_depproc_globsearch calls tem_pathcomparison
request_remotehalos calls identify_stencilneigh, create_allparentneighbors
build_levelelements calls identify_elements, identify_additionalneigh
communicate_elements calls request_remotehalos
identify_additionalneigh calls identify_elements
tem_find_allelements calls build_levelelements, communicate_elements, identify_additionalneigh
tem_create_leveldesc calls tem_find_allelements