identify_halo – Treelm
identify_halo Subroutine
16 statements
Source File
private subroutine identify_halo(haloTreeID, elemPos, haloLevel, levelDesc, tree, updated, nesting, minLevel, stencil)
Map requested halo to a position in my local fluid list or add recursively ghosts until I reach valid fluid elements return type of added element in levelPos(2) Also, non-existing elements are reported as such (levelPos(2))
Arguments
Type Intent Optional Attributes Name
integer(kind=long_k), intent(in) :: haloTreeID
neighboring treeID
integer, intent(out) :: elemPos
type and position in list of found treeID
integer, intent(out) :: haloLevel
type(tem_levelDesc_type), intent(inout) :: levelDesc(minlevel:)
type(treelmesh_type), intent(in) :: tree
logical, intent(out) :: updated
integer, intent(in) :: nesting
integer, intent(in) :: minLevel
type(tem_stencilHeader_type), intent(in) :: stencil
Calls
Called by
Source Code
  subroutine identify_halo( haloTreeID, elemPos, haloLevel, levelDesc, tree,   &
    &                       updated,   nesting, minLevel, stencil )
    ! ---------------------------------------------------------------------------
    !>
    type(treelmesh_type), intent(in) :: tree
    !>
    integer, intent(in) :: minLevel
    !>
    integer, intent(in) :: nesting
    !> neighboring treeID
    integer(kind=long_k), intent(in) :: haloTreeID
    !> type and position in list of found treeID
    integer, intent(out) :: elemPos
    !>
    integer, intent(out) :: haloLevel
    !>
    logical, intent(out) :: updated
    !>
    type(tem_levelDesc_type), intent(inout) :: levelDesc(minlevel:)
    !>
    type(tem_stencilHeader_type), intent(in) :: stencil
    ! ---------------------------------------------------------------------------
    haloLevel = tem_levelOf( haloTreeID )
    elemPos = PositionOfVal( me  = levelDesc( halolevel )%elem%tID,            &
      &                      val = haloTreeID )
    if( elemPos == 0 ) then
      ! requested halo does not exist and has to be created somehow
      call identify_local_element( targetID       = haloTreeID,                &
        &                          levelDesc      = levelDesc,                 &
        &                          tree           = tree,                      &
        &                          elemPos        = elemPos,                   &
        &                          nesting        = nesting,                   &
        &                          updated        = updated,                   &
        &                          minLevel       = minLevel,                  &
        &                          stencil = stencil )
    end if
  end subroutine identify_halo
Call graph
identify_halo calls positionofval, identify_local_element, tem_levelof
positionofval calls posofval_label
identify_local_element calls positionofval, tem_levelof, append, add_all_virtual_children, add_ghostfromfiner, tem_pathof, tem_posofpath, tem_tidinfo
append calls append_ga_dynlong, append_ga_dynlong_vec
add_all_virtual_children calls positionofval, tem_levelof, append, add_all_virtual_children, init, tem_childnumber, tem_coordofid, tem_find_bcs_fromcoarser, tem_idofcoord
add_ghostfromfiner calls positionofval, tem_levelof, append, add_ghostfromfiner, tem_pathof, tem_posofpath, tem_directchildren, tem_find_bcs_fromfiner
posofval_label calls sortedposofval
tem_tidinfo calls tem_baryofid, tem_coordofid, tem_elemsize
init calls init_ga2d_real
sortedposofval calls sortposofval_label
append_ga_dynlong calls expand
append_ga_dynlong_vec calls expand
tem_baryofid calls tem_coordofid, tem_elemsizelevel
tem_coordofid calls tem_levelof
tem_elemsize calls tem_levelof, tem_elemsizelevel
tem_find_bcs_fromcoarser calls childtostencil
tem_find_bcs_fromfiner calls append, init, stenciltochild, update_childneighborid
request_remotehalos calls identify_halo
communicate_elements calls request_remotehalos
tem_find_allelements calls communicate_elements
tem_create_leveldesc calls tem_find_allelements