init_da_label – Treelm
init_da_label Subroutine
14 statements
Source File
public subroutine init_da_label(me, length)
initialization of a dynamic array
before a dynamic array can be used, it has to be initialized with this routine. the initial length provided here, can avoid reallocations and memory copying, if approximated correctly enough. if none is specified, the provided container initially will be of size 0.
Arguments
Type Intent Optional Attributes Name
type(dyn_labelarray_type), intent(out) :: me
integer, intent(in), optional :: length
Called by
Source Code
  subroutine init_da_label(me, length)
    !-----------------------------------------------------------------
    type(dyn_labelarray_type), intent(out) :: me !< dynamic array to init
    integer, intent(in), optional :: length !< initial length of the container
    !-----------------------------------------------------------------
    if (present(length)) then
      me%containersize = length
    else
      me%containersize = zerolength
    end if
    ! deallocate ...
    if( allocated( me%val ) ) deallocate(me%val)
    if( allocated( me%sorted ) ) deallocate(me%sorted)
    ! ... and reallocate
    allocate(me%val(me%containersize))
    allocate(me%sorted(me%containersize))
    me%nvals = 0
  end subroutine init_da_label
Call graph
init calls init_da_label, init_possible_variable
init_possible_variable calls init
sorttruncate_da_int calls init
sorttruncate_da_label calls init
sorttruncate_da_long calls init
sorttruncate_da_real calls init
tem_create_varmap calls init
tem_varsys_init calls init
tem_varsys_load_single calls init
sorttruncate calls sorttruncate_da_long, sorttruncate_da_int, sorttruncate_da_real, sorttruncate_da_label
tem_varsys_load calls tem_varsys_load_single, tem_varsys_load_vector
hvs_output_init calls tem_create_varmap
tem_init_convergence calls tem_create_varmap
tem_init_depend calls tem_create_varmap
tem_init_tracker calls tem_create_varmap, hvs_output_init
tem_opvar_reduction_transient_init calls tem_create_varmap
tem_varsys_load_vector calls tem_varsys_load_single
tem_restart_readheader calls tem_varsys_load