init_tem_bc_prop – Treelm
init_tem_bc_prop Subroutine
28 statements
Source File
public subroutine init_tem_bc_prop(tree, mypart, comm, bc)
Initialize boundary conditions of a given tree.
Arguments
Type Intent Optional Attributes Name
type(treelmesh_type), intent(in) :: tree
integer, intent(in) :: mypart
integer, intent(in) :: comm
Communicator to use
type(tem_BC_prop_type), intent(out) :: bc
Calls
Source Code
  subroutine init_tem_bc_prop( tree, mypart, comm, bc )
    ! ---------------------------------------------------------------------------
    type(treelmesh_type), intent(in)    :: tree
    integer, intent(in)                 :: mypart
    !> Communicator to use
    integer, intent(in) :: comm
    type(tem_bc_prop_type), intent(out) :: bc
    ! ---------------------------------------------------------------------------
    integer :: iprop
    logical :: found_bc
    ! ---------------------------------------------------------------------------
    iProp = tem_bc_prop_pos(tree)
    found_bc = iProp > 0
    if (found_bc) then
      bc%header => tree%global%Property(iprop)
      bc%property => tree%property(iprop)
      select case(trim(bc%header%label))
      case('internal 0D BC')
        call load_bc_intern_0D(tree = tree, me = bc)
      case('internal 1D BC')
        call load_bc_intern_1D(tree = tree, me = bc, xbounds=.false.)
      case('bounded internal 1D BC')
        call load_bc_intern_1D(tree = tree, me = bc, xbounds=.true.)
      case('internal 2D BC')
        call load_bc_intern_2D(tree = tree, me = bc)
      case default
        call load_tem_bc_prop(me       = bc,                               &
          &                   offset   = bc%property%Offset,               &
          &                   nElems   = bc%property%nElems,               &
          &                   basename = trim(tree%global%dirname)//'bnd', &
          &                   comm     = comm,                             &
          &                   mypart   = mypart                            )
      end select
    else
      call tem_empty_BC_prop(bc)
    end if
  end subroutine init_tem_bc_prop
Call graph
init_tem_bc_prop calls load_bc_intern_0d, load_bc_intern_1d, load_bc_intern_2d, load_tem_bc_prop, tem_bc_prop_pos, tem_empty_bc_prop
load_bc_intern_1d calls tem_coordofid, tem_firstidatlevel, tem_idofcoord
load_bc_intern_2d calls tem_coordofid, tem_idofcoord
load_tem_bc_prop calls aot_get_val, aot_table_close, aot_table_open, close_config, mpi_bcast, mpi_comm_rank, mpi_comm_split, mpi_file_close, mpi_file_open, mpi_file_read_all, mpi_file_set_view, mpi_type_commit, mpi_type_contiguous, mpi_type_free, mpi_type_size, open_config_file, check_mpi_error, tem_create_endiansuffix, tem_open