load_tem_BC_normal – Treelm
load_tem_BC_normal Subroutine
11 statements
Source File
public subroutine load_tem_BC_normal(me, offset, nElems, basename, myPart, comm)
load bc qVal header from lua file, qVal from qVal.lsb
Arguments
Type Intent Optional Attributes Name
type(tem_BC_prop_type), intent(inout) :: me
Boundary condition construct to load the data into
integer(kind=long_k), intent(in) :: offset
Offset of the local set of elements in the global list
integer, intent(in) :: nElems
Local number of elements that have qVal
character(len=*), intent(in) :: basename
Name of the file, the data is stored in, will be appended with ".lua" for the header information and ".lsb" or ".msb" for the binary data.
integer, intent(in) :: myPart
Partition to load
integer, intent(in) :: comm
Communicator to use
Calls
Source Code
  subroutine load_tem_BC_normal( me, offset, nElems, basename, myPart, comm )
    ! ---------------------------------------------------------------------------
    !> Boundary condition construct to load the data into
    type(tem_BC_prop_type), intent(inout) :: me
    !> Offset of the local set of elements in the global list
    integer(kind=long_k), intent(in)      :: offset
    !> Local number of elements that have qVal
    integer, intent(in)                   :: nElems
    !> Name of the file, the data is stored in, will be appended with
    !! ".lua" for the header information and ".lsb" or ".msb" for the
    !! binary data.
    character(len=*), intent(in)          :: basename
    !> Partition to load
    integer, intent(in)                   :: myPart
    !> Communicator to use
    integer, intent(in)                   :: comm
    ! ---------------------------------------------------------------------------
    ! ---------------------------------------------------------------------------
    call load_tem_BC_logicalHeader( nBCtypes = me%nBCtypes,     &
      &                             propName = 'hasNormal',     &
      &                             basename = basename,        &
      &                             flag_per_BC = me%hasNormal, &
      &                             myPart   = myPart,          &
      &                             comm     = comm             )
    allocate(me%normal(3, nElems))
    call load_tem_BC_realArray( offset   = offset,      &
      &                         propname = 'hasNormal', &
      &                         arraylen = 3,           &
      &                         nElems   = nElems,      &
      &                         propdat  = me%normal,   &
      &                         basename = basename,    &
      &                         myPart   = myPart,      &
      &                         comm     = comm         )
  end subroutine load_tem_BC_normal
Call graph
load_tem_bc_normal calls load_tem_bc_logicalheader, load_tem_bc_realarray
load_tem_bc_logicalheader calls aot_get_val, aot_table_close, aot_table_open, close_config, mpi_bcast, open_config_file
load_tem_bc_realarray calls mpi_comm_split, mpi_file_close, mpi_file_open, mpi_file_read_all, mpi_file_set_view, mpi_type_commit, mpi_type_contiguous, mpi_type_free, mpi_type_size, check_mpi_error, tem_create_endiansuffix
check_mpi_error calls mpi_error_string, tem_abort
tem_abort calls mpi_abort