load_spatial_parabol – Treelm
load_spatial_parabol Subroutine
23 statements
Source File
private subroutine load_spatial_parabol(me, conf, thandle, nComp)
This subroutine load 3d parabola type variables from LUA file.
Specify amplitude to size of nComp in spatial block. If amplitude is not defined, it set to 1.0_rk for all components Valid definition:
2D parabola
 spatial = {predefined='parabol', shape = { center/origin={-5.0, 0.0, 0.0},
                                            vec={0.0, 1.0, 0.0}},
                                            amplitude = 0.01}
 where, center - line center.
        origin - line origin. (define either center or origin)
        vec    - length of the line.
Parabolic 2D profile at channel inlet.
3D parabola
 spatial = {
   predefined = 'parabol',
   shape = {
     center/origin = {-5.0, 0.0, 0.0},
     vec = {
       {0.0, 1.0, 0.0},
       {1.0, 0.0, 0.0}
     },
     amplitude = 0.01
  }
 where, center - plane center.
        origin - plane origin. (define either center or origin)
        vec    - length of the plane in 2 direction.
        amplitude - maximum value
Parabolic 3D profile at channel inlet.
Example: Inlet velocity at inlet plane with velocity along x-dir with a maximum velocity 0.08. Inlet plane is normal to x-dir and located at offset of {-5,0,0} from origin. The plane spans -1 to 1 in both y and z-dir.
 boundary_condition = {
   {
     label = 'inlet',
     kind = 'inlet_ubb',
     velocityX = {
       kind = 'combined',
       spatial = {
         predefined='parabol',
         shape = {
           origin = {-5.0, 0.0, 0.0},
           vec={ {0.0, 1.0, 0.0}, {0.0, 0.0, 1.0} }
         },
         amplitude = 0.01
       }
     },
     velocityY = 0.0
     velocityZ = 0.0
   }
 }
  _______vecB____
 |       |      |
 |       |      |
 |       |______|vecA
 |     center   |
 |              |
 |______________|_
Arguments
Type Intent Optional Attributes Name
type(spatial_parabol_type), intent(out) :: me
parabola3d spatial datas
type(flu_State) :: conf
lua state type
integer, intent(in) :: thandle
aotus parent handle
integer, intent(in) :: nComp
Number of components
Calls
Called by
Source Code
  subroutine load_spatial_parabol( me, conf, thandle, nComp )
    ! -------------------------------------------------------------------- !
    !> parabola3d spatial datas
    type(spatial_parabol_type),intent(out) :: me
    !> lua state type
    type(flu_State) :: conf
    !> aotus parent handle
    integer, intent(in) :: thandle
    !> Number of components
    integer, intent(in) :: nComp
    ! -------------------------------------------------------------------- !
    integer :: iError
    ! -------------------------------------------------------------------- !
    ! load geometry
    call tem_load_shape( conf    = conf,       &
      &                  parent  = thandle,    &
      &                  me      = me%geometry )
    if (size(me%geometry%canoND) /= 1) then
      write(logUnit(1),*) 'Error: Requires single shape for spatial "parabol"'
      call tem_abort()
    end if
    call load_spatial_asConst( const   = me%amplitude, &
      &                        conf    = conf,         &
      &                        errCode = iError,       &
      &                        parent  = thandle,      &
      &                        key     = 'amplitude',  &
      &                        nComp   = nComp         )
    if ( iError /= 0 ) then
      write(logUnit(1),*) 'Warning: amplitude is not defined.'
      write(logUnit(1),*) '         Set to default value 1.0 for all components'
      me%amplitude = ref_amp
    end if
    if (nComp == 1) then
      write(logUnit(5),"(A)") ' amplitude = ' &
        & // trim(tem_toStr(me%amplitude(1)))
    else
      write(logUnit(5),"(A)") ' amplitude = ' &
        & // trim(tem_toStr(me%amplitude(1:nComp),','))
    end if
  end subroutine load_spatial_parabol
Call graph
load_spatial_parabol calls tem_load_shape, tem_tostr, load_spatial_asconst, tem_abort
tem_load_shape calls tem_load_shape_single, tem_load_shapes
tem_tostr calls tem_b2str, tem_b2str_arr, tem_d2str, tem_d2str_arr, tem_i2str, tem_i2str_arr, tem_l2str, tem_l2str_arr, tem_r2str, tem_r2str_arr
load_spatial_asconst calls tem_abort, aot_get_val
tem_abort calls mpi_abort
tem_load_shape_single calls tem_abort, aot_get_val, aot_table_close, aot_table_open, tem_load_canonicalnd, tem_load_stl, tem_load_transformation, tem_shape_load_bclabels, tem_shape_load_level, tem_shape_load_proplabel, tem_load_cylinder, tem_load_ellipsoid, tem_load_sphere, tem_load_triangle
tem_load_shapes calls tem_load_shape_single, aot_table_close, aot_table_length, aot_table_open
load_spatial_predefined calls load_spatial_parabol
tem_load_spatial calls load_spatial_predefined
load_spacetime_predefined calls tem_load_spatial
tem_load_ic calls tem_load_spatial
tem_load_spacetime_single calls load_spacetime_predefined