logicalToRealArray – Treelm
logicalToRealArray Function
7 statements
Source File
public function logicalToRealArray(value, n) result(res)
Converts an array of logicals into an array of reals.
0 equals to false, everything else equals to true.
Arguments
Type Intent Optional Attributes Name
logical, intent(in) :: value(n)
The value to interpret as boolean
integer, intent(in) :: n
The number of values in the input array
Return Value real(kind=rk), (n)
The values interpreted as booleans
Called by
Source Code
  function logicalToRealArray(value,n) result(res)
    ! ------------------------------------------------------------------------ !
    !> The number of values in the input array
    integer, intent(in) :: n
    !> The value to interpret as boolean
    logical, intent(in) :: value(n)
    !> The values interpreted as booleans
    real(kind=rk) :: res(n)
    ! ------------------------------------------------------------------------ !
    res = numFalse
    where(value) res = numTrue
  end function logicalToRealArray
Call graph
evallogicaland_forpoint calls logicaltorealarray
evallogicaland_fromindex calls logicaltorealarray
evallogicalgreater_forpoint calls logicaltorealarray
evallogicalgreater_fromindex calls logicaltorealarray
evallogicalgreaterorequal_forpoint calls logicaltorealarray
evallogicalgreaterorequal_fromindex calls logicaltorealarray
evallogicalless_forpoint calls logicaltorealarray
evallogicalless_fromindex calls logicaltorealarray
evallogicallessorequal_forpoint calls logicaltorealarray
evallogicallessorequal_fromindex calls logicaltorealarray
evallogicalor_forpoint calls logicaltorealarray
evallogicalor_fromindex calls logicaltorealarray