logicalToReal – Treelm
logicalToReal Function
9 statements
Source File
public function logicalToReal(value) result(res)
Converts a logical into a real.
0 equals to false, everything else equals to true.
Arguments
Type Intent Optional Attributes Name
logical, intent(in) :: value
The value to interpret as boolean
Return Value real(kind=rk)
The value interpreted as boolean
Called by
Source Code
  function logicalToReal(value) result(res)
    ! ------------------------------------------------------------------------ !
    !> The value to interpret as boolean
    logical, intent(in) :: value
    !> The value interpreted as boolean
    real(kind=rk) :: res
    ! ------------------------------------------------------------------------ !
    if (value) then
      res = numTrue
    else
      res = numFalse
    end if
  end function logicalToReal
Call graph
evallogicaland_forelement calls logicaltoreal
evallogicalequal_forelement calls logicaltoreal
evallogicalgreater_forelement calls logicaltoreal
evallogicalgreaterorequal_forelement calls logicaltoreal
evallogicalless_forelement calls logicaltoreal
evallogicallessorequal_forelement calls logicaltoreal
evallogicalnotequal_forelement calls logicaltoreal
evallogicalor_forelement calls logicaltoreal