newunit – Treelm
newunit Function
11 statements
Source File
public function newunit() result(nu)
Helper function to provide new unit, as long as F2008 newunit argument in open statement is not commonly available. To be used right in front of the open statement like this: myUnit = newunit() open(myUnit, ...)
Arguments
None
Return Value integer
Called by
Source Code
  function newunit() result(nu)
    ! ---------------------------------------------------------------------------
    ! Melven Zoellner:
    ! for the solspecunit and in other places the unit is not kept open,
    ! so this does only work correctly if we count up over different calls
    ! to this function, currently not thread save...
    !HK: Sorry this is not the task of newunit, it is supposed to serve
    !HK: as an replacement for the new_unit keyword in the open statement
    !HK: of Fortran, which will definitely not keep track of the units
    !HK: opened so far. Also for iterative calls to newunit, you could
    !HK: reach the limit of integers easily!
    !HK: If you need to keep track of a file over closes and subsequent
    !HK: reopenings, you need to do this in some other way!
    integer :: nu
    ! ---------------------------------------------------------------------------
    integer, parameter :: nu_start = 22
    logical :: connected
    ! ---------------------------------------------------------------------------
    nu = nu_start
    inquire(unit=nu, opened=connected)
    do while(connected)
      nu = nu + 1
      inquire(unit=nu, opened=connected)
    end do
  end function newunit
Call graph
my_status_string calls newunit
my_status_string_vec calls newunit
print_self_status calls newunit
tem_connect_tonull calls newunit
tem_init_restart calls newunit
tem_logging_init_logger calls newunit
tem_open calls newunit
tem_probing_delete calls newunit
tem_probing_write calls newunit
tem_restart_writeheader calls newunit
tem_stop_file_exists calls newunit