placeat_ga_grw_stencilelement – Treelm
placeat_ga_grw_stencilelement Subroutine
11 statements
Source File
private subroutine placeat_ga_grw_stencilelement(me, val, pos, length)
adds the value to a given position inside the growing array.
if the requested position is outside the current array bounds, the array will be resized accordingly. if it is inside the current array bounds, the element at the requested position will be replaced.
Arguments
Type Intent Optional Attributes Name
type(grw_grw_stencilelementarray_type) :: me
type(grw_stencilelementarray_type), intent(in) :: val
integer, intent(in) :: pos
integer, intent(in), optional :: length
optional length to expand the array
Calls
Called by
Source Code
  subroutine placeat_ga_grw_stencilelement(me, val, pos, length)
    type(grw_grw_stencilelementarray_type) :: me !< array to place the value into
    type(grw_stencilelementarray_type), intent(in) :: val !< value to place at the given position
    integer, intent(in) :: pos !< predefined position
    !> optional length to expand the array
    integer, intent(in), optional :: length
    ! value to append is larger than all existing ones,
    ! just put it to the end of the list, this captures
    ! also the case of empty lists.
    ! in this case foundpos = me%nvals + 1 holds.
    if (pos > me%containersize) then
      ! expand the array, if its boundary is reached
      call expand(me = me, pos = pos, length = length)
    end if
    me%nvals = max( pos, me%nvals )
    me%val(pos) = val
  end subroutine placeat_ga_grw_stencilelement
Call graph
placeat_ga_grw_stencilelement calls expand
expand calls expand_ga_dynlong
placeat calls placeat_ga_grw_stencilelement