posofval_label – Treelm
posofval_label Function
20 statements
Source File
public function posofval_label(me, val, nextifnotfound, lower, upper) result(pos)
the actual position of a given value in the dynamic array
most likely this is what you need in codes, using this data structure, it first does the binary search on the sorted values with sortposofval_label and then returns the looked up position in the original unsorted array, which corresponds to the position returned by the append routine.
Arguments
Type Intent Optional Attributes Name
type(dyn_labelarray_type), intent(in) :: me
character(len=*), intent(in) :: val
logical, intent(in), optional :: nextifnotfound
flag to indicate, if the position of the next entry in the sorted list should be returned instead, if val is not found.
integer, intent(in), optional :: lower
integer, intent(in), optional :: upper
Return Value integer
Calls
Called by
Source Code
  function posofval_label(me, val, nextifnotfound, lower, upper) result(pos)
    !------------------------------------------------------------------------
    type(dyn_labelarray_type), intent(in) :: me !< dynamic array
    character(len=*), intent(in) :: val !< value to search for
    !> flag to indicate, if the position of the next entry in the sorted
    !! list should be returned instead, if val is not found.
    logical, intent(in), optional :: nextifnotfound
    integer, intent(in), optional :: lower !< lower search limit
    integer, intent(in), optional :: upper !< upper search limit
    integer :: pos !< position in the array of the searche value, 0 if not found
    !------------------------------------------------------------------------
    integer :: sortpos
    integer :: lb, ub
    !------------------------------------------------------------------------
    lb = 1
    ub = me%nvals
    if( present( lower ) ) lb = lower
    if( present( upper ) ) ub = upper
    sortpos = sortedposofval(me, val, nextifnotfound, lb, ub)
    ! if result (sorted pos)
    if ((sortpos <= me%nvals) .and. (sortpos > 0)) then
      pos = me%sorted(sortpos)
    else
      pos = sortpos
    end if
  end function posofval_label
Call graph
posofval_label calls sortedposofval
sortedposofval calls sortposofval_label
positionofval calls posofval_label
add_all_virtual_children calls positionofval
add_ghostfromfiner calls positionofval
check_opvar_prerequisites calls positionofval
identify_additionalneigh calls positionofval
identify_halo calls positionofval
identify_local_element calls positionofval
request_remotehalos calls positionofval
setup_indices_spacetime calls positionofval
tem_adapt_dump_newmesh calls positionofval
tem_adddep_down calls positionofval
tem_adddep_up calls positionofval
tem_appendface_prp calls positionofval
tem_build_facerecvbuffers calls positionofval
tem_build_facesendbuffers calls positionofval
tem_build_treehorizontaldep calls positionofval
tem_comm_createbuffer calls positionofval
tem_create_varmap calls positionofval
tem_debug_horizontaldependencies calls positionofval
tem_etypeofid calls positionofval
tem_timer_dumplabeled calls positionofval
tem_varsys_append_dervar calls positionofval
tem_varsys_append_luavar calls positionofval