print_nElems – Treelm
print_nElems Subroutine
8 statements
Source File
public subroutine print_nElems(nElems, outUnit)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nElems(eT_minRelevant:eT_maxRelevant)
integer, intent(in) :: outUnit
Called by
Call graph
assemble_lists calls print_nelems
tem_dumptreeidlists calls print_nelems
tem_find_allelements calls assemble_lists
tem_create_leveldesc calls tem_find_allelements
tem_dimbydim_construction calls tem_create_leveldesc