set_offsets – Treelm
set_offsets Subroutine
12 statements
Source File
private subroutine set_offsets(me, nFluids, nGhostFC, nGhostFF, nHalos)
Set the offsets for accessing totallist, invsorted etc. arrays for fluids, ghosts and halos
Arguments
Type Intent Optional Attributes Name
integer, intent(out) :: me(2,eT_minRelevant:eT_maxRelevant)
element type offsets
integer, intent(in) :: nFluids
integer, intent(in) :: nGhostFC
integer, intent(in) :: nGhostFF
integer, intent(in) :: nHalos
Called by
Source Code
  subroutine set_offsets( me, nFluids, nGhostFC, nGhostFF, nHalos )
    ! ---------------------------------------------------------------------------
    !> element type offsets
    integer, intent(out) :: me( 2, eT_minRelevant:eT_maxRelevant )
    !>
    integer, intent(in) :: nFluids, nGhostFC, nGhostFF, nHalos
    ! ---------------------------------------------------------------------------
    ! store the offset for the beginning ...
    me( 1, eT_fluid )             = 0
    me( 1, eT_ghostFromCoarser )  = nFluids
    me( 1, eT_ghostFromFiner )    = nFluids + nGhostFC
    me( 1, eT_halo )              = nFluids + nGhostFC + nGhostFF
    ! ... and the end of the list
    me( 2, eT_fluid )            = me( 1, eT_ghostFromCoarser )
    me( 2, eT_ghostFromCoarser ) = me( 1, eT_ghostFromFiner )
    me( 2, eT_ghostFromFiner )   = me( 1, eT_halo )
    me( 2, eT_halo )             = nFluids + nGhostFC + nGhostFF + nHalos
    ! me( :, eT_distributedGhostFromFiner ) = me( :, eT_GhostFromFiner )
  end subroutine set_offsets
Call graph
identify_lists calls set_offsets
communicate_elements calls identify_lists
tem_find_allelements calls identify_lists, communicate_elements
tem_create_leveldesc calls tem_find_allelements
tem_dimbydim_construction calls tem_create_leveldesc