sorttruncate_da_label – Treelm
sorttruncate_da_label Subroutine
13 statements
Source File
public subroutine sorttruncate_da_label(me)
fixing the dynamic array
truncate the array after the last valid entry and hence cut off the empty trailing empty entries store the array in the sorted order according to the sorted() array
Arguments
Type Intent Optional Attributes Name
type(dyn_labelarray_type) :: me
Calls
Called by
Source Code
  subroutine sorttruncate_da_label(me)
    !------------------------------------------------------------------------
    type(dyn_labelarray_type) :: me !< array to sorttruncate
    !------------------------------------------------------------------------
    type(dyn_labelarray_type) :: tarray !< temporary array
    integer :: ival
    integer :: dpos
    !------------------------------------------------------------------------
    ! allocate the temporary array
    call init( me = tarray, length = me%nvals )
    ! copy the entries in a sorted fashion into the temporary array
    do ival = 1, me%nvals
      call append( me = tarray, val = me%val( me%sorted( ival )), &
           &       pos = dpos)
    enddo
    call destroy( me = me )
    me = tarray
    call destroy( me = tarray )
  end subroutine sorttruncate_da_label
Call graph
sorttruncate_da_label calls append, destroy, init
append calls append_da_label, append_da_veclabel
destroy calls destroy_da_label
init calls init_da_label
append_da_label calls expand, sortedposofval
append_da_veclabel calls expand
expand calls expand_da_label
sortedposofval calls sortposofval_label
sorttruncate calls sorttruncate_da_label