spongelayer_box_roundCornerPolyn5_for_treeIDs – Treelm
spongelayer_box_roundCornerPolyn5_for_treeIDs Function
14 statements
Source File
private function spongelayer_box_roundCornerPolyn5_for_treeIDs(me, treeIds, tree, n) result(res)
This function calculates the sigma for the box shape spongelayer fom treeid for polynomial n5 profile
Arguments
Type Intent Optional Attributes Name
type(tem_spongeLayer_box_type) :: me
Spacetime function to evaluate
integer(kind=long_k), intent(in) :: treeIds(n)
treeIds of elements in given level
type(treelmesh_type), intent(in) :: tree
global treelm mesh
integer, intent(in) :: n
Number of arrays to return
Return Value real(kind=rk), (n)
return value
Calls
Called by
Source Code
  function spongelayer_box_roundCornerPolyn5_for_treeIDs(me, treeIDs, tree, n) &
    &                           result(res)
    ! --------------------------------------------------------------------------
    !> Spacetime function to evaluate
    type(tem_spongeLayer_box_type) :: me
    !> Number of arrays to return
    integer, intent(in) :: n
    !> global treelm mesh
    type( treelmesh_type ), intent(in) ::tree
    !> treeIds of elements in given level
    integer(kind=long_k), intent(in) :: treeIds(n)
    !> return value
    real(kind=rk) :: res(n)
    ! --------------------------------------------------------------------------
    integer :: i
    real(kind=rk) :: res_i(1), coord(3,1)
    ! --------------------------------------------------------------------------
    do i = 1,n
      !barycentric coordinate
      coord(:,1) = tem_BaryOfId( tree, treeIds(i) )
      res_i = spongeLayer_box_roundCornerPolyn5_for_coord(me, coord, 1)
      res(i) = res_i(1)
    end do
  end function spongelayer_box_roundCornerPolyn5_for_treeIDs
Call graph
spongelayer_box_roundcornerpolyn5_for_treeids calls spongelayer_box_roundcornerpolyn5_for_coord, tem_baryofid
tem_baryofid calls tem_coordofid, tem_elemsizelevel
tem_coordofid calls tem_levelof
spongelayer_box_scalar_for_treeids calls spongelayer_box_roundcornerpolyn5_for_treeids
tem_spongelayer_box_for calls spongelayer_box_scalar_for_treeids, spongelayer_box_vector_for_treeids
spongelayer_box_vector_for_treeids calls spongelayer_box_scalar_for_treeids
tem_spatial_for_coord calls tem_spongelayer_box_for
tem_spatial_for_treeids calls tem_spongelayer_box_for
tem_spatial_vector_for_coord calls tem_spongelayer_box_for
tem_spatial_vector_for_treeids calls tem_spongelayer_box_for
tem_spatial_for calls tem_spatial_for_coord, tem_spatial_for_treeids, tem_spatial_vector_for_coord, tem_spatial_vector_for_treeids
tem_spatial_scalar_for_index calls tem_spatial_for_coord
tem_spatial_vector_for_index calls tem_spatial_vector_for_coord