spongeLayer_plane_polyn5_for_treeids – Treelm
spongeLayer_plane_polyn5_for_treeids Function
28 statements
Source File
private function spongeLayer_plane_polyn5_for_treeids(me, treeIds, tree, n) result(res)
This function calculates the sigma for the spongelayer using polynomial order 5 from treeids. Sponge profile: where, \sigma_A - sponge strength, L - thickness, x0 - start of sponge.
Profile is taken from: Xu, Hui; Sagaut, Pierre (2013): Analysis of the absorbing layers for the weakly-compressible lattice Boltzmann methods. In Journal of Computational Physics 245, pp. 14-42. DOI: 10.1016/j.jcp.2013.02.051.
Arguments
Type Intent Optional Attributes Name
type(tem_spongeLayer_plane_type) :: me
Spatial absorb layer to evaluate
integer(kind=long_k), intent(in) :: treeIds(n)
treeIds of elements in given level
type(treelmesh_type), intent(in) :: tree
global treelm mesh
integer, intent(in) :: n
Number of arrays to return
Return Value real(kind=rk), (n)
return value
Calls
Called by
Source Code
  function spongeLayer_plane_polyn5_for_treeids(me, treeids, tree, n) &
    & result(res)
    ! --------------------------------------------------------------------------
    !> Spatial absorb layer to evaluate
    type(tem_spongeLayer_plane_type) :: me
    !> Number of arrays to return
    integer, intent(in) :: n
    !> global treelm mesh
    type( treelmesh_type ), intent(in) ::tree
    !> treeIds of elements in given level
    integer(kind=long_k), intent(in) :: treeIds(n)
    !> return value
    real(kind=rk) :: res(n)
    ! --------------------------------------------------------------------------
    integer :: i
    real(kind=rk) :: sigma, origin(3), normal(3), vec1(3), vec2(3), coord(3)
    real(kind=rk) :: proj_len1, proj_len2, const_fac
    ! --------------------------------------------------------------------------
    origin(:) = me%origin
    normal(:) = me%normal
    const_fac = 3125_rk/(256_rk*me%thickness**5)
    do i = 1,n
      !barycentric coordinate
      coord = tem_BaryOfId( tree, treeIds(i) )
      vec1(:) = coord(:) - origin(:)
      vec2(:) = me%thickness*normal(:) + origin(:) - coord(:)
      proj_len1 = vec1(1)*normal(1)+ vec1(2)*normal(2)+vec1(3)*normal(3)
      proj_len2 = vec2(1)*normal(1)+ vec2(2)*normal(2)+vec2(3)*normal(3)
      if (proj_len1 > 0 .and. proj_len2 > 0) then
        sigma = const_fac * proj_len2 * (proj_len1**4)
        res(i) = sigma*me%dampFactor
      else if (proj_len2 < 0) then ! If coord is beyond thickness
        res(i) = me%dampFactor
      else
        res(i) = 0.0_rk
      end if
    end do
  end function spongeLayer_plane_polyn5_for_treeids
Call graph
spongelayer_plane_polyn5_for_treeids calls tem_baryofid
tem_baryofid calls tem_coordofid, tem_elemsizelevel
tem_coordofid calls tem_levelof
spongelayer_plane_scalar_for_treeids calls spongelayer_plane_polyn5_for_treeids
tem_spongelayer_plane_for calls spongelayer_plane_scalar_for_treeids, spongelayer_plane_vector_for_treeids
spongelayer_plane_vector_for_treeids calls spongelayer_plane_scalar_for_treeids
tem_spatial_for_coord calls tem_spongelayer_plane_for
tem_spatial_for_treeids calls tem_spongelayer_plane_for
tem_spatial_vector_for_coord calls tem_spongelayer_plane_for
tem_spatial_vector_for_treeids calls tem_spongelayer_plane_for
tem_spatial_for calls tem_spatial_for_coord, tem_spatial_for_treeids, tem_spatial_vector_for_coord, tem_spatial_vector_for_treeids
tem_spatial_scalar_for_index calls tem_spatial_for_coord
tem_spatial_vector_for_index calls tem_spatial_vector_for_coord