spongelayer_box_scalar_for_treeIDs – Treelm
spongelayer_box_scalar_for_treeIDs Function
23 statements
Source File
private function spongelayer_box_scalar_for_treeIDs(me, treeIds, tree, n) result(res)
This function returns the sigma for the spongelayer from treeids
Arguments
Type Intent Optional Attributes Name
type(tem_spongeLayer_box_type) :: me
Spacetime function to evaluate
integer(kind=long_k), intent(in) :: treeIds(n)
treeIds of elements in given level
type(treelmesh_type), intent(in) :: tree
global treelm mesh
integer, intent(in) :: n
Number of arrays to return
Return Value real(kind=rk), (n)
return value
Calls
Called by
Source Code
  function spongelayer_box_scalar_for_treeIDs(me, treeids, tree, n)  &
    &                           result(res)
    ! --------------------------------------------------------------------------
    !> Spacetime function to evaluate
    type(tem_spongeLayer_box_type) :: me
    !> Number of arrays to return
    integer, intent(in) :: n
    !> global treelm mesh
    type( treelmesh_type ), intent(in) ::tree
    !> treeIds of elements in given level
    integer(kind=long_k), intent(in) :: treeIds(n)
    !> return value
    real(kind=rk) :: res(n)
    ! --------------------------------------------------------------------------
    select case (trim(me%dampProfile))
    case ('linear', 'exponential')
      res(:) = spongeLayer_box_expon_for_treeIDs(me, treeIDs, tree, n)
    case ('polynomial_n5')
      if (me%rounded_corner) then
        res(:) = spongeLayer_box_roundCornerPolyn5_for_treeIDs(me, treeIDs, &
          &                                                    tree, n)
      else
        res(:) = spongeLayer_box_sharpCornerPolyn5_for_treeIDs(me, treeIDs, &
          &                                                    tree, n)
      end if
    case ('polynomial_n6')
      if (me%rounded_corner) then
        res(:) = spongeLayer_box_roundCornerPolyn6_for_treeIDs(me, treeIDs, &
          &                                                    tree, n)
      else
        res(:) = spongeLayer_box_sharpCornerPolyn6_for_treeIDs(me, treeIDs, &
          &                                                    tree, n)
      end if
    end select
  end function spongeLayer_box_scalar_for_treeIDs
Call graph
spongelayer_box_scalar_for_treeids calls spongelayer_box_expon_for_treeids, spongelayer_box_roundcornerpolyn5_for_treeids, spongelayer_box_roundcornerpolyn6_for_treeids, spongelayer_box_sharpcornerpolyn5_for_treeids, spongelayer_box_sharpcornerpolyn6_for_treeids
spongelayer_box_expon_for_treeids calls spongelayer_box_expon_for_coord, tem_baryofid
spongelayer_box_roundcornerpolyn5_for_treeids calls spongelayer_box_roundcornerpolyn5_for_coord, tem_baryofid
spongelayer_box_roundcornerpolyn6_for_treeids calls spongelayer_box_roundcornerpolyn6_for_coord, tem_baryofid
spongelayer_box_sharpcornerpolyn5_for_treeids calls spongelayer_box_sharpcornerpolyn5_for_coord, tem_baryofid
spongelayer_box_sharpcornerpolyn6_for_treeids calls spongelayer_box_sharpcornerpolyn6_for_coord, tem_baryofid
tem_baryofid calls tem_coordofid, tem_elemsizelevel
tem_coordofid calls tem_levelof
tem_spongelayer_box_for calls spongelayer_box_scalar_for_treeids, spongelayer_box_vector_for_treeids
spongelayer_box_vector_for_treeids calls spongelayer_box_scalar_for_treeids
tem_spatial_for_coord calls tem_spongelayer_box_for
tem_spatial_for_treeids calls tem_spongelayer_box_for
tem_spatial_vector_for_coord calls tem_spongelayer_box_for
tem_spatial_vector_for_treeids calls tem_spongelayer_box_for
tem_spatial_for calls tem_spatial_for_coord, tem_spatial_for_treeids, tem_spatial_vector_for_coord, tem_spatial_vector_for_treeids, tem_spatial_scalar_for_index, tem_spatial_vector_for_index
tem_spatial_scalar_for_index calls tem_spatial_for_coord
tem_spatial_vector_for_index calls tem_spatial_vector_for_coord
tem_spacetime_for_coord calls tem_spatial_for
tem_spacetime_for_treeids calls tem_spatial_for
tem_spacetime_scalar_for_index calls tem_spatial_for
tem_spacetime_vector_for_coord calls tem_spatial_for
tem_spacetime_vector_for_index calls tem_spatial_for
tem_spacetime_vector_for_treeids calls tem_spatial_for
tem_spatial_scalar_storeval calls tem_spatial_for
tem_spatial_vector_storeval calls tem_spatial_for