spongeLayer_radial_polyn6_for_coord – Treelm
spongeLayer_radial_polyn6_for_coord Function
23 statements
Source File
private function spongeLayer_radial_polyn6_for_coord(me, coord, nDim, n) result(res)
This function calculates the sigma for the spongelayer radial from coord for the polynomial order n6. Sponge profile: where, \sigma_A - sponge strength, L - thickness, x0 - start of sponge.
Arguments
Type Intent Optional Attributes Name
type(tem_spongeLayer_radial_type) :: me
Spatial sponge layer to evaluate
real(kind=rk), intent(in) :: coord(n,3)
barycentric Ids of an elements. 1st index goes over number of elements and 2nd index goes over x,y,z coordinates
integer, intent(in) :: nDim
Dimension
integer, intent(in) :: n
Number of arrays to return
Return Value real(kind=rk), (n)
return value
Called by
Source Code
  function spongeLayer_radial_polyn6_for_coord(me, coord, nDim, n) result(res)
    ! --------------------------------------------------------------------------
    !> Spatial sponge layer to evaluate
    type(tem_spongeLayer_radial_type) :: me
    !> Number of arrays to return
    integer, intent(in) :: n
    !> barycentric Ids of an elements.
    !! 1st index goes over number of elements and
    !! 2nd index goes over x,y,z coordinates
    real(kind=rk), intent( in ) :: coord(n,3)
    !> Dimension
    integer, intent(in) :: nDim
    !> return value
    real(kind=rk) :: res(n)
    ! --------------------------------------------------------------------------
    integer :: i
    real(kind=rk) :: rad, outer_radius, sigma, vec(3)
    real(kind=rk) :: const_fac
    ! --------------------------------------------------------------------------
    outer_radius = me%radius + me%thickness
    vec = 0.0_rk
    const_fac = 729_rk/(16_rk*me%thickness**6)
    do i = 1,n
      vec(1:nDim) = coord(i,1:nDim) - me%origin(1:nDim)
      rad = sqrt( vec(1)**2 + vec(2)**2 + vec(3)**2 )
      if (rad > me%radius) then
        sigma = const_fac * (outer_radius - rad)**2 * (rad - me%radius)**4
        res(i) = min(1.0_rk, sigma) * me%dampFactor
      else
        res(i) = 0.0_rk
      end if
    end do
  end function spongeLayer_radial_polyn6_for_coord
Call graph
spongelayer_radial_scalar_for_coord calls spongelayer_radial_polyn6_for_coord
tem_spongelayer_radial_for calls spongelayer_radial_scalar_for_coord, spongelayer_radial_vector_for_coord
spongelayer_radial_vector_for_coord calls spongelayer_radial_scalar_for_coord
tem_spatial_for_coord calls tem_spongelayer_radial_for
tem_spatial_for_treeids calls tem_spongelayer_radial_for
tem_spatial_vector_for_coord calls tem_spongelayer_radial_for
tem_spatial_vector_for_treeids calls tem_spongelayer_radial_for
tem_spatial_for calls tem_spatial_for_coord, tem_spatial_for_treeids, tem_spatial_vector_for_coord, tem_spatial_vector_for_treeids
tem_spatial_scalar_for_index calls tem_spatial_for_coord
tem_spatial_vector_for_index calls tem_spatial_vector_for_coord