spongelayer_radial_vector_for_treeIDs – Treelm
spongelayer_radial_vector_for_treeIDs Function
16 statements
Source File
private function spongelayer_radial_vector_for_treeIDs(me, nComp, treeIds, tree, nDim, n) result(res)
This function calculates the sigma for the radial viscosity spongelayer for 2D and 3D from treeIDs and fills up rest with target_state. This function is currectly used to define viscosity sponge in musubi.
Arguments
Type Intent Optional Attributes Name
type(tem_spongeLayer_radial_type) :: me
Spacetime function to evaluate
integer, intent(in) :: nComp
Number of entrys in each array
integer(kind=long_k), intent(in) :: treeIds(n)
treeIds of elements in given level
type(treelmesh_type), intent(in) :: tree
global treelm mesh
integer, intent(in) :: nDim
Dimension
integer, intent(in) :: n
Number of arrays to return
Return Value real(kind=rk), (n,nComp)
return value
Calls
Called by
Source Code
  function spongelayer_radial_vector_for_treeIDs(me, nComp, treeids, tree, &
    &                                            nDim, n) result(res)
    ! --------------------------------------------------------------------------
    !> Spacetime function to evaluate
    type(tem_spongeLayer_radial_type) :: me
    !> Number of arrays to return
    integer, intent(in) :: n
    !> Number of entrys in each array
    integer, intent(in) :: nComp
    !> global treelm mesh
    type( treelmesh_type ), intent(in) ::tree
    !> treeIds of elements in given level
    integer(kind=long_k), intent(in) :: treeIds(n)
    !> Dimension
    integer, intent(in) :: nDim
    !> return value
    real(kind=rk) :: res(n, nComp)
    ! --------------------------------------------------------------------------
    integer :: i
    ! --------------------------------------------------------------------------
    res(:, 1) = spongeLayer_radial_scalar_for_treeIDs(me, treeids, tree, &
      &                                               nDim, n)
    if (ncomp > 1) then
      do i = 1,n
        res(i,2:) = me%targetState(:)
      end do
    end if
  end function spongelayer_radial_vector_for_treeIDs
Call graph
spongelayer_radial_vector_for_treeids calls spongelayer_radial_scalar_for_treeids
spongelayer_radial_scalar_for_treeids calls spongelayer_radial_expon_for_treeids, spongelayer_radial_polyn5_for_treeids, spongelayer_radial_polyn6_for_treeids
spongelayer_radial_expon_for_treeids calls tem_baryofid
spongelayer_radial_polyn5_for_treeids calls tem_baryofid
spongelayer_radial_polyn6_for_treeids calls tem_baryofid
tem_baryofid calls tem_coordofid, tem_elemsizelevel
tem_spongelayer_radial_for calls spongelayer_radial_vector_for_treeids
tem_spatial_for_coord calls tem_spongelayer_radial_for
tem_spatial_for_treeids calls tem_spongelayer_radial_for
tem_spatial_vector_for_coord calls tem_spongelayer_radial_for
tem_spatial_vector_for_treeids calls tem_spongelayer_radial_for
tem_spatial_for calls tem_spatial_for_coord, tem_spatial_for_treeids, tem_spatial_vector_for_coord, tem_spatial_vector_for_treeids, tem_spatial_scalar_for_index, tem_spatial_vector_for_index
tem_spatial_scalar_for_index calls tem_spatial_for_coord
tem_spatial_vector_for_index calls tem_spatial_vector_for_coord
tem_spacetime_for_coord calls tem_spatial_for
tem_spacetime_for_treeids calls tem_spatial_for
tem_spacetime_scalar_for_index calls tem_spatial_for
tem_spacetime_vector_for_coord calls tem_spatial_for
tem_spacetime_vector_for_index calls tem_spatial_for
tem_spacetime_vector_for_treeids calls tem_spatial_for
tem_spatial_scalar_storeval calls tem_spatial_for
tem_spatial_vector_storeval calls tem_spatial_for