tem_connect_toNull – Treelm
tem_connect_toNull Subroutine
15 statements
Source File
public subroutine tem_connect_toNull(null_unit)
Arguments
Type Intent Optional Attributes Name
integer, intent(out) :: null_unit
Calls
Called by
Source Code
  subroutine tem_connect_toNull(null_unit)
    integer, intent(out) :: null_unit
    logical :: null_connected
    inquire(file=trim(null_device), opened=null_connected)
    if (null_connected) then
      inquire(file=trim(null_device), number=null_unit)
      ! Some MPI implementations might connect stdin to the null device.
      ! Need to check if this is the case and attempt to open it again
      ! with a different unit to make it writable.
      if (null_unit == input_unit) then
        null_unit = newUnit()
        open(file=trim(null_device), unit=null_unit)
      end if
    else
      null_unit = newUnit()
      open(file=trim(null_device), unit=null_unit)
    end if
  end subroutine tem_connect_toNull
Call graph
tem_connect_tonull calls newunit
tem_logging_init_logger calls tem_connect_tonull
tem_logging_init calls tem_logging_init_logger, tem_logging_init_primary
tem_logging_init_primary calls tem_logging_init_logger
tem_logging_load calls tem_logging_init_logger, tem_logging_init_primary
tem_load_debug calls tem_logging_init, tem_logging_load
tem_logging_load_primary calls tem_logging_init_primary, tem_logging_load
tem_debug_load_main calls tem_load_debug