tem_commbuf_int_fillindexed – Treelm
tem_commbuf_int_fillindexed Subroutine
11 statements
Source File
private subroutine tem_commbuf_int_fillindexed(me, pos, nvals)
fill the indexed mpi datatype, which describes how the data in the state vector relates to the entries in the buffer.
Arguments
Type Intent Optional Attributes Name
type(tem_intbuffer_type), intent(inout) :: me
integer, intent(in) :: pos(nvals)
integer, intent(in) :: nvals
Calls
Source Code
  subroutine tem_commbuf_int_fillindexed(me, pos, nvals)
    ! -------------------------------------------------------------------- !
    type(tem_intbuffer_type), intent(inout) :: me
    integer, intent(in) :: nvals
    integer, intent(in) :: pos(nvals)
    ! -------------------------------------------------------------------- !
    integer :: ierror
    ! -------------------------------------------------------------------- !
    me%nvals = nvals
    ! call mpi_type_create_indexed_block(count, blocklength, &
    !   &                   array_of_displacements, &
    !   &                   oldtype, newtype, ierror)
    call mpi_type_create_indexed_block( nvals, 1, pos - 1,                   &
      &                                 mpi_integer, me%memindexed, ierror )
    call check_mpi_error(ierror,'create indexed block in tem_commbuf_int_fillindexed')
    call mpi_type_commit(me%memindexed, ierror)
    call check_mpi_error(ierror,'commit memindexed in tem_commbuf_int_fillindexed')
  end subroutine tem_commbuf_int_fillindexed
Call graph
tem_commbuf_int_fillindexed calls mpi_type_commit, mpi_type_create_indexed_block, check_mpi_error
check_mpi_error calls mpi_error_string, tem_abort
tem_abort calls mpi_abort