tem_load_condition – Treelm
tem_load_condition Subroutine
26 statements
Source File
public subroutine tem_load_condition(me, conf, parent)
Load the condition table in case of convergence
Example:
 condition = {threshold = 2.0e-10, operator = '<='}
The tables inside condition table should be equal to the nVars If thats not the case we return an error message check single or multiple table
Arguments
Type Intent Optional Attributes Name
type(tem_condition_type), intent(inout), allocatable :: me(:)
type(flu_State), intent(in) :: conf
integer, intent(in) :: parent
Calls
Called by
Source Code
  subroutine tem_load_condition( me, conf, parent )
    ! -------------------------------------------------------------------- !
    !>
    type(tem_condition_type), allocatable, intent(inout) :: me(:)
    !>
    type(flu_state), intent(in)             :: conf
    !>
    integer, intent(in)                     :: parent
    ! -------------------------------------------------------------------- !
    integer :: cond_handle          ! handle for the condition table
    integer :: sub_cond_handle      ! handle for subtables inside condition
    integer :: nCond                ! number of conditions
    integer :: iCond                ! index for condition loop
    ! -------------------------------------------------------------------- !
    !! Open the condition table
    call aot_table_open( L       = conf,        &
      &                  parent  = parent,      &
      &                  thandle = cond_handle, &
      &                  key     = 'condition'  )
    !! The tables inside condition table should be equal to the nVars
    !! If thats not the case we return an error message
    nCond = aot_table_length( L=conf, thandle=cond_handle )
    !! check single or multiple table
    call aot_table_open( L       = conf,            &
      &                  parent  = cond_handle,     &
      &                  thandle = sub_cond_handle, &
      &                  pos     = 1                )
    if (sub_cond_handle == 0) then
      call aot_table_close( L = conf, thandle = sub_cond_handle )
      ! just one table within
      allocate ( me(1) )
      call tem_load_cond_single( me(1), conf, cond_handle )
    else
      ! IF there are more tables within condition
      call aot_table_close( L = conf, thandle = sub_cond_handle )
      allocate ( me(nCond) )
      do iCond = 1, nCond
        call aot_table_open( L       = conf,            &
          &                  parent  = cond_handle,     &
          &                  thandle = sub_cond_handle, &
          &                  pos     = iCond            )
        call tem_load_cond_single( me(iCond), conf, sub_cond_handle )
        call aot_table_close( L = conf, thandle = sub_cond_handle )
      end do
    end if ! sub condition check
    call aot_table_close(L=conf, thandle=cond_handle )
  end subroutine tem_load_condition
Call graph
tem_load_condition calls aot_table_close, aot_table_length, aot_table_open, tem_load_cond_single
tem_load_cond_single calls aot_get_val, tem_abort
tem_abort calls mpi_abort
tem_load_convergenceheader calls tem_load_condition
tem_load_depend_single calls tem_load_condition
tem_load_depend calls tem_load_depend_single, tem_load_depend_vector
tem_convergence_load calls tem_load_convergenceheader
tem_load_depend_vector calls tem_load_depend_single
tem_abortcriteria_load calls tem_convergence_load
tem_simcontrol_load calls tem_abortcriteria_load