tem_timer_loadconfig_glob – Treelm
tem_timer_loadconfig_glob Subroutine
5 statements
Source File
public subroutine tem_timer_loadconfig_glob(conf, parent)
Load the configuration for the global (module) timer.
Arguments
Type Intent Optional Attributes Name
type(flu_State) :: conf
Timer configuration to load from the Lua configuration script. Handle to the Lua configuration script.
integer, intent(in), optional :: parent
Handle of the table containing the requested table.
Calls
Called by
Source Code
  subroutine tem_timer_loadconfig_glob(conf, parent)
    ! -------------------------------------------------------------------- !
    !> Timer configuration to load from the Lua configuration script.
    !> Handle to the Lua configuration script.
    type(flu_state) :: conf
    !> Handle of the table containing the requested table.
    integer, intent(in), optional :: parent
    ! -------------------------------------------------------------------- !
    call tem_timer_loadconfig( timer_config = timer%config, &
      &                        conf         = conf,         &
      &                        parent       = parent        )
   end subroutine tem_timer_loadconfig_glob
Call graph
tem_timer_loadconfig_glob calls tem_timer_loadconfig
tem_timer_loadconfig calls aot_get_val, aot_table_close, aot_table_first, aot_table_open, aot_table_top, flu_next, append, upper_to_lower
append calls append_da_label, append_da_veclabel
append_da_label calls expand, sortedposofval
append_da_veclabel calls expand
tem_load_general calls tem_timer_loadconfig_glob