tem_time_set_clock – Treelm
tem_time_set_clock Subroutine
4 statements
Source File
public subroutine tem_time_set_clock(me)
Update the clock measurement in the time description.
The clock component in me is updated with the help of MPI_Wtime.
Arguments
Type Intent Optional Attributes Name
type(tem_time_type), intent(inout) :: me
Time setting to update.
Calls
Called by
Source Code
  subroutine tem_time_set_clock(me)
    ! -------------------------------------------------------------------- !
    !> Time setting to update.
    type(tem_time_type), intent(inout) :: me
    ! -------------------------------------------------------------------- !
    ! -------------------------------------------------------------------- !
    me%clock = MPI_Wtime() - me%clock_start
  end subroutine tem_time_set_clock
Call graph
tem_time_set_clock calls mpi_wtime
tem_load_restart calls tem_time_set_clock
tem_simcontrol_dump_now calls tem_time_set_clock
tem_simcontrol_syncupdate calls tem_time_set_clock
tem_simcontrol_dump calls tem_simcontrol_dump_now
tem_load_general calls tem_simcontrol_dump