tem_init_vrtx_prop – Treelm
tem_init_vrtx_prop Subroutine
9 statements
Source File
private subroutine tem_init_vrtx_prop(vrtx)
Initialize the vertex property headers.
Arguments
Type Intent Optional Attributes Name
type(tem_vrtx_type) :: vrtx
vertex type
Calls
Called by
Source Code
  subroutine tem_init_vrtx_prop(vrtx)
    ! ---------------------------------------------------------------------------
    !> vertex type
    type(tem_vrtx_type)         :: vrtx
    ! ---------------------------------------------------------------------------
    integer :: init_nelems = 1024
    ! ---------------------------------------------------------------------------
    if ( .not.allocated(vrtx%map2global) ) then
      allocate( vrtx%map2global(init_nelems,8) )
      ! vrtx%sim_time = 0.d0
      vrtx%nvertices = 0
    end if
    ! initialise the growing array of actual vrtx real coordinates
    call init( me = vrtx%coord, width = 3 )
  end subroutine tem_init_vrtx_prop
Call graph
tem_init_vrtx_prop calls init
init calls init_ga2d_real
tem_calc_vrtx_coord calls tem_init_vrtx_prop, tem_calc_vrtx_coord_noqval
tem_calc_vrtx_coord_noqval calls tem_init_vrtx_prop
hvs_output_init calls tem_calc_vrtx_coord
tem_init_tracker calls hvs_output_init