tem_logging_load_primary – Treelm
tem_logging_load_primary Subroutine
12 statements
Source File
public subroutine tem_logging_load_primary(conf, rank)
Load the primary logger from a Lua script under its default name of logging as global variable.
If it is not set by the user, a default logging level of 1 is assumed.
Arguments
Type Intent Optional Attributes Name
type(flu_State) :: conf
integer :: rank
Calls
Source Code
  subroutine tem_logging_load_primary( conf, rank )
    ! ---------------------------------------------------------------------------
    !>
    type(flu_state) :: conf
    !>
    integer :: rank
    ! ---------------------------------------------------------------------------
    integer :: thandle
    ! ---------------------------------------------------------------------------
    call aot_table_open(L = conf, thandle = thandle, key = 'logging')
    if (thandle == 0) then
      call tem_logging_init_primary(level = 1, rank = rank)
    else
      call tem_logging_load(conf = conf, thandle = thandle, rank = rank)
    end if
    call aot_table_close(L = conf, thandle = thandle)
  end subroutine tem_logging_load_primary
Call graph
tem_logging_load_primary calls aot_table_close, aot_table_open, tem_logging_init_primary, tem_logging_load
tem_logging_init_primary calls tem_logging_init_logger
tem_logging_load calls tem_logging_init_primary, aot_get_val, tem_logging_init_logger
tem_logging_init_logger calls newunit, tem_connect_tonull
tem_connect_tonull calls newunit