tem_spacetime_lua_for_treeIds – Treelm
tem_spacetime_lua_for_treeIds Function
33 statements
Source File
private function tem_spacetime_lua_for_treeIds(fun_ref, treeIds, time, tree, n, conf) result(res)
\brief This function invokes the Lua function for barycentric coordinates of an element specified by treeIds
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: fun_ref
Reference of the function to open
integer(kind=long_k), intent(in) :: treeIds(n)
treeIds of elements in given level
type(tem_time_type), intent(in) :: time
timer object incl. the current time information
type(treelmesh_type), intent(in) :: tree
global treelm mesh
integer, intent(in) :: n
number of return values
type(flu_State), intent(in) :: conf
lua state
Return Value real(kind=rk), (n)
return value
Calls
Called by
Source Code
  function tem_spacetime_lua_for_treeIds(fun_ref, treeIds, time, tree, n, &
    &                                    conf  )      result(res)
    ! -------------------------------------------------------------------- !
    !> Reference of the function to open
    integer, intent(in) :: fun_ref
    !> global treelm mesh
    type(treelmesh_type), intent(in) ::tree
    !> number of return values
    integer, intent(in) :: n
    !> treeIds of elements in given level
    integer(kind=long_k), intent(in) :: treeIds(n)
    !> timer object incl. the current time information
    type(tem_time_type), intent(in)  :: time
    !> return value
    real(kind=rk) :: res(n)
    !> lua state
    type(flu_State), intent(in) :: conf
    ! -------------------------------------------------------------------- !
    type(aot_fun_type) :: fun
    integer :: iError
    integer :: i, j
    real(kind=rk) :: coord(3)
    ! -------------------------------------------------------------------- !
    call aot_fun_open(L = conf, fun = fun, ref = fun_ref)
    do i=1,n
      coord = tem_BaryOfId( tree, treeIds(i) )
      do j=1,3
        call aot_fun_put(L=conf, fun=fun, arg=coord(j))
      end do
      call aot_fun_put(L=conf, fun=fun, arg=time%sim)
      call aot_fun_do(L=conf, fun=fun, nresults=1)
      call aot_top_get_val(L=conf, val=res(i), ErrCode=iError)
      if ( btest(iError,aoterr_Fatal) ) then
        write(logunit(0),*) "ERROR Obtaining a space time function"
        write(logunit(0),*) "Probably wrong number of components returned"
        write(logunit(0),*) "or a scalar was return as a lua table"
        write(logunit(0),*) 'Expected nComp: 1'
        write(logunit(0),*) 'ErrorCodes: ', iError
        write(logunit(0),*) "Check return values of your Lua functions!"
        call tem_abort()
      end if
    end do
    call aot_fun_close(L = conf, fun = fun)
  end function tem_spacetime_lua_for_treeIds
Call graph
tem_spacetime_lua_for_treeids calls aot_fun_close, aot_fun_do, aot_fun_open, aot_fun_put, aot_top_get_val, tem_abort, tem_baryofid
tem_abort calls mpi_abort
tem_baryofid calls tem_coordofid, tem_elemsizelevel
tem_coordofid calls tem_levelof
tem_spacetime_lua_for calls tem_spacetime_lua_for_treeids
tem_spacetime_for_coord calls tem_spacetime_lua_for
tem_spacetime_for_treeids calls tem_spacetime_lua_for
tem_spacetime_scalar_for_index calls tem_spacetime_lua_for, tem_spacetime_for_coord
tem_spacetime_vector_for_coord calls tem_spacetime_lua_for
tem_spacetime_vector_for_index calls tem_spacetime_lua_for, tem_spacetime_vector_for_coord
tem_spacetime_vector_for_treeids calls tem_spacetime_lua_for
tem_spacetime_for calls tem_spacetime_for_coord, tem_spacetime_for_treeids, tem_spacetime_scalar_for_index, tem_spacetime_vector_for_coord, tem_spacetime_vector_for_index, tem_spacetime_vector_for_treeids, tem_spacetime_for_stcoord
tem_spacetime_for_stcoord calls tem_spacetime_for_coord
evaluate_add_spacetime_scalarbycoordinate calls tem_spacetime_for
evaluate_add_spacetime_scalarbytreeid calls tem_spacetime_for
evaluate_add_spacetime_vectorbycoordinate calls tem_spacetime_for
evaluate_add_spacetime_vectorbytreeid calls tem_spacetime_for
evaluate_first_spacetime_scalarbycoordinate calls tem_spacetime_for
evaluate_first_spacetime_scalarbytreeid calls tem_spacetime_for
evaluate_first_spacetime_vectorbycoordinate calls tem_spacetime_for
evaluate_first_spacetime_vectorbytreeid calls tem_spacetime_for
evaluate_foag_spacetime_scalarbycoordinate calls tem_spacetime_for
evaluate_foag_spacetime_scalarbytreeid calls tem_spacetime_for
evaluate_foag_spacetime_vectorbycoordinate calls tem_spacetime_for
evaluate_foag_spacetime_vectorbytreeid calls tem_spacetime_for
get_valofindex_add_scalar_spacetime calls tem_spacetime_for
get_valofindex_add_vector_spacetime calls tem_spacetime_for
get_valofindex_first_scalar_spacetime calls tem_spacetime_for
get_valofindex_first_vector_spacetime calls tem_spacetime_for
get_valofindex_foag_scalar_spacetime calls tem_spacetime_for
get_valofindex_foag_vector_spacetime calls tem_spacetime_for
tem_update_surfpos calls tem_spacetime_for