tem_eval_polygon_material – Treelm
tem_eval_polygon_material Function
17 statements
Source File
public function tem_eval_polygon_material(me, coord, n) result(res)
Evaluate a list of points, and return inval for each that is within me and outval for all other points.
Arguments
Type Intent Optional Attributes Name
type(tem_polygon_material_type), intent(in) :: me
Description of the polygon to evaluate
real(kind=rk), intent(in) :: coord(n,3)
Coordinates for which the function should be evaluated.
integer, intent(in) :: n
Number of points to get a value for.
Return Value real(kind=rk), (n,me%nComponents)
Resulting value at each point.
Calls
Called by
Source Code
  function tem_eval_polygon_material(me, coord, n) result(res)
    ! ----------------------------------------------------------------------
    !> Description of the polygon to evaluate
    type(tem_polygon_material_type), intent(in) :: me
    !> Number of points to get a value for.
    integer, intent(in) :: n
    !> Coordinates for which the function should be evaluated.
    real(kind=rk), intent(in) :: coord(n,3)
    !> Resulting value at each point.
    real(kind=rk) :: res(n, me%nComponents)
    ! ----------------------------------------------------------------------
    integer :: iPoint, iPoly, icomp
    ! ----------------------------------------------------------------------
    do icomp = 1, me%nComponents
      res(:,iComp) = me%outval(iComp)
    end do
    do iPoly = 1, me%nPoly
      do iPoint=1,n
        if (res(iPoint,1) .feq. me%outval(1) ) then
          res(iPoint,:) = tem_polygon_material_value(  &
            & me          = me%poly_list(ipoly),       &
            & nComponents = me%nComponents,            &
            & inVal       = me%inVal,                  &
            & outVal      = me%outVal,                 &
            & point       = coord(iPoint,:2)           )
         endif
      end do
    end do
  end function tem_eval_polygon_material
Call graph
tem_eval_polygon_material calls tem_polygon_material_value
tem_polygon_material_value calls angle_between
tem_spatial_vector_for_coord calls tem_eval_polygon_material
tem_spatial_for calls tem_spatial_vector_for_coord, tem_spatial_vector_for_index
tem_spatial_vector_for_index calls tem_spatial_vector_for_coord
tem_spacetime_for_coord calls tem_spatial_for
tem_spacetime_for_treeids calls tem_spatial_for
tem_spacetime_scalar_for_index calls tem_spatial_for, tem_spacetime_for_coord
tem_spacetime_vector_for_coord calls tem_spatial_for
tem_spacetime_vector_for_index calls tem_spatial_for, tem_spacetime_vector_for_coord
tem_spacetime_vector_for_treeids calls tem_spatial_for
tem_spatial_scalar_storeval calls tem_spatial_for
tem_spatial_vector_storeval calls tem_spatial_for
tem_spacetime_for calls tem_spacetime_for_coord, tem_spacetime_for_treeids, tem_spacetime_scalar_for_index, tem_spacetime_vector_for_coord, tem_spacetime_vector_for_index, tem_spacetime_vector_for_treeids
tem_spatial_storeval calls tem_spatial_scalar_storeval, tem_spatial_vector_storeval
tem_spacetime_for_stcoord calls tem_spacetime_for_coord