tem_debug_load_main – Treelm
tem_debug_load_main Subroutine
6 statements
Source File
public subroutine tem_debug_load_main(conf, rank)
Load the main debugger object
Arguments
Type Intent Optional Attributes Name
type(flu_State) :: conf
Lua state, to get the configuration from.
integer, intent(in), optional :: rank
Rank of the calling process.
Calls
Source Code
  subroutine tem_debug_load_main( conf, rank )
    ! ---------------------------------------------------------------------------
    !> Lua state, to get the configuration from.
    type(flu_state) :: conf
    !> Rank of the calling process.
    integer, optional, intent(in) :: rank
    ! ---------------------------------------------------------------------------
    call tem_load_debug( me = main_debug, conf = conf, rank = rank )
    ! Fill shorthand for the debug units.
    dbgUnit = main_debug%logger%funit
  end subroutine tem_debug_load_main
Call graph
tem_debug_load_main calls tem_load_debug
tem_load_debug calls aot_get_val, aot_table_close, aot_table_open, tem_logging_init, tem_horizontalspacer, tem_logging_load
tem_logging_init calls tem_logging_init_logger, tem_logging_init_primary
tem_logging_load calls aot_get_val, tem_logging_init_logger, tem_logging_init_primary
tem_logging_init_logger calls newunit, tem_connect_tonull
tem_logging_init_primary calls tem_logging_init_logger