tem_appendTimers – Treelm
tem_appendTimers Subroutine
12 statements
Source File
public subroutine tem_appendTimers(me, nVals)
Append nVals new timers to the timer collection provided in 'me'.
Arguments
Type Intent Optional Attributes Name
type(tem_timer_type), intent(inout) :: me
Timer object to extend by nVals timers
integer, intent(in) :: nVals
Number of timers to append to me.
Calls
Called by
Source Code
  subroutine tem_appendTimers(me, nVals)
    ! -------------------------------------------------------------------- !
    !> Timer object to extend by nVals timers
    type(tem_timer_type), intent(inout) :: me
    !> Number of timers to append to me.
    integer, intent(in) :: nVals
    ! -------------------------------------------------------------------- !
    logical :: running(nVals)
    real(kind=rk) :: zeroes(nVals)
    ! -------------------------------------------------------------------- !
    running = .false.
    zeroes = 0.0_rk
    call append( me  = me%running, &
      &          val = running     )
    call append( me  = me%tStart, &
      &          val = zeroes     )
    call append( me  = me%duration, &
      &          val = zeroes       )
    me%nTimers = me%nTimers + nVals
  end subroutine tem_appendTimers
Call graph
tem_appendtimers calls append
append calls append_da_label, append_da_veclabel
append_da_label calls expand, sortedposofval
append_da_veclabel calls expand
expand calls expand_da_label
sortedposofval calls sortposofval_label
tem_addtimer calls tem_appendtimers
tem_simcontrol_load calls tem_addtimer
tem_start calls tem_addtimer
tem_load_general calls tem_simcontrol_load