tem_halo_init – Treelm
tem_halo_init Subroutine
5 statements
Source File
public subroutine tem_halo_init(me)
Initialize the list of halo elements.
Arguments
Type Intent Optional Attributes Name
type(tem_haloList_type), intent(out) :: me
The list of halo elements to initialize
Calls
Called by
Source Code
  subroutine tem_halo_init(me)
    !> The list of halo elements to initialize
    type(tem_haloList_type), intent(out) :: me
    call init(me%partnerProc)
    call init(me%halos)
  end subroutine tem_halo_init
Call graph
tem_halo_init calls init
init calls init_ga_dynlong
identify_lists calls tem_halo_init
communicate_elements calls identify_lists
tem_find_allelements calls identify_lists, communicate_elements
tem_create_leveldesc calls tem_find_allelements
tem_dimbydim_construction calls tem_create_leveldesc