tem_varSys_dump_vector – Treelm
tem_varSys_dump_vector Subroutine
9 statements
Source File
public subroutine tem_varSys_dump_vector(me, outUnit, dumpVarPos)
Dumps array of varSys to given unit
Arguments
Type Intent Optional Attributes Name
type(tem_varSys_type), intent(in) :: me(:)
variable to write into the lua file
integer, intent(inout) :: outUnit
unit to write to
integer, intent(in), optional :: dumpVarPos(:)
Position of variables to dump
Calls
Called by
Source Code
  subroutine tem_varSys_dump_vector(me, outUnit, dumpVarPos)
    ! ---------------------------------------------------------------------------
    !> variable to write into the lua file
    type(tem_varSys_type), intent(in) :: me(:)
    !> unit to write to
    integer, intent(inout) :: outUnit
    !> Position of variables to dump
    integer, optional, intent(in) :: dumpVarPos(:)
    ! ---------------------------------------------------------------------------
    ! aotus type handling the output to the file in lua format
    type(aot_out_type) :: conf
    ! ---------------------------------------------------------------------------
    call aot_out_open( put_conf = conf, outUnit = outUnit )
    call tem_varSys_out_vector( me, conf, dumpVarPos )
    call aot_out_close( put_conf = conf )
  end subroutine tem_varSys_dump_vector
Call graph
tem_varsys_dump_vector calls aot_out_close, aot_out_open, tem_varsys_out_vector
tem_varsys_out_vector calls aot_out_close_table, aot_out_open_table, tem_varsys_out_single
tem_varsys_out_single calls aot_out_close_table, aot_out_open_table, aot_out_val
tem_varsys_dump calls tem_varsys_dump_vector
tem_restart_readheader calls tem_varsys_dump
tem_load_restart calls tem_restart_readheader