tem_restart_closeRead – Treelm
tem_restart_closeRead Subroutine
11 statements
Source File
public subroutine tem_restart_closeRead(me)
This subroutine closes the restart dump file and writes the last header.
Arguments
Type Intent Optional Attributes Name
type(tem_restart_type) :: me
the restart information
Calls
Source Code
  subroutine tem_restart_closeRead( me )
    ! -------------------------------------------------------------------- !
    !> the restart information
    type(tem_restart_type) :: me
    ! -------------------------------------------------------------------- !
    ! temporary buffer array for empty reads
    real(kind=rk) :: chunk(1)
    integer :: iChunk
    ! -------------------------------------------------------------------- !
    ! If local process has performed less reads than global maximum required,
    ! we need to complete as many empty reads as the difference to maxnChunks
    ! to satisfy collective MPI-IO operations.
    me%nChunkElems = 0
    do iChunk = me%read_file%nChunks+1, me%read_file%maxnChunks
      call tem_restart_readData(restart = me, chunk = chunk)
    end do
    ! Invoke the routine to close current variable system file
    call tem_restart_closeRead_single(me)
    write(logUnit(1),*)' Closed Read.'
  end subroutine tem_restart_closeRead
Call graph
tem_restart_closeread calls tem_restart_closeread_single, tem_restart_readdata
tem_restart_closeread_single calls mpi_file_close, check_mpi_error
tem_restart_readdata calls tem_restart_readdata_single
check_mpi_error calls mpi_error_string, tem_abort
tem_restart_readdata_single calls check_mpi_error, mpi_file_read_all
tem_abort calls mpi_abort