tem_load_adapt – Treelm
tem_load_adapt Subroutine
12 statements
Source File
public subroutine tem_load_adapt(me, conf)
Load variables, parent scheme and conditions defined in lua file.
Arguments
Type Intent Optional Attributes Name
type(tem_adapt_type), intent(inout) :: me
adapt_type to be filled
type(flu_State), intent(in) :: conf
lua state to read from
Calls
Source Code
  subroutine tem_load_adapt( me, conf )
    ! ---------------------------------------------------------------------------
    !> adapt_type to be filled
    type( tem_adapt_type ), intent(inout) :: me
    !> lua state to read from
    type( flu_state ), intent(in)         :: conf
    ! ---------------------------------------------------------------------------
    integer :: adapt_handle
    ! ---------------------------------------------------------------------------
    ! Open the adapt table
    call aot_table_open( L       = conf,                                       &
      &                  thandle = adapt_handle,                               &
      &                  key     = 'adaptation' )
    if ( adapt_handle /= 0 ) then
      ! get timeControl conditions
      call tem_timeControl_load( me     = me%time,                             &
        &                        conf   = conf,                                &
        &                        parent = adapt_handle )
      me%active = .TRUE.
      write(logUnit(1),"(A)") 'Mesh Adaptation is active!'
    end if
    ! close the adaptation table
    call aot_table_close( L=conf, thandle=adapt_handle )
  end subroutine tem_load_adapt
Call graph
tem_load_adapt calls aot_table_close, aot_table_open, tem_timecontrol_load
tem_timecontrol_load calls aot_table_close, aot_table_open, aot_get_val, tem_time_default_zero, tem_time_load, tem_time_needs_reduce, tem_time_never
tem_time_load calls aot_table_close, aot_table_open, aot_get_val, mpi_wtime