tem_exchange_double2 – Treelm
tem_exchange_double2 Subroutine
12 statements
Source File
private subroutine tem_exchange_double2(me, val, nComponents, comm)
Arguments
Type Intent Optional Attributes Name
type(tem_sparta_type), intent(in) :: me
real(kind=double_k), intent(inout), allocatable :: val(:,:)
integer, intent(in) :: nComponents
integer, intent(in) :: comm
Calls
Called by
Source Code
  subroutine tem_exchange_double2( me, val, nComponents, comm )
    ! ---------------------------------------------------------------------------
    type( tem_sparta_type ), intent(in) :: me
    integer, intent(in) :: nComponents
    real(kind=double_k), allocatable, intent(inout) :: val(:,:)
    integer, intent(in) :: comm
    ! ---------------------------------------------------------------------------
    real(kind=double_k), allocatable :: old_val(:,:)
    integer :: iError
    ! ---------------------------------------------------------------------------
    call move_alloc( val, old_val )
    allocate( val(nComponents, me%new_size) )
    call mpi_alltoallv( old_val, me%send_count*nComponents, me%send_index*nComponents, mpi_double_precision,&
                            val, me%recv_count*nComponents, me%recv_index*nComponents, mpi_double_precision,&
                        comm, ierror )
    deallocate( old_val )
  end subroutine tem_exchange_double2
Call graph
tem_exchange_double2 calls mpi_alltoallv
tem_exchange_sparta calls tem_exchange_double2
exchange_elements calls tem_exchange_sparta
load_tem calls exchange_elements
tem_restart_readheader calls load_tem