tem_reduction_transient_load – Treelm
tem_reduction_transient_load Subroutine
20 statements
Source File
public subroutine tem_reduction_transient_load(me, conf, parent)
Read time reduction info from reduction_transient operation variable
Arguments
Type Intent Optional Attributes Name
type(tem_reduction_transient_config_type), intent(out) :: me
time reduction
type(flu_State), intent(inout) :: conf
handle for lua file
integer, intent(in) :: parent
operation table handle
Calls
Called by
Source Code
  subroutine tem_reduction_transient_load( me, conf, parent )
    ! -------------------------------------------------------------------- !
    !> time reduction
    type(tem_reduction_transient_config_type), intent(out) :: me
    !> handle for lua file
    type(flu_State), intent(inout)                    :: conf
    !> operation table handle
    integer, intent(in)                               :: parent
    ! -------------------------------------------------------------------- !
    integer :: iError, reduce_handle
    ! -------------------------------------------------------------------- !
    write(logUnit(10),*) 'Loading reduction transient'
    call aot_table_open( L       = conf,                 &
      &                  thandle = reduce_handle,        &
      &                  parent  = parent,               &
      &                  key     = 'reduction_transient' )
    call aot_get_val( L       = conf,          &
      &               thandle = reduce_handle, &
      &               val     = me%nRecord,    &
      &               ErrCode = iError,        &
      &               key     = "nrecord"      )
    if (btest(iError, aoterr_Fatal)) then
      write(logUnit(1),*)'FATAL Error occured, while retrieving nRecord:'
      if (btest(iError, aoterr_NonExistent))        &
        & write(logUnit(1),*)'Variable not existent!'
      if (btest(iError, aoterr_WrongType))            &
        & write(logUnit(1),*)'Variable has wrong type!'
      write(logUnit(1),*)'STOPPING'
      call tem_abort()
    end if
    call aot_get_val( L       = conf,          &
      &               thandle = reduce_handle, &
      &               val     = me%reduceType, &
      &               ErrCode = iError,        &
      &               default = 'average',     &
      &               key     = "kind"         )
    write(logUnit(10),*) 'Reduction type: '//trim(me%reduceType)
    write(logUnit(10),*) 'nIter to record: ', me%nRecord
    call aot_table_close(L=conf, thandle=reduce_handle)
  end subroutine tem_reduction_transient_load
Call graph
tem_reduction_transient_load calls aot_get_val, aot_table_close, aot_table_open, tem_abort
tem_abort calls mpi_abort
load_variable_operation calls tem_reduction_transient_load
tem_variable_load_single calls load_variable_operation
tem_variable_load calls tem_variable_load_single, tem_variable_load_vector
tem_variable_load_vector calls tem_variable_load_single