tem_spatial_lua_vector_for_index – Treelm
tem_spatial_lua_vector_for_index Function
32 statements
Source File
private function tem_spatial_lua_vector_for_index(fun_ref, conf, grwPnt, idx, nVals, nComps) result(res)
This function invokes the vectorial Lua function, which takes tem_grwPoints_type and evaluate a function at a point of given idx in grwPnt.
Lua function defined in the script is connected to the conf handle and return the result of the function. The Lua function takes barycentric coordinate as input argument i.e fun_name(x,y,z)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: fun_ref
Lua reference to the function to evaluate.
type(flu_State) :: conf
lua state
type(tem_grwPoints_type), intent(in) :: grwPnt
growing array of all spatial point of a variable
integer, intent(in) :: idx(nVals)
Index position to return a pre-store value or to compute
integer, intent(in) :: nVals
number of return values
integer, intent(in) :: nComps
number of components per returned value
Return Value real(kind=rk), (nVals,nComps)
return value
Calls
Called by
Source Code
  function tem_spatial_lua_vector_for_index( fun_ref, conf, grwPnt, idx, &
    &                                        nVals, nComps ) result(res)
    ! -------------------------------------------------------------------- !
    !> Lua reference to the function to evaluate.
    integer, intent(in) :: fun_ref
    !> number of return values
    integer, intent(in) :: nVals
    !> number of components per returned value
    integer, intent(in) :: nComps
    !> growing array of all spatial point of a variable
    type(tem_grwPoints_type), intent(in) :: grwPnt
    !> Index position to return a pre-store value or to compute
    integer, intent(in) :: idx(nVals)
    !> lua state
    type(flu_State) :: conf
    !> return value
    real(kind=rk) :: res(nVals,nComps)
    ! -------------------------------------------------------------------- !
    type(aot_fun_type) :: fun
    integer :: iError(ncomps)
    integer :: iDir, jDir
    real(kind=rk) :: coord(3)
    ! -------------------------------------------------------------------- !
    call aot_fun_open(L=conf, fun=fun, ref=fun_ref)
    do iDir = 1, nVals
      coord(:) =  (/ grwPnt%coordX%val( idx(iDir) ), &
        &            grwPnt%coordY%val( idx(iDir) ), &
        &            grwPnt%coordZ%val( idx(iDir) ) /)
      do jDir = 1, 3
        call aot_fun_put( L=conf, fun=fun, arg=coord(jDir) )
      end do
      call aot_fun_do(L=conf, fun=fun, nresults=1)
      call aot_top_get_val(L=conf, val=res(iDir,:), ErrCode=iError)
      if ( any(btest(iError,aoterr_Fatal)) ) then
        write(logunit(0),*) "ERROR Obtaining a spactial function"
        write(logunit(0),*) "Probably wrong number of components returned"
        write(logunit(0),*) "or a scalar was return as a lua table"
        write(logunit(0),*) 'Expected nComp: ', nComps
        write(logunit(0),*) 'ErrorCodes: ', iError
        write(logunit(0),*) "Check return values of your Lua functions!"
        call tem_abort()
      end if
    end do
    call aot_fun_close(L=conf, fun=fun)
  end function tem_spatial_lua_vector_for_index
Call graph
tem_spatial_lua_vector_for_index calls aot_fun_close, aot_fun_do, aot_fun_open, aot_fun_put, aot_top_get_val, tem_abort
tem_abort calls mpi_abort
tem_spatial_lua_for calls tem_spatial_lua_vector_for_index
tem_spatial_for_coord calls tem_spatial_lua_for
tem_spatial_for_treeids calls tem_spatial_lua_for
tem_spatial_scalar_for_index calls tem_spatial_lua_for, tem_spatial_for_coord
tem_spatial_vector_for_coord calls tem_spatial_lua_for
tem_spatial_vector_for_index calls tem_spatial_lua_for, tem_spatial_vector_for_coord
tem_spatial_vector_for_treeids calls tem_spatial_lua_for
tem_spatial_for calls tem_spatial_for_coord, tem_spatial_for_treeids, tem_spatial_scalar_for_index, tem_spatial_vector_for_coord, tem_spatial_vector_for_index, tem_spatial_vector_for_treeids
tem_spacetime_for_coord calls tem_spatial_for
tem_spacetime_for_treeids calls tem_spatial_for
tem_spacetime_scalar_for_index calls tem_spatial_for
tem_spacetime_vector_for_coord calls tem_spatial_for
tem_spacetime_vector_for_index calls tem_spatial_for
tem_spacetime_vector_for_treeids calls tem_spatial_for
tem_spatial_scalar_storeval calls tem_spatial_for
tem_spatial_vector_storeval calls tem_spatial_for