tem_convergence_out_single – Treelm
tem_convergence_out_single Subroutine
29 statements
Source File
private subroutine tem_convergence_out_single(me, conf, level)
Allows the output of the single convergence to lua out.
The data is written into the file, the lunit is connected to. It is formatted as a Lua table.
Arguments
Type Intent Optional Attributes Name
type(tem_convergence_type), intent(in) :: me
convergence to write into the lua file
type(aot_out_type), intent(inout) :: conf
aotus type handling the output to the file in lua format
integer, intent(in), optional :: level
to dump variable with key or without key
Calls
Called by
Source Code
  subroutine tem_convergence_out_single(me, conf, level)
    ! -------------------------------------------------------------------- !
    !> convergence to write into the lua file
    type(tem_convergence_type), intent(in) :: me
    !> aotus type handling the output to the file in lua format
    type(aot_out_type), intent(inout) :: conf
    !> to dump variable with key or without key
    integer, optional, intent(in) :: level
    ! -------------------------------------------------------------------- !
    integer :: level_loc, iVar
    ! -------------------------------------------------------------------- !
    if (present(level)) then
      level_loc = level
    else
      level_loc = 0
    end if
    if( level_loc == 0) then
      call aot_out_open_table( put_conf = conf, tname = 'convergence' )
    else
      call aot_out_open_table( put_conf = conf )
    end if
    ! write variable names
    call aot_out_open_table( put_conf = conf, tname = 'variable' )
    do iVar = 1, me%header%nRequestedVars
      call aot_out_val( put_conf = conf,                         &
        &               val      = trim(me%header%varName(iVar)) )
    end do
    call aot_out_close_table( put_conf = conf )
    ! convergence norm
    call aot_out_val( put_conf = conf,           &
      &               val      = me%header%norm, &
      &               vname    = 'norm'          )
    call aot_out_val( put_conf = conf,                &
      &               val      = me%header%nLastVals, &
      &               vname    = 'nvals'              )
    call aot_out_val( put_conf = conf,                    &
      &               val      = me%header%absoluteError, &
      &               vname    = 'absolute'               )
    ! write reductions
    call tem_reduction_spatial_out( me%redSpatial, conf )
    ! write conditions
    call tem_condition_out( me%header%cond, conf )
    ! write timeControl info
    call tem_timeControl_out( me%header%timeControl, conf )
    ! write shapes
    call tem_shape_out( me%header%geometry, conf )
    call aot_out_close_table( put_conf = conf )
  end subroutine tem_convergence_out_single
Call graph
tem_convergence_out_single calls aot_out_close_table, aot_out_open_table, aot_out_val, tem_condition_out, tem_reduction_spatial_out, tem_shape_out, tem_timecontrol_out
tem_condition_out calls tem_condition_out_single, tem_condition_out_vector
tem_reduction_spatial_out calls tem_reduction_spatial_out_single, tem_reduction_spatial_out_vector
tem_shape_out calls tem_shape_out_scal, tem_shape_out_vec
tem_timecontrol_out calls aot_out_close_table, aot_out_open_table, aot_out_val, tem_time_out
tem_condition_out_single calls aot_out_close_table, aot_out_open_table, aot_out_val
tem_condition_out_vector calls aot_out_close_table, aot_out_open_table, tem_condition_out_single
tem_reduction_spatial_out_single calls aot_out_val
tem_reduction_spatial_out_vector calls aot_out_val
tem_shape_out_scal calls aot_out_close_table, aot_out_open_table, aot_out_val, tem_canonicalnd_out, tem_cylinder_out, tem_ellipsoid_out, tem_sphere_out, tem_stlhead_out, tem_triangle_out, tem_shape_bclabel_out, tem_shape_level_out, tem_shape_proplabel_out
tem_shape_out_vec calls aot_out_close_table, aot_out_open_table, tem_shape_out_scal
tem_time_out calls aot_out_close_table, aot_out_open_table, aot_out_val
tem_convergence_out calls tem_convergence_out_single, tem_convergence_out_vector
tem_convergence_dump_single calls tem_convergence_out_single
tem_convergence_out_vector calls tem_convergence_out_single
tem_convergence_dump calls tem_convergence_dump_single, tem_convergence_dump_vector
tem_convergence_dump_vector calls tem_convergence_out_vector