tem_shape_out_scal – Treelm
tem_shape_out_scal Subroutine
31 statements
Source File
private subroutine tem_shape_out_scal(me, conf)
Write a shape to lua file
Arguments
Type Intent Optional Attributes Name
type(tem_shape_type), intent(in) :: me
shape types to write out
type(aot_out_type), intent(inout) :: conf
Aotus type handling the output to the file in lua format
Calls
Called by
Source Code
  subroutine tem_shape_out_scal( me, conf )
    !---------------------------------------------------------------------------
    !> shape types to write out
    type( tem_shape_type ), intent(in) :: me
    !> Aotus type handling the output to the file in lua format
    type(aot_out_type), intent(inout) :: conf
    !---------------------------------------------------------------------------
    ! create a table with name shape if not exist
    if( conf%level .eq. 0 ) then
      call aot_out_open_table( put_conf = conf, tname = 'shape' )
    else
      call aot_out_open_table( put_conf = conf )
    end if
    call aot_out_val( put_conf = conf, vname = 'kind', &
      &               val = trim(me%kind) )
    ! choose output shape kind
    select case( trim(me%kind) )
    case('canoND')
      call tem_canonicalND_out(me%canoND, conf)
    case('triangle')
      call tem_triangle_out(me%triangle, conf)
    case('stl')
      call tem_stlHead_out(me%stl_data%head, conf)
    case('sphere')
      call tem_sphere_out(me%sphere, conf)
    case('ellipsoid')
      call tem_ellipsoid_out(me%ellipsoid, conf)
    case('cylinder')
      call tem_cylinder_out(me%cylinder, conf)
    case('property')
      call tem_shape_propLabel_out(me%propBits, conf)
    case('level')
      call tem_shape_level_out(me%minLevel, me%maxLevel, conf)
    case('boundary')
      call tem_shape_bcLabel_out(me%bcLabels, conf)
    end select
    call aot_out_close_table( put_conf = conf )
  end subroutine tem_shape_out_scal
Call graph
tem_shape_out_scal calls aot_out_close_table, aot_out_open_table, aot_out_val, tem_canonicalnd_out, tem_cylinder_out, tem_ellipsoid_out, tem_sphere_out, tem_stlhead_out, tem_triangle_out, tem_shape_bclabel_out, tem_shape_level_out, tem_shape_proplabel_out
tem_canonicalnd_out calls tem_canonicalnd_out_scal, tem_canonicalnd_out_vec
tem_cylinder_out calls tem_cylinder_out_scal, tem_cylinder_out_vec
tem_ellipsoid_out calls tem_ellipsoid_out_scal, tem_ellipsoid_out_vec
tem_sphere_out calls tem_sphere_out_scal, tem_sphere_out_vec
tem_stlhead_out calls tem_stlhead_out_scal, tem_stlhead_out_vec
tem_triangle_out calls tem_triangle_out_scal, tem_triangle_out_vec
tem_shape_bclabel_out calls aot_out_close_table, aot_out_open_table, aot_out_val
tem_shape_level_out calls aot_out_close_table, aot_out_open_table, aot_out_val
tem_shape_proplabel_out calls aot_out_close_table, aot_out_open_table, aot_out_val
tem_canonicalnd_out_scal calls aot_out_close_table, aot_out_open_table, aot_out_val
tem_canonicalnd_out_vec calls aot_out_close_table, aot_out_open_table, tem_canonicalnd_out_scal
tem_cylinder_out_scal calls aot_out_close_table, aot_out_open_table, aot_out_val
tem_cylinder_out_vec calls aot_out_close_table, aot_out_open_table, tem_cylinder_out_scal
tem_ellipsoid_out_scal calls aot_out_close_table, aot_out_open_table, aot_out_val
tem_ellipsoid_out_vec calls aot_out_close_table, aot_out_open_table, tem_ellipsoid_out_scal
tem_sphere_out_scal calls aot_out_close_table, aot_out_open_table, aot_out_val
tem_sphere_out_vec calls aot_out_close_table, aot_out_open_table, tem_sphere_out_scal
tem_stlhead_out_scal calls aot_out_close_table, aot_out_open_table, aot_out_val
tem_stlhead_out_vec calls aot_out_close_table, aot_out_open_table, tem_stlhead_out_scal
tem_triangle_out_scal calls aot_out_close_table, aot_out_open_table, aot_out_val
tem_triangle_out_vec calls aot_out_close_table, aot_out_open_table, aot_out_val, tem_triangle_out_scal
tem_shape_out calls tem_shape_out_scal, tem_shape_out_vec
tem_shape_out_vec calls tem_shape_out_scal
hvs_ascii_write_header calls tem_shape_out
tem_convergence_out_single calls tem_shape_out
tem_convergence_out calls tem_convergence_out_single, tem_convergence_out_vector
hvs_ascii_init calls hvs_ascii_write_header
hvs_asciispatial_init calls hvs_ascii_write_header
tem_convergence_dump_single calls tem_convergence_out_single
tem_convergence_out_vector calls tem_convergence_out_single
tem_convergence_dump calls tem_convergence_dump_single
hvs_output_init calls hvs_ascii_init, hvs_asciispatial_init
tem_convergence_dump_vector calls tem_convergence_out_vector