tem_simControl_dump_now – Treelm
tem_simControl_dump_now Subroutine
6 statements
Source File
public subroutine tem_simControl_dump_now(me, outUnit)
Dump the current time (now) of the simControl to outUnit.
This also updates the clock in now to really show the current time.
Arguments
Type Intent Optional Attributes Name
type(tem_simControl_type), intent(inout) :: me
Simulation control settings to write to outUnit.
integer, intent(in) :: outUnit
File unit to write to.
Calls
Called by
Source Code
  subroutine tem_simControl_dump_now(me, outUnit)
    ! -------------------------------------------------------------------- !
    !> Simulation control settings to write to outUnit.
    type(tem_simControl_type), intent(inout) :: me
    !> File unit to write to.
    integer, intent(in) :: outUnit
    ! -------------------------------------------------------------------- !
    call tem_time_set_clock(me%now)
    call tem_time_dump(me%now, outUnit)
  end subroutine tem_simControl_dump_now
Call graph
tem_simcontrol_dump_now calls tem_time_dump, tem_time_set_clock
tem_time_set_clock calls mpi_wtime
tem_simcontrol_dump calls tem_simcontrol_dump_now
tem_load_general calls tem_simcontrol_dump