tem_triangle_out_scal – Treelm
tem_triangle_out_scal Subroutine
16 statements
Source File
private subroutine tem_triangle_out_scal(me, conf)
Write out a triangle shape in lua format
Arguments
Type Intent Optional Attributes Name
type(tem_triangle_type), intent(in) :: me
triangle types to write out
type(aot_out_type), intent(inout) :: conf
Aotus type handling the output to the file in lua format
Calls
Called by
Source Code
  subroutine tem_triangle_out_scal( me, conf )
    ! --------------------------------------------------------------------------
    !> triangle types to write out
    type( tem_triangle_type ), intent(in) :: me
    !> Aotus type handling the output to the file in lua format
    type(aot_out_type), intent(inout) :: conf
    ! --------------------------------------------------------------------------
    integer :: iNode
    ! ---------------------------------------------------------------------------
    ! create a table with name triangle if not exist
    if( conf%level == 0 ) then
      call aot_out_open_table( put_conf = conf, tname = 'triangle' )
    else
      call aot_out_open_table( put_conf = conf )
    end if
    !write nodes
    call aot_out_open_table( put_conf = conf, tname = 'nodes' )
    do iNode=1,3
      call aot_out_val( put_conf = conf, val = me%nodes(:,iNode) )
    enddo
    call aot_out_close_table( put_conf = conf )
    call aot_out_close_table( put_conf = conf )
  end subroutine tem_triangle_out_scal
Call graph
tem_triangle_out_scal calls aot_out_close_table, aot_out_open_table, aot_out_val
tem_triangle_out calls tem_triangle_out_scal, tem_triangle_out_vec
tem_triangle_out_vec calls tem_triangle_out_scal
tem_shape_out_scal calls tem_triangle_out
tem_shape_out calls tem_shape_out_scal, tem_shape_out_vec
tem_shape_out_vec calls tem_shape_out_scal
hvs_ascii_write_header calls tem_shape_out
tem_convergence_out_single calls tem_shape_out