tem_boxCubeOverlap – Treelm
tem_boxCubeOverlap Function
14 statements
Source File
public function tem_boxCubeOverlap(box, cube) result(overlap)
This function checks for intersection of box and cube
Currently support only axis aligned box @note Todo implemented oriented box - cube overlap
Arguments
Type Intent Optional Attributes Name
type(tem_box_type), intent(in) :: box
type(tem_cube_type), intent(in) :: cube
Return Value logical
Calls
Called by
Source Code
  function tem_boxCubeOverlap( box, cube ) result(overlap)
    type(tem_box_type), intent(in) :: box
    type(tem_cube_type), intent(in) :: cube
    logical :: overlap
    integer :: iPlane
    if (box%only_surface) then
      overlap = .false.
      do iPlane = 1, 6
        overlap = overlap .or. tem_planeCubeOverlap( box%plane(iPlane), cube)
      end do
    else
      overlap = boxBoxOverlap( cube%center, &
        &                      [cube%halfwidth, &
        &                       cube%halfwidth, &
        &                       cube%halfwidth], &
        &                      box%center,  &
        &                      [box%halfwidth(1), &
        &                       box%halfwidth(2), &
        &                       box%halfwidth(3)], &
        &                      box%normal)
    end if
  end function tem_boxCubeOverlap
Call graph
tem_boxcubeoverlap calls boxboxoverlap, tem_planecubeoverlap
tem_planecubeoverlap calls tem_trianglecubeoverlap
tem_trianglecubeoverlap calls triboxoverlap_loc
triboxoverlap_loc calls axistest, cross_product3d, planeboxoverlap
tem_cano_initsubtree calls tem_boxcubeoverlap
tem_shape_subtreefromgeominters calls tem_cano_initsubtree
tem_shape2subtree calls tem_shape_subtreefromgeominters
tem_create_subtree_of calls tem_shape2subtree