tem_childNumber – Treelm
tem_childNumber Function
7 statements
Source File
public elemental function tem_childNumber(TreeID) result(res)
This function delivers of TreeID, which child number it is from its parent
Arguments
Type Intent Optional Attributes Name
integer(kind=long_k), intent(in) :: TreeID
current treeID
Return Value integer
result of function containing child number
Called by
Source Code
  elemental function tem_childNumber( TreeID ) result(res)
    ! ---------------------------------------------------------------------------
    !> current treeID
    integer(kind=long_k), intent(in) :: TreeID
    !> result of function containing child number
    integer :: res
    ! ---------------------------------------------------------------------------
    integer(kind=long_k) :: offset
    ! ---------------------------------------------------------------------------
    ! offset = ((treeID-1)/8) * 8
    offset = ishft((TreeID-1_long_k), -3) * 8_long_k
    res    = int( TreeID - offset )
  end function tem_childNumber
Call graph
add_all_virtual_children calls tem_childnumber, add_all_virtual_children
tem_build_verticaldependencies calls tem_childnumber
identify_local_element calls add_all_virtual_children
tem_create_leveldesc calls tem_build_verticaldependencies
identify_halo calls identify_local_element
single_process_element calls identify_local_element
tem_dimbydim_construction calls tem_create_leveldesc
identify_elements calls single_process_element
request_remotehalos calls identify_halo
tem_build_face_info calls tem_dimbydim_construction