tem_spacetime_for_stcoord – Treelm
tem_spacetime_for_stcoord Function
14 statements
Source File
private function tem_spacetime_for_stcoord(me, stCoord, n) result(res)
This function computes the space time function for given list of space-time coordinates.
Todo
JZ: i added the subroutine for the space-time formulation. Below you see, that we create a tem_time_type variable in each loop. The code can be faster if we implement this routine in a nicer way.
Arguments
Type Intent Optional Attributes Name
type(tem_spacetime_fun_type) :: me
Spacetime function to evaluate
real(kind=rk), intent(in) :: stCoord(n,4)
barycentric Ids of an elements. 1st index goes over number of elements and 2nd index goes over x,y,z,t coordinates
integer, intent(in) :: n
Number of values to return
Return Value real(kind=rk), (n)
return value of the function
Calls
Called by
Source Code
  function tem_spacetime_for_stcoord( me, stCoord, n  ) result(res)
    ! -------------------------------------------------------------------- !
    !> Spacetime function to evaluate
    type(tem_spacetime_fun_type) :: me
    !> Number of values to return
    integer, intent(in) :: n
    !> barycentric Ids of an elements.
    !! 1st index goes over number of elements and
    !! 2nd index goes over x,y,z,t coordinates
    real(kind=rk), intent(in) :: stCoord(n,4)
    !> return value of the function
    real(kind=rk) :: res(n)
    ! -------------------------------------------------------------------- !
    real(kind=rk) :: spaceCoord(1,3)
    integer :: iPoint
    type(tem_time_type) :: time
    ! -------------------------------------------------------------------- !
    !> @todo JZ: i added the subroutine for the space-time formulation.
    !! Below you see, that we create a tem_time_type variable in each loop.
    !! The code can be faster if we implement this routine in a nicer way.
    do iPoint = 1, n
      time%sim = stcoord(iPoint, 4)
      spaceCoord(1,1:3) = stcoord(iPoint, 1:3)
      res(iPoint:iPoint)                                                       &
        & = tem_spacetime_for_coord( me    = me,         &
        &                            coord = spaceCoord, &
        &                            time  = time,       &
        &                            n     = 1           )
    end do
  end function tem_spacetime_for_stcoord
Call graph
tem_spacetime_for_stcoord calls tem_spacetime_for_coord
tem_spacetime_for_coord calls tem_spacetime_lua_for, tem_spatial_for, tem_abort, tem_eval_acoustic_pulse, tem_eval_cylindricalwave, tem_eval_miescatter_displz, tem_eval_miescatter_magnx, tem_eval_miescatter_magny, tem_polygon_material_movement_multi, tem_polygon_material_movement_single, tem_temporal_for
tem_spacetime_lua_for calls tem_spacetime_lua_for_coord, tem_spacetime_lua_for_treeids, tem_spacetime_lua_vector_for_coord, tem_spacetime_lua_vector_for_treeids
tem_spatial_for calls tem_spatial_for_coord, tem_spatial_for_treeids, tem_spatial_scalar_for_index, tem_spatial_vector_for_coord, tem_spatial_vector_for_index, tem_spatial_vector_for_treeids
tem_abort calls mpi_abort
tem_polygon_material_movement_multi calls tem_abort, tem_polygon_material_value
tem_polygon_material_movement_single calls tem_abort, tem_polygon_material_value
tem_temporal_for calls tem_abort, temporal_from_file_periodic_for, temporal_linear_for, temporal_lua_for, temporal_smooth_for
tem_spacetime_for calls tem_spacetime_for_stcoord
evaluate_add_spacetime_scalarbycoordinate calls tem_spacetime_for
evaluate_add_spacetime_scalarbytreeid calls tem_spacetime_for
evaluate_add_spacetime_vectorbycoordinate calls tem_spacetime_for
evaluate_add_spacetime_vectorbytreeid calls tem_spacetime_for
evaluate_first_spacetime_scalarbycoordinate calls tem_spacetime_for
evaluate_first_spacetime_scalarbytreeid calls tem_spacetime_for
evaluate_first_spacetime_vectorbycoordinate calls tem_spacetime_for
evaluate_first_spacetime_vectorbytreeid calls tem_spacetime_for
evaluate_foag_spacetime_scalarbycoordinate calls tem_spacetime_for
evaluate_foag_spacetime_scalarbytreeid calls tem_spacetime_for
evaluate_foag_spacetime_vectorbycoordinate calls tem_spacetime_for
evaluate_foag_spacetime_vectorbytreeid calls tem_spacetime_for
get_valofindex_add_scalar_spacetime calls tem_spacetime_for
get_valofindex_add_vector_spacetime calls tem_spacetime_for
get_valofindex_first_scalar_spacetime calls tem_spacetime_for
get_valofindex_first_vector_spacetime calls tem_spacetime_for
get_valofindex_foag_scalar_spacetime calls tem_spacetime_for
get_valofindex_foag_vector_spacetime calls tem_spacetime_for
tem_update_surfpos calls tem_spacetime_for