tem_getTimerVal – Treelm
tem_getTimerVal Function
16 statements
Source File
public function tem_getTimerVal(me, timerHandle) result(retValue)
Write out the timer name and its value
Arguments
Type Intent Optional Attributes Name
type(tem_timer_type), intent(inout), optional :: me
timer object
integer, intent(in) :: timerHandle
timer handle
Return Value real(kind=rk)
timer value
Calls
Called by
Source Code
  function tem_getTimerVal( me, timerHandle ) result( retValue )
    ! -------------------------------------------------------------------- !
    !> timer object
    type(tem_timer_type), intent(inout), optional :: me
    !> timer handle
    integer, intent(in) :: timerHandle
    !> timer value
    real(kind=rk) :: retValue
    ! -------------------------------------------------------------------- !
    if ( present(me) ) then
      if ( me%running%val(timerHandle) ) then
        call tem_stoptimer(me, timerhandle)
      end if
      retValue = me%duration%val(timerHandle)
    else
      if ( timer%timedat%running%val(timerHandle) ) then
        call tem_stoptimer(timerhandle = timerhandle)
      end if
      retValue = timer%timedat%duration%val(timerHandle)
    end if
  end function tem_getTimerVal
Call graph
tem_gettimerval calls tem_stoptimer
tem_stoptimer calls mpi_wtime
tem_finalize calls tem_gettimerval, tem_timer_dump_glob
tem_getavetimerval calls tem_gettimerval
tem_getmaxtimerval calls tem_gettimerval
tem_getmintimerval calls tem_gettimerval
tem_getsumtimerval calls tem_gettimerval
tem_timer_dumplabeled calls tem_getmaxtimerval, tem_getmintimerval, tem_getsumtimerval
tem_timer_dump_glob calls tem_timer_dumplabeled