tem_GetLocalBoundingCube_fromSubTree – Treelm
tem_GetLocalBoundingCube_fromSubTree Function
30 statements
Source File
private function tem_GetLocalBoundingCube_fromSubTree(subTree, globalTree) result(BoundingCube)
Run through all the elements, check the vertices and return the fluid bounding cube
Arguments
Type Intent Optional Attributes Name
type(tem_subTree_type), intent(in) :: subTree
subTree to locate point in
type(treelmesh_type), intent(in) :: globalTree
corresponding global tree
Return Value real(kind=rk), (3,2)
xyz coordinate for min and max of bounding cube
Calls
Called by
Source Code
  function tem_GetLocalBoundingCube_fromSubTree( subTree, globalTree ) &
    &        result(BoundingCube)
    ! -------------------------------------------------------------------- !
    !> subTree to locate point in
    type(tem_subTree_type), intent(in) :: subTree
    !> corresponding global tree
    type(treelmesh_type), intent(in) :: globalTree
    !> xyz coordinate for min and max of bounding cube
    real(kind=rk) :: BoundingCube(3,2)
    ! -------------------------------------------------------------------- !
    real(kind=rk) :: vrtxCoord(3,8) ! coordinates for all eight vertices
    real(kind=rk) :: minX(3) ! xyz coordinate for min of bounding cube
    real(kind=rk) :: maxX(3) ! xyz coordinate for max of bounding cube
    integer(kind=long_k) :: tTreeID
    integer :: iElem, iVert
    ! -------------------------------------------------------------------- !
    ! if the subTree equals to the global shape
    if( subTree%useGlobalMesh ) then
      ! ... the effective bounding cube equals to the one of the tree
      BoundingCube = globalTree%global%effboundingCube(3,2)
    else ! if this is not the case
      minX =  huge( minX )
      maxX = -huge( maxX )
      ! loop over all elements
      do iElem = 1, subTree%nElems
        ! ... and distinguish between local shapes and other shapes
        if( subTree%useLocalMesh ) then
          ! ... copy the treeIDs directly
          tTreeID = subTree%treeID( iElem )
        else
          ! ... the treeIDs from the globalTree via the positions in map2global
          tTreeID = globalTree%treeID( subTree%map2global( iElem ))
        end if
        ! Calculate coordinates of vertices
        vrtxCoord(:,:) = tem_vrtxCoordOfId( globalTree, tTreeID )
        do iVert = 1, 8
          ! Compare with min max
          minX(:) = min( minX(:), vrtxCoord(:, iVert ))
          maxX(:) = max( maxX(:), vrtxCoord(:, iVert ))
        enddo
      enddo
      BoundingCube(:,1) = minX(:)
      BoundingCube(:,2) = maxX(:)
    end if ! useGlobalShape
  end function tem_GetLocalBoundingCube_fromSubTree
Call graph
tem_getlocalboundingcube_fromsubtree calls tem_vrtxcoordofid
tem_vrtxcoordofid calls tem_baryofid, tem_coordofid
tem_baryofid calls tem_coordofid, tem_elemsizelevel
tem_coordofid calls tem_levelof
tem_getlocalboundingcube calls tem_getlocalboundingcube_fromsubtree
tem_getrealboundingcube calls tem_getlocalboundingcube
tem_seteffboundingbox_fromsubtree calls tem_getlocalboundingcube
tem_seteffboundingbox calls tem_seteffboundingbox_fromsubtree, tem_seteffboundingbox_fromtree
tem_seteffboundingbox_fromtree calls tem_getrealboundingcube
tem_create_subtree_of calls tem_seteffboundingbox