tem_getFace_prp – Treelm
tem_getFace_prp Subroutine
8 statements
Source File
private subroutine tem_getFace_prp(faces, facePos, leftPrp, rightPrp)
Subroutine returns left and right propery of a face.
Arguments
Type Intent Optional Attributes Name
type(tem_face_descriptor_type), intent(in) :: faces
The face descriptor the face is located in.
integer, intent(in) :: facePos
The position of the face in the face descriptor.
integer, intent(out) :: leftPrp
The left property of the face.
integer, intent(out) :: rightPrp
The right property of the face.
Called by
Source Code
  subroutine tem_getFace_prp( faces, facePos, leftPrp, rightPrp)
    ! --------------------------------------------------------------------------
    !> The face descriptor the face is located in.
    type(tem_face_descriptor_type), intent(in) :: faces
    !> The position of the face in the face descriptor.
    integer, intent(in) :: facePos
    !> The left property of the face.
    integer, intent(out) :: leftPrp
    !> The right property of the face.
    integer, intent(out) :: rightPrp
    ! --------------------------------------------------------------------------
    ! --------------------------------------------------------------------------
    ! read the left and right property
    leftPrp = faces%faceList%leftPrp%val(facePos)
    rightPrp = faces%faceList%rightPrp%val(facePos)
  end subroutine tem_getFace_prp
Call graph
tem_facedep_verticaldown calls tem_getface_prp
tem_facedep_verticalup calls tem_getface_prp
tem_facedep_vertical calls tem_facedep_verticaldown, tem_facedep_verticalup
tem_build_face_info calls tem_facedep_vertical