tem_create_EndianSuffix – Treelm
tem_create_EndianSuffix Function
8 statements
Source File
public function tem_create_EndianSuffix() result(suffix)
This function returns the string in the line which starts with the specified key string in the text returned from print_self_status. The key string itself is excluded from the returned string. If the specified key is not found in the text an empty string will be returned.
Arguments
None
Return Value character(len=4)
Called by
Source Code
  function tem_create_EndianSuffix()  result(suffix)
    ! ---------------------------------------------------------------------------
    character(len=4) :: suffix
    ! ---------------------------------------------------------------------------
    if (isLittleEndian) then
      suffix = '.lsb'
    else
      suffix = '.msb'
    end if
  end function tem_create_endianSuffix
Call graph
dump_tem_bc_prop calls tem_create_endiansuffix
dump_tem_bc_realarray calls tem_create_endiansuffix
dump_treelmesh calls tem_create_endiansuffix
load_tem calls tem_create_endiansuffix, load_treelmesh, tem_load_weights
load_tem_bc_prop calls tem_create_endiansuffix
load_tem_bc_realarray calls tem_create_endiansuffix
load_treelmesh calls tem_create_endiansuffix
tem_load_weights calls tem_create_endiansuffix
tem_restart_openwrite calls tem_create_endiansuffix, dump_treelmesh, tem_dump_subtree
dump_tem_bc_normal calls dump_tem_bc_realarray
dump_tem_bc_qval calls dump_tem_bc_realarray
getelemweight calls tem_load_weights
hvs_output_open calls tem_restart_openwrite
init_tem_bc_prop calls load_tem_bc_prop
load_tem_bc_normal calls load_tem_bc_realarray
load_tem_bc_qval calls load_tem_bc_realarray
tem_adapt_dump_newmesh calls dump_treelmesh
tem_dump_subtree calls dump_treelmesh
tem_restart_readheader calls load_tem
hvs_output_init calls tem_dump_subtree
tem_load_restart calls tem_restart_readheader
tem_tracker calls hvs_output_open
tem_write_debugmesh calls tem_dump_subtree
tem_init_tracker calls hvs_output_init