tem_sphere_out_scal – Treelm
tem_sphere_out_scal Subroutine
13 statements
Source File
private subroutine tem_sphere_out_scal(me, conf)
Write out a sphere shape in lua format
Arguments
Type Intent Optional Attributes Name
type(tem_sphere_type), intent(in) :: me
sphere types to write out
type(aot_out_type), intent(inout) :: conf
Aotus type handling the output to the file in lua format
Calls
Called by
Source Code
  subroutine tem_sphere_out_scal( me, conf )
    ! --------------------------------------------------------------------------
    !> sphere types to write out
    type( tem_sphere_type ), intent(in) :: me
    !> Aotus type handling the output to the file in lua format
    type(aot_out_type), intent(inout) :: conf
    ! --------------------------------------------------------------------------
    ! create a table with name sphere if not exist
    if( conf%level == 0 ) then
      call aot_out_open_table( put_conf = conf, tname = 'object' )
    else
      call aot_out_open_table( put_conf = conf )
    end if
    call aot_out_val( put_conf = conf, vname = 'origin', val = me%origin )
    call aot_out_val( put_conf = conf, vname = 'radius', val = me%radius )
    call aot_out_val( put_conf = conf, vname = 'only_surface', &
      &               val = me%only_surface )
    call aot_out_close_table( put_conf = conf )
  end subroutine tem_sphere_out_scal
Call graph
tem_sphere_out_scal calls aot_out_close_table, aot_out_open_table, aot_out_val
tem_sphere_out calls tem_sphere_out_scal, tem_sphere_out_vec
tem_sphere_out_vec calls tem_sphere_out_scal
tem_shape_out_scal calls tem_sphere_out
tem_shape_out calls tem_shape_out_scal, tem_shape_out_vec
tem_shape_out_vec calls tem_shape_out_scal
hvs_ascii_write_header calls tem_shape_out
tem_convergence_out_single calls tem_shape_out