tem_treeIDinTotal – Treelm
tem_treeIDinTotal Function
17 statements
Source File
public function tem_treeIDinTotal(tID, levelDesc, eType) result(elemPos)
Returns the absolute position in the total list of a given treeID opposed to PosOfId, where the relative position in one of the separate lists is returned. Herefore, total list has to be created beforehand.
Arguments
Type Intent Optional Attributes Name
integer(kind=long_k), intent(in) :: tID
the element you are looking for
type(tem_levelDesc_type), intent(in) :: levelDesc
the descriptor you use for searching
integer, intent(in), optional :: eType
element type
Return Value integer
return position of tID in levelDesc%total list
Calls
Called by
Source Code
  function tem_treeIDinTotal( tID, levelDesc, eType ) result( elemPos )
    ! -------------------------------------------------------------------- !
    !> the element you are looking for
    integer(kind=long_k), intent(in) :: tID
    !> the descriptor you use for searching
    type(tem_levelDesc_type), intent(in) :: levelDesc
    !> element type
    integer, intent(in), optional :: eType
    !> return position of tID in levelDesc%total list
    integer :: elemPos
    ! -------------------------------------------------------------------- !
    integer :: eType_loc
    ! -------------------------------------------------------------------- !
    if( present( eType )) then
      eType_loc = eType
    else
      eType_loc = tem_eTypeOfID( tID, levelDesc%elem )
    end if
    elemPos = 0
    if( eType_loc > 0 ) then
      elemPos = tem_PositionInSorted( me    = levelDesc%total,                 &
        &                             lower = levelDesc%offset(1, eType_loc)+1,&
        &                             upper = levelDesc%offset(2, eType_loc),  &
        &                             val   = tID )
    end if
    elemPos = max( elemPos, 0 )
  end function tem_treeIDinTotal
Call graph
tem_treeidintotal calls tem_etypeofid, tem_positioninsorted
tem_etypeofid calls positionofval
positionofval calls posofval_label
posofval_label calls sortedposofval
tem_build_listhorizontaldep calls tem_treeidintotal
tem_build_treehorizontaldep calls tem_treeidintotal
tem_build_verticaldependencies calls tem_treeidintotal
tem_get_faceneigh calls tem_treeidintotal
tem_init_surfdata calls tem_treeidintotal
update_buffer_elempos calls tem_treeidintotal
update_elempostototalpos calls tem_treeidintotal, update_buffer_elempos
tem_build_horizontaldependencies calls tem_build_listhorizontaldep, tem_build_treehorizontaldep
tem_create_leveldesc calls tem_build_verticaldependencies, tem_build_horizontaldependencies, tem_find_allelements
tem_extend_commfromcoarserprp calls tem_get_faceneigh
tem_extend_commfromfinerprp calls tem_get_faceneigh
tem_find_allelements calls update_elempostototalpos
tem_get_faces calls tem_get_faceneigh
tem_update_surfpos calls tem_init_surfdata
tem_collect_faces calls tem_get_faces
tem_dimbydim_construction calls tem_create_leveldesc
tem_extend_remoteprp calls tem_extend_commfromcoarserprp, tem_extend_commfromfinerprp
tem_build_face_info calls tem_collect_faces, tem_dimbydim_construction, tem_extend_remoteprp