tem_PosOfId – Treelm
tem_PosOfId Function
46 statements
Source File
public pure function tem_PosOfId(sTreeID, treeIDlist, lower, upper) result(IdPos)
This subroutine does a binary search on a given (sparse) list of elements. The result is the position of the given tree ID in the list, 0 if no corresponding node is found, or the negative of the found ID, if it is a virtual node.
Build the path to the searched TreeID from the leaf to the root.
Arguments
Type Intent Optional Attributes Name
integer(kind=long_k), intent(in) :: sTreeID
tree ID to search for
integer(kind=long_k), intent(in) :: treeIDlist(:)
List to search in
integer, intent(in), optional :: lower
lowerbound of search interval
integer, intent(in), optional :: upper
upperbound of search interval
Return Value integer
position of sTreeID in the list of elements
Calls
Called by
Source Code
  pure function tem_PosOfId(sTreeID, treeIDlist, lower, upper) result(IdPos)
    ! -------------------------------------------------------------------- !
    !> tree ID to search for
    integer(kind=long_k), intent(in)  :: sTreeID
    !> List to search in
    integer(kind=long_k), intent(in)  :: treeIDlist(:)
    !> lowerbound of search interval
    integer, intent(in), optional     :: lower
    !> upperbound of search interval
    integer, intent(in), optional     :: upper
    !> position of sTreeID in the list of elements
    integer                           :: IdPos
    ! -------------------------------------------------------------------- !
    integer :: lb, ub
    integer :: middleSearch
    type(tem_path_type) :: searched
    type(tem_path_type) :: current
    integer :: pathRelation
    ! -------------------------------------------------------------------- !
    if (present(lower)) then
      lb = lower
    else
      lb = lbound(treeIDList,1)
    end if
    if (present(upper)) then
      ub = upper
    else
      ub = ubound(treeIDList,1)
    end if
    !> Build the path to the searched TreeID from the leaf to the root.
    searched = tem_PathOf(sTreeID)
    ! Start the Binary search for the neighbor elements
    binSearchLoop: do
      middleSearch = (lb + ub) / 2
      ! Build the path to the currently investigated element from leaf to root.
      current = tem_PathOf(treeIDList(middleSearch))
      pathRelation = tem_PathComparison(searched, current)
      if ((pathRelation == 0) .or. (lb >= ub)) then
        ! Leave the loop, if element has been found, or this
        ! was the last element to investigate.
        exit binSearchLoop
      else
        halves: if (pathRelation == 1) then
          ! Continue the search in the higher half, as the looked up element is
          ! to small.
          lb = min(middleSearch + 1, ub)
        else
          ! Continue search in the lower half, as the looked up element is to
          ! large.
          ub = max(middleSearch - 1, lb)
        end if halves
      end if
    end do binSearchLoop
    if (pathRelation == 0) then
      if (current%Level <= searched%Level) then
        ! The found ID is actually a leaf
        IdPos = middleSearch
      else
        ! The found ID is a parent of the searched
        ! virtual treeID
        IdPos = -middleSearch
      end if
    else
      IdPos = 0 ! no matching element found.
    end if
  end function tem_PosOfId
Call graph
tem_posofid calls tem_pathcomparison, tem_pathof
evaluate_add_spacetime_scalarbycoordinate calls tem_posofid
evaluate_add_spacetime_vectorbycoordinate calls tem_posofid
evaluate_first_spacetime_scalarbycoordinate calls tem_posofid
evaluate_first_spacetime_vectorbycoordinate calls tem_posofid
setup_indices_spacetime calls tem_posofid
tem_cano_checkneigh calls tem_posofid
tem_cano_initsubtree calls tem_posofid
tem_cano_storepntsinsubtree calls tem_posofid
tem_findelement calls tem_posofid, tem_findelement
tem_unify_vrtx calls tem_posofid
tem_calc_vrtx_coord calls tem_unify_vrtx
tem_shape_subtreefromgeominters calls tem_cano_checkneigh, tem_cano_initsubtree, tem_cano_storepntsinsubtree
hvs_output_init calls tem_calc_vrtx_coord
tem_shape2subtree calls tem_shape_subtreefromgeominters
tem_create_subtree_of calls tem_shape2subtree
tem_init_tracker calls hvs_output_init