tem_init_faceList – Treelm
tem_init_faceList Subroutine
9 statements
Source File
private subroutine tem_init_faceList(faceList)
Subroutine to initialize the dyanmic content of a face list.
Arguments
Type Intent Optional Attributes Name
type(tem_faceList_type), intent(inout) :: faceList
The face list to initialize.
Calls
Called by
Source Code
  subroutine tem_init_faceList( faceList )
    ! --------------------------------------------------------------------------
    !> The face list to initialize.
    type(tem_faceList_type), intent(inout) :: faceList
    ! --------------------------------------------------------------------------
    call init( me = faceList%faceId, length = 32 )
    call init( me = faceList%rightElemId, length = 32 )
    call init( me = faceList%leftElemPos, length = 32 )
    call init( me = faceList%rightElemPos, length = 32 )
    call init( me = faceList%leftPrp, length = 32 )
    call init( me = faceList%rightPrp, length = 32 )
  end subroutine tem_init_faceList
Call graph
tem_init_facelist calls init
init calls init_ga2d_real
tem_get_faces calls tem_init_facelist
tem_collect_faces calls tem_get_faces
tem_build_face_info calls tem_collect_faces