tem_size_stlb – Treelm
tem_size_stlb Subroutine
18 statements
Source File
public subroutine tem_size_stlb(filename, nNodes, nTris)
This subroutine reads the number of nodes and triangles from a given binary stl file.
Arguments
Type Intent Optional Attributes Name
character(len=PathLen), intent(in) :: filename
name of the binary stl file
integer, intent(out) :: nNodes
number of nodes in the file
integer, intent(out) :: nTris
number of triangles in the file
Calls
Called by
Source Code
  subroutine tem_size_stlb( filename, nNodes, nTris )
    ! --------------------------------------------------------------------------
    !> name of the binary stl file
    character(len=PathLen),intent(in) :: filename
    !> number of nodes in the file
    integer,intent(out) :: nNodes
    !> number of triangles in the file
    integer,intent(out) :: nTris
    ! --------------------------------------------------------------------------
    character(len=LabelLen) :: header
    integer :: stlUnit
    logical :: file_exists
    ! --------------------------------------------------------------------------
    inquire(file = trim(filename), exist = file_exists)
    if (.not. file_exists) then
      write(logUnit(0),*) trim(filename)//" file was not found. Dying..."
      call tem_abort()
    endif
    call tem_open( newunit = stlUnit,        &
      &            file    = trim(filename), &
      &            access  = 'stream',       &
      &            action  = 'read',         &
      &            status  = 'old'           )
    read(stlUnit) header
    read(stlUnit) nTris
    nNodes = nTris * 3
    close(stlUnit)
  end subroutine tem_size_stlb
Call graph
tem_size_stlb calls tem_abort, tem_open
tem_abort calls mpi_abort
tem_open calls tem_abort, newunit, upper_to_lower
tem_read_stlfiles calls tem_size_stlb
tem_readandunify_surfdata calls tem_size_stlb
tem_load_stl calls tem_read_stlfiles
tem_load_shape_single calls tem_load_stl
tem_load_shape calls tem_load_shape_single
tem_load_shapes calls tem_load_shape_single