tem_variable_out_vector – Treelm
tem_variable_out_vector Subroutine
10 statements
Source File
public subroutine tem_variable_out_vector(me, conf)
Allows the output of array of variable to lua out
Arguments
Type Intent Optional Attributes Name
type(tem_variable_type), intent(in) :: me(:)
variable to write into the lua file
type(aot_out_type), intent(inout) :: conf
aotus type handling the output to the file in lua format
Calls
Called by
Source Code
  subroutine tem_variable_out_vector(me, conf)
    ! ---------------------------------------------------------------------------
    !> variable to write into the lua file
    type(tem_variable_type), intent(in) :: me(:)
    !> aotus type handling the output to the file in lua format
    type(aot_out_type), intent(inout) :: conf
    ! ---------------------------------------------------------------------------
    integer :: iVar
    ! ---------------------------------------------------------------------------
    call aot_out_open_table( put_conf = conf, tname='variable' )
    do iVar = 1,size(me)
      call tem_variable_out_single( me(iVar), conf, level=1 )
    end do
    call aot_out_close_table( put_conf = conf )
  end subroutine tem_variable_out_vector
Call graph
tem_variable_out_vector calls aot_out_close_table, aot_out_open_table, tem_variable_out_single
tem_variable_out_single calls aot_out_close_table, aot_out_open_table, aot_out_val
tem_variable_out calls tem_variable_out_vector
tem_variable_dump_vector calls tem_variable_out_vector
tem_variable_dump calls tem_variable_dump_vector