tem_load_cond_single – Treelm
tem_load_cond_single Subroutine
20 statements
Source File
private subroutine tem_load_cond_single(cond, conf, thandle)
Load the conditions for geomIncr and convergence check within convergence conditions mean the operator and threshold against which the macroscopic variable has to be compared
Arguments
Type Intent Optional Attributes Name
type(tem_condition_type), intent(inout) :: cond
type(flu_State), intent(in) :: conf
integer, intent(in) :: thandle
Calls
Called by
Source Code
  subroutine tem_load_cond_single( cond, conf, thandle )
    ! -------------------------------------------------------------------- !
    !>
    type(tem_condition_type), intent(inout) :: cond
    !>
    type(flu_state), intent(in)             :: conf
    !>
    integer, intent(in)                     :: thandle
    ! -------------------------------------------------------------------- !
    integer :: iError
    ! -------------------------------------------------------------------- !
    call aot_get_val( L       = conf,           &
      &               thandle = thandle,        &
      &               val     = cond%threshold, &
      &               ErrCode = iError,         &
      &               key     = 'threshold'     )
    if ( btest(iError, aoterr_Fatal) ) then
      write(logUnit(0),*) "Fatal Error: In reading 'threshold' in condition"
      if ( btest(iError, aoterr_NonExistent) ) &
        & write(logUnit(0),*) 'NonExistent.'
      if ( btest(iError, aoterr_WrongType) ) write(logUnit(0),*) 'WrongType.'
      call tem_abort()
    end if
    call aot_get_val( L       = conf,           &
      &               thandle = thandle,        &
      &               val     = cond%operation, &
      &               ErrCode = iError,         &
      &               key     = 'operator'      )
    if ( btest(iError, aoterr_Fatal) ) then
      write(logUnit(0),*) "Fatal Error: In reading 'operator' for condition"
      if ( btest(iError, aoterr_NonExistent) ) &
        & write(logUnit(0),*) 'NonExistent.'
      if( btest(iError, aoterr_WrongType) ) write(logUnit(0),*) 'WrongType.'
      call tem_abort()
    end if
  end subroutine tem_load_cond_single
Call graph
tem_load_cond_single calls aot_get_val, tem_abort
tem_abort calls mpi_abort
tem_load_condition calls tem_load_cond_single
tem_load_convergenceheader calls tem_load_condition
tem_load_depend_single calls tem_load_condition
tem_load_depend calls tem_load_depend_single, tem_load_depend_vector
tem_convergence_load calls tem_load_convergenceheader
tem_load_depend_vector calls tem_load_depend_single
tem_abortcriteria_load calls tem_convergence_load