tem_restart_openRead – Treelm
tem_restart_openRead Subroutine
5 statements
Source File
public subroutine tem_restart_openRead(me)
open the restart dump file and write out the 'normal' restart header.
Arguments
Type Intent Optional Attributes Name
type(tem_restart_type) :: me
the restart information
Calls
Source Code
  subroutine tem_restart_openRead(me)
    ! -------------------------------------------------------------------- !
    !> the restart information
    type(tem_restart_type) :: me
    write(logUnit(1),*)' Open read... '
    ! read the restart header file
    ! prepare everything for the serialization of the data
    ! Invoke the routine to open single variable system from restart file
    call tem_restart_openRead_single(me)
  end subroutine tem_restart_openRead
Call graph
tem_restart_openread calls tem_restart_openread_single
tem_restart_openread_single calls mpi_file_open, mpi_file_set_view, check_mpi_error
check_mpi_error calls mpi_error_string, tem_abort
tem_abort calls mpi_abort