tem_LevelOf – Treelm
tem_LevelOf Function
13 statements
Source File
public elemental function tem_LevelOf(TreeID) result(res)
This function delivers the refinement level of a TreeID
The refinement level of a \ref treelmesh_module::treelmesh_type::treeid "treeID" is found by repeatedly computing the parents with the equation used in the [tem_ParentOf function] (@ref tem_parentatlevel) and counting the iterations, until the universal root is reached.
Arguments
Type Intent Optional Attributes Name
integer(kind=long_k), intent(in) :: TreeID
ID in the complete tree to look up
Return Value integer
Level of the given TreeID
Called by
Source Code
  elemental function tem_LevelOf( TreeID ) result(res)
    ! ---------------------------------------------------------------------------
    !> ID in the complete tree to look up
    integer(kind=long_k), intent(in) :: TreeID
    !> Level of the given TreeID
    integer :: res
    ! ---------------------------------------------------------------------------
    integer(kind=long_k) :: tElem
    integer :: level
    ! ---------------------------------------------------------------------------
    level = 0
    tElem = TreeID
    do while (tElem /= 0)
      ! bit operation is more efficient than division
      ! tElem = (tElem-1) / 8
      tElem = ishft( (tElem-1), -3 )
      level = level + 1
    end do
    res = level
  ! end function tem_LevelOf_singleTreeID
  end function tem_LevelOf
Call graph
add_all_virtual_children calls tem_levelof
add_ghostfromfiner calls tem_levelof
derivelevel calls tem_levelof
identify_elements calls tem_levelof
identify_halo calls tem_levelof
identify_local_element calls tem_levelof
single_process_element calls tem_levelof
tem_adapt_dump_newmesh calls tem_levelof
tem_build_levelpointer calls tem_levelof
tem_cano_checkneigh calls tem_levelof
tem_cano_initsubtree calls tem_levelof
tem_coordofid calls tem_levelof
tem_elemsize calls tem_levelof
tem_load_weights calls tem_levelof
tem_parentatlevel calls tem_levelof
tem_reduction_spatial_append calls tem_levelof
tem_shape_initbylevels calls tem_levelof
tem_shape_initpropelements calls tem_levelof
tem_shape_subtreefromgeominters calls tem_levelof