tem_stencil_getHeaderPos – Treelm
tem_stencil_getHeaderPos Function
12 statements
Source File
public function tem_stencil_getHeaderPos(me, val) result(headerPos)
find position stencil
Arguments
Type Intent Optional Attributes Name
type(grw_stencilelementarray_type), intent(in) :: me
List of element stencil definitions
integer, intent(in) :: val
Stencil to search for
Return Value integer
Position of the header in the list, 0 if not found
Called by
Source Code
  function tem_stencil_getHeaderPos( me, val ) result( headerPos )
    ! -------------------------------------------------------------------- !
    !> List of element stencil definitions
    type( grw_stencilElementArray_type ), intent(in) :: me
    !> Stencil to search for
    integer, intent(in) :: val
    !> Position of the header in the list, 0 if not found
    integer :: headerPos
    ! -------------------------------------------------------------------- !
    integer :: iStencil
    ! -------------------------------------------------------------------- !
    headerPos = 0
    ! Run over all the stencils
    do iStencil = 1, me%nVals
      if ( me%val(iStencil)%headerPos == val ) then
        headerPos = iStencil
      end if
    end do
  end function tem_stencil_getHeaderPos
Call graph
tem_build_treehorizontaldep calls tem_stencil_getheaderpos
tem_debug_horizontaldependencies calls tem_stencil_getheaderpos
tem_stencil_communicate calls tem_stencil_getheaderpos
redefine_halos calls tem_stencil_communicate
tem_build_horizontaldependencies calls tem_build_treehorizontaldep
communicate_elements calls redefine_halos
tem_create_leveldesc calls tem_build_horizontaldependencies
tem_dimbydim_construction calls tem_create_leveldesc
tem_find_allelements calls communicate_elements