tem_planeCubeOverlap – Treelm
tem_planeCubeOverlap Function
10 statements
Source File
public function tem_planeCubeOverlap(plane, cube) result(overlap)
This function checks for intersection of plane and cube by checking two triangles of plane with a cube
Arguments
Type Intent Optional Attributes Name
type(tem_plane_type), intent(in) :: plane
type(tem_cube_type), intent(in) :: cube
Return Value logical
Calls
Called by
Source Code
  function tem_planeCubeOverlap( plane, cube ) result(overlap)
    !--------------------------------------------------------------------------!
    type(tem_plane_type), intent(in) :: plane
    type(tem_cube_type), intent(in) :: cube
    logical :: overlap
    !--------------------------------------------------------------------------!
    integer :: iTri
    overlap = .false.
    do iTri = 1, 2
      overlap = overlap .or.                                        &
        &       tem_triangleCubeOverlap( plane%triangle(iTri), cube )
    end do
  end function tem_planeCubeOverlap
Call graph
tem_planecubeoverlap calls tem_trianglecubeoverlap
tem_trianglecubeoverlap calls triboxoverlap_loc
triboxoverlap_loc calls axistest, cross_product3d, planeboxoverlap
axistest calls cross_product3d
tem_boxcubeoverlap calls tem_planecubeoverlap
tem_cano_initsubtree calls tem_planecubeoverlap, tem_boxcubeoverlap
tem_shape_subtreefromgeominters calls tem_cano_initsubtree
tem_shape2subtree calls tem_shape_subtreefromgeominters
tem_create_subtree_of calls tem_shape2subtree