tem_timeControl_dump – Treelm
tem_timeControl_dump Subroutine
15 statements
Source File
public subroutine tem_timeControl_dump(me, outUnit)
Dump timecontrol information to the specified outUnit.
Arguments
Type Intent Optional Attributes Name
type(tem_timeControl_type), intent(inout) :: me
Time control to write on outUnit.
integer, intent(in) :: outUnit
The file unit to write the time control to.
Calls
Called by
Source Code
  subroutine tem_timeControl_dump(me, outUnit)
    ! -------------------------------------------------------------------- !
    !> Time control to write on outUnit.
    type(tem_timeControl_type), intent(inout) :: me
    !> The file unit to write the time control to.
    integer, intent(in) :: outUnit
    ! -------------------------------------------------------------------- !
    ! -------------------------------------------------------------------- !
    write(outUnit,*) '+-------------------------------------------+'
    write(outUnit,'(A,I0)') 'Iterations between trigger checks: ', me%check_iter
    write(outUnit,*) ' - Min:'
    call tem_time_dump(me%min, outUnit)
    write(outUnit,*) ''
    write(outUnit,*) ' - Max:'
    call tem_time_dump(me%max, outUnit)
    write(outUnit,*) ''
    write(outUnit,*) ' - Interval:'
    call tem_time_dump(me%interval, outUnit)
    write(outUnit,*) '+-------------------------------------------+'
  end subroutine tem_timeControl_dump
Call graph
tem_timecontrol_dump calls tem_time_dump
tem_load_convergenceheader calls tem_timecontrol_dump
tem_load_restart calls tem_timecontrol_dump
tem_load_surfdata calls tem_timecontrol_dump
tem_load_trackingconfig calls tem_timecontrol_dump
tem_simcontrol_dump calls tem_timecontrol_dump
tem_convergence_load calls tem_load_convergenceheader
tem_load_general calls tem_simcontrol_dump
tem_load_tracking calls tem_load_trackingconfig
tem_abortcriteria_load calls tem_convergence_load
tem_simcontrol_load calls tem_abortcriteria_load