tem_tracking_has_triggered – Treelm
tem_tracking_has_triggered Function
9 statements
Source File
public function tem_tracking_has_triggered(timeControl, simControl, proc) result(triggered)
Decision on whether the giving tracker should be written in the current iteration.
Arguments
Type Intent Optional Attributes Name
type(tem_timeControl_type), intent(inout) :: timeControl
type(tem_simControl_type), intent(in) :: simControl
type(tem_comm_env_type), intent(inout) :: proc
Return Value logical
Calls
Called by
Source Code
  function tem_tracking_has_triggered( timeControl, simControl, proc ) &
    &      result(triggered)
    type(tem_timeControl_type), intent(inout) :: timeControl
    type(tem_comm_env_type),    intent(inout) :: proc
    type(tem_simControl_type),  intent(in) :: simControl
    logical :: triggered
    logical :: tc_triggered
    call tem_timeControl_check( me        = timeControl,    &
      &                         now       = simControl%now, &
      &                         comm      = proc%comm,      &
      &                         triggered = tc_triggered    )
    triggered = tc_triggered                                   &
      &         .or. tem_status_run_end(simControl%status)     &
      &         .or. tem_status_run_terminate(simControl%status)
  end function tem_tracking_has_triggered
Call graph
tem_tracking_has_triggered calls tem_status_run_end, tem_status_run_terminate, tem_timecontrol_check
tem_timecontrol_check calls tem_timecontrol_globaltriggered, tem_timecontrol_update
tem_timecontrol_globaltriggered calls mpi_allreduce, mpi_iallreduce, mpi_wait, tem_timecontrol_triggered
tem_timecontrol_update calls tem_timecontrol_triggered
tem_timecontrol_triggered calls tem_time_ge_trigger, tem_time_gt_trigger, tem_time_never
tem_tracker calls tem_tracking_has_triggered