tem_write_debugMesh – Treelm
tem_write_debugMesh Subroutine
25 statements
Source File
public subroutine tem_write_debugMesh(globtree, levelDesc, debug, myPart)
Write the complete mesh including fluid, ghosts and halo elements to disk
Define in the tem_load_debug table as
   debug = { debugMode = true,
             debugMesh = true }
Arguments
Type Intent Optional Attributes Name
type(treelmesh_type), intent(in) :: globtree
mesh to locate the point in
type(tem_levelDesc_type), intent(in) :: levelDesc(:)
current level descriptor
type(tem_debug_type), intent(inout), optional :: debug
debug info
integer, intent(in) :: myPart
Partition to use on the calling process (= MPI Rank in comm)
Calls
Source Code
  subroutine tem_write_debugMesh( globtree, levelDesc, debug, myPart )
    ! ---------------------------------------------------------------------------
    !> mesh to locate the point in
    type(treelmesh_type), intent(in) :: globtree
    !> current level descriptor
    type(tem_levelDesc_type ),intent(in) :: levelDesc(:)
    !> debug info
    type(tem_debug_type ), optional, intent(inout) :: debug
    !> Partition to use on the calling process (= MPI Rank in comm)
    integer, intent(in) :: myPart
    ! ---------------------------------------------------------------------------
    type( tem_shape_type ) :: inShape(1)
    character(len=pathLen) :: dirname
    type( tem_debug_type ) :: local_debug
    ! local subTree that is dumped to disc
    type( tem_subTree_type ) :: subTree
    ! dummy variable which is required by tem_create_subTree_of but indeed not used
    type( tem_bc_prop_type ) :: bc_prop
    ! dummy variable which is required by tem_create_subTree_of but indeed not used
    type( tem_stencilHeader_type ) :: stencil
    ! ---------------------------------------------------------------------------
    if( present( debug ))then
      local_debug = debug
    else
      local_debug = main_debug
    end if
    if( trim( local_debug%debugMesh ) .ne. '')then
      write(logUnit(1),*)' Writing debug mesh to disk '
      inShape(1)%shapeID = tem_local_shape
      write(dirname ,'(a,i6.6,a)')trim( local_debug%debugMesh ),myPart,'_'
      call tem_create_subTree_of( inTree    = globtree,                        &
        &                         subTree   = subTree,                         &
        &                         inShape   = inShape,                         &
        &                         levelDesc = levelDesc,                       &
        &                         bc_prop   = bc_prop,                         &
        &                         stencil   = stencil,                         &
        &                         prefix    = trim( dirname ))
      call tem_dump_subTree( subTree, globtree, root_only = .false. )
      write(logUnit(1),*) 'Done writing debugMesh'
    endif ! output debugmesh
  end subroutine tem_write_debugMesh
Call graph
tem_write_debugmesh calls tem_create_subtree_of, tem_dump_subtree
tem_create_subtree_of calls destroy, init, tem_copypropertybits, tem_seteffboundingbox, mpi_allreduce, mpi_comm_rank, mpi_comm_size, mpi_comm_split, tem_abort, tem_horizontalspacer, tem_shape2subtree, tem_shape_initlocal, tem_subtree_from
tem_dump_subtree calls dump_treelmesh