tem_faceDep_verticalUp – Treelm
tem_faceDep_verticalUp Subroutine
12 statements
Source File
private subroutine tem_faceDep_verticalUp(fineFaces, coarseFaces)
Arguments
Type Intent Optional Attributes Name
type(tem_face_descriptor_type), intent(inout) :: fineFaces
Face description on the fine level. The dependencies to the coarser level will be appended to this face descriptor.
type(tem_face_descriptor_type), intent(in) :: coarseFaces
Face description on the coarse level.
Calls
Called by
Source Code
  subroutine tem_faceDep_verticalUp( fineFaces, coarseFaces )
    ! --------------------------------------------------------------------------
    !> Face description on the fine level. The dependencies to the coarser
    !! level will be appended to this face descriptor.
    type(tem_face_descriptor_type), intent(inout) :: fineFaces
    !> Face description on the coarse level.
    type(tem_face_descriptor_type), intent(in) :: coarseFaces
    ! --------------------------------------------------------------------------
    integer :: iFace
    integer :: leftPrp, rightPrp
    ! --------------------------------------------------------------------------
    ! Run over all the faces and add the downward depndency (depending on the
    ! properties of the face).
    faceLoop: do iFace = 1, fineFaces%faceList%faceId%nVals
      ! get its properties from left and right
      call tem_getFace_prp( fineFaces, iFace, leftPrp, rightPrp )
      ! check if this face requires upwards dependencies. If yes, we just add
      ! this dependency to the coarse face descriptor.
      if( tem_reqDep_up(leftPrp, rightPrp) ) then
        call tem_addDep_up( iFace, fineFaces, coarseFaces )
      end if
    end do faceLoop
  end subroutine tem_faceDep_verticalUp
Call graph
tem_facedep_verticalup calls tem_adddep_up, tem_getface_prp, tem_reqdep_up
tem_adddep_up calls positionofval, tem_parentof
positionofval calls posofval_label
tem_parentof calls tem_directparent, tem_parentatlevel
posofval_label calls sortedposofval
tem_parentatlevel calls tem_levelof
tem_facedep_vertical calls tem_facedep_verticalup
tem_build_face_info calls tem_facedep_vertical