tem_reportStatus – Treelm
tem_reportStatus Subroutine
26 statements
Source File
public subroutine tem_reportStatus(level, text, debug, string)
print an array to the debugunit
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: level
level for debug output
character(len=*) :: text
Array title in debug output for easy identification in the file
type(tem_debug_type), intent(in), optional :: debug
optional debug type
character(len=*), optional :: string
optional additional string extending the title
Calls
Source Code
  subroutine tem_reportStatus( level, text, debug, string )
    ! ---------------------------------------------------------------------------
    !> level for debug output
    integer, intent(in) :: level
    !> Array title in debug output for easy identification in the file
    character( len=* ) :: text
    !> optional debug type
    type(tem_debug_type), optional, intent(in) :: debug
    !> optional additional string extending the title
    character( len=* ), optional :: string
    ! ---------------------------------------------------------------------------
    character( len=labelLen ) :: traceString
    character(len=labelLen) :: stat_str
    integer :: nUnit
    logical :: isActive
    ! ---------------------------------------------------------------------------
    if( present( debug ))then
      nUnit = debug%logger%funit(level)
      isActive = tem_logging_isActive( debug%logger, level )
    else
      nUnit = main_debug%logger%funit(level)
      isActive = tem_logging_isActive( main_debug%logger, level )
    end if
    if( present ( string )) then
      traceString = string
    else
      traceString = 'VmHWM'
    endif
    if( isActive ) then
      stat_str = my_status_string(trim(traceString))
      write(nUnit,*) trim(stat_str), '  ',  trim(text)
    end if
  end subroutine tem_reportStatus
Call graph
tem_reportstatus calls tem_logging_isactive, my_status_string
tem_logging_isactive calls tem_logging_isactive_for, tem_logging_isactive_primary
my_status_string calls newunit, print_self_status
print_self_status calls newunit