tem_simControl_dump – Treelm
tem_simControl_dump Subroutine
17 statements
Source File
public subroutine tem_simControl_dump(me, outUnit)
Dump simcontrol information to the specified outUnit.
Arguments
Type Intent Optional Attributes Name
type(tem_simControl_type), intent(inout) :: me
Simulation control settings to write to outUnit.
integer, intent(in) :: outUnit
File unit to write to.
Calls
Called by
Source Code
  subroutine tem_simControl_dump(me, outUnit)
    ! -------------------------------------------------------------------- !
    !> Simulation control settings to write to outUnit.
    type(tem_simControl_type), intent(inout) :: me
    !> File unit to write to.
    integer, intent(in) :: outUnit
    ! -------------------------------------------------------------------- !
    write(outUnit,*) '+-------------------------------------------+'
    write(outUnit,*) ' - Now:'
    call tem_simControl_dump_now(me, outUnit)
    write(outUnit,*) ''
    write(outUnit,*) ' - Time Control:'
    call tem_timeControl_dump(me%timeControl, outUnit)
    write(outUnit,*) ''
    write(outUnit,*) ' - Abort Criteria:'
    call tem_abortCriteria_dump(me%abortCriteria, outUnit)
    write(outUnit,*) ''
    write(outUnit,*) ' - Status:'
    call tem_status_dump(me%status, outUnit)
    write(outUnit,*) '+-------------------------------------------+'
  end subroutine tem_simControl_dump
Call graph
tem_simcontrol_dump calls tem_abortcriteria_dump, tem_simcontrol_dump_now, tem_status_dump, tem_timecontrol_dump
tem_simcontrol_dump_now calls tem_time_dump, tem_time_set_clock
tem_timecontrol_dump calls tem_time_dump
tem_time_set_clock calls mpi_wtime
tem_load_general calls tem_simcontrol_dump