tem_ElemSizeLevel – Treelm
tem_ElemSizeLevel Function
6 statements
Source File
public pure function tem_ElemSizeLevel(tree, level) result(dx)
Return the size of elements on a given levle in the mesh by taking into account the size of the bounding cube given in the global info of the tree
Arguments
Type Intent Optional Attributes Name
type(treelmesh_type), intent(in) :: tree
Mesh to locate the point in
integer, intent(in) :: level
given level to get the size for
Return Value real(kind=rk)
size of Element
Called by
Source Code
  pure function tem_ElemSizeLevel( tree, level ) result( dx )
    ! -------------------------------------------------------------------- !
    !> Mesh to locate the point in
    type(treelmesh_type), intent(in) :: tree
    !> given level to get the size for
    integer, intent(in) :: level
    !> size of Element
    real(kind=rk) :: dx
    ! -------------------------------------------------------------------- !
    dx = tree%global%BoundingCubeLength / real(2**level, kind=rk)
  end function tem_ElemSizeLevel
Call graph
tem_baryofid calls tem_elemsizelevel
tem_elemsize calls tem_elemsizelevel
tem_endofid calls tem_elemsizelevel
tem_originofid calls tem_elemsizelevel