tem_restart_closeRead_single – Treelm
tem_restart_closeRead_single Subroutine
6 statements
Source File
public subroutine tem_restart_closeRead_single(me)
Close the restart dump file corresponding to a particular variable system
Arguments
Type Intent Optional Attributes Name
type(tem_restart_type) :: me
the restart infotmation
Calls
Called by
Source Code
  subroutine tem_restart_closeRead_single(me)
    ! -------------------------------------------------------------------- !
    !> the restart infotmation
    type(tem_restart_type) :: me
    ! -------------------------------------------------------------------- !
    ! variables to catch possible MPI I/O errors
    integer :: iError
    ! -------------------------------------------------------------------- !
    ! now close the binary file
    call MPI_File_close(me%binaryUnit, iError)
    call check_mpi_error( iError, 'File close in tem_restart_closeRead_single' )
  end subroutine tem_restart_closeRead_single
Call graph
tem_restart_closeread_single calls mpi_file_close, check_mpi_error
check_mpi_error calls mpi_error_string, tem_abort
tem_abort calls mpi_abort
tem_restart_closeread calls tem_restart_closeread_single