tem_BaryOfId – Treelm
tem_BaryOfId Function
10 statements
Source File
public pure function tem_BaryOfId(tree, TreeID) result(bary)
The following function provides the coordinates of the barycenter for a given treeID in the complete mesh.
Arguments
Type Intent Optional Attributes Name
type(treelmesh_type), intent(in) :: tree
mesh information
integer(kind=long_k), intent(in) :: TreeID
input Element ID
Return Value real(kind=rk), (3)
barycenter return value
Calls
Called by
assemble_lists w tem_BaryOfId
w
exit_element w
w
hvs_ascii_dump_point_data w
w
hvs_asciiSpatial_dump_point_data w
w
hvs_output_init w
w
spongelayer_box2d_expon_for_treeIDs w
w
spongelayer_box2d_roundCornerPolyn5_for_treeIDs w
w
spongelayer_box2d_roundCornerPolyn6_for_treeIDs w
w
spongelayer_box2d_sharpCornerPolyn5_for_treeIDs w
w
spongelayer_box2d_sharpCornerPolyn6_for_treeIDs w
w
spongelayer_box_expon_for_treeIDs w
w
spongelayer_box_roundCornerPolyn5_for_treeIDs w
w
spongelayer_box_roundCornerPolyn6_for_treeIDs w
w
spongelayer_box_sharpCornerPolyn5_for_treeIDs w
w
spongelayer_box_sharpCornerPolyn6_for_treeIDs w
w
spongelayer_plane_expon_for_treeIDs w
w
spongeLayer_plane_polyn5_for_treeids w
w
spongeLayer_plane_polyn6_for_treeids w
w
spongelayer_radial_expon_for_treeIDs w
w
spongeLayer_radial_polyn5_for_treeids w
w
spongeLayer_radial_polyn6_for_treeids w
w
tem_build_treeHorizontalDep w
w
tem_calc_vrtxOf_qVal w
w
tem_cano_checkNeigh w
w
tem_convergence_check_point w
w
tem_shape_findElemByBCLabels w
w
tem_spacetime_lua_for_treeIds w
w
tem_spacetime_lua_vector_for_treeIds w
w
tem_spatial_lua_for_treeIds w
w
tem_spatial_lua_vector_for_treeIds w
w
tem_spatial_parabol2d_for_treeIds w
w
tem_spatial_parabol3d_for_treeIds w
w
tem_tIDinfo w
w
tem_vrtxCoordOfId w
w
viscSpongelayer_box2d_for_treeIDs w
w
viscSpongelayer_box_for_treeIDs w
w
viscSpongelayer_plane_for_treeIDs w
w
viscSpongelayer_radial_for_treeIDs w
w
Source Code
  pure function tem_BaryOfId(tree,TreeID) result(bary)
    ! -------------------------------------------------------------------- !
    !> mesh information
    type(treelmesh_type), intent(in) :: tree
    !> input Element ID
    integer(kind=long_k), intent(in) :: TreeID
    !> barycenter return value
    real(kind=rk) :: bary(3)
    ! -------------------------------------------------------------------- !
    integer       :: coord(4) ! spatial index triple for a given ID
    real(kind=rk) :: dx ! size of Element
    ! -------------------------------------------------------------------- !
    coord = tem_CoordOfId(TreeID)
    dx = tem_elemSizeLevel( tree, coord(4) )
    bary = tree%global%origin + (real(coord(:3), kind=rk) + 0.5_rk)*dx
  end function tem_BaryOfId
Call graph
tem_baryofid calls tem_coordofid, tem_elemsizelevel
tem_coordofid calls tem_levelof