tem_convergence_dump_vector – Treelm
tem_convergence_dump_vector Subroutine
8 statements
Source File
private subroutine tem_convergence_dump_vector(me, outUnit)
Dumps array of convergence to given unit
Arguments
Type Intent Optional Attributes Name
type(tem_convergence_type), intent(in) :: me(:)
convergence to write into the lua file
integer, intent(in) :: outUnit
unit to write to
Calls
Called by
Source Code
  subroutine tem_convergence_dump_vector(me, outUnit)
    ! -------------------------------------------------------------------- !
    !> convergence to write into the lua file
    type(tem_convergence_type), intent(in) :: me(:)
    !> unit to write to
    integer, intent(in) :: outUnit
    ! -------------------------------------------------------------------- !
    ! aotus type handling the output to the file in lua format
    type(aot_out_type) :: conf
    ! -------------------------------------------------------------------- !
    call aot_out_open( put_conf = conf, outUnit = outUnit )
    call tem_convergence_out_vector( me, conf )
    call aot_out_close( put_conf = conf )
  end subroutine tem_convergence_dump_vector
Call graph
tem_convergence_dump_vector calls aot_out_close, aot_out_open, tem_convergence_out_vector
tem_convergence_out_vector calls aot_out_close_table, aot_out_open_table, tem_convergence_out_single
tem_convergence_out_single calls aot_out_close_table, aot_out_open_table, aot_out_val, tem_condition_out, tem_reduction_spatial_out, tem_shape_out, tem_timecontrol_out
tem_condition_out calls tem_condition_out_single, tem_condition_out_vector
tem_reduction_spatial_out calls tem_reduction_spatial_out_single, tem_reduction_spatial_out_vector
tem_shape_out calls tem_shape_out_scal, tem_shape_out_vec
tem_timecontrol_out calls aot_out_close_table, aot_out_open_table, aot_out_val, tem_time_out
tem_convergence_dump calls tem_convergence_dump_vector