tem_simControl_steadyState_reset – Treelm
tem_simControl_steadyState_reset Subroutine
9 statements
Source File
public subroutine tem_simControl_steadyState_reset(me)
Reset trigger, status bit and current time for steady state
Arguments
Type Intent Optional Attributes Name
type(tem_simControl_type), intent(inout) :: me
Calls
Source Code
  subroutine tem_simControl_steadyState_reset(me)
    ! -------------------------------------------------------------------- !
    type(tem_simControl_type), intent(inout) :: me
    ! -------------------------------------------------------------------- !
    ! clear status bit
    call tem_status_clear(me%status)
    ! reset current time
    call tem_time_reset(me%now)
    ! Run steady state solver untill the solution convergences
    me%timeControl%max%sim = huge(me%timeControl%max%sim)
    me%timeControl%max%iter = huge(me%timeControl%max%iter)
    ! reset simcontrol trigger
    call tem_timeControl_reset_trigger(me%timeControl)
    ! reset convergence to check for new steady state
    call tem_convergence_reset(me%abortCriteria%convergence )
  end subroutine tem_simControl_steadyState_reset
Call graph
tem_simcontrol_steadystate_reset calls tem_convergence_reset, tem_status_clear, tem_time_reset, tem_timecontrol_reset_trigger
tem_convergence_reset calls tem_timecontrol_reset_trigger
tem_time_reset calls mpi_wtime