tem_time_dump – Treelm
tem_time_dump Subroutine
7 statements
Source File
public subroutine tem_time_dump(me, outUnit)
Dump the given time to outUnit.
Values which are not set, are omitted.
Arguments
Type Intent Optional Attributes Name
type(tem_time_type), intent(inout) :: me
The time that should be written to outunit.
integer, intent(in) :: outUnit
The unit to write to.
Called by
Source Code
  subroutine tem_time_dump(me, outUnit)
    ! -------------------------------------------------------------------- !
    !> The time that should be written to outunit.
    type(tem_time_type), intent(inout) :: me
    !> The unit to write to.
    integer, intent(in) :: outUnit
    ! -------------------------------------------------------------------- !
    if (me%iter  < huge(me%iter))  write(outUnit, *) ' iterations: ', me%iter
    if (me%sim   < huge(me%sim))   write(outUnit, *) ' simTime   : ', me%sim
    if (me%clock < huge(me%clock)) write(outUnit, *) ' wallClock : ', me%clock
  end subroutine tem_time_dump
Call graph
tem_restart_readheader calls tem_time_dump
tem_simcontrol_dump_now calls tem_time_dump
tem_simcontrol_syncupdate calls tem_time_dump
tem_timecontrol_dump calls tem_time_dump
tem_load_convergenceheader calls tem_timecontrol_dump
tem_load_restart calls tem_restart_readheader, tem_timecontrol_dump
tem_load_surfdata calls tem_timecontrol_dump
tem_load_trackingconfig calls tem_timecontrol_dump
tem_simcontrol_dump calls tem_simcontrol_dump_now, tem_timecontrol_dump
tem_convergence_load calls tem_load_convergenceheader
tem_load_general calls tem_simcontrol_dump
tem_load_tracking calls tem_load_trackingconfig
tem_abortcriteria_load calls tem_convergence_load