tem_load_heaviside_gibbs – Treelm
tem_load_heaviside_gibbs Subroutine
15 statements
Source File
public subroutine tem_load_heaviside_gibbs(conf, thandle, me)
This subroutine loads the definition of a spatial Heaviside function including Gibbs oscillations occuring for a high order approximation.
Arguments
Type Intent Optional Attributes Name
type(flu_State) :: conf
lua state type
integer, intent(in) :: thandle
aotus parent handle
type(tem_heaviside_gibbs_type), intent(out) :: me
Heaviside function data
Calls
Called by
Source Code
  subroutine tem_load_heaviside_gibbs( conf, thandle, me )
    ! ---------------------------------------------------------------------------
    !> Heaviside function data
    type(tem_heaviside_gibbs_type),intent(out) :: me
    !> lua state type
    type(flu_State) :: conf
    !> aotus parent handle
    integer, intent(in) :: thandle
    ! ---------------------------------------------------------------------------
    integer :: iError
    ! ---------------------------------------------------------------------------
    ! Center
    call aot_get_val( L       = conf,                                          &
      &               thandle = thandle,                                       &
      &               key     = 'center',                                      &
      &               val     = me%center,                                     &
      &               ErrCode = iError )
    ! Order
    call aot_get_val( L       = conf,                                          &
      &               thandle = thandle,                                       &
      &               key     = 'order',                                       &
      &               val     = me%order,                                      &
      &               ErrCode = iError )
    ! Left value
    call aot_get_val( L       = conf,                                          &
      &               thandle = thandle,                                       &
      &               key     = 'left',                                        &
      &               val     = me%left,                                       &
      &               ErrCode = iError )
    ! Right value
    call aot_get_val( L       = conf,                                          &
      &               thandle = thandle,                                       &
      &               key     = 'right',                                       &
      &               val     = me%right,                                      &
      &               ErrCode = iError )
    write(logUnit(1),*) ' Data for Heaviside function (including Gibbs'//      &
      &                'oscillations):'
    write(logUnit(1),*) ' * center =', me%center
    write(logUnit(1),*) ' * order  =', me%order
    write(logUnit(1),*) ' * left   =', me%left
    write(logUnit(1),*) ' * right  =', me%right
  end subroutine tem_load_heaviside_gibbs
Call graph
tem_load_heaviside_gibbs calls aot_get_val
load_spatial_predefined calls tem_load_heaviside_gibbs
tem_load_spatial calls load_spatial_predefined
load_spacetime_predefined calls tem_load_spatial
tem_load_ic calls tem_load_spatial
tem_load_spacetime_single calls load_spacetime_predefined