tem_load_transformation – Treelm
tem_load_transformation Subroutine
15 statements
Source File
public subroutine tem_load_transformation(transform, conf, thandle)
This routine loads the transformation table for each spatial object table in config file
If single spatial object contains multiple geometry then the transformation is applied to all geometries defined in that spatial object
Arguments
Type Intent Optional Attributes Name
type(tem_transformation_type), intent(out) :: transform
transformation for spatial object
type(flu_State) :: conf
lua state
integer, intent(in) :: thandle
spatial object parent handle
Calls
Called by
Source Code
  subroutine tem_load_transformation( transform, conf, thandle )
    !--------------------------------------------------------------------------!
    !inferface variables
    !> transformation for spatial object
    type(tem_transformation_type), intent(out) :: transform
    !> lua state
    type(flu_state) :: conf
    !> spatial object parent handle
    integer, intent(in) :: thandle
    !--------------------------------------------------------------------------!
    integer :: transform_handle
    !--------------------------------------------------------------------------!
    !set default to false
    transform%active = .false.
    call aot_table_open(L = conf, parent = thandle, &
      &                 thandle = transform_handle, &
      &                 key = 'transformation')
    if (transform_handle > 0) then
      write(logunit(1),*) 'Loading transformation '
      transform%active = .true.
      !load translation table
      call tem_load_translation( translate = transform%translate, &
        &                        conf = conf, &
        &                        thandle = transform_handle )
      !load deformation table
      call tem_load_deformation( deform = transform%deform, &
        &                        conf = conf, &
        &                        thandle = transform_handle )
     endif
    call aot_table_close(L=conf, thandle=transform_Handle)
  end subroutine tem_load_transformation
Call graph
tem_load_transformation calls aot_table_close, aot_table_open, tem_load_deformation, tem_load_translation
tem_load_deformation calls aot_table_close, aot_table_open, aot_get_val, tem_abort
tem_load_translation calls aot_table_close, aot_table_open, aot_get_val, tem_abort
tem_abort calls mpi_abort
tem_load_shape_single calls tem_load_transformation
tem_load_shape calls tem_load_shape_single, tem_load_shapes
tem_load_shapes calls tem_load_shape_single
load_spatial_parabol calls tem_load_shape
tem_load_convergenceheader calls tem_load_shape
tem_load_spacetime_single calls tem_load_shape, tem_load_spacetime_single
tem_load_trackingconfig calls tem_load_shape
tem_load_spacetime calls tem_load_spacetime_single
load_spatial_predefined calls load_spatial_parabol
tem_convergence_load calls tem_load_convergenceheader
tem_load_spacetime_table calls tem_load_spacetime_single
tem_load_tracking calls tem_load_trackingconfig