tem_sphereCubeOverlap – Treelm
tem_sphereCubeOverlap Function
10 statements
Source File
public function tem_sphereCubeOverlap(sphere, cube) result(overlap)
This function checks intesection of solid cube and sphere
Arguments
Type Intent Optional Attributes Name
type(tem_sphere_type), intent(in) :: sphere
type(tem_cube_type), intent(in) :: cube
Return Value logical
Calls
Called by
Source Code
  function tem_sphereCubeOverlap(sphere, cube) result(overlap)
    ! -------------------------------------------------------------------------!
    !interface variables
    type(tem_sphere_type), intent(in) :: sphere !< spacer geometry data
    type(tem_cube_type), intent(in) :: cube
    logical :: overlap !< return value
    ! -------------------------------------------------------------------------!
    if(sphere%only_surface) then
      overlap = hollowSphereCubeOverlap(sphere, cube)
    else
      overlap = solidSphereCubeOverlap(sphere, cube)
    endif
  end function tem_sphereCubeOverlap
Call graph
tem_spherecubeoverlap calls hollowspherecubeoverlap, solidspherecubeoverlap
tem_cylindercubeoverlap calls tem_spherecubeoverlap
tem_shape_subtreefromgeominters calls tem_spherecubeoverlap, tem_cylindercubeoverlap
tem_shape2subtree calls tem_shape_subtreefromgeominters
tem_create_subtree_of calls tem_shape2subtree
tem_create_subtree_of_st_funlist calls tem_create_subtree_of
tem_init_convergence calls tem_create_subtree_of
tem_init_tracker_subtree calls tem_create_subtree_of
tem_write_debugmesh calls tem_create_subtree_of