tem_time_out – Treelm
tem_time_out Subroutine
22 statements
Source File
public subroutine tem_time_out(me, conf, key)
Write the time into a Lua table
Entries, which are set to the maximal represantable values (meaning never), are ignored and not written.
Arguments
Type Intent Optional Attributes Name
type(tem_time_type), intent(in) :: me
The time descritpion to write out as Lua table.
type(aot_out_type), intent(inout) :: conf
Output handle for the script to write to.
character(len=*), intent(in), optional :: key
Name for the tabel to write this time description to.
Calls
Called by
Source Code
  subroutine tem_time_out(me, conf, key)
    ! -------------------------------------------------------------------- !
    !> The time descritpion to write out as Lua table.
    type(tem_time_type), intent(in) :: me
    !> Output handle for the script to write to.
    type(aot_out_type), intent(inout) :: conf
    !> Name for the tabel to write this time description to.
    character(len=*), intent(in), optional :: key
    ! -------------------------------------------------------------------- !
    character(len=labelLen) :: loc_key
    ! -------------------------------------------------------------------- !
    if (present(key)) then
      loc_key = trim(key)
    else
      loc_key = 'time'
    end if
    call aot_out_open_table( put_conf = conf, tname = loc_key )
    if (me%sim < huge(me%sim)) then
      call aot_out_val( put_conf = conf,   &
        &               val      = me%sim, &
        &               vname    = 'sim'   )
    end if
    if (me%iter < huge(me%iter)) then
      call aot_out_val( put_conf = conf,    &
        &               val      = me%iter, &
        &               vname    = 'iter'   )
    end if
    if (me%clock < huge(me%clock)) then
      call aot_out_val( put_conf = conf,     &
        &               val      = me%clock, &
        &               vname    = 'clock'   )
    end if
    call aot_out_close_table( put_conf = conf )
  end subroutine tem_time_out
Call graph
tem_time_out calls aot_out_close_table, aot_out_open_table, aot_out_val
tem_restart_writeheader calls tem_time_out
tem_simcontrol_out calls tem_time_out, tem_timecontrol_out
tem_timecontrol_out calls tem_time_out
hvs_ascii_write_header calls tem_timecontrol_out
tem_convergence_out_single calls tem_timecontrol_out
tem_restart_closewrite calls tem_restart_writeheader
tem_restart_openwrite calls tem_restart_writeheader
tem_convergence_out calls tem_convergence_out_single, tem_convergence_out_vector
hvs_ascii_init calls hvs_ascii_write_header
hvs_asciispatial_init calls hvs_ascii_write_header
hvs_output_close calls tem_restart_closewrite
hvs_output_open calls tem_restart_openwrite
tem_convergence_dump_single calls tem_convergence_out_single
tem_convergence_out_vector calls tem_convergence_out_single
tem_convergence_dump calls tem_convergence_dump_single
hvs_output_init calls hvs_ascii_init, hvs_asciispatial_init
tem_convergence_dump_vector calls tem_convergence_out_vector
tem_tracker calls hvs_output_close, hvs_output_open