tem_stencilElement_dump – Treelm
tem_stencilElement_dump Subroutine
27 statements
Source File
private subroutine tem_stencilElement_dump(me, nUnit, neighID, tIDonly)
Write element information to disk
Arguments
Type Intent Optional Attributes Name
type(tem_stencilElement_type), intent(in) :: me
stencil element to be dumped
integer, intent(in) :: nUnit
unit to dump to
integer(kind=long_k), intent(in), optional, allocatable :: neighID(:)
neighbor ID
logical, intent(in), optional :: tIDonly
only use tree IDs
Calls
Called by
Source Code
  subroutine tem_stencilElement_dump( me, nUnit, neighID, tIDonly )
    ! -------------------------------------------------------------------- !
    !> stencil element to be dumped
    type( tem_stencilElement_type ), intent(in) :: me
    !> unit to dump to
    integer, intent(in) :: nUnit
    !> neighbor ID
    integer(kind=long_k), allocatable, intent(in), optional :: neighID(:)
    !> only use tree IDs
    logical, intent(in), optional :: tIDonly
    ! -------------------------------------------------------------------- !
    integer :: iVal
    logical :: tIDonly_loc
    integer(kind=long_k) :: treeIDs( me%QQN )
    ! -------------------------------------------------------------------- !
    if( present( tIDonly )) then
      tIDonly_loc = tIDonly
    else
      tIDonly_loc = .false.
    endif
    write(nUnit, "(' QQN: ', I2, ', headerPos: ', I0 )" ) me%QQN, me%headerPos
    if ( present(neighID) ) then
      if ( allocated(neighID) .and. allocated(me%tIDpos) ) then
        ! get neighIDs
        do iVal=1,size(me%tIDpos)
          if ( me%tIDpos(iVal) == 0 ) then
            treeIDs(iVal) = 0
          else
            treeIDs(iVal) = neighID( me%tIDpos(iVal) )
          end if
        end do
        call tem_printArray( treeIDs, 8, 'neighIDs', 120, nUnit)
      end if
    end if
  end subroutine tem_stencilElement_dump
Call graph
tem_stencilelement_dump calls tem_printarray
tem_stencil_dump calls tem_stencilelement_dump
tem_dimbydim_construction calls tem_stencil_dump
tem_element_dump calls tem_stencil_dump
tem_build_face_info calls tem_dimbydim_construction
tem_elemlist_dump calls tem_element_dump
build_levelelements calls tem_elemlist_dump
communicate_elements calls tem_elemlist_dump
tem_init_elemlevels calls tem_elemlist_dump