tem_shape_initByLevels – Treelm
tem_shape_initByLevels Subroutine
30 statements
Source File
private subroutine tem_shape_initByLevels(inTree, minLevel, maxLevel, countElems, map2global)
Arguments
Type Intent Optional Attributes Name
type(treelmesh_type), intent(in) :: inTree
Global mesh from which the elements are identified and then stored to
integer, intent(in) :: minLevel
level range of target elements
integer, intent(in) :: maxLevel
level range of target elements
integer, intent(out) :: countElems(globalMaxLevels)
How many elements there will be for each level in the track
type(dyn_intarray_type), intent(inout) :: map2global
growing array. Elements positions in inTree%treeID
Calls
Called by
Source Code
  subroutine tem_shape_initByLevels( inTree, minLevel, maxLevel, countElems, &
    &                                map2global )
    ! ---------------------------------------------------------------------------
    !> Global mesh from which the elements are identified and then stored to
    type( treelmesh_type ), intent(in) :: inTree
    !> level range of target elements
    integer, intent(in)  :: minLevel, maxLevel
    !> How many elements there will be for each level in the track
    integer, intent(out) :: countElems( globalMaxLevels )
    !> growing array. Elements positions in inTree%treeID
    type(dyn_intArray_type), intent(inout) :: map2global
    ! ---------------------------------------------------------------------------
    integer(kind=long_k)  :: myID, minID, maxID
    integer :: tLevel, dPos, iElem, loc_min, loc_max
    logical :: wasAdded
    ! ---------------------------------------------------------------------------
    loc_min = minLevel
    loc_max = maxLevel
    if ( minLevel > maxLevel ) then
      ! take inverse
      loc_min = maxLevel
      loc_max = minLevel
    end if
    if ( minLevel < 1 )               loc_min = 1
    if ( maxLevel > globalMaxLevels ) loc_max = globalMaxLevels
    call tem_log(3, 'Initializing shapes by elements between level '&
      &        //trim(tem_toStr(loc_min))//' and '//trim(tem_toStr(loc_max)) )
    ! the treeID range is the first ID on min level and the last ID on max level
    minID = tem_firstIdAtLevel( loc_min )
    maxID =  tem_lastIdAtLevel( loc_max )
    ! Loop over all elements in inTree
    do iElem = 1, inTree%nElems
      myID = inTree%treeID(iElem)
      if( (myID >= minID) .and. (myID <= maxID) ) then
        ! Append to treeID list (note that already existing ones are
        ! omitted)
        call append( me       = map2global, &
          &          pos      = dPos,       &
          &          val      = iElem,      &
          &          wasAdded = wasAdded )
        ! Count up if it was added
        if( wasAdded ) then
          tLevel   = tem_levelOf( inTree%treeID(iElem) )
          countElems( tLevel ) = countElems( tLevel ) + 1
        end if ! wasAdded
      end if
    end do ! iElem
  end subroutine tem_shape_initByLevels
Call graph
tem_shape_initbylevels calls append, tem_log, tem_tostr, tem_firstidatlevel, tem_lastidatlevel, tem_levelof
append calls append_da_label, append_da_veclabel
tem_log calls tem_log_for, tem_log_primary
tem_tostr calls tem_b2str, tem_b2str_arr, tem_d2str, tem_d2str_arr, tem_i2str, tem_i2str_arr, tem_l2str, tem_l2str_arr, tem_r2str, tem_r2str_arr
append_da_label calls expand, sortedposofval
append_da_veclabel calls expand
expand calls expand_da_label
sortedposofval calls sortposofval_label
tem_shape2subtree calls tem_shape_initbylevels
tem_create_subtree_of calls tem_shape2subtree
tem_create_subtree_of_st_funlist calls tem_create_subtree_of
tem_init_convergence calls tem_create_subtree_of
tem_init_tracker_subtree calls tem_create_subtree_of
tem_write_debugmesh calls tem_create_subtree_of