tem_load_miescatter – Treelm
tem_load_miescatter Subroutine
9 statements
Source File
private subroutine tem_load_miescatter(conf, thandle, me)
load gauss pulse variables to set initial condition
Arguments
Type Intent Optional Attributes Name
type(flu_State) :: conf
lua state type
integer, intent(in) :: thandle
aotus parent handle
type(tem_miescatter_field_type), intent(out) :: me
Global gauss pulse data type
Calls
Called by
Source Code
  subroutine tem_load_miescatter(conf, thandle, me)
    ! ---------------------------------------------------------------------------
    !> lua state type
    type(flu_State) :: conf
    !> aotus parent handle
    integer, intent(in) :: thandle
    !> Global gauss pulse data type
    type(tem_miescatter_field_type), intent(out) :: me
    ! ---------------------------------------------------------------------------
    write(logUnit(0),*)'ERROR: the Mie-Scatter function is not available in '//&
      &                'this'
    write(logUnit(0),*)'       executable, due to the compiler lacking '//     &
      &                'support of'
    write(logUnit(0),*)'       Bessel functions!'
    call tem_abort()
  end subroutine tem_load_miescatter
Call graph
tem_load_miescatter calls tem_abort
tem_abort calls mpi_abort
tem_load_miescatter_displacementfieldz calls tem_load_miescatter
tem_load_miescatter_magneticfieldx calls tem_load_miescatter
tem_load_miescatter_magneticfieldy calls tem_load_miescatter