tem_elemList_dump – Treelm
tem_elemList_dump Subroutine
16 statements
Source File
public subroutine tem_elemList_dump(me, nUnit, string, stencil, compact)
write out the complete list of elements of a given level
Arguments
Type Intent Optional Attributes Name
type(tem_element_type), intent(in) :: me
integer, intent(in) :: nUnit
character(len=*), intent(in) :: string
logical, intent(in), optional :: stencil
logical, intent(in), optional :: compact
Calls
Called by
Source Code
  subroutine tem_elemList_dump( me, nUnit, string, stencil, compact )
    ! ---------------------------------------------------------------------------
    type( tem_element_type ), intent(in) :: me
    integer, intent(in) :: nUnit
    character(len=*), intent(in) :: string
    logical, intent(in), optional :: stencil
    logical, intent(in), optional :: compact
    ! ---------------------------------------------------------------------------
    integer :: iElem
    ! ---------------------------------------------------------------------------
    write(nUnit, *) '========================================================='
    write(nUnit, *) '= ', trim(string), ', size: ', me%tID%nVals
    write(nUnit, *) '========================================================='
    do iElem = 1, me%tID%nVals
      call tem_element_dump( me         = me,                 &
        &                    elemPos    = iElem,              &
        &                    nUnit      = nUnit,              &
        &                    header     = (mod(iElem,32)==1), &
        &                    compact    = compact,            &
        &                    stencil    = stencil             )
    end do
    write(nUnit, *) '==  DONE! ', trim(string)
    write(nUnit, *) '========================================================='
  end subroutine tem_elemList_dump
Call graph
tem_elemlist_dump calls tem_element_dump
tem_element_dump calls tem_stencil_dump
tem_stencil_dump calls tem_stencilelement_dump, tem_stencilheader_dump
tem_stencilelement_dump calls tem_printarray
tem_stencilheader_dump calls tem_tostr
build_levelelements calls tem_elemlist_dump
communicate_elements calls tem_elemlist_dump
tem_init_elemlevels calls tem_elemlist_dump
tem_create_leveldesc calls tem_init_elemlevels, tem_find_allelements
tem_find_allelements calls build_levelelements, communicate_elements
tem_dimbydim_construction calls tem_create_leveldesc
tem_build_face_info calls tem_dimbydim_construction