tem_time_reset – Treelm
tem_time_reset Subroutine
7 statements
Source File
public subroutine tem_time_reset(me)
Reset the time definition.
All counters are reset to 0, and the starting clock is set to the current time.
Arguments
Type Intent Optional Attributes Name
type(tem_time_type), intent(out) :: me
Time type to reset
Calls
Called by
Source Code
  subroutine tem_time_reset(me)
    ! -------------------------------------------------------------------- !
    !> Time type to reset
    type(tem_time_type), intent(out) :: me
    ! -------------------------------------------------------------------- !
    ! -------------------------------------------------------------------- !
    me%sim   = 0.0_rk
    me%iter  = 0
    me%clock = 0.0_rk
    me%clock_start = MPI_Wtime()
  end subroutine tem_time_reset
Call graph
tem_time_reset calls mpi_wtime
hvs_output_open calls tem_time_reset
tem_load_restart calls tem_time_reset
tem_simcontrol_start calls tem_time_reset
tem_simcontrol_steadystate_reset calls tem_time_reset
tem_start calls tem_simcontrol_start
tem_tracker calls hvs_output_open