tem_condition_dump_vector – Treelm
tem_condition_dump_vector Subroutine
8 statements
Source File
private subroutine tem_condition_dump_vector(me, outUnit)
Dumps array of condition to given unit
Arguments
Type Intent Optional Attributes Name
type(tem_condition_type), intent(in) :: me(:)
condition to write into the lua file
integer, intent(in) :: outUnit
unit to write to
Calls
Called by
Source Code
  subroutine tem_condition_dump_vector(me, outUnit)
    ! -------------------------------------------------------------------- !
    !> condition to write into the lua file
    type(tem_condition_type), intent(in) :: me(:)
    !> unit to write to
    integer, intent(in) :: outUnit
    ! -------------------------------------------------------------------- !
    ! aotus type handling the output to the file in lua format
    type(aot_out_type) :: conf
    ! -------------------------------------------------------------------- !
    call aot_out_open( put_conf = conf, outUnit = outUnit )
    call tem_condition_out_vector( me, conf )
    call aot_out_close( put_conf = conf )
  end subroutine tem_condition_dump_vector
Call graph
tem_condition_dump_vector calls aot_out_close, aot_out_open, tem_condition_out_vector
tem_condition_out_vector calls aot_out_close_table, aot_out_open_table, tem_condition_out_single
tem_condition_out_single calls aot_out_close_table, aot_out_open_table, aot_out_val
tem_condition_dump calls tem_condition_dump_vector