tem_load_stl – Treelm
tem_load_stl Subroutine
25 statements
Source File
public subroutine tem_load_stl(stl_data, transform, conf, thandle)
This routine loads STL files from config and reads the triangles from the files into the dynamic array of triangles.
Arguments
Type Intent Optional Attributes Name
type(tem_stlData_type), intent(out) :: stl_data
Array array of triangles in stlData
type(tem_transformation_type), intent(in) :: transform
transformation for spatial object
type(flu_State) :: conf
Lua state
integer, intent(in) :: thandle
Calls
Called by
Source Code
  subroutine tem_load_stl(stl_data, transform, conf, thandle)
    ! --------------------------------------------------------------------------!
    !> Array array of triangles in stlData
    type(tem_stlData_type), intent(out) :: stl_data
    !> transformation for spatial object
    type(tem_transformation_type), intent(in) :: transform
    !> Lua state
    type(flu_state) :: conf
    integer, intent(in) :: thandle !< handle for canonical objects
    ! --------------------------------------------------------------------------!
    integer :: iTri, iVer
    ! --------------------------------------------------------------------------!
    ! Load stl files from config file.
    call tem_load_stlhead(me = stl_data%head, conf = conf, thandle = thandle)
    ! Load triangles and nodes from stl files.
    call tem_read_stlFiles(stl_data = stl_data )
    ! if transformation is active apply transformation to all triangles
    ! first apply deformation and then translation
    if(transform%active) then
      if(transform%deform%active) then
        do iTri=1, stl_data%nTris
          do iVer=1,3
            stl_data%nodes(:, stl_data%tri_node(iVer, iTri)) = &
              &            matmul( transform%deform%matrix, &
              &            stl_data%nodes(:, stl_data%tri_node(iVer, iTri)) )
          enddo
        enddo
      endif
      if(transform%translate%active) then
        do iTri=1, stl_data%nTris
          do iVer=1,3
            stl_data%nodes(:, stl_data%tri_node(iVer, iTri)) = &
              &            transform%translate%vec + &
              &            stl_data%nodes(:, stl_data%tri_node(iVer, iTri))
          enddo
        enddo
      endif
    endif
  end subroutine tem_load_stl
Call graph
tem_load_stl calls tem_load_stlhead, tem_read_stlfiles
tem_load_stlhead calls aot_table_close, aot_table_length, aot_table_open, tem_load_stlhead_single
tem_read_stlfiles calls tem_read_stlb, tem_size_stlb, stla_read, stla_size
tem_load_stlhead_single calls aot_get_val, tem_abort
tem_read_stlb calls tem_open
tem_size_stlb calls tem_abort, tem_open
tem_abort calls mpi_abort
tem_open calls tem_abort, newunit, upper_to_lower
tem_load_shape_single calls tem_load_stl
tem_load_shape calls tem_load_shape_single, tem_load_shapes
tem_load_shapes calls tem_load_shape_single
load_spatial_parabol calls tem_load_shape
tem_load_convergenceheader calls tem_load_shape
tem_load_spacetime_single calls tem_load_shape, tem_load_spacetime_single
tem_load_trackingconfig calls tem_load_shape
tem_load_spacetime calls tem_load_spacetime_single
load_spatial_predefined calls load_spatial_parabol
tem_convergence_load calls tem_load_convergenceheader
tem_load_spacetime_table calls tem_load_spacetime_single
tem_load_tracking calls tem_load_trackingconfig