tem_GetRealBoundingCube – Treelm
tem_GetRealBoundingCube Function
11 statements
Source File
private function tem_GetRealBoundingCube(tree) result(boundingCube)
Calculate the real bounding box around the fluid domain and return only to root (efficiency reasons)
Arguments
Type Intent Optional Attributes Name
type(treelmesh_type), intent(in) :: tree
Return Value real(kind=rk), (3,2)
Calls
Called by
Source Code
  function tem_GetRealBoundingCube( tree ) result( boundingCube )
    ! -------------------------------------------------------------------- !
    !>
    type(treelmesh_type), intent(in) :: tree
    !>
    real(kind=rk) :: boundingCube(3,2)
    ! -------------------------------------------------------------------- !
    real(kind=rk) :: tBounding(3)
    integer :: iErr
    ! -------------------------------------------------------------------- !
    ! Calculate process-local bounding cube
    boundingCube = tem_GetLocalBoundingCube( tree )
    ! Exchange with neighbors
    call mpi_reduce( boundingCube(:,1), tBounding, 3, rk_mpi, mpi_min, &
      &              0, tree%global%comm, iErr  )
    boundingCube(:,1) = tBounding
    call mpi_reduce( boundingCube(:,2), tBounding, 3, rk_mpi, mpi_max, &
      &              0, tree%global%comm, iErr  )
    boundingCube(:,2) = tBounding
  end function tem_GetRealBoundingCube
Call graph
tem_getrealboundingcube calls tem_getlocalboundingcube, mpi_reduce
tem_getlocalboundingcube calls tem_getlocalboundingcube_fromsubtree, tem_getlocalboundingcube_fromtree
tem_getlocalboundingcube_fromsubtree calls tem_vrtxcoordofid
tem_getlocalboundingcube_fromtree calls tem_vrtxcoordofid
tem_vrtxcoordofid calls tem_baryofid, tem_coordofid
tem_seteffboundingbox_fromtree calls tem_getrealboundingcube
tem_seteffboundingbox calls tem_seteffboundingbox_fromtree
tem_create_subtree_of calls tem_seteffboundingbox
tem_create_subtree_of_st_funlist calls tem_create_subtree_of
tem_init_convergence calls tem_create_subtree_of
tem_init_tracker_subtree calls tem_create_subtree_of
tem_write_debugmesh calls tem_create_subtree_of