tem_reduction_spatial_out_vector – Treelm
tem_reduction_spatial_out_vector Subroutine
5 statements
Source File
private subroutine tem_reduction_spatial_out_vector(me, conf)
Allows the output of array of reduction to lua out
Arguments
Type Intent Optional Attributes Name
type(tem_reduction_spatial_type), intent(in) :: me(:)
reduction to write into the lua file
type(aot_out_type), intent(inout) :: conf
aotus type handling the output to the file in lua format
Calls
Called by
Source Code
  subroutine tem_reduction_spatial_out_vector(me, conf)
    ! ---------------------------------------------------------------------------
    !> reduction to write into the lua file
    type(tem_reduction_spatial_type), intent(in) :: me(:)
    !> aotus type handling the output to the file in lua format
    type(aot_out_type), intent(inout) :: conf
    ! ---------------------------------------------------------------------------
    call aot_out_val( put_conf = conf,             &
      &               val      = me(:)%reduceType, &
      &               vname    = 'reduction'       )
  end subroutine tem_reduction_spatial_out_vector
Call graph
tem_reduction_spatial_out_vector calls aot_out_val
tem_reduction_spatial_out calls tem_reduction_spatial_out_vector
tem_reduction_spatial_dump_vector calls tem_reduction_spatial_out_vector
tem_reduction_spatial_dump calls tem_reduction_spatial_dump_vector
tem_convergence_out_single calls tem_reduction_spatial_out
tem_convergence_out calls tem_convergence_out_single, tem_convergence_out_vector
tem_convergence_dump_single calls tem_convergence_out_single
tem_convergence_out_vector calls tem_convergence_out_single
tem_convergence_dump calls tem_convergence_dump_single
tem_convergence_dump_vector calls tem_convergence_out_vector