tem_timer_dump_glob – Treelm
tem_timer_dump_glob Subroutine
6 statements
Source File
public subroutine tem_timer_dump_glob(comm, myrank, nProcs)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: comm
communicator handle
integer, intent(in) :: myrank
MPI rank of the calling process.
integer, intent(in) :: nProcs
Number of processes in the communicator.
Calls
Called by
Source Code
  subroutine tem_timer_dump_glob(comm, myrank, nProcs)
    ! -------------------------------------------------------------------- !
    !> communicator handle
    integer, intent(in) :: comm
    !> MPI rank of the calling process.
    integer, intent(in) :: myrank
    !> Number of processes in the communicator.
    integer, intent(in) :: nProcs
    ! -------------------------------------------------------------------- !
    call tem_timer_dumplabeled(timer, comm, myrank, nProcs)
  end subroutine tem_timer_dump_glob
Call graph
tem_timer_dump_glob calls tem_timer_dumplabeled
tem_timer_dumplabeled calls positionofval, mpi_gather, tem_getmaxtimerval, tem_getmintimerval, tem_getsumtimerval, tem_open, upper_to_lower
positionofval calls posofval_label
tem_getmaxtimerval calls mpi_allreduce, tem_gettimerval
tem_getmintimerval calls mpi_allreduce, tem_gettimerval
tem_getsumtimerval calls mpi_allreduce, tem_gettimerval
tem_open calls upper_to_lower, newunit, tem_abort
posofval_label calls sortedposofval
tem_abort calls mpi_abort
tem_gettimerval calls tem_stoptimer
tem_finalize calls tem_timer_dump_glob