tem_solverTag – Treelm
tem_solverTag Function
5 statements
Source File
public function tem_solverTag(solver) result(tag)
Function to return a solver tag (combination of solver name and version)
Arguments
Type Intent Optional Attributes Name
type(tem_solveHead_type), intent(in) :: solver
solver information
Return Value character(len=LabelLen)
Called by
Source Code
  function tem_solverTag( solver ) result( tag )
    ! ---------------------------------------------------------------------------
    !> solver information
    type(tem_solveHead_type), intent(in) :: solver
    ! ---------------------------------------------------------------------------
    ! defining local variables
    character(len=LabelLen) :: tag  ! solver
    ! ---------------------------------------------------------------------------
    tag = trim(solver%solName(:labellen/2)) // '_' &
      & // trim(solver%version(:(labellen/2)-1))
  end function tem_solverTag
Call graph
hvs_ascii_write_header calls tem_solvertag
tem_init_restart_alloc calls tem_solvertag
hvs_ascii_init calls hvs_ascii_write_header
hvs_asciispatial_init calls hvs_ascii_write_header
tem_init_restart calls tem_init_restart_alloc
hvs_output_init calls hvs_ascii_init, hvs_asciispatial_init, tem_init_restart
tem_init_tracker calls hvs_output_init