tem_init_depend – Treelm
tem_init_depend Subroutine
9 statements
Source File
public subroutine tem_init_depend(me, varSys)
This subroutine initializes the loaded depend table
Arguments
Type Intent Optional Attributes Name
type(tem_depend_type), intent(inout) :: me(:)
list of depend types to be filled
type(tem_varSys_type), intent(in) :: varSys
list of all global variable systems
Calls
Source Code
  subroutine tem_init_depend( me, varSys )
    !---------------------------------------------------------------------------
    !> list of depend types to be filled
    type(tem_depend_type), intent(inout)  :: me(:)
    !> list of all global variable systems
    type(tem_varSys_type), intent(in)     :: varSys
    !---------------------------------------------------------------------------
    integer :: iDepend, nDepends
    !---------------------------------------------------------------------------
    nDepends = size(me)
    do iDepend = 1, nDepends
      ! map variables
      ! create depend variable position in the global varSys
      call tem_create_varMap( varname = me(iDepend)%varname, &
        &                     varSys  = varSys,              &
        &                     varMap  = me(iDepend)%varMap   )
    end do ! iDepend
  end subroutine tem_init_depend
Call graph
tem_init_depend calls tem_create_varmap
tem_create_varmap calls append, init, positionofval, truncate
append calls append_ga_stringkeyvaluepair, append_ga_stringkeyvaluepair_vec
init calls init_da_label
positionofval calls posofval_label
truncate calls truncate_da_label
append_ga_stringkeyvaluepair calls expand
append_ga_stringkeyvaluepair_vec calls expand
posofval_label calls sortedposofval