tem_collect_faces – Treelm
tem_collect_faces Subroutine
12 statements
Source File
private subroutine tem_collect_faces(levelDesc, minLevel, maxLevel, faces)
element that exists in the level descriptor.
Arguments
Type Intent Optional Attributes Name
type(tem_levelDesc_type), intent(in) :: levelDesc(1:3,minLevel:maxLevel)
Level descriptor for each spatial direction and each level of your mesh.
integer, intent(in) :: minLevel
Minimum level of your mesh.
integer, intent(in) :: maxLevel
Maximum level of your mesh.
type(tem_face_type), intent(inout) :: faces(minLevel:maxLevel)
Face descriptor where the faces will be appended to.
Calls
Called by
Source Code
  subroutine tem_collect_faces(levelDesc, minLevel, maxLevel, faces )
    ! --------------------------------------------------------------------------
    !> Minimum level of your mesh.
    integer, intent(in) :: minLevel
    !> Maximum level of your mesh.
    integer, intent(in) :: maxLevel
    !> Level descriptor for each spatial direction and each level of your mesh.
    type(tem_levelDesc_type), intent(in) :: levelDesc(1:3,minLevel:maxLevel)
    !> Face descriptor where the faces will be appended to.
    type(tem_face_type),intent(inout)  :: faces(minLevel:maxLevel)
    ! --------------------------------------------------------------------------
    integer :: iLevel, iDir
    ! --------------------------------------------------------------------------
    levelLoop: do iLevel = minLevel, maxLevel
      directionLoop: do iDir = 1, 3
        ! For this level and this direction we collect all the faces.
        call tem_get_faces( levelDesc = levelDesc(iDir, iLevel),  &
          &                 direction = iDir,                     &
          &                 faces     = faces(iLevel)%faces(iDir) )
      end do directionLoop
    end do levelLoop
  end subroutine tem_collect_faces
Call graph
tem_collect_faces calls tem_get_faces
tem_get_faces calls tem_addface, tem_get_elemprp, tem_get_faceneigh, tem_init_facelist
tem_addface calls append
tem_get_elemprp calls tem_abort
tem_get_faceneigh calls tem_abort, tem_coordofid, tem_idofcoord, tem_treeidintotal
tem_init_facelist calls init
append calls append_arrayga2d_real, append_singlega2d_real
init calls init_ga2d_real
tem_abort calls mpi_abort
tem_coordofid calls tem_levelof
tem_treeidintotal calls tem_etypeofid, tem_positioninsorted
tem_build_face_info calls tem_collect_faces