tem_convertTreeIDtoCube – Treelm
tem_convertTreeIDtoCube Subroutine
10 statements
Source File
public subroutine tem_convertTreeIDtoCube(cube, tree, TreeID)
This routine converts treeID in given tree to cube
Arguments
Type Intent Optional Attributes Name
type(tem_cube_type), intent(out) :: cube
type(treelmesh_type), intent(in) :: tree
mesh information
integer(kind=long_k), intent(in) :: TreeID
input Element ID
Calls
Called by
Source Code
  subroutine tem_convertTreeIDtoCube(cube, tree, treeID)
    ! --------------------------------------------------------------------------!
    !> mesh information
    type(treelmesh_type), intent(in) :: tree
    !> input Element ID
    integer(kind=long_k), intent(in) :: TreeID
    type(tem_cube_type), intent(out) :: cube !< cube type
    ! --------------------------------------------------------------------------!
    cube%origin = tem_originOfId(tree, treeID)
    cube%endPnt = tem_endOfId(tree, treeID)
    cube%extent = tem_ElemSize(tree, treeID)
    cube%halfwidth = 0.5_rk*cube%extent
    cube%center = cube%origin + cube%halfwidth
  end subroutine tem_convertTreeIDtoCube
Call graph
tem_converttreeidtocube calls tem_elemsize, tem_endofid, tem_originofid
tem_elemsize calls tem_elemsizelevel, tem_levelof
tem_endofid calls tem_coordofid, tem_elemsizelevel
tem_originofid calls tem_coordofid, tem_elemsizelevel
tem_coordofid calls tem_levelof
tem_cano_initsubtree calls tem_converttreeidtocube
tem_shape_subtreefromgeominters calls tem_converttreeidtocube, tem_cano_initsubtree
tem_shape2subtree calls tem_shape_subtreefromgeominters
tem_create_subtree_of calls tem_shape2subtree
tem_create_subtree_of_st_funlist calls tem_create_subtree_of
tem_init_convergence calls tem_create_subtree_of
tem_init_tracker_subtree calls tem_create_subtree_of
tem_write_debugmesh calls tem_create_subtree_of