tem_create_subTree_of_st_funList – Treelm
tem_create_subTree_of_st_funList Subroutine
23 statements
Source File
public subroutine tem_create_subTree_of_st_funList(me, tree, bc_prop, stencil)
create subtree for shapes defined in each spacetime functions
Arguments
Type Intent Optional Attributes Name
type(tem_st_fun_linkedList_type), intent(inout) :: me
Linked list to append the spacetime function to.
type(treelmesh_type), intent(in) :: tree
Global treelmesh
type(tem_BC_prop_type), intent(in) :: bc_prop
bc property
type(tem_stencilHeader_type), intent(in), optional :: stencil
stencil
Calls
Source Code
  subroutine tem_create_subTree_of_st_funList( me, tree, bc_prop, stencil )
    ! -------------------------------------------------------------------- !
    !> Linked list to append the spacetime function to.
    type( tem_st_fun_linkedList_type ), intent(inout) :: me
    !> Global treelmesh
    type( treelmesh_type ),     intent(in) :: tree
    !> bc property
    type( tem_bc_prop_type ), intent(in) :: bc_prop
    !> stencil
    type( tem_stencilHeader_type ), optional, intent(in) :: stencil
    ! -------------------------------------------------------------------- !
    type(tem_st_fun_listElem_type), pointer :: st_fun
    integer :: iSt, iList
    ! -------------------------------------------------------------------- !
    call tem_horizontalSpacer( fUnit = logUnit(3))
    write(logUnit(3),*) 'Create subtree for all space time functions stored '
    write(logUnit(3),*) 'in linked list of spacetime function'
    st_fun => me%head
    iList = 0
    do
      if (.not. associated(st_fun)) EXIT
      iList = iList + 1
      do iSt = 1, st_fun%nVals
        call tem_create_subTree_of( inTree  = tree,                    &
          &                         subTree = st_fun%val(iSt)%subTree, &
          &                         bc_prop = bc_prop,                 &
          &                         stencil = stencil,                 &
          &                         inShape = st_fun%val(iSt)%geom     )
      end do
      st_fun => st_fun%next
    end do
    write(logUnit(3),'(a,i3,a)') ' Done creating subtree for ', iList, &
      &                          ' spacetime functions'
    call tem_horizontalSpacer( fUnit = logUnit(3))
  end subroutine tem_create_subTree_of_st_funList
Call graph
tem_create_subtree_of_st_funlist calls tem_create_subtree_of, tem_horizontalspacer
tem_create_subtree_of calls tem_horizontalspacer, destroy, init, tem_copypropertybits, tem_seteffboundingbox, mpi_allreduce, mpi_comm_rank, mpi_comm_size, mpi_comm_split, tem_abort, tem_shape2subtree, tem_shape_initlocal, tem_subtree_from
destroy calls destroy_ga2d_real
init calls init_ga2d_real
tem_copypropertybits calls tem_copypropertybitsfromleveldesc, tem_copypropertybitsfromtree
tem_seteffboundingbox calls tem_seteffboundingbox_fromsubtree, tem_seteffboundingbox_fromtree
tem_abort calls mpi_abort
tem_shape2subtree calls tem_abort, tem_shape_findelembybclabels, tem_shape_initbylevels, tem_shape_initpropelements, tem_shape_subtreefromgeominters
tem_subtree_from calls mpi_comm_rank, mpi_comm_size, tem_abort, mpi_bcast, mpi_exscan, mpi_reduce