tem_halo_destroy – Treelm
tem_halo_destroy Subroutine
5 statements
Source File
public subroutine tem_halo_destroy(me)
Destroy the list of halo elements.
Arguments
Type Intent Optional Attributes Name
type(tem_haloList_type), intent(inout) :: me
The list of halo elements to destroy.
Calls
Called by
Source Code
  subroutine tem_halo_destroy(me)
    !> The list of halo elements to destroy.
    type(tem_haloList_type), intent(inout) :: me
    call destroy(me%partnerProc)
    call destroy(me%halos)
  end subroutine tem_halo_destroy
Call graph
tem_halo_destroy calls destroy
destroy calls destroy_ga_dynlong
identify_lists calls tem_halo_destroy
tem_cleanupdependencyarrays calls tem_halo_destroy
communicate_elements calls identify_lists
tem_create_leveldesc calls tem_cleanupdependencyarrays, tem_find_allelements
tem_find_allelements calls identify_lists, tem_cleanupdependencyarrays, communicate_elements
tem_dimbydim_construction calls tem_create_leveldesc
tem_build_face_info calls tem_dimbydim_construction