tem_tIDinfo – Treelm
tem_tIDinfo Subroutine
17 statements
Source File
public subroutine tem_tIDinfo(me, tree, nUnit)
Prints information about a treeID to a file unit.
Arguments
Type Intent Optional Attributes Name
integer(kind=long_k), intent(in) :: me
given level to get the size for
type(treelmesh_type), intent(in) :: tree
Mesh to locate the point in
integer, intent(in), optional :: nUnit
the file unit to use for printing the information.
Calls
Called by
Source Code
  subroutine tem_tIDinfo( me, tree, nUnit)
    ! -------------------------------------------------------------------- !
    !> given level to get the size for
    integer(kind=long_k), intent(in) :: me
    !> Mesh to locate the point in
    type(treelmesh_type), intent(in) :: tree
    !> the file unit to use for printing the information.
    integer, intent(in), optional :: nUnit
    ! -------------------------------------------------------------------- !
    integer :: writeUnit, x(4)
    ! -------------------------------------------------------------------- !
    if ( present( nUnit )) then
      writeUnit = nUnit
    else
      writeUnit = output_unit
    end if
    write(writeUnit,*) '  treeID info ', me
    x(:) = tem_coordOfId( me )
    write(writeUnit,*) '       level   ', x(4)
    write(writeUnit,*) '       coord   ', x(1:3)
    write(writeUnit,*) '       elemSize', tem_elemSize( tree, me )
    write(writeUnit,*) '       bary    ', tem_baryOfId( tree, me )
  end subroutine tem_tIDinfo
Call graph
tem_tidinfo calls tem_baryofid, tem_coordofid, tem_elemsize
tem_baryofid calls tem_coordofid, tem_elemsizelevel
tem_coordofid calls tem_levelof
tem_elemsize calls tem_elemsizelevel, tem_levelof
identify_elements calls tem_tidinfo, identify_elements, create_allparentneighbors, identify_stencilneigh, single_process_element
identify_local_element calls tem_tidinfo
build_levelelements calls identify_elements, identify_additionalneigh
create_allparentneighbors calls identify_elements, identify_stencilneigh
identify_additionalneigh calls identify_elements
identify_halo calls identify_local_element
identify_stencilneigh calls identify_elements
single_process_element calls identify_local_element
request_remotehalos calls create_allparentneighbors, identify_halo, identify_stencilneigh
tem_find_allelements calls build_levelelements, identify_additionalneigh
communicate_elements calls request_remotehalos
tem_create_leveldesc calls tem_find_allelements