tem_endOfId – Treelm
tem_endOfId Function
10 statements
Source File
public pure function tem_endOfId(tree, TreeID) result(origin)
The following function provides the coordinates of the end for a given ID in the complete mesh. The described element lies between the origin and this end point.
The end point of the element with a given ID coincides with the origin of treeID with a coordinate shift of +1 in each dimension.
Arguments
Type Intent Optional Attributes Name
type(treelmesh_type), intent(in) :: tree
mesh information
integer(kind=long_k), intent(in) :: TreeID
input element ID
Return Value real(kind=rk), (3)
origin return value
Calls
Called by
Source Code
  pure function tem_endOfId(tree,TreeID) result(origin)
    ! -------------------------------------------------------------------- !
    !> mesh information
    type(treelmesh_type), intent(in) :: tree
    !> input element ID
    integer(kind=long_k), intent(in) :: TreeID
    !> origin return value
    real(kind=rk) :: origin(3)
    ! -------------------------------------------------------------------- !
    integer       :: coord(4) !< spatial index triple for a given ID
    real(kind=rk) :: dx !< size of Element
    ! -------------------------------------------------------------------- !
    coord = tem_CoordOfId( TreeID )
    dx = tem_elemSizeLevel( tree, coord(4) )
    origin = tree%global%origin + real(coord(:3)+1, kind=rk)*dx
  end function tem_endOfId
Call graph
tem_endofid calls tem_coordofid, tem_elemsizelevel
tem_coordofid calls tem_levelof
tem_converttreeidtocube calls tem_endofid
tem_cano_initsubtree calls tem_converttreeidtocube
tem_shape_subtreefromgeominters calls tem_converttreeidtocube, tem_cano_initsubtree
tem_shape2subtree calls tem_shape_subtreefromgeominters
tem_create_subtree_of calls tem_shape2subtree