tem_stlCubeOverlap – Treelm
tem_stlCubeOverlap Function
15 statements
Source File
public function tem_stlCubeOverlap(stl_data, cube) result(overlaps)
Compute, if the triangles in stl intersects the cube.
Arguments
Type Intent Optional Attributes Name
type(tem_stlData_type), intent(in) :: stl_data
type(tem_cube_type), intent(in) :: cube
Return Value logical
Calls
Called by
Source Code
  function tem_stlCubeOverlap(stl_data, cube) result(overlaps)
    !--------------------------------------------------------------------------!
    type(tem_stlData_type), intent(in) :: stl_data
    type(tem_cube_type), intent(in) :: cube
    logical :: overlaps
    !--------------------------------------------------------------------------!
    integer :: iTri
    type(tem_triangle_type) :: triangle
    !--------------------------------------------------------------------------!
    overlaps = .false.
    do iTri=1, stl_data%nTris
      triangle%nodes(:,1) = stl_data%nodes( :, stl_data%tri_node(1,iTri) )
      triangle%nodes(:,2) = stl_data%nodes( :, stl_data%tri_node(2,iTri) )
      triangle%nodes(:,3) = stl_data%nodes( :, stl_data%tri_node(3,iTri) )
      overlaps = overlaps .or. tem_triangleCubeOverlap(triangle, cube)
      ! if intersection is found then terminate the loop and return overlaps
      if (overlaps) return
    end do
  end function tem_stlCubeOverlap
Call graph
tem_stlcubeoverlap calls tem_trianglecubeoverlap
tem_trianglecubeoverlap calls triboxoverlap_loc
triboxoverlap_loc calls axistest, cross_product3d, planeboxoverlap
axistest calls cross_product3d
tem_shape_subtreefromgeominters calls tem_stlcubeoverlap
tem_shape2subtree calls tem_shape_subtreefromgeominters
tem_create_subtree_of calls tem_shape2subtree
tem_create_subtree_of_st_funlist calls tem_create_subtree_of
tem_init_convergence calls tem_create_subtree_of
tem_init_tracker_subtree calls tem_create_subtree_of
tem_write_debugmesh calls tem_create_subtree_of