tem_ParentAtLevel – Treelm
tem_ParentAtLevel Function
12 statements
Source File
private function tem_ParentAtLevel(TreeID, level) result(parentID)
This function provides the parent ID of a given tree ID on a given level.
The parent ID on a given level is calculated using the equation \f[ id_{l-1}=\frac{id_{l}-1}{8} \f] in a loop.
Arguments
Type Intent Optional Attributes Name
integer(kind=long_k), intent(in) :: TreeID
treeID of which the pID is requested
integer, intent(in) :: level
the level on which the pID is requested
Return Value integer(kind=long_k)
resulting parent ID
Calls
Called by
Source Code
  function tem_ParentAtLevel(TreeID, level) result(parentID)
    ! ---------------------------------------------------------------------------
    !> treeID of which the pID is requested
    integer(kind=long_k),intent(in) :: TreeID
    !> the level on which the pID is requested
    integer,intent(in) :: level
    !> resulting parent ID
    integer(kind=long_k) :: parentID
    ! ---------------------------------------------------------------------------
    integer :: cLevel ! the current level of the tree ID
    integer :: iLevel ! level iterator
    ! ---------------------------------------------------------------------------
    parentID = TreeID
    cLevel = tem_LevelOf(TreeID)
    do iLevel = 1, cLevel-level
      ! parentID = (parentID - 1) / 8
      parentID = ishft( (parentID-1_long_k), -3 )
    end do
  end function tem_ParentAtLevel
Call graph
tem_parentatlevel calls tem_levelof
tem_parentof calls tem_parentatlevel
create_allparentneighbors calls tem_parentof, identify_elements
tem_adddep_up calls tem_parentof
tem_build_verticaldependencies calls tem_parentof
update_childneighborid calls tem_parentof
identify_elements calls create_allparentneighbors, identify_elements
request_remotehalos calls create_allparentneighbors
tem_create_leveldesc calls tem_build_verticaldependencies
tem_facedep_verticalup calls tem_adddep_up
tem_find_bcs_fromfiner calls update_childneighborid
add_ghostfromfiner calls tem_find_bcs_fromfiner
build_levelelements calls identify_elements
communicate_elements calls request_remotehalos
identify_additionalneigh calls identify_elements
identify_stencilneigh calls identify_elements
tem_dimbydim_construction calls tem_create_leveldesc
tem_facedep_vertical calls tem_facedep_verticalup