tem_finalize – Treelm
tem_finalize Subroutine
17 statements
Source File
public subroutine tem_finalize(general)
Finalize the environment, should be the very last call in the program.
Arguments
Type Intent Optional Attributes Name
type(tem_general_type), intent(in) :: general
encapsulates global parameters which are common for all solvers
Calls
Source Code
  subroutine tem_finalize(general)
    ! ----------------------------------------------------------------------
    !> encapsulates global parameters which are common for all solvers
    type(tem_general_type), intent(in) :: general
    ! ----------------------------------------------------------------------
    character(len=labelLen) :: timerName
    real(kind=rk) :: timerValue
    ! ----------------------------------------------------------------------
    if ( tem_status_run_terminate(general%simControl%status) ) then
      call tem_abort()
    end if
    call tem_timer_dump_glob( comm   = general%proc%comm,     &
      &                       myrank = general%proc%rank,     &
      &                       nProcs = general%proc%comm_size )
    if ( general%proc%isRoot ) then
      if ( printRuntimeInfo ) call print_self_status()
      timerName  = tem_getTimerName(timerHandle = general%solver%timerHandle )
      timerValue = tem_getTimerVal( timerHandle = general%solver%timerHandle )
      write(logUnit(1),*)
      write(logUnit(1),"(A,F10.2,A)") " Done with " // trim(timerName) &
        &                             // " in ", timerValue, ' s'
    end if
    ! finialize mpi
    call fin_env()
  end subroutine tem_finalize
Call graph
tem_finalize calls fin_env, print_self_status, tem_abort, tem_gettimername, tem_gettimerval, tem_status_run_terminate, tem_timer_dump_glob
fin_env calls mpi_finalize
print_self_status calls newunit
tem_abort calls mpi_abort
tem_gettimerval calls tem_stoptimer
tem_timer_dump_glob calls tem_timer_dumplabeled
tem_stoptimer calls mpi_wtime
tem_timer_dumplabeled calls positionofval, mpi_gather, tem_getmaxtimerval, tem_getmintimerval, tem_getsumtimerval, tem_open, upper_to_lower
positionofval calls posofval_label
tem_getmaxtimerval calls tem_gettimerval, mpi_allreduce
tem_getmintimerval calls tem_gettimerval, mpi_allreduce
tem_getsumtimerval calls tem_gettimerval, mpi_allreduce
tem_open calls tem_abort, newunit, upper_to_lower