tem_time_sim_stamp – Treelm
tem_time_sim_stamp Function
6 statements
Source File
public function tem_time_sim_stamp(time) result(timeStamp)
Generate a time stamp from the simulation time in the given time definition.
This basically generates a string identifying the solution time and writing it in a meaningful format, so that it can be easily recognized.
Arguments
Type Intent Optional Attributes Name
type(tem_time_type), intent(in) :: time
Time definition to create the stamp off.
Return Value character(len=12)
String representation of the given simulation time.
Called by
Source Code
  function tem_time_sim_stamp(time) result(timeStamp)
    ! -------------------------------------------------------------------- !
    !> Time definition to create the stamp off.
    type(tem_time_type), intent(in) :: time
    !> String representation of the given simulation time.
    character(len=12) :: timeStamp
    ! -------------------------------------------------------------------- !
    ! -------------------------------------------------------------------- !
    write(timeStamp, '(EN12.3)') time%sim
    ! remove leading empty spaces in the timestamp
    timeStamp = adjustl(timeStamp)
  end function  tem_time_sim_stamp
Call graph
hvs_asciispatial_open calls tem_time_sim_stamp
hvs_vtk_open calls tem_time_sim_stamp
tem_dump_stlb calls tem_time_sim_stamp
tem_restart_openwrite calls tem_time_sim_stamp
tem_restart_readheader calls tem_time_sim_stamp
hvs_dump_debug_array calls hvs_vtk_open
hvs_output_open calls hvs_asciispatial_open, hvs_vtk_open, tem_restart_openwrite
tem_load_restart calls tem_restart_readheader
tem_tracker calls hvs_output_open