tem_dump_subTree – Treelm
tem_dump_subTree Subroutine
27 statements
Source File
public subroutine tem_dump_subTree(me, globalTree, root_only)
This subroutine creates a new mesh in treelmesh format from a global and a sub tree and dumps it to disc in treelmesh format (needed for tracking in harvester format where the mesh has to be dumped to disc)
Arguments
Type Intent Optional Attributes Name
type(tem_subTree_type), intent(in) :: me
subTree to dump to disk
type(treelmesh_type), intent(in) :: globalTree
the global tree
logical, intent(in), optional :: root_only
root dump global mesh when true and all process dump its own mesh when false
Calls
Called by
Source Code
  subroutine tem_dump_subTree( me, globalTree, root_only )
    ! ---------------------------------------------------------------------------
    !> subTree to dump to disk
    type(tem_subTree_type), intent(in) :: me
    !> the global tree
    type(treelmesh_type), intent(in) :: globalTree
    !> root dump global mesh when true and
    !! all process dump its own mesh when false
    logical, intent(in), optional :: root_only
    ! ---------------------------------------------------------------------------
    type(treelmesh_type) :: local_tree
    integer :: iElem
    ! ---------------------------------------------------------------------------
    local_tree%global     = me%global
    local_tree%nElems     = me%nElems
    local_tree%elemOffset = me%elemOffset
    allocate(local_tree%treeID( me%nElems ))
    if (me%useLocalMesh) then
      local_tree%treeID = me%treeID
    else if (me%useGlobalMesh) then
      local_tree%treeID = globalTree%treeID
    else
      do iElem = 1, me%nElems
        local_tree%treeID( iElem ) = globalTree%treeID( me%map2global( iElem ))
      end do
    endif
    allocate( local_tree%ElemPropertyBits( size( me%ElemPropertyBits )))
    local_tree%ElemPropertyBits = me%ElemPropertyBits
    if (associated(me%property)) then
      allocate( local_tree%Property( size( me%Property )))
      local_tree%Property = me%Property
    end if
    call dump_treelmesh( me = local_tree, root_only = root_only )
  end subroutine tem_dump_subTree
Call graph
tem_dump_subtree calls dump_treelmesh
dump_treelmesh calls mpi_exscan, mpi_file_close, mpi_file_open, mpi_file_set_view, mpi_file_write_all, mpi_type_commit, mpi_type_contiguous, mpi_type_free, mpi_type_size, check_mpi_error, dump_tem_global, tem_create_endiansuffix
check_mpi_error calls mpi_error_string, tem_abort
dump_tem_global calls aot_out_close, aot_out_close_table, aot_out_open, aot_out_open_table, aot_out_val, dump_tem_prophead
dump_tem_prophead calls aot_out_close_table, aot_out_open_table, aot_out_val
tem_abort calls mpi_abort
hvs_output_init calls tem_dump_subtree
tem_restart_openwrite calls tem_dump_subtree
tem_write_debugmesh calls tem_dump_subtree
hvs_output_open calls tem_restart_openwrite
tem_init_tracker calls hvs_output_init
tem_tracker calls hvs_output_open