tem_condition_out_single – Treelm
tem_condition_out_single Subroutine
19 statements
Source File
private subroutine tem_condition_out_single(me, conf, level)
Allows the output of the single condition to lua out.
The data is written into the file, the lunit is connected to. It is formatted as a Lua table.
Arguments
Type Intent Optional Attributes Name
type(tem_condition_type), intent(in) :: me
condition to write into the lua file
type(aot_out_type), intent(inout) :: conf
aotus type handling the output to the file in lua format
integer, intent(in), optional :: level
to dump variable with key or without key
Calls
Called by
Source Code
  subroutine tem_condition_out_single(me, conf, level)
    ! -------------------------------------------------------------------- !
    !> condition to write into the lua file
    type(tem_condition_type), intent(in) :: me
    !> aotus type handling the output to the file in lua format
    type(aot_out_type), intent(inout) :: conf
    !> to dump variable with key or without key
    integer, optional, intent(in) :: level
    ! -------------------------------------------------------------------- !
    integer :: level_loc
    ! -------------------------------------------------------------------- !
    if (present(level)) then
      level_loc = level
    else
      level_loc = 0
    end if
    if( level_loc == 0) then
      call aot_out_open_table( put_conf = conf, tname = 'condition' )
    else
      call aot_out_open_table( put_conf = conf )
    end if
    call aot_out_val( put_conf = conf,         &
      &               val      = me%operation, &
      &               vname    = 'operator'    )
    call aot_out_val( put_conf = conf,         &
      &               val      = me%threshold, &
      &               vname    = 'threshold'   )
    call aot_out_close_table( put_conf = conf )
  end subroutine tem_condition_out_single
Call graph
tem_condition_out_single calls aot_out_close_table, aot_out_open_table, aot_out_val
tem_condition_out calls tem_condition_out_single, tem_condition_out_vector
tem_condition_dump_single calls tem_condition_out_single
tem_condition_out_vector calls tem_condition_out_single
tem_condition_dump calls tem_condition_dump_single, tem_condition_dump_vector
tem_condition_dump_vector calls tem_condition_out_vector
tem_convergence_out_single calls tem_condition_out
tem_convergence_out calls tem_convergence_out_single, tem_convergence_out_vector
tem_convergence_dump_single calls tem_convergence_out_single
tem_convergence_out_vector calls tem_convergence_out_single
tem_convergence_dump calls tem_convergence_dump_single
tem_convergence_dump_vector calls tem_convergence_out_vector