tem_eTypeIsValid – Treelm
tem_eTypeIsValid Function
9 statements
Source File
private pure function tem_eTypeIsValid(eT) result(isValid)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: eT
Return Value logical
Called by
Source Code
  pure function tem_eTypeIsValid( eT ) result( isValid )
    ! ---------------------------------------------------------------------------
    integer, intent(in) :: eT
    logical :: isValid
    ! ---------------------------------------------------------------------------
    if ( (eT >= eT_minNumber) .and. (eT <= eT_maxNumber) ) then
      isValid = .true.
    else
      isValid = .false.
    end if
  end function tem_eTypeIsValid
Call graph
append_element calls tem_etypeisvalid
changetype_element calls tem_etypeisvalid
changetype_element_vec calls tem_etypeisvalid
append calls append_element
changetype calls changetype_element, changetype_element_vec
communicate_elements calls changetype, identify_lists, redefine_halos
identify_lists calls changetype
redefine_halos calls changetype
tem_find_allelements calls communicate_elements, identify_lists