tem_tracking_finalize – Treelm
tem_tracking_finalize Subroutine
7 statements
Source File
public subroutine tem_tracking_finalize(me)
Close all the units of the tracking objects
Arguments
Type Intent Optional Attributes Name
type(tem_tracking_type), intent(inout) :: me
tracker object to close
Calls
Source Code
  subroutine tem_tracking_finalize( me )
    ! -------------------------------------------------------------------- !
    !> tracker object to close
    type(tem_tracking_type ), intent(inout) :: me
    ! -------------------------------------------------------------------- !
    integer :: iTrack !, iError
    ! -------------------------------------------------------------------- !
    do iTrack = 1, me%control%nActive
      call hvs_output_finalize( out_file = me%instance(iTrack)%output_file )
    end do
  end subroutine tem_tracking_finalize
Call graph
tem_tracking_finalize calls hvs_output_finalize
hvs_output_finalize calls hvs_ascii_close, hvs_vtk_closepvd, tem_restart_finalize, tem_vrtx_finalize
hvs_vtk_closepvd calls tem_abort
tem_restart_finalize calls mpi_type_free, check_mpi_error
check_mpi_error calls tem_abort, mpi_error_string
tem_abort calls mpi_abort