tem_shape_propLabel_out – Treelm
tem_shape_propLabel_out Subroutine
8 statements
Source File
private subroutine tem_shape_propLabel_out(propBits, conf)
Write out a shape property label in lua format
Arguments
Type Intent Optional Attributes Name
integer(kind=long_k), intent(in) :: propBits
property bits
type(aot_out_type), intent(inout) :: conf
Aotus type handling the output to the file in lua format
Calls
Called by
Source Code
  subroutine tem_shape_propLabel_out( propBits, conf )
    ! --------------------------------------------------------------------------
    !> property bits
    integer(kind=long_k), intent(in) :: propBits
    !> Aotus type handling the output to the file in lua format
    type(aot_out_type), intent(inout) :: conf
    ! --------------------------------------------------------------------------
    call aot_out_open_table( put_conf = conf, tname = 'property' )
    if (btest(propBits, prp_hasBnd)) &
      call aot_out_val( put_conf = conf, val = 'boundary' )
    if (btest(propBits, prp_fluidify)) &
      call aot_out_val( put_conf = conf, val = 'solidified' )
    call aot_out_close_table( put_conf = conf )
  end subroutine tem_shape_propLabel_out
Call graph
tem_shape_proplabel_out calls aot_out_close_table, aot_out_open_table, aot_out_val
tem_shape_out_scal calls tem_shape_proplabel_out
tem_shape_out calls tem_shape_out_scal, tem_shape_out_vec
tem_shape_out_vec calls tem_shape_out_scal
hvs_ascii_write_header calls tem_shape_out
tem_convergence_out_single calls tem_shape_out
tem_convergence_out calls tem_convergence_out_single
hvs_ascii_init calls hvs_ascii_write_header
hvs_asciispatial_init calls hvs_ascii_write_header
tem_convergence_dump_single calls tem_convergence_out_single
tem_convergence_out_vector calls tem_convergence_out_single