tem_timeformatter_init – Treelm
tem_timeformatter_init Function
15 statements
Source File
public function tem_timeformatter_init(timeform, stamp) result(formatter)
Reading a timeformatter description from a Lua script given by conf.
Initializing a timeformatter * timeform defines the formatting string to be used for the timestamp this defaults to default_form * stamp defines the routine to use for the timestamp generation and defaults to tem_timeformatter_sim_stamp
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in), optional :: timeform
procedure(timestamp), optional :: stamp
Return Value type(tem_timeformatter_type)
Called by
Source Code
  function tem_timeformatter_init(timeform, stamp) result(formatter)
    character(len=*), optional, intent(in) :: timeform
    procedure(timestamp), optional :: stamp
    type(tem_timeformatter_type) :: formatter
    if (present(timeform)) then
      formatter%timeform = timeform
    else
      formatter%timeform = default_form
    end if
    if (present(stamp)) then
      formatter%stamp => stamp
    else
      formatter%stamp => tem_timeformatter_sim_stamp
    end if
  end function tem_timeformatter_init
Call graph
hvs_asciispatial_init calls tem_timeformatter_init
tem_dump_stlb calls tem_timeformatter_init
tem_restart_readheader calls tem_timeformatter_init
tem_timeformatter_load calls tem_timeformatter_init
hvs_output_init calls hvs_asciispatial_init
hvs_output_load calls tem_timeformatter_load
tem_load_restart calls tem_restart_readheader, tem_timeformatter_load
tem_init_tracker calls hvs_output_init
tem_load_trackingconfig calls hvs_output_load
tem_load_tracking calls tem_load_trackingconfig