tem_spatial_random_for – Treelm
tem_spatial_random_for Function
7 statements
Source File
private function tem_spatial_random_for(me, n) result(res)
Produce random numbers
Arguments
Type Intent Optional Attributes Name
type(spatial_random_type), intent(in) :: me
Interval definition to get the random values from.
integer, intent(in) :: n
number of return values
Return Value real(kind=rk), (n)
return value of a function
Called by
Source Code
  function tem_spatial_random_for( me, n ) result(res)
    ! -------------------------------------------------------------------- !
    !> Interval definition to get the random values from.
    type(spatial_random_type), intent(in) :: me
    !> number of return values
    integer, intent(in) :: n
    !> return value of a function
    real(kind=rk) :: res(n)
    ! -------------------------------------------------------------------- !
    call random_number(res)
    res = me%val_min + me%val_range*res
  end function tem_spatial_random_for
Call graph
tem_spatial_for_coord calls tem_spatial_random_for
tem_spatial_for_treeids calls tem_spatial_random_for
tem_spatial_for calls tem_spatial_for_coord, tem_spatial_for_treeids, tem_spatial_scalar_for_index
tem_spatial_scalar_for_index calls tem_spatial_for_coord
tem_spacetime_for_coord calls tem_spatial_for
tem_spacetime_for_treeids calls tem_spatial_for
tem_spacetime_scalar_for_index calls tem_spatial_for, tem_spacetime_for_coord
tem_spacetime_vector_for_coord calls tem_spatial_for
tem_spacetime_vector_for_index calls tem_spatial_for, tem_spacetime_vector_for_coord
tem_spacetime_vector_for_treeids calls tem_spatial_for
tem_spatial_scalar_storeval calls tem_spatial_for
tem_spatial_vector_storeval calls tem_spatial_for
tem_spacetime_for calls tem_spacetime_for_coord, tem_spacetime_for_treeids, tem_spacetime_scalar_for_index, tem_spacetime_vector_for_coord, tem_spacetime_vector_for_index, tem_spacetime_vector_for_treeids
tem_spatial_storeval calls tem_spatial_scalar_storeval, tem_spatial_vector_storeval
tem_spacetime_for_stcoord calls tem_spacetime_for_coord