tem_triangleCubeOverlap – Treelm
tem_triangleCubeOverlap Function
8 statements
Source File
public function tem_triangleCubeOverlap(triangle, cube) result(overlaps)
Compute, if the triangle intersects the cube.
Arguments
Type Intent Optional Attributes Name
type(tem_triangle_type), intent(in) :: triangle
type(tem_cube_type), intent(in) :: cube
Return Value logical
Calls
Called by
Source Code
  function tem_triangleCubeOverlap(triangle, cube) result(overlaps)
    !--------------------------------------------------------------------------!
    type(tem_triangle_type), intent(in) :: triangle
    type(tem_cube_type), intent(in) :: cube
    logical :: overlaps
    !--------------------------------------------------------------------------!
    real(kind=rk) :: halfwidth
    !--------------------------------------------------------------------------!
    ! halfwidth is increased by eps to avoid precision problem in
    ! triangöe box intersection.
    halfwidth = cube%halfwidth + eps
    overlaps = triBoxOverlap_loc( cube%center,                       &
      &                           [halfwidth, halfwidth, halfwidth], &
      &                           triangle%nodes )
  end function tem_triangleCubeOverlap
Call graph
tem_trianglecubeoverlap calls triboxoverlap_loc
triboxoverlap_loc calls axistest, cross_product3d, planeboxoverlap
axistest calls cross_product3d
tem_planecubeoverlap calls tem_trianglecubeoverlap
tem_shape_subtreefromgeominters calls tem_trianglecubeoverlap, tem_stlcubeoverlap, tem_cano_initsubtree
tem_stlcubeoverlap calls tem_trianglecubeoverlap
tem_boxcubeoverlap calls tem_planecubeoverlap
tem_cano_initsubtree calls tem_planecubeoverlap, tem_boxcubeoverlap
tem_shape2subtree calls tem_shape_subtreefromgeominters
tem_create_subtree_of calls tem_shape2subtree
tem_create_subtree_of_st_funlist calls tem_create_subtree_of
tem_init_convergence calls tem_create_subtree_of
tem_init_tracker_subtree calls tem_create_subtree_of
tem_write_debugmesh calls tem_create_subtree_of