tem_triangle_out_vec – Treelm
tem_triangle_out_vec Subroutine
15 statements
Source File
private subroutine tem_triangle_out_vec(me, conf)
Write out an array of triangles in lua format Only if nTriangles <= 10
Arguments
Type Intent Optional Attributes Name
type(tem_triangle_type), intent(in) :: me(:)
triangle types to write out
type(aot_out_type), intent(inout) :: conf
Aotus type handling the output to the file in lua format
Calls
Called by
Source Code
  subroutine tem_triangle_out_vec( me, conf )
    ! --------------------------------------------------------------------------
    !> triangle types to write out
    type( tem_triangle_type ), intent(in) :: me(:)
    !> Aotus type handling the output to the file in lua format
    type(aot_out_type), intent(inout) :: conf
    ! --------------------------------------------------------------------------
    ! counter
    integer :: i
    ! --------------------------------------------------------------------------
    ! create a table with name triangle
    call aot_out_open_table( put_conf = conf, tname = 'triangle' )
    if (size(me)<=10) then
      do i = 1, size(me)
        call tem_triangle_out_scal( me(i), conf )
      end do
    else
      call aot_out_val( put_conf = conf, vname = 'nTriangles', val = size(me) )
      call aot_out_val( put_conf = conf,                                  &
        &               val = 'Write triangle is limited to 10 triangles' )
    end if
    call aot_out_close_table( put_conf = conf )
  end subroutine tem_triangle_out_vec
Call graph
tem_triangle_out_vec calls aot_out_close_table, aot_out_open_table, aot_out_val, tem_triangle_out_scal
tem_triangle_out_scal calls aot_out_close_table, aot_out_open_table, aot_out_val
tem_triangle_out calls tem_triangle_out_vec
tem_shape_out_scal calls tem_triangle_out
tem_shape_out calls tem_shape_out_scal, tem_shape_out_vec
tem_shape_out_vec calls tem_shape_out_scal
hvs_ascii_write_header calls tem_shape_out
tem_convergence_out_single calls tem_shape_out