tem_load_translation – Treelm
tem_load_translation Subroutine
24 statements
Source File
private subroutine tem_load_translation(translate, conf, thandle)
This routine loads the translation table from transformation table
Arguments
Type Intent Optional Attributes Name
type(tem_translation_type), intent(out) :: translate
translate for spatial object
type(flu_State) :: conf
lua state
integer, intent(in) :: thandle
spatial object parent handle
Calls
Called by
Source Code
  subroutine tem_load_translation( translate, conf, thandle )
    !--------------------------------------------------------------------------!
    !inferface variables
    !> translate for spatial object
    type(tem_translation_type), intent(out) :: translate
    !> lua state
    type(flu_state) :: conf
    !> spatial object parent handle
    integer, intent(in) :: thandle
    !--------------------------------------------------------------------------!
    integer :: translate_handle
    integer :: vError(3), errFatal(3)
    !--------------------------------------------------------------------------!
    errFatal = aoterr_fatal
    translate%active = .false.
    translate%vec = 0.0_rk
    call aot_table_open(L = conf, parent = thandle, &
      &                 thandle = translate_handle, &
      &                 key = 'translation')
    if(translate_handle > 0) then
      translate%active = .true.
      call aot_get_val(L=conf, thandle = thandle, key = 'translation', &
        &              val=translate%vec, ErrCode = vError )
      if (any(btest(vError, errFatal))) then
        write(logunit(0),*) 'Error in configuration: translate table in'
        write(logunit(0),*) '    transformation table'
        call tem_abort()
      end if
    endif
    call aot_table_close(L=conf, thandle=translate_Handle)
    if (translate%active) then
      write(logunit(1),*) ' Translation = ', translate%vec
    endif
  end subroutine tem_load_translation
Call graph
tem_load_translation calls aot_get_val, aot_table_close, aot_table_open, tem_abort
tem_abort calls mpi_abort
tem_load_transformation calls tem_load_translation
tem_load_shape_single calls tem_load_transformation
tem_load_shape calls tem_load_shape_single, tem_load_shapes
tem_load_shapes calls tem_load_shape_single
load_spatial_parabol calls tem_load_shape
tem_load_convergenceheader calls tem_load_shape
tem_load_spacetime_single calls tem_load_shape
tem_load_trackingconfig calls tem_load_shape