tem_LastIdAtLevel – Treelm
tem_LastIdAtLevel Function
12 statements
Source File
public elemental function tem_LastIdAtLevel(level) result(res)
Last ID in the complete tree on a given level
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: level
level to check
Return Value integer(kind=long_k)
resulting last treeID
Called by
Source Code
  elemental function tem_LastIdAtLevel( level ) result(res)
    ! ---------------------------------------------------------------------------
    !> level to check
    integer, intent(in) :: level
    !> resulting last treeID
    integer(kind=long_k) :: res
    ! ---------------------------------------------------------------------------
    integer :: i
    integer(kind=long_k) :: monomonial
    ! ---------------------------------------------------------------------------
    res = -1
    monomonial = 1
    do i = 0, level
      res = res + monomonial
      monomonial = monomonial * 8
    end do
  end function tem_LastIdAtLevel
Call graph
generate_treelm_cube calls tem_lastidatlevel
tem_shape_initbylevels calls tem_lastidatlevel
tem_load_internal calls generate_treelm_cube
tem_shape2subtree calls tem_shape_initbylevels
load_tem calls tem_load_internal
tem_create_subtree_of calls tem_shape2subtree
tem_create_subtree_of_st_funlist calls tem_create_subtree_of
tem_init_convergence calls tem_create_subtree_of
tem_init_tracker_subtree calls tem_create_subtree_of
tem_restart_readheader calls load_tem
tem_write_debugmesh calls tem_create_subtree_of