tem_getMinTimerVal – Treelm
tem_getMinTimerVal Function
11 statements
Source File
public function tem_getMinTimerVal(me, timerHandle, comm) result(retValue)
Get the minimum timer duration across all partitions.
Note
This assumes the same timerhandle to be used across all partitions for all timers.
Arguments
Type Intent Optional Attributes Name
type(tem_timer_type), intent(inout), optional :: me
timer object
integer, intent(in) :: timerHandle
timer handle
integer, intent(in) :: comm
communicator handle
Return Value real(kind=rk)
timer value
Calls
Called by
Source Code
  function tem_getMinTimerVal( me, timerHandle, comm ) result( retValue )
    ! -------------------------------------------------------------------- !
    !> timer object
    type(tem_timer_type), intent(inout), optional :: me
    !> timer handle
    integer, intent(in) :: timerHandle
    !> communicator handle
    integer, intent(in) :: comm
    !> timer value
    real(kind=rk) :: retValue
    ! -------------------------------------------------------------------- !
    real(kind=rk) :: send, recv
    integer :: iError
    ! -------------------------------------------------------------------- !
    send = tem_getTimerVal( me = me, timerHandle = timerHandle )
    call MPI_Allreduce( send, recv, 1, rk_mpi, MPI_MIN, comm, iError )
    retValue = recv
  end function tem_getMinTimerVal
Call graph
tem_getmintimerval calls mpi_allreduce, tem_gettimerval
tem_gettimerval calls tem_stoptimer
tem_stoptimer calls mpi_wtime
tem_timer_dumplabeled calls tem_getmintimerval
tem_timer_dump_glob calls tem_timer_dumplabeled
tem_finalize calls tem_timer_dump_glob