tem_stringKVP_equals – Treelm
tem_stringKVP_equals Function
6 statements
Source File
private pure function tem_stringKVP_equals(me, other) result(res)
Indicates whether this instance and a specified object are equal.
Arguments
Type Intent Optional Attributes Name
type(tem_stringKeyValuePair_type), intent(in) :: me
THe current instance.
type(tem_stringKeyValuePair_type), intent(in) :: other
The instance to compare with the current instance.
Return Value logical
.true. when both instances are equal, otherwise .false.
Called by
Source Code
  pure function tem_stringKVP_equals(me, other) result (res)
    ! ---------------------------------------------------------------------------
    !> THe current instance.
    type(tem_stringKeyValuePair_type), intent(in) :: me
    !> The instance to compare with the current instance.
    type(tem_stringKeyValuePair_type), intent(in) :: other
    !> .true. when both instances are equal, otherwise .false.
    logical :: res
    ! ---------------------------------------------------------------------------
    res = (me%key == other%key) .and. (me%value == other%value)
  end function tem_stringKVP_equals
Call graph
operator (==) calls tem_stringkvp_equals
tem_stringkvp_notequals calls tem_stringkvp_equals
operator (SLASH=) calls tem_stringkvp_notequals