tem_timeControl_reset_trigger – Treelm
tem_timeControl_reset_trigger Subroutine
5 statements
Source File
public subroutine tem_timeControl_reset_trigger(me)
This routine resets trigger to min and sets min_reached to false
Arguments
Type Intent Optional Attributes Name
type(tem_timeControl_type), intent(inout) :: me
Time control settings to check.
Called by
Source Code
  subroutine tem_timeControl_reset_trigger(me)
    ! -------------------------------------------------------------------- !
    !> Time control settings to check.
    type(tem_timeControl_type), intent(inout) :: me
    ! -------------------------------------------------------------------- !
    ! -------------------------------------------------------------------- !
    me%trigger = me%min
    me%min_reached = .false.
  end subroutine tem_timeControl_reset_trigger
Call graph
tem_convergence_reset calls tem_timecontrol_reset_trigger
tem_simcontrol_steadystate_reset calls tem_timecontrol_reset_trigger, tem_convergence_reset