tem_comparator – Treelm
tem_comparator Function
19 statements
Source File
public function tem_comparator(val, operation, threshold) result(comp)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: val
character(len=2), intent(in) :: operation
real(kind=rk), intent(in) :: threshold
Return Value logical
return value
Called by
Source Code
  function tem_comparator( val, operation, threshold ) result(comp)
    ! -------------------------------------------------------------------- !
    !>
    real(kind=rk), intent(in)      :: val
    !>
    character(len=2), intent(in)   :: operation
    !>
    real(kind=rk), intent(in)      :: threshold
    !> return value
    logical                        :: comp
    ! -------------------------------------------------------------------- !
    comp = .false.
    select case( trim(operation))
    case ('<')
      comp = (val < threshold)
    case ('<=')
      comp = (val <= threshold)
    case ('>')
      comp = (val > threshold)
    case ('>=')
      comp = (val >= threshold)
    case ('=')
      comp = (val .feq. threshold)
    end select
  end function tem_comparator
Call graph
tem_convergence_evaluate calls tem_comparator
tem_convergence_check_element calls tem_convergence_evaluate
tem_convergence_check_point calls tem_convergence_evaluate
tem_convergence_check calls tem_convergence_check_element, tem_convergence_check_point