tem_time_never – Treelm
tem_time_never Function
6 statements
Source File
public function tem_time_never()
Representation of a point in time, that should never happen.
Arguments
None
Return Value type(tem_time_type)
A time that represents never in all definitions.
Called by
Source Code
  function tem_time_never()
    ! -------------------------------------------------------------------- !
    !> A time that represents never in all definitions.
    type(tem_time_type) :: tem_time_never
    ! -------------------------------------------------------------------- !
    tem_time_never%sim   = huge(tem_time_never%sim)
    tem_time_never%iter  = huge(tem_time_never%iter)
    tem_time_never%clock = huge(tem_time_never%clock)
  end function tem_time_never
Call graph
tem_balance_load calls tem_time_never, tem_timecontrol_load
tem_timecontrol_load calls tem_time_never
tem_timecontrol_start_at_sim calls tem_time_never
tem_timecontrol_triggered calls tem_time_never
tem_load_adapt calls tem_timecontrol_load
tem_load_convergenceheader calls tem_timecontrol_load
tem_load_general calls tem_balance_load, tem_simcontrol_load
tem_load_output calls tem_timecontrol_load
tem_load_restart calls tem_timecontrol_load
tem_load_surfdata calls tem_timecontrol_load
tem_load_trackingconfig calls tem_timecontrol_load
tem_simcontrol_load calls tem_timecontrol_load, tem_timecontrol_start_at_sim
tem_simcontrol_syncupdate calls tem_timecontrol_triggered, tem_timecontrol_update
tem_timecontrol_globaltriggered calls tem_timecontrol_triggered
tem_timecontrol_update calls tem_timecontrol_triggered
tem_convergence_load calls tem_load_convergenceheader
tem_load_tracking calls tem_load_trackingconfig
tem_timecontrol_check calls tem_timecontrol_globaltriggered, tem_timecontrol_update
tem_abortcriteria_load calls tem_convergence_load
tem_convergence_check calls tem_timecontrol_check
tem_tracking_has_triggered calls tem_timecontrol_check