tem_timeControl_out – Treelm
tem_timeControl_out Subroutine
18 statements
Source File
public subroutine tem_timeControl_out(me, conf, key)
Write a time control definition to a Lua script.
Arguments
Type Intent Optional Attributes Name
type(tem_timeControl_type), intent(in) :: me
Time control definition to write to a Lua config.
type(aot_out_type) :: conf
Handle for the Lua script.
character(len=*), intent(in), optional :: key
Name of the time control table. Default: 'time_control'
Calls
Called by
Source Code
  subroutine tem_timeControl_out(me, conf, key)
    ! -------------------------------------------------------------------- !
    !> Time control definition to write to a Lua config.
    type(tem_timeControl_type), intent(in) :: me
    !> Handle for the Lua script.
    type(aot_out_type) :: conf
    !> Name of the time control table. Default: 'time_control'
    character(len=*), intent(in), optional :: key
    ! -------------------------------------------------------------------- !
    character(len=labelLen) :: localKey
    ! -------------------------------------------------------------------- !
    if (present(key)) then
      localKey = key
    else
      localKey = 'time_control'
    endif
    call aot_out_open_table( put_conf = conf,    &
      &                      tname    = localkey )
    call tem_time_out(me     = me%min, &
      &               conf   = conf,   &
      &               key    = 'min'   )
    call tem_time_out(me     = me%max, &
      &               conf   = conf,   &
      &               key    = 'max'   )
    call tem_time_out(me     = me%interval, &
      &               conf   = conf,        &
      &               key    = 'interval'   )
    call aot_out_val( put_conf = conf,          &
      &               val      = me%check_iter, &
      &               vname    = 'check_iter'   )
    call aot_out_val( put_conf = conf,           &
      &               val      = me%delay_check, &
      &               vname    = 'delay_check'   )
    call aot_out_close_table(put_conf = conf)
  end subroutine tem_timeControl_out
Call graph
tem_timecontrol_out calls aot_out_close_table, aot_out_open_table, aot_out_val, tem_time_out
tem_time_out calls aot_out_close_table, aot_out_open_table, aot_out_val
hvs_ascii_write_header calls tem_timecontrol_out
tem_convergence_out_single calls tem_timecontrol_out
tem_simcontrol_out calls tem_timecontrol_out
tem_convergence_out calls tem_convergence_out_single, tem_convergence_out_vector
hvs_ascii_init calls hvs_ascii_write_header
hvs_asciispatial_init calls hvs_ascii_write_header
tem_convergence_dump_single calls tem_convergence_out_single
tem_convergence_out_vector calls tem_convergence_out_single
tem_convergence_dump calls tem_convergence_dump_single, tem_convergence_dump_vector
hvs_output_init calls hvs_ascii_init, hvs_asciispatial_init
tem_convergence_dump_vector calls tem_convergence_out_vector
tem_init_tracker calls hvs_output_init