tem_spacetime_for_treeIDs – Treelm
tem_spacetime_for_treeIDs Function
22 statements
Source File
private function tem_spacetime_for_treeIDs(me, treeIDs, time, tree, n) result(res)
This function compute space time function for given list of treeIDs
Todo
pass subtree with treeIDs lists instead of treeIds and tree
Arguments
Type Intent Optional Attributes Name
type(tem_spacetime_fun_type) :: me
Spacetime function to evaluate
integer(kind=long_k), intent(in) :: treeIDs(n)
TreeIDs where to evaluate the function
type(tem_time_type), intent(in) :: time
timer object incl. the current time information
type(treelmesh_type), intent(in) :: tree
Global treelmesh to look for positions in
integer, intent(in) :: n
Number of values to return
Return Value real(kind=rk), (n)
return value of the function
Calls
Called by
Source Code
  function tem_spacetime_for_treeIDs( me, treeIDs, time, tree, n ) result(res)
    ! -------------------------------------------------------------------- !
    !> Spacetime function to evaluate
    type(tem_spacetime_fun_type) :: me
    !> Global treelmesh to look for positions in
    type(treelmesh_type), intent(in) ::tree
    !> Number of values to return
    integer, intent(in) :: n
    !> TreeIDs where to evaluate the function
    integer(kind=long_k), intent( in ) :: treeIDs(n)
    !> timer object incl. the current time information
    type(tem_time_type), intent( in )  :: time
    !> return value of the function
    real(kind=rk) :: res(n)
    ! -------------------------------------------------------------------- !
    select case(trim(adjustl(me%fun_kind)))
    case('none')
      res = 0.0_rk
    case('const')
      res = me%const(1)
    case('lua_fun')
      res = tem_spacetime_lua_for( me%lua_fun_ref, treeIDs, time, tree, n, &
        &                          me%conf)
    case('combined')
      res = tem_spatial_for( me      = me%spatial,    &
        &                    treeIDs = treeIDs,       &
        &                    tree    = tree,          &
        &                    n       = n           )  &
        & * tem_temporal_for( temporal = me%temporal, &
        &                     time     = time         )
    case default
      write(logUnit(1),*)'ERROR: Unknown spatial function in '//               &
        &                'tem_spacetime_for_treeIDs.'
      write(logUnit(1),*) 'tem_spacetime_fun_type%fun_kind = ', &
        &                 trim(me%fun_kind)
      call tem_abort()
    end select
  end function tem_spacetime_for_treeIDs
Call graph
tem_spacetime_for_treeids calls tem_spacetime_lua_for, tem_spatial_for, tem_abort, tem_temporal_for
tem_spacetime_lua_for calls tem_spacetime_lua_for_coord, tem_spacetime_lua_for_treeids, tem_spacetime_lua_vector_for_coord, tem_spacetime_lua_vector_for_treeids
tem_spatial_for calls tem_spatial_for_coord, tem_spatial_for_treeids, tem_spatial_scalar_for_index, tem_spatial_vector_for_coord, tem_spatial_vector_for_index, tem_spatial_vector_for_treeids
tem_abort calls mpi_abort
tem_temporal_for calls tem_abort, temporal_from_file_periodic_for, temporal_linear_for, temporal_lua_for, temporal_smooth_for
tem_spacetime_for calls tem_spacetime_for_treeids
evaluate_add_spacetime_scalarbycoordinate calls tem_spacetime_for
evaluate_add_spacetime_scalarbytreeid calls tem_spacetime_for
evaluate_add_spacetime_vectorbycoordinate calls tem_spacetime_for
evaluate_add_spacetime_vectorbytreeid calls tem_spacetime_for
evaluate_first_spacetime_scalarbycoordinate calls tem_spacetime_for
evaluate_first_spacetime_scalarbytreeid calls tem_spacetime_for
evaluate_first_spacetime_vectorbycoordinate calls tem_spacetime_for
evaluate_first_spacetime_vectorbytreeid calls tem_spacetime_for
evaluate_foag_spacetime_scalarbycoordinate calls tem_spacetime_for
evaluate_foag_spacetime_scalarbytreeid calls tem_spacetime_for
evaluate_foag_spacetime_vectorbycoordinate calls tem_spacetime_for
evaluate_foag_spacetime_vectorbytreeid calls tem_spacetime_for
get_valofindex_add_scalar_spacetime calls tem_spacetime_for
get_valofindex_add_vector_spacetime calls tem_spacetime_for
get_valofindex_first_scalar_spacetime calls tem_spacetime_for
get_valofindex_first_vector_spacetime calls tem_spacetime_for
get_valofindex_foag_scalar_spacetime calls tem_spacetime_for
get_valofindex_foag_vector_spacetime calls tem_spacetime_for
tem_update_surfpos calls tem_spacetime_for