tem_ElemSize – Treelm
tem_ElemSize Function
8 statements
Source File
public pure function tem_ElemSize(tree, treeID) result(dx)
Return the size of a given treeID in the mesh by taking into account the size of the bounding cube given in the global info of the tree
Arguments
Type Intent Optional Attributes Name
type(treelmesh_type), intent(in) :: tree
Mesh to locate point in
integer(kind=long_k), intent(in) :: treeID
input elements
Return Value real(kind=rk)
size of element
Calls
Called by
Source Code
  pure function tem_ElemSize( tree, treeID ) result(dx)
    ! -------------------------------------------------------------------- !
    !> Mesh to locate point in
    type(treelmesh_type), intent(in) :: tree
    !> input elements
    integer(kind=long_k), intent(in) :: treeID
    !> size of element
    real(kind=rk) :: dx
    ! -------------------------------------------------------------------- !
    integer       :: level
    ! -------------------------------------------------------------------- !
    level = tem_levelOf(TreeID)
    dx = tem_elemSizeLevel( tree, level )
  end function tem_ElemSize
Call graph
tem_elemsize calls tem_elemsizelevel, tem_levelof
deriveelemvol calls tem_elemsize
derivevolfrac calls tem_elemsize
tem_calc_vrtxof_qval calls tem_elemsize
tem_converttreeidtocube calls tem_elemsize
tem_reduction_spatial_append calls tem_elemsize
tem_shape_findelembybclabels calls tem_elemsize
tem_tidinfo calls tem_elemsize
hvs_ascii_dump_elem_data calls tem_reduction_spatial_append
hvs_ascii_dump_point_data calls tem_reduction_spatial_append
identify_elements calls tem_tidinfo, identify_elements
identify_local_element calls tem_tidinfo
tem_calc_vrtx_coord calls tem_calc_vrtxof_qval
tem_cano_initsubtree calls tem_converttreeidtocube
tem_convergence_check_element calls tem_reduction_spatial_append
tem_convergence_check_point calls tem_reduction_spatial_append
tem_shape2subtree calls tem_shape_findelembybclabels, tem_shape_subtreefromgeominters
tem_shape_subtreefromgeominters calls tem_converttreeidtocube, tem_cano_initsubtree
build_levelelements calls identify_elements
create_allparentneighbors calls identify_elements
hvs_output_init calls tem_calc_vrtx_coord
hvs_output_write calls hvs_ascii_dump_elem_data, hvs_ascii_dump_point_data
identify_additionalneigh calls identify_elements
identify_halo calls identify_local_element
identify_stencilneigh calls identify_elements
single_process_element calls identify_local_element
tem_convergence_check calls tem_convergence_check_element, tem_convergence_check_point
tem_create_subtree_of calls tem_shape2subtree