tem_addTimer – Treelm
tem_addTimer Subroutine
17 statements
Source File
public subroutine tem_addTimer(me, timerName, timerHandle)
Setup a new timer object, reset the values and give it a label for later identification
Arguments
Type Intent Optional Attributes Name
type(tem_labeledtimer_type), intent(inout), optional :: me
timer object
character(len=*), intent(in) :: timerName
Name for this timer
integer, intent(out) :: timerHandle
A handle to reference this timer
Calls
Called by
Source Code
  subroutine tem_addTimer( me, timerName, timerHandle )
    ! -------------------------------------------------------------------- !
    !> timer object
    type(tem_labeledtimer_type), intent(inout), optional :: me
    !> Name for this timer
    character(len=*), intent(in) :: timerName
    !> A handle to reference this timer
    integer, intent(out) :: timerHandle
    ! -------------------------------------------------------------------- !
    logical :: is_newtimer
    ! -------------------------------------------------------------------- !
    if ( present(me) ) then
      call append( me       = me%label,        &
        &          val      = trim(timerName), &
        &          pos      = timerHandle,     &
        &          wasAdded = is_newtimer      )
      if (is_newtimer) then
        call tem_appendTimers( me    = me%timedat, &
          &                    nVals = 1           )
      end if
    else
      call append( me       = timer%label,     &
        &          val      = trim(timerName), &
        &          pos      = timerHandle,     &
        &          wasAdded = is_newtimer      )
      if (is_newtimer) then
        call tem_appendTimers( me    = timer%timedat, &
          &                    nVals = 1              )
      end if
    end if
  end subroutine tem_addTimer
Call graph
tem_addtimer calls append, tem_appendtimers
append calls append_da_label, append_da_veclabel
tem_appendtimers calls append
append_da_label calls expand, sortedposofval
append_da_veclabel calls expand
expand calls expand_da_label
sortedposofval calls sortposofval_label
tem_simcontrol_load calls tem_addtimer
tem_start calls tem_addtimer
tem_load_general calls tem_simcontrol_load