tem_stlHead_out_scal – Treelm
tem_stlHead_out_scal Subroutine
11 statements
Source File
private subroutine tem_stlHead_out_scal(me, conf)
Write out a stlHead shape in lua format
Arguments
Type Intent Optional Attributes Name
type(tem_stlHead_type), intent(in) :: me
stlHead types to write out
type(aot_out_type), intent(inout) :: conf
Aotus type handling the output to the file in lua format
Calls
Called by
Source Code
  subroutine tem_stlHead_out_scal( me, conf )
    ! --------------------------------------------------------------------------
    !> stlHead types to write out
    type( tem_stlHead_type ), intent(in) :: me
    !> Aotus type handling the output to the file in lua format
    type(aot_out_type), intent(inout) :: conf
    ! --------------------------------------------------------------------------
    ! ---------------------------------------------------------------------------
    ! create a table with name stlHead if not exist
    if( conf%level == 0 ) then
      call aot_out_open_table( put_conf = conf, tname = 'object' )
    else
      call aot_out_open_table( put_conf = conf )
    end if
    call aot_out_val( put_conf = conf, vname = 'filename', val = me%filename )
    call aot_out_close_table( put_conf = conf )
  end subroutine tem_stlHead_out_scal
Call graph
tem_stlhead_out_scal calls aot_out_close_table, aot_out_open_table, aot_out_val
tem_stlhead_out calls tem_stlhead_out_scal, tem_stlhead_out_vec
tem_stlhead_out_vec calls tem_stlhead_out_scal
tem_shape_out_scal calls tem_stlhead_out
tem_shape_out calls tem_shape_out_scal, tem_shape_out_vec
tem_shape_out_vec calls tem_shape_out_scal
hvs_ascii_write_header calls tem_shape_out
tem_convergence_out_single calls tem_shape_out