tem_eTypeOfId – Treelm
tem_eTypeOfId Function
11 statements
Source File
public function tem_eTypeOfId(tID, me) result(eType)
Return the element type of a treeID .
Arguments
Type Intent Optional Attributes Name
integer(kind=long_k), intent(in) :: tID
the element you are looking for
type(tem_element_type), intent(in) :: me
the descriptor you use for searching
Return Value integer
element type
Calls
Called by
Source Code
  function tem_eTypeOfId( tID, me ) result( eType )
    ! ---------------------------------------------------------------------------
    !> the element you are looking for
    integer(kind=long_k), intent(in) :: tID
    !> the descriptor you use for searching
    type(tem_element_type), intent(in) :: me
    !> element type
    integer :: eType
    ! ---------------------------------------------------------------------------
    integer :: pos
    ! ---------------------------------------------------------------------------
    eType = eT_undefined
    pos = PositionOfVal( me  = me%tID, val = tID )
    if( pos > 0 ) then
      eType = me%eType%val( pos )
    end if
  end function tem_eTypeOfId
Call graph
tem_etypeofid calls positionofval
positionofval calls posofval_label
posofval_label calls sortedposofval
sortedposofval calls sortposofval_label
tem_treeidintotal calls tem_etypeofid
tem_build_listhorizontaldep calls tem_treeidintotal
tem_build_treehorizontaldep calls tem_treeidintotal
tem_build_verticaldependencies calls tem_treeidintotal
tem_get_faceneigh calls tem_treeidintotal
tem_init_surfdata calls tem_treeidintotal
update_buffer_elempos calls tem_treeidintotal
update_elempostototalpos calls tem_treeidintotal, update_buffer_elempos
tem_build_horizontaldependencies calls tem_build_listhorizontaldep, tem_build_treehorizontaldep
tem_create_leveldesc calls tem_build_verticaldependencies, tem_build_horizontaldependencies, tem_find_allelements
tem_extend_commfromcoarserprp calls tem_get_faceneigh
tem_extend_commfromfinerprp calls tem_get_faceneigh
tem_find_allelements calls update_elempostototalpos
tem_get_faces calls tem_get_faceneigh
tem_update_surfpos calls tem_init_surfdata
tem_collect_faces calls tem_get_faces
tem_dimbydim_construction calls tem_create_leveldesc
tem_extend_remoteprp calls tem_extend_commfromcoarserprp, tem_extend_commfromfinerprp