tem_stopTimer – Treelm
tem_stopTimer Subroutine
17 statements
Source File
public subroutine tem_stopTimer(me, timerHandle)
Stop the timer for the given timer handle and update the timings
Arguments
Type Intent Optional Attributes Name
type(tem_timer_type), intent(inout), optional :: me
timer object
integer, intent(in) :: timerHandle
Handle of the timer to stop
Calls
Called by
Source Code
  subroutine tem_stopTimer( me, timerHandle )
    ! -------------------------------------------------------------------- !
    !> timer object
    type(tem_timer_type), intent(inout), optional :: me
    !> Handle of the timer to stop
    integer, intent(in) :: timerHandle
    ! -------------------------------------------------------------------- !
    real(kind=rk) :: endTime
    ! -------------------------------------------------------------------- !
    endTime = mpi_wtime()
    if ( present(me) ) then
      if ( me%running%val(timerHandle) ) then
        me%running%val(timerHandle) = .false.
        me%duration%val(timerHandle) = me%duration%val(timerHandle) &
          &                            + endTime                    &
          &                            - me%tStart%val(timerHandle)
      end if
    else
      if ( timer%timedat%running%val(timerHandle) ) then
        timer%timedat%running%val(timerHandle) = .false.
        timer%timedat%duration%val(timerHandle) &
          &  = timer%timedat%duration%val(timerHandle) &
          &    + endTime                               &
          &    - timer%timedat%tStart%val(timerHandle)
      end if
    end if
  end subroutine tem_stopTimer
Call graph
tem_stoptimer calls mpi_wtime
tem_gettimerval calls tem_stoptimer
tem_simcontrol_syncupdate calls tem_stoptimer
tem_finalize calls tem_gettimerval
tem_getavetimerval calls tem_gettimerval
tem_getmaxtimerval calls tem_gettimerval
tem_getmintimerval calls tem_gettimerval
tem_getsumtimerval calls tem_gettimerval
tem_timer_dumplabeled calls tem_getmaxtimerval, tem_getmintimerval, tem_getsumtimerval
tem_timer_dump_glob calls tem_timer_dumplabeled