tem_commbuf_long_fintyped – Treelm
tem_commbuf_long_fintyped Subroutine
7 statements
Source File
private subroutine tem_commbuf_long_fintyped(me)
free the communication buffer allocated by the fillindexed routine again.
Arguments
Type Intent Optional Attributes Name
type(tem_longbuffer_type), intent(inout) :: me
Calls
Source Code
  subroutine tem_commbuf_long_fintyped(me)
    ! -------------------------------------------------------------------- !
    type(tem_longbuffer_type), intent(inout) :: me
    ! -------------------------------------------------------------------- !
    integer :: ierror
    ! -------------------------------------------------------------------- !
    me%nvals = 0
    call mpi_type_free(me%memindexed, ierror)
    call check_mpi_error(ierror,'free memindexed in tem_commbuf_long_fintyped')
  end subroutine tem_commbuf_long_fintyped
Call graph
tem_commbuf_long_fintyped calls mpi_type_free, check_mpi_error
check_mpi_error calls mpi_error_string, tem_abort
tem_abort calls mpi_abort