tem_simControl_load – Treelm
tem_simControl_load Subroutine
27 statements
Source File
public subroutine tem_simControl_load(me, conf, parent, key, solverAborts)
Load sim control settings from a configuration script.
The sim control should be started beforhand to ensure a sane setting of the current time. The main setting here, is the time_control, which is also attempted to be read directly, if there is no sim_control table provided. Solvers may pass solverAborts to load additional abort criteria that are to be loaded from the configuration.
Arguments
Type Intent Optional Attributes Name
type(tem_simControl_type), intent(inout) :: me
Simulation control parameters to set.
type(flu_State) :: conf
Handle to the configuration script to load the settings from.
integer, intent(in), optional :: parent
Potential parent table, in which the simulation control table is to be found.
character(len=*), optional :: key
Name for the simulation control table. Default is 'sim_control'.
class(tem_solverAborts_type), intent(inout), optional :: solverAborts
Solver specific abort criteria to load.
Calls
Called by
Source Code
  subroutine tem_simControl_load(me, conf, parent, key, solverAborts)
    ! -------------------------------------------------------------------- !
    !> Simulation control parameters to set.
    type(tem_simControl_type), intent(inout) :: me
    !> Handle to the configuration script to load the settings from.
    type(flu_state) :: conf
    !> Potential parent table, in which the simulation control table is to be
    !! found.
    integer, intent(in), optional :: parent
    !> Name for the simulation control table. Default is 'sim_control'.
    character(len=*), optional :: key
    !> Solver specific abort criteria to load.
    class(tem_solverAborts_type), intent(inout), optional :: solverAborts
    ! -------------------------------------------------------------------- !
    character(len=labelLen) :: loc_key
    integer :: thandle
    integer :: iErr
    ! -------------------------------------------------------------------- !
    loc_key = 'sim_control'
    if (present(key)) loc_key = key
    call aot_table_open( L       = conf,    &
      &                  parent  = parent,  &
      &                  thandle = thandle, &
      &                  key     = loc_key  )
    call aot_get_val(L       = conf,           &
      &              thandle = thandle,        &
      &              val     = me%delay_check, &
      &              key     = 'delay_check',  &
      &              default = .false.,        &
      &              ErrCode = iErr            )
    if (thandle /= 0) then
      ! There is a sim control table in the configuration.
      call tem_timeControl_load(me          = me%timeControl, &
        &                       conf        = conf,           &
        &                       parent      = thandle,        &
        &                       delay_check = me%delay_check  )
      call tem_abortCriteria_load( me     = me%abortCriteria,  &
        &                          conf   = conf,              &
        &                          parent = thandle,           &
        &                          solverAborts = solverAborts )
    else
      ! No sim control table found, try to load the time control table itself.
      call tem_timeControl_load(me%timeControl, conf, parent)
      me%abortCriteria = tem_abortCriteria_new()
    end if
    if (me%delay_check) then
      write(logUnit(1),*) 'Delaying status checks by one interval' &
        // '(delay_check=True).'
    end if
    call aot_table_close(L = conf, thandle = thandle)
    ! Overwrite the min of the simulation time range to point to the current
    ! simulation time.
    call tem_timeControl_start_at_sim(me = me%timeControl, now = me%now)
    call tem_addTimer( timerHandle = me%syncUpdate_timer, &
      &                timerName = 'tem_syncUpdate'       )
  end subroutine tem_simControl_load
Call graph
tem_simcontrol_load calls aot_get_val, aot_table_close, aot_table_open, tem_abortcriteria_load, tem_abortcriteria_new, tem_addtimer, tem_timecontrol_load, tem_timecontrol_start_at_sim
tem_abortcriteria_load calls aot_get_val, aot_table_close, aot_table_open, load, tem_convergence_load
tem_addtimer calls append, tem_appendtimers
tem_timecontrol_load calls aot_get_val, aot_table_close, aot_table_open, tem_time_default_zero, tem_time_load, tem_time_needs_reduce, tem_time_never
tem_timecontrol_start_at_sim calls tem_time_never
append calls append_da_label, append_da_veclabel
tem_appendtimers calls append
tem_convergence_load calls aot_table_close, aot_table_open, aot_table_length, tem_horizontalspacer, tem_load_convergenceheader
tem_time_load calls aot_get_val, aot_table_close, aot_table_open, mpi_wtime
append_da_label calls expand, sortedposofval
append_da_veclabel calls expand
tem_load_convergenceheader calls aot_get_val, aot_table_close, tem_timecontrol_load, tem_load_shape, tem_abort, tem_load_condition, tem_load_reduction_spatial, tem_timecontrol_dump, upper_to_lower
tem_load_general calls tem_simcontrol_load