tem_directChildren – Treelm
tem_directChildren Function
11 statements
Source File
public function tem_directChildren(TreeID) result(childrenIDs)
This function delivers the direct children in the full tree for a given tree ID
Arguments
Type Intent Optional Attributes Name
integer(kind=long_k), intent(in) :: TreeID
given treeID
Return Value integer(kind=long_k), (8)
Array for the treeIDs of the 8 direct children
Called by
Source Code
  function tem_directChildren( TreeID ) result(childrenIDs)
    ! ---------------------------------------------------------------------------
    !> given treeID
    integer(kind=long_k), intent(in) :: TreeID
    !> Array for the treeIDs of the 8 direct children
    integer(kind=long_k) :: childrenIDs(8)
    ! ---------------------------------------------------------------------------
    integer :: childCount
    integer(kind=long_k) :: off
    ! ---------------------------------------------------------------------------
    childrenIDs(:) = 0
    off = treeID * 8_long_k
    do childCount = 1,8
      childrenIDs(childCount) = off + int(childCount, kind=long_k)
    end do
  end function tem_directChildren
Call graph
add_ghostfromfiner calls tem_directchildren, add_ghostfromfiner
identify_elements calls tem_directchildren, identify_elements, create_allparentneighbors, identify_stencilneigh, single_process_element
tem_adapt_dump_newmesh calls tem_directchildren
tem_adddep_down calls tem_directchildren
tem_build_verticaldependencies calls tem_directchildren
build_levelelements calls identify_elements, identify_additionalneigh
create_allparentneighbors calls identify_elements, identify_stencilneigh
identify_additionalneigh calls identify_elements
identify_local_element calls add_ghostfromfiner
identify_stencilneigh calls identify_elements
tem_create_leveldesc calls tem_build_verticaldependencies, tem_find_allelements
tem_facedep_verticaldown calls tem_adddep_down
identify_halo calls identify_local_element
request_remotehalos calls create_allparentneighbors, identify_stencilneigh, identify_halo
single_process_element calls identify_local_element
tem_dimbydim_construction calls tem_create_leveldesc
tem_facedep_vertical calls tem_facedep_verticaldown
tem_find_allelements calls build_levelelements, identify_additionalneigh
communicate_elements calls request_remotehalos
tem_build_face_info calls tem_dimbydim_construction, tem_facedep_vertical