tem_shape_load_bcLabels – Treelm
tem_shape_load_bcLabels Subroutine
27 statements
Source File
private subroutine tem_shape_load_bcLabels(bcLabels, conf, thandle)
Loading bc labels from the config file, save those labels for further use.
Arguments
Type Intent Optional Attributes Name
character(len=labelLen), allocatable :: bcLabels(:)
bc labels
type(flu_State) :: conf
lua config handle
integer, intent(in) :: thandle
table handle from which to read
Calls
Called by
Source Code
  subroutine tem_shape_load_bcLabels( bcLabels, conf, thandle )
    !---------------------------------------------------------------------------
    !> bc labels
    character(len=labelLen), allocatable :: bcLabels(:)
    !> lua config handle
    type(flu_state) :: conf
    !> table handle from which to read
    integer, intent(in) :: thandle
    !---------------------------------------------------------------------------
    ! lua handles
    integer :: bcLabel_handle, nBCLabels
    character(len=labelLen) :: labelBuff
    integer :: iLabel, iErr
    !---------------------------------------------------------------------------
    call aot_table_open( L       = conf,            &
      &                  parent  = thandle,         &
      &                  thandle = bcLabel_handle,  &
      &                  key     = 'boundary' )
    ! get the number of property labels
    nBCLabels = aot_table_length( L = conf, thandle = bcLabel_handle )
    if ( nBCLabels == 0 ) then
      write(logUnit(3),*) ' Boundary label table is empty!'
      allocate( bcLabels(0) )
    else
      allocate( bcLabels( nBCLabels ) )
      do iLabel = 1, nBCLabels
        ! Now read in BC labels
        call aot_get_val( L       = conf,           &
          &               thandle = bcLabel_handle, &
          &               val     = labelBuff,      &
          &               ErrCode = iErr,           &
          &               pos     = iLabel          )
        ! set propBits according to property labels
        if( iErr == 0 ) then
          write(logUnit(3),*) '  name of boundary label: '//trim(labelBuff)
          bcLabels( iLabel ) = trim(labelBuff)
        else
          write(logUnit(3),*) '  failed to read boundary label!'
          bcLabels( iLabel ) = ''
        end if
      end do
    end if ! nBCLabels == 0
    call aot_table_close( L = conf, thandle = bcLabel_handle )
  end subroutine tem_shape_load_bcLabels
Call graph
tem_shape_load_bclabels calls aot_get_val, aot_table_close, aot_table_length, aot_table_open
tem_load_shape_single calls tem_shape_load_bclabels
tem_load_shape calls tem_load_shape_single, tem_load_shapes
tem_load_shapes calls tem_load_shape_single
load_spatial_parabol calls tem_load_shape
tem_load_convergenceheader calls tem_load_shape
tem_load_spacetime_single calls tem_load_shape, tem_load_spacetime_single
tem_load_trackingconfig calls tem_load_shape
tem_load_spacetime calls tem_load_spacetime_single
load_spatial_predefined calls load_spatial_parabol
tem_convergence_load calls tem_load_convergenceheader
tem_load_spacetime_table calls tem_load_spacetime_single
tem_load_tracking calls tem_load_trackingconfig