tem_PathOf – Treelm
tem_PathOf Function
10 statements
Source File
public elemental function tem_PathOf(TreeID) result(res)
This function returns the complete path through the tree from a given treeID to the root (all parents).
Arguments
Type Intent Optional Attributes Name
integer(kind=long_k), intent(in) :: TreeID
current treeID
Return Value type(tem_path_type)
resulting path
Called by
Source Code
  elemental function tem_PathOf( TreeID ) result(res)
    ! ---------------------------------------------------------------------------
    !> current treeID
    integer(kind=long_k), intent(in) :: TreeID
    !> resulting path
    type(tem_path_type) :: res
    ! ---------------------------------------------------------------------------
    res%level = 1
    res%Node(res%Level) = treeID
    do while (res%Node(res%Level) > 0)
      res%Level = res%Level + 1
      ! res%Node(res%Level) = (res%Node(res%Level-1)-1) / 8
      res%Node(res%Level) = ishft( (res%Node(res%Level-1)-1), -3 )
    end do
  end function tem_PathOf
Call graph
add_ghostfromfiner calls tem_pathof, add_ghostfromfiner
identify_elements calls tem_pathof, identify_elements, create_allparentneighbors, identify_stencilneigh, single_process_element
identify_local_element calls tem_pathof, add_ghostfromfiner
tem_find_allelements calls tem_pathof, build_levelelements, identify_additionalneigh
tem_findpath calls tem_pathof, tem_findpath
tem_init_surfdata calls tem_pathof
tem_posofid calls tem_pathof
tem_treeidcomparison calls tem_pathof
build_levelelements calls identify_elements, identify_additionalneigh
create_allparentneighbors calls identify_elements, identify_stencilneigh
evaluate_add_spacetime_scalarbycoordinate calls tem_posofid
evaluate_add_spacetime_vectorbycoordinate calls tem_posofid
evaluate_first_spacetime_scalarbycoordinate calls tem_posofid
evaluate_first_spacetime_vectorbycoordinate calls tem_posofid
identify_additionalneigh calls identify_elements
identify_halo calls identify_local_element
identify_stencilneigh calls identify_elements
setup_indices_spacetime calls tem_posofid
single_process_element calls identify_local_element
tem_cano_checkneigh calls tem_posofid
tem_cano_initsubtree calls tem_posofid
tem_cano_storepntsinsubtree calls tem_posofid
tem_create_leveldesc calls tem_find_allelements
tem_findelement calls tem_posofid, tem_findelement
tem_unify_vrtx calls tem_posofid
tem_update_surfpos calls tem_init_surfdata
request_remotehalos calls create_allparentneighbors, identify_halo, identify_stencilneigh
tem_calc_vrtx_coord calls tem_unify_vrtx
tem_dimbydim_construction calls tem_create_leveldesc
tem_shape_subtreefromgeominters calls tem_cano_checkneigh, tem_cano_initsubtree, tem_cano_storepntsinsubtree