tem_status_clear – Treelm
tem_status_clear Subroutine
4 statements
Source File
public subroutine tem_status_clear(me)
Clear (unset) all status bits.
Arguments
Type Intent Optional Attributes Name
type(tem_status_type), intent(inout) :: me
Status type to initialize.
Called by
Source Code
  subroutine tem_status_clear(me)
    ! --------------------------------------------------------------------------!
    !> Status type to initialize.
    type(tem_status_type), intent(inout) :: me
    ! --------------------------------------------------------------------------!
    me%bits = .false.
  end subroutine tem_status_clear
Call graph
tem_simcontrol_clearstat calls tem_status_clear
tem_simcontrol_start calls tem_status_clear
tem_simcontrol_steadystate_reset calls tem_status_clear
tem_start calls tem_simcontrol_start