tem_PathComparison – Treelm
tem_PathComparison Function
10 statements
Source File
public elemental function tem_PathComparison(left, right) result(relation)
Compare two Paths in the linearized tree Result: -1: left is lower than right 0: left is same than right 1: left is higher than right
Arguments
Type Intent Optional Attributes Name
type(tem_path_type), intent(in) :: left
candidate path
type(tem_path_type), intent(in) :: right
candidate path
Return Value integer
relation between the paths
Called by
Source Code
  elemental function tem_PathComparison( left, right ) result(relation)
    ! ---------------------------------------------------------------------------
    !> candidate path
    type(tem_path_type), intent(in) :: left
    !> candidate path
    type(tem_path_type), intent(in) :: right
    !> relation between the paths
    integer :: relation
    ! ---------------------------------------------------------------------------
    integer :: maxPathLen
    integer(kind=long_k) :: diff
    ! ---------------------------------------------------------------------------
    ! Find the greatest common level.
    maxPathLen = min(left%level-1, right%level-1)
    ! Difference of treeIDs on that level indicates the relation of the two
    ! paths.
    diff =  left%Node( left%Level - maxPathLen)                                &
      &  - right%Node(right%Level - maxPathLen)
    ! Normalize the relation.
    relation = int(diff / max(1_long_k, abs(diff)))
  end function tem_PathComparison
Call graph
isequal calls tem_pathcomparison
isgreater calls tem_pathcomparison
isgreaterorequal calls tem_pathcomparison
issmaller calls tem_pathcomparison
issmallerorequal calls tem_pathcomparison
isunequal calls tem_pathcomparison
tem_find_depproc calls tem_pathcomparison, tem_find_depproc_globsearch
tem_find_depproc_globsearch calls tem_pathcomparison
tem_init_surfdata calls tem_pathcomparison
tem_posofid calls tem_pathcomparison
tem_treeidcomparison calls tem_pathcomparison
operator(==) calls isequal
operator(SLASH=) calls isunequal
operator(gt) calls isgreater
operator(gt=) calls isgreaterorequal
operator(lt) calls issmaller
operator(lt=) calls issmallerorequal
evaluate_add_spacetime_scalarbycoordinate calls tem_posofid
evaluate_add_spacetime_vectorbycoordinate calls tem_posofid
evaluate_first_spacetime_scalarbycoordinate calls tem_posofid
evaluate_first_spacetime_vectorbycoordinate calls tem_posofid
identify_elements calls tem_find_depproc
setup_indices_spacetime calls tem_posofid
tem_cano_checkneigh calls tem_posofid
tem_cano_initsubtree calls tem_posofid
tem_cano_storepntsinsubtree calls tem_posofid
tem_findelement calls tem_posofid
tem_unify_vrtx calls tem_posofid
tem_update_surfpos calls tem_init_surfdata