tem_load_cylindricalWave – Treelm
tem_load_cylindricalWave Subroutine
10 statements
Source File
public subroutine tem_load_cylindricalWave(conf, thandle, me)
Load definition of the scalar cylindrical wave.
Arguments
Type Intent Optional Attributes Name
type(flu_State) :: conf
lua state type
integer, intent(in) :: thandle
aotus parent handle
type(tem_cylindricalWave_type), intent(out) :: me
Calls
Called by
Source Code
  subroutine tem_load_cylindricalWave(conf, thandle, me)
    ! ---------------------------------------------------------------------------
    !> lua state type
    type(flu_State) :: conf
    !> aotus parent handle
    integer, intent(in) :: thandle
    type(tem_cylindricalWave_type), intent(out) :: me
    ! ---------------------------------------------------------------------------
    integer :: iError
    ! ---------------------------------------------------------------------------
    write(logUnit(0),*)'ERROR: the cylindrical wave function is not available' &
      &                // ' in this'
    write(logUnit(0),*)'       executable, due to the compiler lacking ' &
      &                // 'support of'
    write(logUnit(0),*)'       Bessel functions!'
    call tem_abort()
  end subroutine tem_load_cylindricalWave
Call graph
tem_load_cylindricalwave calls tem_abort
tem_abort calls mpi_abort
load_spacetime_predefined calls tem_load_cylindricalwave, tem_load_spatial
load_spatial_predefined calls tem_load_cylindricalwave
tem_load_spacetime_single calls load_spacetime_predefined, tem_load_spacetime_single
tem_load_spatial calls load_spatial_predefined
tem_load_spacetime calls tem_load_spacetime_single, tem_load_spacetime_table
tem_load_ic calls tem_load_spatial
tem_load_spacetime_table calls tem_load_spacetime_single
tem_variable_load_single calls tem_load_spacetime
tem_variable_loadmapping_single calls tem_load_spacetime