tem_varSys_out_vector – Treelm
tem_varSys_out_vector Subroutine
11 statements
Source File
public subroutine tem_varSys_out_vector(me, conf, dumpVarPos)
Allows the output of array of varSys to lua out
Arguments
Type Intent Optional Attributes Name
type(tem_varSys_type), intent(in) :: me(:)
variable to write into the lua file
type(aot_out_type), intent(inout) :: conf
aotus type handling the output to the file in lua format
integer, intent(in), optional :: dumpVarPos(:)
Position of variables to dump
Calls
Called by
Source Code
  subroutine tem_varSys_out_vector(me, conf, dumpVarPos)
    ! ---------------------------------------------------------------------------
    !> variable to write into the lua file
    type(tem_varSys_type), intent(in) :: me(:)
    !> aotus type handling the output to the file in lua format
    type(aot_out_type), intent(inout) :: conf
    !> Position of variables to dump
    integer, optional, intent(in) :: dumpVarPos(:)
    ! ---------------------------------------------------------------------------
    integer :: iSys
    ! ---------------------------------------------------------------------------
    call aot_out_open_table( put_conf = conf, tname='varsys' )
    do iSys = 1, size(me)
      call tem_varSys_out_single( me         = me(iSys),   &
        &                         conf       = conf,       &
        &                         dumpVarPos = dumpVarPos, &
        &                         level      = 1           )
    end do
    call aot_out_close_table( put_conf = conf )
  end subroutine tem_varSys_out_vector
Call graph
tem_varsys_out_vector calls aot_out_close_table, aot_out_open_table, tem_varsys_out_single
tem_varsys_out_single calls aot_out_close_table, aot_out_open_table, aot_out_val
tem_varsys_out calls tem_varsys_out_vector
tem_varsys_dump_vector calls tem_varsys_out_vector
tem_varsys_dump calls tem_varsys_dump_vector
hvs_ascii_write_header calls tem_varsys_out
tem_restart_writeheader calls tem_varsys_out
hvs_ascii_init calls hvs_ascii_write_header
hvs_asciispatial_init calls hvs_ascii_write_header
tem_restart_closewrite calls tem_restart_writeheader
tem_restart_openwrite calls tem_restart_writeheader
tem_restart_readheader calls tem_varsys_dump
hvs_output_close calls tem_restart_closewrite
hvs_output_init calls hvs_ascii_init, hvs_asciispatial_init
hvs_output_open calls tem_restart_openwrite
tem_load_restart calls tem_restart_readheader