tem_ellipsoid_out_vec – Treelm
tem_ellipsoid_out_vec Subroutine
10 statements
Source File
private subroutine tem_ellipsoid_out_vec(me, conf)
Write out an array of ellipsoids in lua format
Arguments
Type Intent Optional Attributes Name
type(tem_ellipsoid_type), intent(in) :: me(:)
ellipsoid types to write out
type(aot_out_type), intent(inout) :: conf
Aotus type handling the output to the file in lua format
Calls
Called by
Source Code
  subroutine tem_ellipsoid_out_vec( me, conf )
    ! --------------------------------------------------------------------------
    !> ellipsoid types to write out
    type( tem_ellipsoid_type ), intent(in) :: me(:)
    !> Aotus type handling the output to the file in lua format
    type(aot_out_type), intent(inout) :: conf
    ! --------------------------------------------------------------------------
    ! counter
    integer :: i
    ! --------------------------------------------------------------------------
    ! create a table with name ellipsoid
    call aot_out_open_table( put_conf = conf, tname = 'object' )
    do i = 1, size(me)
      call tem_ellipsoid_out_scal( me(i), conf )
    end do
    call aot_out_close_table( put_conf = conf )
  end subroutine tem_ellipsoid_out_vec
Call graph
tem_ellipsoid_out_vec calls aot_out_close_table, aot_out_open_table, tem_ellipsoid_out_scal
tem_ellipsoid_out_scal calls aot_out_close_table, aot_out_open_table, aot_out_val
tem_ellipsoid_out calls tem_ellipsoid_out_vec
tem_shape_out_scal calls tem_ellipsoid_out
tem_shape_out calls tem_shape_out_scal, tem_shape_out_vec
tem_shape_out_vec calls tem_shape_out_scal
hvs_ascii_write_header calls tem_shape_out
tem_convergence_out_single calls tem_shape_out