tem_convergence_out_vector – Treelm
tem_convergence_out_vector Subroutine
10 statements
Source File
private subroutine tem_convergence_out_vector(me, conf)
Allows the output of array of convergence to lua out
Arguments
Type Intent Optional Attributes Name
type(tem_convergence_type), intent(in) :: me(:)
convergence to write into the lua file
type(aot_out_type), intent(inout) :: conf
aotus type handling the output to the file in lua format
Calls
Called by
Source Code
  subroutine tem_convergence_out_vector(me, conf)
    ! -------------------------------------------------------------------- !
    !> convergence to write into the lua file
    type(tem_convergence_type), intent(in) :: me(:)
    !> aotus type handling the output to the file in lua format
    type(aot_out_type), intent(inout) :: conf
    ! -------------------------------------------------------------------- !
    integer :: iConv
    ! -------------------------------------------------------------------- !
    call aot_out_open_table( put_conf = conf, tname='convergence' )
    do iConv = 1,size(me)
      call tem_convergence_out_single( me(iConv), conf, level=1 )
    end do
    call aot_out_close_table( put_conf = conf )
  end subroutine tem_convergence_out_vector
Call graph
tem_convergence_out_vector calls aot_out_close_table, aot_out_open_table, tem_convergence_out_single
tem_convergence_out_single calls aot_out_close_table, aot_out_open_table, aot_out_val, tem_condition_out, tem_reduction_spatial_out, tem_shape_out, tem_timecontrol_out
tem_condition_out calls tem_condition_out_single, tem_condition_out_vector
tem_reduction_spatial_out calls tem_reduction_spatial_out_single, tem_reduction_spatial_out_vector
tem_shape_out calls tem_shape_out_scal, tem_shape_out_vec
tem_timecontrol_out calls aot_out_close_table, aot_out_open_table, aot_out_val, tem_time_out
tem_condition_out_single calls aot_out_close_table, aot_out_open_table, aot_out_val
tem_condition_out_vector calls aot_out_close_table, aot_out_open_table, tem_condition_out_single
tem_reduction_spatial_out_single calls aot_out_val
tem_reduction_spatial_out_vector calls aot_out_val
tem_shape_out_scal calls aot_out_close_table, aot_out_open_table, aot_out_val, tem_canonicalnd_out, tem_cylinder_out, tem_ellipsoid_out, tem_sphere_out, tem_stlhead_out, tem_triangle_out, tem_shape_bclabel_out, tem_shape_level_out, tem_shape_proplabel_out
tem_shape_out_vec calls aot_out_close_table, aot_out_open_table, tem_shape_out_scal
tem_time_out calls aot_out_close_table, aot_out_open_table, aot_out_val
tem_convergence_out calls tem_convergence_out_vector
tem_convergence_dump_vector calls tem_convergence_out_vector
tem_convergence_dump calls tem_convergence_dump_vector