tem_FirstIdAtLevel – Treelm
tem_FirstIdAtLevel Function
5 statements
Source File
public elemental function tem_FirstIdAtLevel(level) result(res)
This function delivers the refinement level of a TreeID
The refinement level of a \ref treelmesh_module::treelmesh_type::treeid "treeID" is found by repeatedly computing the parents with the equation used in the [tem_ParentOf function] (@ref tem_parentatlevel) and counting the iterations, until the universal root is reached.
First TreeID in the complete tree on a given level
e.g. level 1: 1 .. 8 -> offset = 1 level 2: 9 .. 72 -> offset = 9 level 3: 73 .. -> offset = 73
A level offset is calculated by summing all the nodes of coarser levels. With a level count starting at \f$0\f$ on the coarsest level (the universal root node), this offset \f$s\f$ for a given level \f$L\f$ can be computed by the follwing equation: \f[ s = \sum\limits_{i=0}^{L-1} 8^i = \frac{8^{L} - 1}{7} \f]
Todo
calling to this function can be replaced by accessing array firstIdAtLevel which explicitly stores the results
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: level
level to check
Return Value integer(kind=long_k)
resulting first treeID
Called by
Source Code
  elemental function tem_FirstIdAtLevel( level ) result(res)
    ! ---------------------------------------------------------------------------
    !> level to check
    integer, intent(in) :: level
    !> resulting first treeID
    integer(kind=long_k) :: res
    ! ---------------------------------------------------------------------------
    res = ( 8_long_k**level - 1_long_k ) / 7_long_k
  end function tem_FirstIdAtLevel
Call graph
generate_treelm_cube calls tem_firstidatlevel
generate_treelm_elements calls tem_firstidatlevel
generate_treelm_line calls tem_firstidatlevel
generate_treelm_slice calls tem_firstidatlevel
load_bc_intern_1d calls tem_firstidatlevel
tem_calc_neighbors calls tem_firstidatlevel
tem_cano_checkneigh calls tem_firstidatlevel
tem_cano_storepntsinsubtree calls tem_firstidatlevel
tem_shape_initbylevels calls tem_firstidatlevel
init_tem_bc_prop calls load_bc_intern_1d
tem_init_elemlevels calls tem_calc_neighbors
tem_load_internal calls generate_treelm_cube, generate_treelm_elements, generate_treelm_line, generate_treelm_slice
tem_shape2subtree calls tem_shape_initbylevels, tem_shape_subtreefromgeominters
tem_shape_subtreefromgeominters calls tem_cano_checkneigh, tem_cano_storepntsinsubtree
load_tem calls tem_load_internal
tem_create_leveldesc calls tem_init_elemlevels
tem_create_subtree_of calls tem_shape2subtree
tem_create_subtree_of_st_funlist calls tem_create_subtree_of
tem_dimbydim_construction calls tem_create_leveldesc
tem_init_convergence calls tem_create_subtree_of
tem_init_tracker_subtree calls tem_create_subtree_of
tem_restart_readheader calls load_tem
tem_write_debugmesh calls tem_create_subtree_of