tem_build_horizontalDependencies – Treelm
tem_build_horizontalDependencies Subroutine
29 statements
Source File
public subroutine tem_build_horizontalDependencies(iStencil, levelDesc, tree, computeStencil)
Building neighor array
Todo
is neighID and stencil in element_type still used after this?
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: iStencil
Index of your neighbor list??
type(tem_levelDesc_type), intent(inout) :: levelDesc(tree%global%minLevel:)
Level descriptor for each level of your mesh (starting from minimum level).
type(treelmesh_type), intent(in) :: tree
Tree representation of your mesh.
type(tem_stencilHeader_type), intent(in) :: computeStencil
The stencil you build the horizontal dependencies for.
Calls
Called by
Source Code
  subroutine tem_build_horizontalDependencies( iStencil, levelDesc, tree,      &
    &                                          computeStencil )
    ! ---------------------------------------------------------------------------
    !> Tree representation of your mesh.
    type(treelmesh_type), intent(in) :: tree
    !> Level descriptor for each level of your mesh (starting from minimum
    !! level).
    type(tem_levelDesc_type), intent(inout) :: levelDesc(tree%global%minLevel:)
    !> Index of your neighbor list??
    integer, intent(in) :: iStencil
    !> The stencil you build the horizontal dependencies for.
    type(tem_stencilHeader_type), intent(in) :: computeStencil
    ! ---------------------------------------------------------------------------
    integer :: iLevel, iIndex
    integer :: nElemsWithNeigh
    ! ---------------------------------------------------------------------------
    write(logUnit(4),"(A,I0)") 'Build neighbor array for stencil: ', iStencil
    do iLevel = tree%global%minLevel,tree%global%maxLevel
      if( computeStencil%useAll .and. iStencil == 1 ) then
        ! JQ: is it possible the 1st stencil does not use all?
        ! all fluid and ghost and halo elements
        nElemsWithNeigh = levelDesc(iLevel)%nElems
      else if( computeStencil%useAll ) then
        ! @todo: the logic of this IF condition is not clear
        ! all fluid and ghost elements no halos
        nElemsWithNeigh =   levelDesc(iLevel)%nElems     &
          &               - levelDesc(iLevel)%elem%nElems( eT_halo )
      else
        ! only the fluids and ghosts??? that have the stencil iStencil
        nElemsWithNeigh = computeStencil%elemLvl( iLevel )%nVals
      end if
      write(logUnit(4),"(A,I2,A,I0)") ' level: ', iLevel, &
        &                             ', nElems to treat: ', nElemsWithNeigh
      ! allocate the nghElems array with the number of elements this stencil is
      ! used by
      allocate( levelDesc( iLevel )%neigh( iStencil )%            &
        &          nghElems( computeStencil%QQN, nElemsWithNeigh ) )
      iIndex = 0
      if( computeStencil%QQN > 0 ) then
        ! we init everything by default with 0 to find a bug as fast as possible
        levelDesc( iLevel )%neigh( iStencil )%nghElems(:,:) = 0
        if (computeStencil%useAll) then
!          write(logUnit(5),*) '     fluid elements  ', iIndex
          call tem_build_listHorizontalDep(                                    &
            &                  levelDesc      = levelDesc( iLevel ),           &
            &                  iStencil       = iStencil,                      &
            &                  posInSortElem  = levelDesc( iLevel )%totalPnt,  &
            &                  nElems         = nElemsWithNeigh,               &
            &                  iIndex         = iIndex )
        else ! stencil not using all elements
!          write(logUnit(5),*) '     not all elems   ', iIndex
          call tem_build_treeHorizontalDep(                                    &
            &         levelDesc      = levelDesc( iLevel ),                    &
            &         computeStencil = computeStencil,                         &
            &         iStencil       = iStencil,                               &
            &         list           = computeStencil%elemLvl( iLevel )%val,   &
            &         nElems         = nElemsWithNeigh,                        &
            &         tree           = tree                                    )
        end if
      end if
    end do ! iLevel
  end subroutine tem_build_horizontalDependencies
Call graph
tem_build_horizontaldependencies calls tem_build_listhorizontaldep, tem_build_treehorizontaldep
tem_build_listhorizontaldep calls tem_treeidintotal
tem_build_treehorizontaldep calls positionofval, tem_baryofid, tem_stencil_getheaderpos, tem_treeidintotal
positionofval calls posofval_label
tem_baryofid calls tem_coordofid, tem_elemsizelevel
tem_treeidintotal calls tem_etypeofid, tem_positioninsorted
posofval_label calls sortedposofval
tem_coordofid calls tem_levelof
tem_etypeofid calls positionofval
tem_create_leveldesc calls tem_build_horizontaldependencies
tem_dimbydim_construction calls tem_create_leveldesc
tem_build_face_info calls tem_dimbydim_construction