tem_stencilHeader_dump – Treelm
tem_stencilHeader_dump Subroutine
26 statements
Source File
private subroutine tem_stencilHeader_dump(me, nUnit)
Write element information to disk
Arguments
Type Intent Optional Attributes Name
type(tem_stencilHeader_type), intent(in) :: me
stencil header to be dumped
integer, intent(in), optional :: nUnit
Calls
Called by
Source Code
  subroutine tem_stencilHeader_dump( me, nUnit )
    ! -------------------------------------------------------------------- !
    !> stencil header to be dumped
    type( tem_stencilHeader_type ), intent(in) :: me
    integer, optional, intent(in) :: nUnit
    ! -------------------------------------------------------------------- !
    integer :: iDir
    integer :: dmpU
    ! -------------------------------------------------------------------- !
    ! Default to write to logUnit
    dmpU = logUnit(6)
    if (present(nUnit)) then
      dmpU = nUnit
    end if
    write(dmpU, *) '   Stencil  '
    write(dmpU, *) '     QQ   : ', me%QQ
    write(dmpU, *) '     QQN  : ', me%QQN
    if ( allocated(me%cxDir) ) then
      write(dmpU, *) '     Offset directions:'
      do iDir=1,me%QQN
        if ( allocated(me%cxDir) ) then
          write(dmpU, *) '       cxDir(:,', iDir, ') = ', &
            &            me%cxDir(:,iDir)
        end if
      end do
    end if
    write(dmpU, *) '     useAll: ', me%useAll
    if ( .not. me%useAll ) then
      write(dmpU, *) '     nElems: ', me%nElems
      if ( me%elem%nVals > 0 )                              &
        write(dmpU, *) '     Elems : '                      &
          &            //trim( tem_toStr(val = me%elem%val, &
          &                              sep = ','        ) )
    end if
  end subroutine tem_stencilHeader_dump
Call graph
tem_stencilheader_dump calls tem_tostr
tem_tostr calls tem_b2str, tem_b2str_arr, tem_d2str, tem_d2str_arr, tem_i2str, tem_i2str_arr, tem_l2str, tem_l2str_arr, tem_r2str, tem_r2str_arr
tem_stencil_dump calls tem_stencilheader_dump
tem_dimbydim_construction calls tem_stencil_dump
tem_element_dump calls tem_stencil_dump
tem_build_face_info calls tem_dimbydim_construction
tem_elemlist_dump calls tem_element_dump
build_levelelements calls tem_elemlist_dump
communicate_elements calls tem_elemlist_dump
tem_init_elemlevels calls tem_elemlist_dump