tem_simControl_out – Treelm
tem_simControl_out Subroutine
14 statements
Source File
public subroutine tem_simControl_out(me, conf, key)
Write sim control settings to a configuration script.
Arguments
Type Intent Optional Attributes Name
type(tem_simControl_type), intent(inout) :: me
The simulation control settings to write to a Lua table.
type(aot_out_type) :: conf
Handle for the Lua script to write to.
character(len=*), optional :: key
Name for the simulation control table. Default is sim_control.
Calls
Source Code
  subroutine tem_simControl_out(me, conf, key)
    ! -------------------------------------------------------------------- !
    !> The simulation control settings to write to a Lua table.
    type(tem_simControl_type), intent(inout) :: me
    !> Handle for the Lua script to write to.
    type(aot_out_type) :: conf
    !> Name for the simulation control table. Default is sim_control.
    character(len=*), optional :: key
    ! -------------------------------------------------------------------- !
    character(len=labelLen) :: loc_key
    ! -------------------------------------------------------------------- !
    loc_key = 'sim_control'
    if (present(key)) loc_key = key
    call aot_out_open_table( put_conf = conf,   &
      &                      tname    = loc_key )
    call tem_time_out( me   = me%now, &
      &                conf = conf    )
    call tem_timeControl_out( me   = me%timeControl, &
      &                       conf = conf            )
    call tem_abortCriteria_out( me   = me%abortCriteria, &
      &                         conf = conf              )
    call aot_out_val( put_conf = conf,           &
      &               val      = me%delay_check, &
      &               vname    = 'delay_check'   )
    call aot_out_close_table( put_conf = conf )
  end subroutine tem_simControl_out
Call graph
tem_simcontrol_out calls aot_out_close_table, aot_out_open_table, aot_out_val, tem_abortcriteria_out, tem_time_out, tem_timecontrol_out
tem_abortcriteria_out calls aot_out_close_table, aot_out_open_table, aot_out_val
tem_time_out calls aot_out_close_table, aot_out_open_table, aot_out_val
tem_timecontrol_out calls aot_out_close_table, aot_out_open_table, aot_out_val, tem_time_out