tem_setEffBoundingBox_fromSubTree – Treelm
tem_setEffBoundingBox_fromSubTree Subroutine
19 statements
Source File
private subroutine tem_setEffBoundingBox_fromSubTree(subTree, globalTree)
Calculate the real bounding box around the fluid domain
Arguments
Type Intent Optional Attributes Name
type(tem_subTree_type) :: subTree
subTree to get effective bounding cube from
type(treelmesh_type), intent(in) :: globalTree
corresponding global tree
Calls
Called by
Source Code
  subroutine tem_setEffBoundingBox_fromSubTree( subTree, globalTree )
    ! -------------------------------------------------------------------- !
    !> subTree to get effective bounding cube from
    type(tem_subTree_type)   :: subTree
    !> corresponding global tree
    type(treelmesh_type), intent(in) :: globalTree
    ! -------------------------------------------------------------------- !
    real(kind=rk) :: boundingBox(3,2)
    real(kind=rk) :: tBounding(3)
    integer :: iErr
    ! -------------------------------------------------------------------- !
    ! if the subTree equals to the global tree take over the settings
    if( subTree%useGlobalMesh )then
      subTree%global%effOrigin = globalTree%global%effOrigin
      subTree%global%effLength = globalTree%global%effLength
    else ! subTree is not equal to the global tree
      ! Calculate process-local bounding cube
      boundingBox = tem_GetLocalBoundingCube( subTree, globalTree )
      ! Exchange with neighbors
      call mpi_allreduce( boundingBox(:,1), tBounding, 3, rk_mpi, mpi_min, &
        &                 subTree%global%comm, iErr  )
      boundingBox(:,1) = tBounding
      call mpi_allreduce( boundingBox(:,2), tBounding, 3, rk_mpi, mpi_max, &
        &                 subTree%global%comm, iErr  )
      boundingBox(:,2) = tBounding
      ! Set the effective origin and length in the global subTree part
      subTree%global%effOrigin(:) = boundingBox(:,1)
      subTree%global%effLength(:) = boundingBox(:,2) -  boundingBox(:,1)
    end if
  end subroutine tem_setEffBoundingBox_fromSubTree
Call graph
tem_seteffboundingbox_fromsubtree calls tem_getlocalboundingcube, mpi_allreduce
tem_getlocalboundingcube calls tem_getlocalboundingcube_fromsubtree, tem_getlocalboundingcube_fromtree
tem_getlocalboundingcube_fromsubtree calls tem_vrtxcoordofid
tem_getlocalboundingcube_fromtree calls tem_vrtxcoordofid
tem_vrtxcoordofid calls tem_baryofid, tem_coordofid
tem_seteffboundingbox calls tem_seteffboundingbox_fromsubtree
tem_create_subtree_of calls tem_seteffboundingbox
tem_create_subtree_of_st_funlist calls tem_create_subtree_of
tem_init_convergence calls tem_create_subtree_of
tem_init_tracker_subtree calls tem_create_subtree_of
tem_write_debugmesh calls tem_create_subtree_of