tem_comm_dumpType – Treelm
tem_comm_dumpType Subroutine
9 statements
Source File
public subroutine tem_comm_dumpType(me, nUnit)
Write communication type data to nUnit (debugging routine)
Arguments
Type Intent Optional Attributes Name
type(tem_communication_type), intent(in) :: me
integer, intent(in) :: nUnit
Calls
Called by
Source Code
  subroutine tem_comm_dumpType(me, nUnit)
    ! -------------------------------------------------------------------- !
    type( tem_communication_type ), intent(in) :: me
    integer, intent(in) :: nUnit
    ! -------------------------------------------------------------------- !
    write(nUnit,*)        '----   Communication type    -----------------------'
    write(nUnit,"(A,I0)") '       nProcs: ', me%nProcs
    write(nUnit,"(A   )") '         proc: '//trim(tem_toStr( me%proc, ',' ))
    write(nUnit,"(A   )") '   nElemsProc: ' &
      &                   // trim(tem_toStr( me%nElemsProc, ',' ))
    write(nUnit,*)        '---------------------------------------------'
  end subroutine tem_comm_dumpType
Call graph
tem_comm_dumptype calls tem_tostr
tem_tostr calls tem_b2str, tem_b2str_arr, tem_d2str, tem_d2str_arr, tem_i2str, tem_i2str_arr, tem_l2str, tem_l2str_arr, tem_r2str, tem_r2str_arr
redefine_halos calls tem_comm_dumptype
communicate_elements calls redefine_halos
tem_find_allelements calls communicate_elements
tem_create_leveldesc calls tem_find_allelements