tem_log_for – Treelm
tem_log_for Subroutine
6 statements
Source File
private subroutine tem_log_for(me, level, msg)
Log a message in the given logger.
Arguments
Type Intent Optional Attributes Name
type(tem_logging_type), intent(in) :: me
integer, intent(in) :: level
character(len=*), intent(in) :: msg
Called by
Source Code
  subroutine tem_log_for( me, level, msg )
    ! ---------------------------------------------------------------------------
    !>
    type(tem_logging_type), intent(in) :: me
    !>
    integer, intent(in) :: level
    !>
    character(len=*), intent(in) :: msg
    ! ---------------------------------------------------------------------------
    write(me%funit(level),'(a)') msg
  end subroutine tem_log_for
Call graph
tem_log calls tem_log_for
tem_shape_initbylevels calls tem_log
tem_shape_load_level calls tem_log
tem_load_shape_single calls tem_shape_load_level
tem_shape2subtree calls tem_shape_initbylevels
tem_load_shape calls tem_load_shape_single
tem_create_subtree_of calls tem_shape2subtree
tem_load_shapes calls tem_load_shape_single