tem_build_faceLists – Treelm
tem_build_faceLists Subroutine
11 statements
Source File
private subroutine tem_build_faceLists(minLevel, maxLevel, nEligibleChildren, faces)
communicated, refined/coarsened and local faces.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: minLevel
Minimum level of your mesh.
integer, intent(in) :: maxLevel
Maximum level of your mesh.
integer, intent(in) :: nEligibleChildren
The number of eligible children for the vertical face dependency
type(tem_face_type), intent(inout) :: faces(minLevel:maxLevel)
The created face descriptor.
Calls
Called by
Source Code
  subroutine tem_build_faceLists( minLevel, maxLevel, nEligibleChildren, faces )
    ! --------------------------------------------------------------------------
    !> Minimum level of your mesh.
    integer, intent(in) :: minLevel
    !> Maximum level of your mesh.
    integer, intent(in) :: maxLevel
    !> The number of eligible children for the vertical face dependency
    integer, intent(in) :: nEligibleChildren
    !> The created face descriptor.
    type(tem_face_type),intent(inout) :: faces(minLevel:maxLevel)
    ! --------------------------------------------------------------------------
    integer :: iLevel
    ! --------------------------------------------------------------------------
    levelLoop: do iLevel = minLevel, maxLevel
      ! Build the list of compute faces for the current level
      call tem_build_computeList( faces(iLevel), nEligibleChildren )
    end do levelLoop
    ! Build the list of from finer faces for the current level
    call tem_build_fromFinerList( minLevel, maxLevel, nEligibleChildren, faces )
  end subroutine tem_build_faceLists
Call graph
tem_build_facelists calls tem_build_computelist, tem_build_fromfinerlist
tem_build_computelist calls tem_iscomputeface
tem_build_fromfinerlist calls tem_isfromfinerface
tem_iscomputeface calls tem_abort
tem_isfromfinerface calls tem_abort
tem_abort calls mpi_abort
tem_build_face_info calls tem_build_facelists