tem_logging_isActive_for – Treelm
tem_logging_isActive_for Function
6 statements
Source File
private function tem_logging_isActive_for(me, level) result(isActive)
Check if the given logger is active for the given level.
Arguments
Type Intent Optional Attributes Name
type(tem_logging_type), intent(in) :: me
integer, intent(in) :: level
Return Value logical
Called by
Source Code
  function tem_logging_isActive_for(me, level) result(isActive)
    ! ---------------------------------------------------------------------------
    !>
    type(tem_logging_type), intent(in) :: me
    !>
    integer, intent(in) :: level
    !>
    logical :: isActive
    ! ---------------------------------------------------------------------------
    isActive = (me%participating .and. (me%log_level >= level))
  end function tem_logging_isActive_for
Call graph
tem_logging_isactive calls tem_logging_isactive_for
build_levelelements calls tem_logging_isactive
communicate_elements calls tem_logging_isactive, redefine_halos
redefine_halos calls tem_logging_isactive
tem_init_elemlevels calls tem_logging_isactive
tem_reportstatus calls tem_logging_isactive
tem_create_leveldesc calls tem_init_elemlevels, tem_find_allelements
tem_find_allelements calls build_levelelements, communicate_elements
tem_dimbydim_construction calls tem_create_leveldesc