temporal_linear_for – Treelm
temporal_linear_for Function
12 statements
Source File
private pure function temporal_linear_for(me, t) result(res)
This function returns value of linear function which is defined by from_time, to_time, min_factor and max_factor
Arguments
Type Intent Optional Attributes Name
type(tem_linear_type), intent(in) :: me
temporal linear type
real(kind=rk), intent(in) :: t
current time
Return Value real(kind=rk)
return value of a function
Called by
Source Code
  pure function temporal_linear_for( me, t ) result(res)
    ! --------------------------------------------------------------------------
    !> temporal linear type
    type(tem_linear_type), intent(in) :: me
    !> current time
    real(kind=rk), intent(in) :: t
    !> return value of a function
    real(kind=rk) :: res
    ! --------------------------------------------------------------------------
    if (t <= me%from_time) then
      res = me%min_factor
    else if (t >= me%to_time) then
      res = me%max_factor
    else
      res = me%min_factor + (me%max_factor - me%min_factor)                    &
        & * (  (t - me%from_time) / (me%to_time - me%from_time) )
    end if
  end function temporal_linear_for
Call graph
tem_temporal_for calls temporal_linear_for
tem_spacetime_for_coord calls tem_temporal_for
tem_spacetime_for_treeids calls tem_temporal_for
tem_spacetime_scalar_for_index calls tem_temporal_for, tem_spacetime_for_coord
tem_spacetime_vector_for_coord calls tem_temporal_for
tem_spacetime_vector_for_index calls tem_temporal_for, tem_spacetime_vector_for_coord
tem_spacetime_vector_for_treeids calls tem_temporal_for
tem_spacetime_for calls tem_spacetime_for_coord, tem_spacetime_for_treeids, tem_spacetime_scalar_for_index, tem_spacetime_vector_for_coord, tem_spacetime_vector_for_index, tem_spacetime_vector_for_treeids, tem_spacetime_for_stcoord
tem_spacetime_for_stcoord calls tem_spacetime_for_coord
evaluate_add_spacetime_scalarbycoordinate calls tem_spacetime_for
evaluate_add_spacetime_scalarbytreeid calls tem_spacetime_for
evaluate_add_spacetime_vectorbycoordinate calls tem_spacetime_for
evaluate_add_spacetime_vectorbytreeid calls tem_spacetime_for
evaluate_first_spacetime_scalarbycoordinate calls tem_spacetime_for
evaluate_first_spacetime_scalarbytreeid calls tem_spacetime_for
evaluate_first_spacetime_vectorbycoordinate calls tem_spacetime_for
evaluate_first_spacetime_vectorbytreeid calls tem_spacetime_for
evaluate_foag_spacetime_scalarbycoordinate calls tem_spacetime_for
evaluate_foag_spacetime_scalarbytreeid calls tem_spacetime_for
evaluate_foag_spacetime_vectorbycoordinate calls tem_spacetime_for
evaluate_foag_spacetime_vectorbytreeid calls tem_spacetime_for
get_valofindex_add_scalar_spacetime calls tem_spacetime_for
get_valofindex_add_vector_spacetime calls tem_spacetime_for
get_valofindex_first_scalar_spacetime calls tem_spacetime_for
get_valofindex_first_vector_spacetime calls tem_spacetime_for
get_valofindex_foag_scalar_spacetime calls tem_spacetime_for
get_valofindex_foag_vector_spacetime calls tem_spacetime_for
tem_update_surfpos calls tem_spacetime_for