truncate_da_label – Treelm
truncate_da_label Subroutine
14 statements
Source File
public subroutine truncate_da_label(me)
truncate the array after the last valid entry and hence cut off the empty trailing empty entries
Arguments
Type Intent Optional Attributes Name
type(dyn_labelarray_type) :: me
Called by
Source Code
  subroutine truncate_da_label(me)
    !------------------------------------------------------------------------
    type(dyn_labelarray_type) :: me !< array to sorttruncate
    !------------------------------------------------------------------------
    character(len=labellen), allocatable :: swpval(:)
    integer, allocatable :: swpsort(:)
    !------------------------------------------------------------------------
    if (me%nvals < me%containersize) then
      allocate(swpval(me%nvals))
      allocate(swpsort(me%nvals))
      swpval = me%val(:me%nvals)
      swpsort = me%sorted(:me%nvals)
      call move_alloc(swpval, me%val)
      call move_alloc(swpsort, me%sorted)
      me%containersize = me%nvals
    end if
  end subroutine truncate_da_label
Call graph
truncate calls truncate_da_label, truncate_possible_variable
tem_create_varmap calls truncate
truncate_possible_variable calls truncate
hvs_output_init calls tem_create_varmap
tem_init_convergence calls tem_create_varmap
tem_init_depend calls tem_create_varmap
tem_init_tracker calls tem_create_varmap, hvs_output_init
tem_opvar_reduction_transient_init calls tem_create_varmap