truncate_ga_char – Treelm
truncate_ga_char Subroutine
13 statements
Source File
public subroutine truncate_ga_char(me)
Arguments
Type Intent Optional Attributes Name
type(grw_chararray_type) :: me
Called by
Source Code
  subroutine truncate_ga_char(me)
    !------------------------------------------------------------------------
    type(grw_chararray_type) :: me !< array to truncate
    !------------------------------------------------------------------------
    character, allocatable :: tarray(:)
    !------------------------------------------------------------------------
    integer :: ii
    !------------------------------------------------------------------------
    ! nothing to do if container size is not larger than the number of values
    ! in the array.
    if (me%containersize > me%nvals) then
      allocate(tarray(me%nvals))
      do ii = 1, me%nvals
        tarray(ii) = me%val(ii)
      end do
      call move_alloc(tarray, me%val)
      me%containersize = me%nvals
    end if
  end subroutine truncate_ga_char
Call graph
truncate calls truncate_ga_char, truncate_grwpoints, truncate_intpmatrixlsf
destroy_intpmatrixlsf calls truncate
setup_indices_spacetime calls truncate, tem_spatial_storeval
tem_opvar_fill_inputindex calls truncate
tem_opvar_setupindices calls truncate, tem_opvar_fill_inputindex
tem_spatial_scalar_storeval calls truncate
tem_spatial_vector_storeval calls truncate
truncate_grwpoints calls truncate
truncate_intpmatrixlsf calls truncate
destroy calls destroy_intpmatrixlsf
tem_spatial_storeval calls tem_spatial_scalar_storeval, tem_spatial_vector_storeval