truncate_element – Treelm
truncate_element Subroutine
20 statements
Source File
private subroutine truncate_element(me)
truncate all the lists in the element object
Arguments
Type Intent Optional Attributes Name
type(tem_element_type), intent(inout) :: me
element object
Calls
Called by
Source Code
  subroutine truncate_element( me )
    ! ---------------------------------------------------------------------------
    !> element object
    type( tem_element_type ), intent(inout) :: me
    ! ---------------------------------------------------------------------------
    integer :: iVal
    ! ---------------------------------------------------------------------------
    call truncate( me = me%tID )
    call truncate( me = me%property )
    call truncate( me = me%eType )
    call truncate( me = me%pntTID )
    call truncate( me = me%stencil )
    do iVal = 1, me%stencil%nVals
      call truncate( me = me%stencil%val( iVal ) )
    end do
    call truncate( me = me%neighID )
    do iVal = 1, me%neighID%nVals
      call truncate( me = me%neighID%val( iVal ) )
      deallocate( me%neighID%val(iVal)%sorted)
    end do
    call truncate( me = me%sourceProc )
    call truncate( me = me%haloNesting )
    call truncate( me = me%needsUpdate )
  end subroutine truncate_element
Call graph
truncate_element calls truncate
truncate calls truncate_ga_dynlong, truncate_element