upper_to_lower – Treelm
upper_to_lower Function
13 statements
Source File
public function upper_to_lower(string) result(result_string)
Function to turn all upper case characters to lower case.
The resulting string returned has the same length as the input string, and all upper case characters turned into lower case.
Arguments
Type Intent Optional Attributes Name
character(len=*) :: string
string to be converted
Return Value character(len=len)
converted string
Called by
Source Code
  function upper_to_lower(string) result(result_string)
    ! ---------------------------------------------------------------------------
    !> string to be converted
    character(len=*)    :: string
    !> converted string
    character(len=len(string))    :: result_string
    ! ---------------------------------------------------------------------------
    integer :: mm
    ! ---------------------------------------------------------------------------
    result_string=''
    do mm=1,len_trim(string)
      if( ('A' <= string(mm:mm)) .and. (string(mm:mm) <= 'Z') ) then
        result_string(mm:mm) = char(iachar(string(mm:mm))+32)
      else
        result_string(mm:mm)=string(mm:mm)
      end if
    end do
  end function upper_to_lower
Call graph
hvs_output_load calls upper_to_lower
hvs_vtk_config_load calls upper_to_lower
load_spacetime_predefined calls upper_to_lower
load_spatial_predefined calls upper_to_lower
tem_load_convergenceheader calls upper_to_lower
tem_load_onecanonicalnd calls upper_to_lower
tem_load_reduction_single calls upper_to_lower
tem_open calls upper_to_lower
tem_timer_dumplabeled calls upper_to_lower
tem_timer_loadconfig calls upper_to_lower
tem_variable_load_single calls upper_to_lower