viscSpongelayer_box2d_for_treeIDs – Treelm
viscSpongelayer_box2d_for_treeIDs Function
14 statements
Source File
private function viscSpongelayer_box2d_for_treeIDs(me, treeIds, tree, n) result(res)
This function calculates the sigma for the box viscosity spongelayer box2d and multiply with targetState 'viscosity' from treeid. This function is currectly used to define viscosity sponge in musubi.
Arguments
Type Intent Optional Attributes Name
type(tem_spongeLayer_box_type) :: me
Spacetime function to evaluate
integer(kind=long_k), intent(in) :: treeIds(n)
treeIds of elements in given level
type(treelmesh_type), intent(in) :: tree
global treelm mesh
integer, intent(in) :: n
Number of arrays to return
Return Value real(kind=rk), (n)
return value
Calls
Called by
Source Code
  function viscSpongelayer_box2d_for_treeIDs(me, treeIDs, tree, n)  &
    &                           result(res)
    !> Spacetime function to evaluate
    type(tem_spongeLayer_box_type) :: me
    !> Number of arrays to return
    integer, intent(in) :: n
    !> global treelm mesh
    type( treelmesh_type ), intent(in) ::tree
    !> treeIds of elements in given level
    integer(kind=long_k), intent(in) :: treeIds(n)
    !> return value
    real(kind=rk) :: res(n)
    ! --------------------------------------------------------------------------
    integer :: i
    real(kind=rk) :: res_i(1), coord(3,1)
    ! --------------------------------------------------------------------------
    do i = 1,n
      !barycentric coordinate
      coord(:,1) = tem_BaryOfId( tree, treeIds(i) )
      res_i = viscSpongeLayer_box2d_for_coord(me, coord, 1)
      res(i) = res_i(1)
    end do
  end function viscSpongelayer_box2d_for_treeIDs
Call graph
viscspongelayer_box2d_for_treeids calls tem_baryofid, viscspongelayer_box2d_for_coord
tem_baryofid calls tem_coordofid, tem_elemsizelevel
tem_coordofid calls tem_levelof
tem_viscspongelayer_box2d_for calls viscspongelayer_box2d_for_treeids
tem_spatial_for_coord calls tem_viscspongelayer_box2d_for
tem_spatial_for_treeids calls tem_viscspongelayer_box2d_for
tem_spatial_for calls tem_spatial_for_coord, tem_spatial_for_treeids, tem_spatial_scalar_for_index
tem_spatial_scalar_for_index calls tem_spatial_for_coord
tem_spacetime_for_coord calls tem_spatial_for
tem_spacetime_for_treeids calls tem_spatial_for
tem_spacetime_scalar_for_index calls tem_spatial_for
tem_spacetime_vector_for_coord calls tem_spatial_for
tem_spacetime_vector_for_index calls tem_spatial_for
tem_spacetime_vector_for_treeids calls tem_spatial_for
tem_spatial_scalar_storeval calls tem_spatial_for
tem_spatial_vector_storeval calls tem_spatial_for