append – Treelm
append Interface
4 statements
Source File
public interface append
append a value to the dynamic array and return its position.
Calls
Called by
Module Procedures
public subroutine append_da_label(me, val, length, pos, wasadded)
appending a value to the dynamic array
Read more…
Arguments
Type Intent Optional Attributes Name
type(dyn_labelarray_type) :: me
character(len=*), intent(in) :: val
integer, intent(in), optional :: length
optional length to expand the array
integer, intent(out), optional :: pos
position in the array, if the value is found
logical, intent(out), optional :: wasadded
flag to indicate, if val was newly added
public subroutine append_da_veclabel(me, val, length, pos, wasadded)
appending a sorted list of values to the dynamic array
Read more…
Arguments
Type Intent Optional Attributes Name
type(dyn_labelarray_type) :: me
character(len=*), intent(in) :: val(:)
integer, intent(in), optional :: length
optional length to expand the array
integer, intent(out), optional :: pos(:)
position in the array, the values are found at.
logical, intent(out), optional :: wasadded(:)
flag to indicate, if val was newly added
Call graph
append calls append_da_label, append_da_veclabel
append_da_label calls expand, sortedposofval
append_da_veclabel calls expand
expand calls expand_da_label
sortedposofval calls sortposofval_label
append_pointdata calls append
append_singlepnt2grwpoints calls append
append_vectorpnt2grwpoints calls append
setup_indices_spacetime calls append
sorttruncate_da_int calls append
sorttruncate_da_label calls append
sorttruncate_da_long calls append
sorttruncate_da_real calls append
tem_addtimer calls append
tem_appendtimers calls append
tem_cano_checkneigh calls append
tem_cano_initsubtree calls append
tem_cano_storepntsinsubtree calls append
tem_comm_createbuffer calls append
tem_commbuf_int_gatherindexed calls append
tem_commbuf_long_gatherindexed calls append
tem_commbuf_real_gatherindexed calls append
tem_shape_findelembybclabels calls append
tem_shape_initbylevels calls append
tem_shape_initpropelements calls append
tem_shape_subtreefromgeominters calls append
tem_timer_loadconfig calls append
tem_varsys_append_auxfieldvar calls append
tem_varsys_append_dervar calls append
tem_varsys_append_statevar calls append
tem_varsys_append_stfun_raw calls append
tem_varsys_append_stfunvar calls append
tem_varsys_load_single calls append