append – Treelm
append Interface
4 statements
Source File
public interface append
append a value to the dynamic array and return its position.
Calls
Module Procedures
public subroutine append_ga_int(me, val, length)
Arguments
Type Intent Optional Attributes Name
type(grw_intarray_type) :: me
integer, intent(in) :: val
integer, intent(in), optional :: length
optional length to expand the array
public subroutine append_ga_int_vec(me, val, length)
Arguments
Type Intent Optional Attributes Name
type(grw_intarray_type) :: me
integer, intent(in) :: val(:)
integer, intent(in), optional :: length
optional length to expand the array
Call graph
append calls append_ga_int, append_ga_int_vec
append_ga_int calls expand
append_ga_int_vec calls expand
expand calls expand_ga2d_real