append – Treelm
append Interface
3 statements
Source File
private interface append
Calls
Module Procedures
private subroutine append_element(me, tID, property, eType, pntTID, sourceProc, nNeighIDs, haloNesting, needsUpdate, stencilElements, pos, wasAdded)
append an element with its treeID, property, element type, position in Tree, position in boundary_ID, number of neighbors, procID
Arguments
Type Intent Optional Attributes Name
type(tem_element_type), intent(inout) :: me
element object
integer(kind=long_k), intent(in) :: tID
element treeID
integer(kind=long_k), intent(in), optional :: property
property associated with the treeID
integer, intent(in), optional :: eType
element type
integer, intent(in), optional :: pntTID
count of this type pointer of the treeID
integer, intent(in), optional :: sourceProc
the procID which is adding the element
integer, intent(in), optional :: nNeighIDs
number of neighbors
integer, intent(in), optional :: haloNesting
nesting level for haloElems
logical, intent(in), optional :: needsUpdate
type(tem_stencilElement_type), intent(in), optional :: stencilElements(:)
integer, intent(out) :: pos
position of treeID
logical, intent(out), optional :: wasAdded
Call graph
append calls append_element, append_ga_dynlong, append_ga_dynlong_vec
append_element calls append, init, tem_etypeisvalid
init calls init_ga2d_real
append_ga_dynlong calls expand
append_ga_dynlong_vec calls expand