append – Treelm
append Interface
4 statements
Source File
public interface append
append a value to the dynamic array and return its position.
Calls
Called by
Module Procedures
public subroutine append_ga_dynlong(me, val, length)
Arguments
Type Intent Optional Attributes Name
type(grw_dynlongarray_type) :: me
type(dyn_longarray_type), intent(in) :: val
integer, intent(in), optional :: length
optional length to expand the array
public subroutine append_ga_dynlong_vec(me, val, length)
Arguments
Type Intent Optional Attributes Name
type(grw_dynlongarray_type) :: me
type(dyn_longarray_type), intent(in) :: val(:)
integer, intent(in), optional :: length
optional length to expand the array
Call graph
append calls append_ga_dynlong, append_ga_dynlong_vec, append_element
append_ga_dynlong calls expand
append_ga_dynlong_vec calls expand
expand calls expand_ga_dynlong
add_all_virtual_children calls append, add_all_virtual_children
add_ghostfromfiner calls append, add_ghostfromfiner, tem_find_bcs_fromfiner
append_element calls append
appendghostdependency calls append
create_allparentneighbors calls append, identify_elements, identify_stencilneigh
depsource_append calls append
identify_elements calls append, create_allparentneighbors, identify_elements, single_process_element, identify_stencilneigh
identify_local_element calls append, add_all_virtual_children, add_ghostfromfiner
redefine_halos calls append, tem_stencil_communicate
request_remotehalos calls append, create_allparentneighbors, identify_halo, identify_stencilneigh
single_process_element calls append, identify_local_element
tem_adapt_dump_newmesh calls append
tem_find_bcs_fromfiner calls append
tem_halo_append calls append
tem_init_elemlevels calls append
tem_stencil_communicate calls append
build_levelelements calls identify_elements, identify_additionalneigh
communicate_elements calls redefine_halos, request_remotehalos, identify_lists
identify_additionalneigh calls identify_elements
identify_halo calls identify_local_element
identify_lists calls tem_halo_append
identify_stencilneigh calls identify_elements
tem_build_verticaldependencies calls appendghostdependency
tem_create_leveldesc calls tem_init_elemlevels, tem_build_verticaldependencies, tem_find_allelements
tem_dimbydim_construction calls tem_create_leveldesc
tem_find_allelements calls build_levelelements, communicate_elements, identify_additionalneigh, identify_lists
tem_build_face_info calls tem_dimbydim_construction