append – Treelm
append Interface
4 statements
Source File
public interface append
append a value to the dynamic array and return its position.
Calls
Module Procedures
private subroutine append_ga_cylinder(me, val, length)
Arguments
Type Intent Optional Attributes Name
type(grw_cylinderarray_type) :: me
type(tem_cylinder_type), intent(in) :: val
integer, intent(in), optional :: length
optional length to expand the array
private subroutine append_ga_cylinder_vec(me, val, length)
Arguments
Type Intent Optional Attributes Name
type(grw_cylinderarray_type) :: me
type(tem_cylinder_type), intent(in) :: val(:)
integer, intent(in), optional :: length
optional length to expand the array
Call graph
append calls append_ga_cylinder, append_ga_cylinder_vec
append_ga_cylinder calls expand
append_ga_cylinder_vec calls expand
expand calls expand_ga_cylinder