append – Treelm
append Interface
4 statements
Source File
public interface append
append a value to the dynamic array and return its position.
Calls
Module Procedures
public subroutine append_da_real(me, val, length, pos, wasadded)
appending a value to the dynamic array
Read more…
Arguments
Type Intent Optional Attributes Name
type(dyn_realarray_type) :: me
real(kind=rk), intent(in) :: val
integer, intent(in), optional :: length
optional length to expand the array
integer, intent(out), optional :: pos
position in the array, if the value is found
logical, intent(out), optional :: wasadded
flag to indicate, if val was newly added
public subroutine append_da_vecreal(me, val, length, pos, wasadded)
appending a sorted list of values to the dynamic array
Read more…
Arguments
Type Intent Optional Attributes Name
type(dyn_realarray_type) :: me
real(kind=rk), intent(in) :: val(:)
integer, intent(in), optional :: length
optional length to expand the array
integer, intent(out), optional :: pos(:)
position in the array, the values are found at.
logical, intent(out), optional :: wasadded(:)
flag to indicate, if val was newly added
Call graph
append calls append_da_real, append_da_vecreal
append_da_real calls expand, sortedposofval
append_da_vecreal calls expand
expand calls expand_da_label
sortedposofval calls sortposofval_label