append – Treelm
append Interface
4 statements
Source File
public interface append
Interface to append a single point or array of points to growing array of points
Calls
Module Procedures
private subroutine append_singlePnt2grwPoints(me, val)
This routine append a single point to growing array of points
Arguments
Type Intent Optional Attributes Name
type(tem_grwPoints_type), intent(inout) :: me
Growing array of points in each dimension
real(kind=rk), intent(in) :: val(3)
single point to append
private subroutine append_vectorPnt2grwPoints(me, val)
This routine append a array of points to growing array of points
Arguments
Type Intent Optional Attributes Name
type(tem_grwPoints_type), intent(inout) :: me
Growing array of points in each dimension
real(kind=rk), intent(in) :: val(:,:)
Array of points to append
Call graph
append calls append_singlepnt2grwpoints, append_vectorpnt2grwpoints, append_da_label, append_da_veclabel
append_singlepnt2grwpoints calls append
append_vectorpnt2grwpoints calls append, tem_abort
tem_abort calls mpi_abort
append_da_label calls expand, sortedposofval
append_da_veclabel calls expand