append – Treelm
append Interface
13 statements
Source File
public interface append
Todo
append position should be only int type. Only the value should be long_k
Calls
Called by
Module Procedures
private subroutine tem_appendIntList(firstEntry, entryPos)
append an entry at the end of the integer list If the first entry is zero, write into that one
Arguments
Type Intent Optional Attributes Name
type(tem_intList), pointer :: firstEntry
linked list of resulting elements building the neighbor
integer(kind=int_k), intent(in) :: entryPos
Add that element
private subroutine tem_appendLongList(firstEntry, entryPos)
append an entry at the end of the integer list If the first entry is zero, write into that one
Arguments
Type Intent Optional Attributes Name
type(tem_longList), pointer :: firstEntry
linked list of resulting elements building the neighbor
integer(kind=long_k), intent(in) :: entryPos
Add that element
private subroutine tem_appendInt1dArray(Array, Position, Value)
append an entry to an allocatable array 1d with single integer If the array is too small, reallocate with double size
Arguments
Type Intent Optional Attributes Name
integer(kind=int_k), intent(inout), allocatable :: Array(:)
array to append value to
integer, intent(in) :: Position
position the value is appended to
integer(kind=int_k), intent(in) :: Value
value to append
private subroutine tem_appendInt2dArray(Array, Position1, Position2, Value)
append an entry to an allocatable array 1d with single integer If the array is too small, reallocate with double size
Arguments
Type Intent Optional Attributes Name
integer(kind=int_k), intent(inout), allocatable :: Array(:,:)
array to append value to
integer, intent(in) :: Position1
integer, intent(in) :: Position2
integer(kind=int_k), intent(in) :: Value
value to append
private subroutine tem_appendIntLong1dArray(Array, Position, Value)
append an entry to an allocatable array 1d with long integer If the array is too small, reallocate with double size
Arguments
Type Intent Optional Attributes Name
integer(kind=long_k), intent(inout), allocatable :: Array(:)
array to append value to
integer, intent(in) :: Position
position the value is appended to
integer(kind=long_k), intent(in) :: Value
value to append
private subroutine tem_appendIntLong2dArray(Array, Position1, Position2, Value)
append an entry to an allocatable array 1d with long integer If the array is too small, reallocate with double size
Arguments
Type Intent Optional Attributes Name
integer(kind=long_k), intent(inout), allocatable :: Array(:,:)
array to append value to
integer(kind=long_k), intent(in) :: Position1
integer(kind=long_k), intent(in) :: Position2
integer(kind=long_k), intent(in) :: Value
value to append
private subroutine tem_appendSp1dArray(Array, Position, Value)
append an entry to an allocatable array 1d with single precision If the array is too small, reallocate with double size
Arguments
Type Intent Optional Attributes Name
real(kind=single_k), intent(inout), allocatable :: Array(:)
array to append value to
integer, intent(in) :: Position
position the value is appended to
real(kind=single_k), intent(in) :: Value
value to append
private subroutine tem_appendSp2dArray(Array, Position1, Position2, Value)
append an entry to an allocatable array 1d with single precision If the array is too small, reallocate with double size
Arguments
Type Intent Optional Attributes Name
real(kind=single_k), intent(inout), allocatable :: Array(:,:)
array to append value to
integer, intent(in) :: Position1
integer, intent(in) :: Position2
real(kind=single_k), intent(in) :: Value
value to append
private subroutine tem_appendDp1dArray(Array, Position, Value)
append an entry to an allocatable array 1d with double precision If the array is too small, reallocate with double size
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(inout), allocatable :: Array(:)
array to append value to
integer, intent(in) :: Position
position the value is appended to
real(kind=rk), intent(in) :: Value
value to append
private subroutine tem_appendDp2dArray(Array, Position1, Position2, Value)
append an entry to an allocatable array 1d with double precision If the array is too small, reallocate with double size
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(inout), allocatable :: Array(:,:)
array to append value to
integer, intent(in) :: Position1
integer, intent(in) :: Position2
real(kind=rk), intent(in) :: Value
value to append
private subroutine tem_appendIntLongArrayTo1dArray(Array, ArrayToAppend)
append an entry to an allocatable array 1d with long integer If the array is too small, reallocate with double size
Arguments
Type Intent Optional Attributes Name
integer(kind=long_k), intent(inout), allocatable :: Array(:)
array to append to
integer(kind=long_k), intent(in) :: ArrayToAppend(:)
array to append
Call graph
append calls tem_appenddp1darray, tem_appenddp2darray, tem_appendint1darray, tem_appendint2darray, tem_appendintlist, tem_appendintlong1darray, tem_appendintlong2darray, tem_appendintlongarrayto1darray, tem_appendlonglist, tem_appendsp1darray, tem_appendsp2darray
tem_calc_vrtx_coord calls append, tem_unify_vrtx
tem_findelement calls append, tem_findelement
tem_findpath calls append, tem_findpath
tem_unify_vrtx calls append
hvs_output_init calls tem_calc_vrtx_coord
tem_init_tracker calls hvs_output_init