changeType – Treelm
changeType Interface
4 statements
Source File
public interface changeType
Calls
Called by
Module Procedures
private subroutine changeType_element(me, elemPos, new_eType)
Arguments
Type Intent Optional Attributes Name
type(tem_element_type), intent(inout) :: me
integer, intent(in) :: elemPos
integer, intent(in) :: new_eType
private subroutine changeType_element_vec(me, nElems, elemPos, new_eType)
Arguments
Type Intent Optional Attributes Name
type(tem_element_type), intent(inout) :: me
integer, intent(in) :: nElems
integer, intent(in) :: elemPos(:)
integer, intent(in) :: new_eType
Call graph
changetype calls changetype_element, changetype_element_vec
changetype_element calls tem_etypeisvalid
changetype_element_vec calls tem_etypeisvalid
communicate_elements calls changetype, identify_lists, redefine_halos
identify_lists calls changetype
redefine_halos calls changetype
tem_find_allelements calls communicate_elements, identify_lists
tem_create_leveldesc calls tem_find_allelements
tem_dimbydim_construction calls tem_create_leveldesc