convert_to_Base64 – Treelm
convert_to_Base64 Interface
8 statements
Source File
public interface convert_to_Base64
Calls
Called by
Module Procedures
public subroutine real32_to_base64(indata, iplen, outfile)
this routine encodes data of type real32 to base64 format
Arguments
Type Intent Optional Attributes Name
real(kind=c_float), intent(in), target :: indata(iplen)
data to be encoded
integer, intent(in) :: iplen
size of data to be encoded
integer, intent(in) :: outfile
output file unit
public subroutine real64_to_base64(indata, iplen, outfile)
this routine encodes data of type real64 to base64 format
Arguments
Type Intent Optional Attributes Name
real(kind=c_double), intent(in), target :: indata(iplen)
data to be encoded
integer, intent(in) :: iplen
size of data to be encoded
integer, intent(in) :: outfile
output file unit
public subroutine char_to_base64(indata, iplen, outfile)
this routine encodes data of type char to base64 format
Arguments
Type Intent Optional Attributes Name
character(kind=c_char, len=1), intent(in), target :: indata(iplen)
data to be encoded
integer, intent(in) :: iplen
size of data to be encoded
integer, intent(in) :: outfile
output file unit
public subroutine int8_to_base64(indata, iplen, outfile)
this routine encodes data of type int8 to base64 format
Arguments
Type Intent Optional Attributes Name
integer(kind=c_int_least8_t), intent(in), target :: indata(iplen)
data to be encoded
integer, intent(in) :: iplen
size of data to be encoded
integer, intent(in) :: outfile
output file unit
public subroutine int32_to_base64(indata, iplen, outfile)
this routine encodes data of type int32 to base64 format
Arguments
Type Intent Optional Attributes Name
integer(kind=c_int), intent(in), target :: indata(iplen)
data to be encoded
integer, intent(in) :: iplen
size of data to be encoded
integer, intent(in) :: outfile
output file unit
public subroutine int64_to_base64(indata, iplen, outfile)
this routine encodes data of type int64 to base64 format
Arguments
Type Intent Optional Attributes Name
integer(kind=c_int_least64_t), intent(in), target :: indata(iplen)
data to be encoded
integer, intent(in) :: iplen
size of data to be encoded
integer, intent(in) :: outfile
output file unit
Call graph
convert_to_base64 calls char_to_base64, int32_to_base64, int64_to_base64, int8_to_base64, real32_to_base64, real64_to_base64
char_to_base64 calls convert_to_base64_single, encodeblock, encodeindex
int32_to_base64 calls convert_to_base64_single, encodeblock, encodeindex
int64_to_base64 calls convert_to_base64_single, encodeblock, encodeindex
int8_to_base64 calls convert_to_base64_single, encodeblock, encodeindex
real32_to_base64 calls convert_to_base64_single, encodeblock, encodeindex
real64_to_base64 calls convert_to_base64_single, encodeblock, encodeindex
convert_to_base64_single calls char_to_base64_single, int32_to_base64_single, int64_to_base64_single, int8_to_base64_single, real32_to_base64_single, real64_to_base64_single
char_to_base64_single calls encodeblock, encodeindex
int32_to_base64_single calls encodeblock, encodeindex
int64_to_base64_single calls encodeblock, encodeindex
int8_to_base64_single calls encodeblock, encodeindex
real32_to_base64_single calls encodeblock, encodeindex
real64_to_base64_single calls encodeblock, encodeindex
hvs_dump_debug_array calls convert_to_base64, hvs_vtk_write_meshdata
hvs_vtk_dump_data calls convert_to_base64
hvs_vtk_write_meshdata calls convert_to_base64