destroy – Treelm
destroy Interface
4 statements
Source File
private interface destroy
Calls
Module Procedures
private subroutine empty_stencil(me)
Delete all entries in the stencil
Arguments
Type Intent Optional Attributes Name
type(tem_stencilHeader_type), intent(out) :: me
stencil header type to empty
private subroutine destroy_stencilElement(me)
destroy stencil
Arguments
Type Intent Optional Attributes Name
type(tem_stencilElement_type), intent(out) :: me
stencil element type to be destroyed
Call graph
destroy calls destroy_stencilelement, empty_stencil, destroy_ga2d_real
empty_stencil calls destroy