destroy – Treelm
destroy Interface
3 statements
Source File
public interface destroy
destroy the dynamic array
Calls
Called by
Module Procedures
public subroutine destroy_da_label(me)
destruction of a dynamic array
Read more…
Arguments
Type Intent Optional Attributes Name
type(dyn_labelarray_type), intent(inout) :: me
Call graph
destroy calls destroy_da_label
sorttruncate_da_int calls destroy
sorttruncate_da_label calls destroy
sorttruncate_da_long calls destroy
sorttruncate_da_real calls destroy
tem_comm_createbuffer calls destroy
tem_comm_destroy calls destroy
tem_commbuf_int_gatherindexed calls destroy
tem_commbuf_long_gatherindexed calls destroy
tem_commbuf_real_gatherindexed calls destroy
sorttruncate calls sorttruncate_da_long, sorttruncate_da_int, sorttruncate_da_real, sorttruncate_da_label