destroy – Treelm
destroy Interface
3 statements
Source File
public interface destroy
destroy the dynamic array
Calls
Called by
Module Procedures
public subroutine destroy_ga_dynlong(me)
Arguments
Type Intent Optional Attributes Name
type(grw_dynlongarray_type), intent(inout) :: me
Call graph
destroy calls destroy_ga_dynlong
tem_halo_destroy calls destroy
identify_lists calls tem_halo_destroy
tem_cleanupdependencyarrays calls tem_halo_destroy
communicate_elements calls identify_lists
tem_create_leveldesc calls tem_cleanupdependencyarrays, tem_find_allelements
tem_find_allelements calls identify_lists, tem_cleanupdependencyarrays, communicate_elements
tem_dimbydim_construction calls tem_create_leveldesc