destroy – Treelm
destroy Interface
3 statements
Source File
private interface destroy
Calls
Module Procedures
private subroutine destroy_intpMatrixLSF(me)
Arguments
Type Intent Optional Attributes Name
type(tem_intpMatrixLSF_type), intent(inout) :: me
Call graph
destroy calls destroy_intpmatrixlsf, destroy_ga2d_real
destroy_intpmatrixlsf calls destroy, truncate
truncate calls truncate_ga_char