EncodeBlock – Treelm
EncodeBlock Interface
10 statements
Source File
interface
Convert one block of input (3 Bytes) into its base64 representation (4 Bytes).
Called by
public function EncodeBlock(input, output, iplen, oplen) bind(c, name='encodeblock')
Arguments
Type Intent Optional Attributes Name
type(c_ptr), value :: input
input character stream in ascii
type(c_ptr), value :: output
output character stream in base64
integer(kind=c_int), intent(in), value :: iplen
length of the input stream
integer(kind=c_int), value :: oplen
length of the output stream
Return Value integer(kind=c_int)
Result, indicating the status of encode
Call graph
char_to_base64 calls encodeblock, convert_to_base64_single
char_to_base64_single calls encodeblock
int32_to_base64 calls encodeblock, convert_to_base64_single
int32_to_base64_single calls encodeblock
int64_to_base64 calls encodeblock, convert_to_base64_single
int64_to_base64_single calls encodeblock
int8_to_base64 calls encodeblock, convert_to_base64_single
int8_to_base64_single calls encodeblock
real32_to_base64 calls encodeblock, convert_to_base64_single
real32_to_base64_single calls encodeblock
real64_to_base64 calls encodeblock, convert_to_base64_single
real64_to_base64_single calls encodeblock
convert_to_base64 calls char_to_base64, int32_to_base64, int64_to_base64, int8_to_base64, real32_to_base64, real64_to_base64
convert_to_base64_single calls char_to_base64_single, int32_to_base64_single, int64_to_base64_single, int8_to_base64_single, real32_to_base64_single, real64_to_base64_single
hvs_dump_debug_array calls convert_to_base64, hvs_vtk_write_meshdata
hvs_vtk_dump_data calls convert_to_base64
hvs_vtk_write_meshdata calls convert_to_base64