EncodeIndex – Treelm
EncodeIndex Interface
11 statements
Source File
interface
Interface to convert ascii to binary base64 encoder
Called by
public function EncodeIndex(input, output, iplen, ind, ipindex) bind(c, name='EncodeIndex')
Arguments
Type Intent Optional Attributes Name
type(c_ptr), value :: input
input character stream in ascii
type(c_ptr), value :: output
output character stream in base64
integer(kind=c_int), intent(in), value :: iplen
length of the input stream
integer(kind=c_int), value :: ind
current length
integer(kind=c_int), value :: ipindex
current length
Return Value integer(kind=c_int)
Result, indicating the status of encode
Call graph
char_to_base64 calls encodeindex, convert_to_base64_single
char_to_base64_single calls encodeindex
int32_to_base64 calls encodeindex, convert_to_base64_single
int32_to_base64_single calls encodeindex
int64_to_base64 calls encodeindex, convert_to_base64_single
int64_to_base64_single calls encodeindex
int8_to_base64 calls encodeindex, convert_to_base64_single
int8_to_base64_single calls encodeindex
real32_to_base64 calls encodeindex, convert_to_base64_single
real32_to_base64_single calls encodeindex
real64_to_base64 calls encodeindex, convert_to_base64_single
real64_to_base64_single calls encodeindex
convert_to_base64 calls char_to_base64, int32_to_base64, int64_to_base64, int8_to_base64, real32_to_base64, real64_to_base64
convert_to_base64_single calls char_to_base64_single, int32_to_base64_single, int64_to_base64_single, int8_to_base64_single, real32_to_base64_single, real64_to_base64_single
hvs_dump_debug_array calls convert_to_base64, hvs_vtk_write_meshdata
hvs_vtk_dump_data calls convert_to_base64
hvs_vtk_write_meshdata calls convert_to_base64
hvs_output_open calls hvs_vtk_write_meshdata
hvs_output_write calls hvs_vtk_dump_data