expand – Treelm
expand Interface
3 statements
Source File
public interface expand
increase the size of the container for the array.
Calls
Called by
Module Procedures
public subroutine expand_da_label(me, increment, length)
expanding the dynamic array
Read more…
Arguments
Type Intent Optional Attributes Name
type(dyn_labelarray_type) :: me
integer, optional :: increment
integer, intent(in), optional :: length
optional length to expand the array
Call graph
expand calls expand_da_label
append_da_int calls expand
append_da_label calls expand
append_da_long calls expand
append_da_real calls expand
append_da_vecint calls expand
append_da_veclabel calls expand
append_da_veclong calls expand
append_da_vecreal calls expand
append calls append_da_long, append_da_veclong, append_da_int, append_da_vecint, append_da_real, append_da_vecreal, append_da_label, append_da_veclabel