expand – Treelm
expand Interface
3 statements
Source File
private interface expand
increase the size of the container for the array.
Calls
Called by
Module Procedures
private subroutine expand_ga_ellipsoid(me, pos, length)
Arguments
Type Intent Optional Attributes Name
type(grw_ellipsoidarray_type) :: me
integer, intent(in), optional :: pos
integer, intent(in), optional :: length
optional length to expand the array
Call graph
expand calls expand_ga_ellipsoid
append_ga_ellipsoid calls expand
append_ga_ellipsoid_vec calls expand
placeat_ga_ellipsoid calls expand
placeat_ga_ellipsoid_vec calls expand
append calls append_ga_ellipsoid, append_ga_ellipsoid_vec
placeat calls placeat_ga_ellipsoid, placeat_ga_ellipsoid_vec