expand – Treelm
expand Interface
3 statements
Source File
private interface expand
increase the size of the container for the array.
Calls
Called by
Module Procedures
private subroutine expand_ga_matrix(me, pos, length)
Arguments
Type Intent Optional Attributes Name
type(grw_matrixarray_type) :: me
integer, intent(in), optional :: pos
integer, intent(in), optional :: length
optional length to expand the array
Call graph
expand calls expand_ga_matrix
append_ga_matrix calls expand
append_ga_matrix_vec calls expand
placeat_ga_matrix calls expand
placeat_ga_matrix_vec calls expand
append calls append_ga_matrix, append_ga_matrix_vec
placeat calls placeat_ga_matrix, placeat_ga_matrix_vec