expand – Treelm
expand Interface
3 statements
Source File
public interface expand
increase the size of the container for the array.
Calls
Called by
Module Procedures
public subroutine expand_ga_dynlong(me, pos, length)
Arguments
Type Intent Optional Attributes Name
type(grw_dynlongarray_type) :: me
integer, intent(in), optional :: pos
integer, intent(in), optional :: length
optional length to expand the array
Call graph
expand calls expand_ga_dynlong
append_ga_dynint calls expand
append_ga_dynint_vec calls expand
append_ga_dynlong calls expand
append_ga_dynlong_vec calls expand
append_ga_grw_stencilelement calls expand
append_ga_grw_stencilelement_vec calls expand
placeat_ga_dynint calls expand
placeat_ga_dynint_vec calls expand
placeat_ga_dynlong calls expand
placeat_ga_dynlong_vec calls expand
placeat_ga_grw_stencilelement calls expand
placeat_ga_grw_stencilelement_vec calls expand
append calls append_ga_dynint, append_ga_dynint_vec, append_ga_dynlong, append_ga_dynlong_vec, append_ga_grw_stencilelement, append_ga_grw_stencilelement_vec
placeat calls placeat_ga_dynint, placeat_ga_dynint_vec, placeat_ga_dynlong, placeat_ga_dynlong_vec, placeat_ga_grw_stencilelement, placeat_ga_grw_stencilelement_vec