init – Treelm
init Interface
3 statements
Source File
public interface init
initialize the dynamic array
Calls
Called by
Module Procedures
public subroutine init_da_label(me, length)
initialization of a dynamic array
Read more…
Arguments
Type Intent Optional Attributes Name
type(dyn_labelarray_type), intent(out) :: me
integer, intent(in), optional :: length
Call graph
init calls init_da_label, init_possible_variable
init_possible_variable calls init
sorttruncate_da_int calls init
sorttruncate_da_label calls init
sorttruncate_da_long calls init
sorttruncate_da_real calls init
tem_create_varmap calls init
tem_varsys_init calls init
tem_varsys_load_single calls init
sorttruncate calls sorttruncate_da_long, sorttruncate_da_int, sorttruncate_da_real, sorttruncate_da_label
tem_varsys_load calls tem_varsys_load_single, tem_varsys_load_vector
hvs_output_init calls tem_create_varmap
tem_init_convergence calls tem_create_varmap
tem_init_depend calls tem_create_varmap
tem_init_tracker calls tem_create_varmap, hvs_output_init
tem_opvar_reduction_transient_init calls tem_create_varmap
tem_varsys_load_vector calls tem_varsys_load_single
tem_restart_readheader calls tem_varsys_load
tem_load_restart calls tem_restart_readheader