init – Treelm
init Interface
4 statements
Source File
private interface init
Calls
Module Procedures
private subroutine init_stencilHeader(me, QQN, QQ, nElems, useAll, nDims, label, cxDir)
initialize stencil
Arguments
Type Intent Optional Attributes Name
type(tem_stencilHeader_type), intent(out) :: me
stencil header to be initialized
integer, intent(in) :: QQN
number of discrete velocities in the model (without the center one)
integer, intent(in), optional :: QQ
number of discrete velocities in the model (incl. the center one)
integer, intent(in), optional :: nElems
The number of elements to use this stencil for
logical, intent(in), optional :: useAll
use this stencil for all elements?
integer, intent(in), optional :: nDims
character(len=*), intent(in), optional :: label
integer, intent(in), optional :: cxDir(:,:)
private subroutine init_stencilElement(me, QQN, headerPos, tIDpos)
initialize stencil
Arguments
Type Intent Optional Attributes Name
type(tem_stencilElement_type), intent(out) :: me
stencil element type to be initialized
integer, intent(in) :: QQN
number of discrete velocities in the model (without the center one)
integer, intent(in), optional :: headerPos
integer, intent(in), optional :: tIDpos(:)
Call graph
init calls init_stencilelement, init_stencilheader, init_ga2d_real
init_stencilheader calls init, tem_identify_inversedirections, tem_stencil_createcxcx