init – Treelm
init Interface
3 statements
Source File
public interface init
initialize the dynamic array
Calls
Called by
Module Procedures
public subroutine init_ga_dynlong(me, length)
Arguments
Type Intent Optional Attributes Name
type(grw_dynlongarray_type), intent(out) :: me
integer, intent(in), optional :: length
Call graph
init calls init_ga_dynlong
tem_halo_init calls init
identify_lists calls tem_halo_init
communicate_elements calls identify_lists
tem_find_allelements calls identify_lists, communicate_elements
tem_create_leveldesc calls tem_find_allelements