operator (.fne.) – Treelm
operator (.fne.) Interface
4 statements
Source File
private interface operator (.fne.)
Calls
Module Procedures
private elemental function notEqual(a, b) result(res)
Relational operator to test the not-equality of floating point numbers.
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: a
Floating point value to be compared.
real(kind=rk), intent(in) :: b
Floating point value to be compared.
Return Value logical
The result is a logical value indicating whether the operands are not equal to within numerical precision.
private pure function notEqual_array(a, b) result(res)
Relational operator to test the not-equality of two floating point arrays.
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: a(:)
Floating point array to be compared.
real(kind=rk), intent(in) :: b(:)
Floating point array to be compared.
Return Value logical
The result is a logical value indicating whether the operands are not equal to within numerical precision.
Call graph
operator (.fne.) calls notequal, notequal_array
notequal calls equal
notequal_array calls equal_array
equal_array calls equal