placeat – Treelm
placeat Interface
4 statements
Source File
public interface placeat
Calls
Module Procedures
public subroutine placeat_singlega2d_char(me, val, pos1, pos2, length)
append a single value to the growing 2d array.
Arguments
Type Intent Optional Attributes Name
type(grw_char2darray_type) :: me
array to append the value to
character(len=1), intent(in) :: val
value to append
integer, intent(in) :: pos1
position in first dimension (cannot grow)
integer, intent(in) :: pos2
position in second dimension (can grow)
integer, intent(in), optional :: length
optional length to expand the array
public subroutine placeat_arrayga2d_char(me, val, pos2, length)
append an array of values to the growing 2d array.
Arguments
Type Intent Optional Attributes Name
type(grw_char2darray_type) :: me
array to append the value to
character(len=1), intent(in) :: val(:)
array of values to append
integer, intent(in) :: pos2
position in second dimension (can grow)
integer, intent(in), optional :: length
optional length to expand the array
Call graph
placeat calls placeat_arrayga2d_char, placeat_singlega2d_char
placeat_arrayga2d_char calls expand
placeat_singlega2d_char calls expand
expand calls expand_ga2d_real