placeat – Treelm
placeat Interface
4 statements
Source File
public interface placeat
insert an element at a given position
Calls
Module Procedures
public subroutine placeat_ga_dynlong(me, val, pos, length)
adds the value to a given position inside the growing array.
Read more…
Arguments
Type Intent Optional Attributes Name
type(grw_dynlongarray_type) :: me
type(dyn_longarray_type), intent(in) :: val
integer, intent(in) :: pos
integer, intent(in), optional :: length
optional length to expand the array
public subroutine placeat_ga_dynlong_vec(me, val, pos, length)
adds the values starting from a given position inside the growing array.
Read more…
Arguments
Type Intent Optional Attributes Name
type(grw_dynlongarray_type) :: me
type(dyn_longarray_type), intent(in) :: val(:)
integer, intent(in) :: pos
integer, intent(in), optional :: length
optional length to expand the array
Call graph
placeat calls placeat_ga_dynlong, placeat_ga_dynlong_vec
placeat_ga_dynlong calls expand
placeat_ga_dynlong_vec calls expand
expand calls expand_ga_dynlong