positionofval – Treelm
positionofval Interface
3 statements
Source File
public interface positionofval
return the position of a given value in the array val, which is what you usually want to know. it is the index of a given value
Calls
Module Procedures
public function posofval_int(me, val, nextifnotfound, lower, upper) result(pos)
the actual position of a given value in the dynamic array
Read more…
Arguments
Type Intent Optional Attributes Name
type(dyn_intarray_type), intent(in) :: me
integer, intent(in) :: val
logical, intent(in), optional :: nextifnotfound
flag to indicate, if the position of the next entry in the sorted list should be returned instead, if val is not found.
integer, intent(in), optional :: lower
integer, intent(in), optional :: upper
Return Value integer
Call graph
positionofval calls posofval_int
posofval_int calls sortedposofval
sortedposofval calls sortposofval_label