resize – Treelm
resize Interface
8 statements
Source File
public interface resize
Calls
Module Procedures
private subroutine tem_resizeInt1dArray(Array, Newsize)
append an entry to an allocatable array 1d with integer If the array is too small, reallocate with double size
Arguments
Type Intent Optional Attributes Name
integer(kind=int_k), intent(inout), allocatable :: Array(:)
array to resize
integer, intent(in) :: Newsize
new size of the array
private subroutine tem_resizeInt2dArray(Array, Newsize1, Newsize2)
append an entry to an allocatable array 2d with integer If the array is too small, reallocate with double size
Arguments
Type Intent Optional Attributes Name
integer(kind=int_k), intent(inout), allocatable :: Array(:,:)
array to resize
integer, intent(in) :: Newsize1
first new size
integer, intent(in) :: Newsize2
second new size
private subroutine tem_resizeIntLong1dArray(Array, Newsize)
append an entry to an allocatable array 1d with long integer If the array is too small, reallocate with double size
Arguments
Type Intent Optional Attributes Name
integer(kind=long_k), intent(inout), allocatable :: Array(:)
array to resize
integer, intent(in) :: Newsize
new size of the array
private subroutine tem_resizeIntLong2dArray(Array, Newsize1, Newsize2)
append an entry to an allocatable array 2d with long integer If the array is too small, reallocate with double size
Arguments
Type Intent Optional Attributes Name
integer(kind=long_k), intent(inout), allocatable :: Array(:,:)
array to resize
integer, intent(in) :: Newsize1
first new size
integer, intent(in) :: Newsize2
second new size
private subroutine tem_resizeDp1dArray(Array, Newsize)
append an entry to an allocatable array 1d with integer If the array is too small, reallocate with double size
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(inout), allocatable :: Array(:)
array to resize
integer, intent(in) :: Newsize
new size of the array
private subroutine tem_resizeDp2dArray(Array, Newsize1, Newsize2)
append an entry to an allocatable array 2d with integer If the array is too small, reallocate with double size
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(inout), allocatable :: Array(:,:)
array to resize
integer, intent(in) :: Newsize1
first new size
integer, intent(in) :: Newsize2
second new size
Call graph
resize calls tem_resizedp1darray, tem_resizedp2darray, tem_resizeint1darray, tem_resizeint2darray, tem_resizeintlong1darray, tem_resizeintlong2darray