sorttruncate – Treelm
sorttruncate Interface
3 statements
Source File
public interface sorttruncate
fix the dynamic array, meaning: store the array in the sorted order and cut off the trailing empty entries
Calls
Module Procedures
public subroutine sorttruncate_da_label(me)
fixing the dynamic array
Read more…
Arguments
Type Intent Optional Attributes Name
type(dyn_labelarray_type) :: me
Call graph
sorttruncate calls sorttruncate_da_label
sorttruncate_da_label calls append, destroy, init
append calls append_da_label, append_da_veclabel
destroy calls destroy_da_label
init calls init_da_label
append_da_label calls expand, sortedposofval
append_da_veclabel calls expand