sortedposofval – Treelm
sortedposofval Interface
3 statements
Source File
public interface sortedposofval
return the position of a given value in the list 'sorted'. this is mainly for internal usage. the sorted list is only a pointer list to the actual values thus, in order to get the index of a given value, you need to look up the entry in the sorted list. this is done by the positionofval routine
Calls
Called by
Module Procedures
public function sortposofval_label(me, val, nextifnotfound, lower, upper) result(pos)
return the sorted position of a value in the given dynamic array
Read more…
Arguments
Type Intent Optional Attributes Name
type(dyn_labelarray_type), intent(in) :: me
character(len=*), intent(in) :: val
logical, intent(in), optional :: nextifnotfound
flag to indicate, if the next entry in the list should be returned, if the searched one is not found.
integer, intent(in), optional :: lower
integer, intent(in), optional :: upper
Return Value integer
Call graph
sortedposofval calls sortposofval_label
append_da_int calls sortedposofval
append_da_label calls sortedposofval
append_da_long calls sortedposofval
append_da_real calls sortedposofval
posofval_int calls sortedposofval
posofval_label calls sortedposofval
posofval_long calls sortedposofval
posofval_real calls sortedposofval
append calls append_da_long, append_da_int, append_da_real, append_da_label
positionofval calls posofval_long, posofval_int, posofval_real, posofval_label