tem_reduction_spatial_dump – Treelm
tem_reduction_spatial_dump Interface
4 statements
Source File
public interface tem_reduction_spatial_dump
Calls
Module Procedures
private subroutine tem_reduction_spatial_dump_vector(me, outUnit)
Dumps array of reduction to given unit
Arguments
Type Intent Optional Attributes Name
type(tem_reduction_spatial_type), intent(in) :: me(:)
reduction to write into the lua file
integer, intent(in) :: outUnit
unit to write to
private subroutine tem_reduction_spatial_dump_single(me, outUnit)
Dump single reduction to given unit
Arguments
Type Intent Optional Attributes Name
type(tem_reduction_spatial_type), intent(in) :: me
reduction to write into the lua file
integer, intent(in) :: outUnit
unit to write to
Call graph
tem_reduction_spatial_dump calls tem_reduction_spatial_dump_single, tem_reduction_spatial_dump_vector
tem_reduction_spatial_dump_single calls aot_out_close, aot_out_open, tem_reduction_spatial_out_single
tem_reduction_spatial_dump_vector calls aot_out_close, aot_out_open, tem_reduction_spatial_out_vector
tem_reduction_spatial_out_single calls aot_out_val
tem_reduction_spatial_out_vector calls aot_out_val