tem_log – Treelm
tem_log Interface
4 statements
Source File
public interface tem_log
Calls
Called by
Module Procedures
private subroutine tem_log_for(me, level, msg)
Log a message in the given logger.
Arguments
Type Intent Optional Attributes Name
type(tem_logging_type), intent(in) :: me
integer, intent(in) :: level
character(len=*), intent(in) :: msg
private subroutine tem_log_primary(level, msg)
Log a message in the primary logger.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: level
character(len=*), intent(in) :: msg
Call graph
tem_log calls tem_log_for, tem_log_primary
tem_shape_initbylevels calls tem_log
tem_shape_load_level calls tem_log
tem_load_shape_single calls tem_shape_load_level
tem_shape2subtree calls tem_shape_initbylevels
tem_load_shape calls tem_load_shape_single, tem_load_shapes
tem_create_subtree_of calls tem_shape2subtree
tem_load_shapes calls tem_load_shape_single
load_spatial_parabol calls tem_load_shape
tem_create_subtree_of_st_funlist calls tem_create_subtree_of
tem_init_convergence calls tem_create_subtree_of
tem_init_tracker_subtree calls tem_create_subtree_of
tem_load_convergenceheader calls tem_load_shape
tem_load_spacetime_single calls tem_load_shape
tem_load_trackingconfig calls tem_load_shape
tem_write_debugmesh calls tem_create_subtree_of