tem_GetLocalBoundingCube – Treelm
tem_GetLocalBoundingCube Interface
4 statements
Source File
public interface tem_GetLocalBoundingCube
Calls
Called by
Module Procedures
private function tem_GetLocalBoundingCube_fromTree(tree) result(BoundingCube)
Run through all the elements, check the vertices and return the fluid bounding cube
Arguments
Type Intent Optional Attributes Name
type(treelmesh_type), intent(in) :: tree
global mesh information
Return Value real(kind=rk), (3,2)
xyz coordinate for min and max of bounding cube
private function tem_GetLocalBoundingCube_fromSubTree(subTree, globalTree) result(BoundingCube)
Run through all the elements, check the vertices and return the fluid bounding cube
Arguments
Type Intent Optional Attributes Name
type(tem_subTree_type), intent(in) :: subTree
subTree to locate point in
type(treelmesh_type), intent(in) :: globalTree
corresponding global tree
Return Value real(kind=rk), (3,2)
xyz coordinate for min and max of bounding cube
Call graph
tem_getlocalboundingcube calls tem_getlocalboundingcube_fromsubtree, tem_getlocalboundingcube_fromtree
tem_getlocalboundingcube_fromsubtree calls tem_vrtxcoordofid
tem_getlocalboundingcube_fromtree calls tem_vrtxcoordofid
tem_vrtxcoordofid calls tem_baryofid, tem_coordofid
tem_baryofid calls tem_coordofid, tem_elemsizelevel
tem_coordofid calls tem_levelof
tem_getrealboundingcube calls tem_getlocalboundingcube
tem_seteffboundingbox_fromsubtree calls tem_getlocalboundingcube
tem_seteffboundingbox calls tem_seteffboundingbox_fromsubtree, tem_seteffboundingbox_fromtree
tem_seteffboundingbox_fromtree calls tem_getrealboundingcube
tem_create_subtree_of calls tem_seteffboundingbox
tem_create_subtree_of_st_funlist calls tem_create_subtree_of
tem_init_convergence calls tem_create_subtree_of
tem_init_tracker_subtree calls tem_create_subtree_of
tem_write_debugmesh calls tem_create_subtree_of