tem_load_spacetime – Treelm
tem_load_spacetime Interface
4 statements
Source File
public interface tem_load_spacetime
Calls
Called by
Module Procedures
private recursive subroutine tem_load_spacetime_single(me, conf, parent, key, pos, nComp, errCode, recurred)
This routine loads the single spacetime function from the given key or position
Read more…
Arguments
Type Intent Optional Attributes Name
type(tem_spacetime_fun_type), intent(out) :: me
spacetime fun information
type(flu_State) :: conf
lua state type
integer, intent(in), optional :: parent
aotus parent handle
character(len=*), intent(in), optional :: key
name of the variable which is defined as spacetime function
integer, intent(in), optional :: pos
position of spacetime fun in a table
integer, intent(in), optional :: nComp
number of components of the variable
integer, intent(out), optional :: errCode
errCode /=0, space time function fails use errCode to abort code outside this routine call
integer, intent(in), optional :: recurred
Number of recursion steps done so far (defaults to 0)
private subroutine tem_load_spacetime_table(me, conf, parent, key, nComp, errCode)
This routine loads table of spacetime functions from the given key or pos
Read more…
Arguments
Type Intent Optional Attributes Name
type(tem_spacetime_fun_type), intent(out), allocatable :: me(:)
spacetime fun information
type(flu_State) :: conf
lua state handle
integer, intent(inout), optional :: parent
aotus parent handle
character(len=*), intent(in) :: key
name of the variable which is defined as spacetime function
integer, intent(in), optional :: nComp
number of components of the variable
integer, intent(out), optional :: errCode
errCode /=0, space time function fails use errCode to abort code outside this routine call
Call graph
tem_load_spacetime calls tem_load_spacetime_single, tem_load_spacetime_table
tem_load_spacetime_single calls tem_load_spacetime_single, aot_exists, aot_fun_close, aot_fun_open, aot_get_val, aot_reference_for, aot_table_open, aot_type_of, tem_load_shape, load_spacetime_asconst, load_spacetime_predefined, tem_abort
tem_load_spacetime_table calls tem_load_spacetime_single, aot_table_close, aot_table_length, aot_table_open
tem_load_shape calls tem_load_shape_single, tem_load_shapes
load_spacetime_asconst calls aot_get_val
load_spacetime_predefined calls tem_abort, tem_load_miescatter_displacementfieldz, tem_load_miescatter_magneticfieldx, tem_load_miescatter_magneticfieldy, tem_aps_load_coupling, tem_load_acoustic_pulse, tem_load_cylindricalwave, tem_load_spatial, tem_load_temporal, tem_polygon_material_multi_load, tem_polygon_material_single_load, upper_to_lower, tem_precice_load_coupling
tem_abort calls mpi_abort
tem_variable_load_single calls tem_load_spacetime
tem_variable_loadmapping_single calls tem_load_spacetime
tem_variable_load calls tem_variable_load_single, tem_variable_load_vector
tem_variable_loadmapping calls tem_variable_loadmapping_single, tem_variable_loadmapping_vector
tem_variable_load_vector calls tem_variable_load_single
tem_variable_loadmapping_vector calls tem_variable_loadmapping_single
tem_load_bc_state calls tem_variable_loadmapping