tem_load_depend – Treelm
tem_load_depend Interface
4 statements
Source File
public interface tem_load_depend
load depend table
Calls
Module Procedures
private subroutine tem_load_depend_vector(me, conf, parent, label, requireCond)
Load variables, parent scheme and conditions defined in lua file. This routine serves as a wrapper and calls the single routine which loads the various arguments
Arguments
Type Intent Optional Attributes Name
type(tem_depend_type), intent(inout), allocatable :: me(:)
list of depend types to be filled
type(flu_State), intent(in) :: conf
lua state to read from
integer, intent(in) :: parent
parent table identifier
character(len=*), intent(in) :: label
label to identify depend type
logical, intent(in), optional :: requireCond
if true? load condition table for each variable
private subroutine tem_load_depend_single(me, conf, parent, label, requireCond)
Load single dependent variable of the scheme, in case of geomIncr: load the dependent variable as well as the conditions to be imposed for the geometry increase to take place.
Arguments
Type Intent Optional Attributes Name
type(tem_depend_type), intent(inout) :: me
depend type to be filled
type(flu_State), intent(in) :: conf
lua state to read from
integer, intent(in) :: parent
handle of parent table
character(len=*), intent(in) :: label
label to identify depend type
logical, intent(in), optional :: requireCond
if true? load condition table for each variable
Call graph
tem_load_depend calls tem_load_depend_single, tem_load_depend_vector
tem_load_depend_single calls aot_get_val, aot_table_close, aot_table_open, tem_abort, tem_load_condition
tem_load_depend_vector calls tem_load_depend_single, aot_table_close, aot_table_length, aot_table_open, tem_horizontalspacer
tem_abort calls mpi_abort
tem_load_condition calls aot_table_close, aot_table_length, aot_table_open, tem_load_cond_single
tem_load_cond_single calls aot_get_val, tem_abort