tem_spacetime_lua_for – Treelm
tem_spacetime_lua_for Interface
6 statements
Source File
private interface tem_spacetime_lua_for
Calls
Called by
Module Procedures
private function tem_spacetime_lua_for_treeIds(fun_ref, treeIds, time, tree, n, conf) result(res)
\brief This function invokes the Lua function for barycentric coordinates of an element specified by treeIds
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: fun_ref
Reference of the function to open
integer(kind=long_k), intent(in) :: treeIds(n)
treeIds of elements in given level
type(tem_time_type), intent(in) :: time
timer object incl. the current time information
type(treelmesh_type), intent(in) :: tree
global treelm mesh
integer, intent(in) :: n
number of return values
type(flu_State), intent(in) :: conf
lua state
Return Value real(kind=rk), (n)
return value
private function tem_spacetime_lua_vector_for_treeIds(fun_ref, treeIds, time, tree, n, ncomp, conf) result(res)
This function invokes the Lua function for barycentric coordinates of an element specified by treeIds and returns an array with the given number of components.
Read more…
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: fun_ref
Reference of the function to open
integer(kind=long_k), intent(in) :: treeIds(n)
treeIds of elements in given level
type(tem_time_type), intent(in) :: time
timer object incl. the current time information
type(treelmesh_type), intent(in) :: tree
global treelm mesh
integer, intent(in) :: n
number of return values
integer, intent(in) :: ncomp
number of components per returned value
type(flu_State), intent(in) :: conf
lua state
Return Value real(kind=rk), (n,ncomp)
return value
private function tem_spacetime_lua_for_coord(fun_ref, coord, time, n, conf) result(res)
\brief This function invokes the Lua function for a given coordinate.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: fun_ref
Reference of the function to open
real(kind=rk), intent(in) :: coord(n,3)
barycentric Ids of an elements. 1st index goes over number of elements and 2nd index goes over x,y,z coordinates
type(tem_time_type), intent(in) :: time
timer object incl. the current time information
integer, intent(in) :: n
number of return values
type(flu_State), intent(in) :: conf
lua state
Return Value real(kind=rk), (n)
return value
private function tem_spacetime_lua_vector_for_coord(fun_ref, coord, time, n, ncomp, conf) result(res)
This function invokes the Lua function for a given coordinate and returns an array valued result.
Read more…
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: fun_ref
Reference of the function to open
real(kind=rk), intent(in) :: coord(n,3)
barycentric Ids of an elements. 1st index goes over number of elements and 2nd index goes over x,y,z coordinates
type(tem_time_type), intent(in) :: time
timer object incl. the current time information
integer, intent(in) :: n
number of return values
integer, intent(in) :: ncomp
number of components returned for each value
type(flu_State), intent(in), optional :: conf
lua state
Return Value real(kind=rk), (n,ncomp)
return value
Call graph
tem_spacetime_lua_for calls tem_spacetime_lua_for_coord, tem_spacetime_lua_for_treeids, tem_spacetime_lua_vector_for_coord, tem_spacetime_lua_vector_for_treeids
tem_spacetime_lua_for_coord calls aot_fun_close, aot_fun_do, aot_fun_open, aot_fun_put, aot_top_get_val, tem_abort
tem_spacetime_lua_for_treeids calls aot_fun_close, aot_fun_do, aot_fun_open, aot_fun_put, aot_top_get_val, tem_abort, tem_baryofid
tem_spacetime_lua_vector_for_coord calls aot_fun_close, aot_fun_do, aot_fun_open, aot_fun_put, aot_top_get_val, tem_abort
tem_spacetime_lua_vector_for_treeids calls aot_fun_close, aot_fun_do, aot_fun_open, aot_fun_put, aot_top_get_val, tem_abort, tem_baryofid
tem_abort calls mpi_abort
tem_baryofid calls tem_coordofid, tem_elemsizelevel
tem_coordofid calls tem_levelof
tem_spacetime_for_coord calls tem_spacetime_lua_for
tem_spacetime_for_treeids calls tem_spacetime_lua_for
tem_spacetime_scalar_for_index calls tem_spacetime_lua_for, tem_spacetime_for_coord
tem_spacetime_vector_for_coord calls tem_spacetime_lua_for
tem_spacetime_vector_for_index calls tem_spacetime_lua_for, tem_spacetime_vector_for_coord
tem_spacetime_vector_for_treeids calls tem_spacetime_lua_for
tem_spacetime_for calls tem_spacetime_for_coord, tem_spacetime_for_treeids, tem_spacetime_scalar_for_index, tem_spacetime_vector_for_coord, tem_spacetime_vector_for_index, tem_spacetime_vector_for_treeids, tem_spacetime_for_stcoord
tem_spacetime_for_stcoord calls tem_spacetime_for_coord
evaluate_add_spacetime_scalarbycoordinate calls tem_spacetime_for
evaluate_add_spacetime_scalarbytreeid calls tem_spacetime_for
evaluate_add_spacetime_vectorbycoordinate calls tem_spacetime_for
evaluate_add_spacetime_vectorbytreeid calls tem_spacetime_for
evaluate_first_spacetime_scalarbycoordinate calls tem_spacetime_for
evaluate_first_spacetime_scalarbytreeid calls tem_spacetime_for
evaluate_first_spacetime_vectorbycoordinate calls tem_spacetime_for
evaluate_first_spacetime_vectorbytreeid calls tem_spacetime_for
evaluate_foag_spacetime_scalarbycoordinate calls tem_spacetime_for
evaluate_foag_spacetime_scalarbytreeid calls tem_spacetime_for
evaluate_foag_spacetime_vectorbycoordinate calls tem_spacetime_for
evaluate_foag_spacetime_vectorbytreeid calls tem_spacetime_for
get_valofindex_add_scalar_spacetime calls tem_spacetime_for
get_valofindex_add_vector_spacetime calls tem_spacetime_for
get_valofindex_first_scalar_spacetime calls tem_spacetime_for
get_valofindex_first_vector_spacetime calls tem_spacetime_for
get_valofindex_foag_scalar_spacetime calls tem_spacetime_for
get_valofindex_foag_vector_spacetime calls tem_spacetime_for
tem_update_surfpos calls tem_spacetime_for