tem_convergence_dump – Treelm
tem_convergence_dump Interface
4 statements
Source File
public interface tem_convergence_dump
Calls
Module Procedures
private subroutine tem_convergence_dump_vector(me, outUnit)
Dumps array of convergence to given unit
Arguments
Type Intent Optional Attributes Name
type(tem_convergence_type), intent(in) :: me(:)
convergence to write into the lua file
integer, intent(in) :: outUnit
unit to write to
private subroutine tem_convergence_dump_single(me, outUnit)
Dump single convergence to given unit
Arguments
Type Intent Optional Attributes Name
type(tem_convergence_type), intent(in) :: me
convergence to write into the lua file
integer, intent(in) :: outUnit
unit to write to
Call graph
tem_convergence_dump calls tem_convergence_dump_single, tem_convergence_dump_vector
tem_convergence_dump_single calls aot_out_close, aot_out_open, tem_convergence_out_single
tem_convergence_dump_vector calls aot_out_close, aot_out_open, tem_convergence_out_vector
tem_convergence_out_single calls aot_out_close_table, aot_out_open_table, aot_out_val, tem_condition_out, tem_reduction_spatial_out, tem_shape_out, tem_timecontrol_out
tem_convergence_out_vector calls tem_convergence_out_single, aot_out_close_table, aot_out_open_table
tem_condition_out calls tem_condition_out_single, tem_condition_out_vector
tem_reduction_spatial_out calls tem_reduction_spatial_out_single, tem_reduction_spatial_out_vector
tem_shape_out calls tem_shape_out_scal, tem_shape_out_vec
tem_timecontrol_out calls aot_out_close_table, aot_out_open_table, aot_out_val, tem_time_out