tem_varSys_load – Treelm
tem_varSys_load Interface
4 statements
Source File
public interface tem_varSys_load
Calls
Called by
Module Procedures
public subroutine tem_varSys_load_vector(me, conf, parent, key)
Load variable system(s) from a lua file
Arguments
Type Intent Optional Attributes Name
type(tem_varSys_type), intent(out), allocatable :: me(:)
The variable system to read in
type(flu_State) :: conf
Lua handle connected to the script to read the table from
integer, intent(in), optional :: parent
A parent table handle in which to look the current variables up
character(len=*), intent(in), optional :: key
load from this key
public subroutine tem_varSys_load_single(me, conf, parent, key, openTable)
load varSys from lua file. Required for harvester to load varSys from tracking or restart header file.
Arguments
Type Intent Optional Attributes Name
type(tem_varSys_type), intent(out) :: me
varSys to read from the Lua script(conf) and fill
type(flu_State) :: conf
Lua handle connected to the script to read the table from
integer, intent(in), optional :: parent
A parent table handle in which to look the current variable up
character(len=*), intent(in), optional :: key
load varsys from this key
logical, intent(in), optional :: openTable
Call graph
tem_varsys_load calls tem_varsys_load_single, tem_varsys_load_vector
tem_varsys_load_single calls aot_get_val, aot_table_close, aot_table_length, aot_table_open, append, init, tem_abort
tem_varsys_load_vector calls tem_varsys_load_single, aot_table_close, aot_table_length, aot_table_open, tem_abort
append calls append_da_label, append_da_veclabel
init calls init_da_label
tem_abort calls mpi_abort
append_da_label calls expand, sortedposofval
append_da_veclabel calls expand
tem_restart_readheader calls tem_varsys_load
tem_load_restart calls tem_restart_readheader