tem_toStr – Treelm
tem_toStr Interface
12 statements
Source File
public interface tem_toStr
Calls
Called by
Module Procedures
private function tem_r2str(val, logger) result(str)
Convert a real to a string according to the format provided in the logger.
Arguments
Type Intent Optional Attributes Name
real(kind=single_k), intent(in) :: val
type(tem_logging_type), intent(in), optional :: logger
Return Value character(len=SolSpecLen)
private function tem_d2str(val, logger) result(str)
Converts a double to a string according to the format provided in the logger.
Arguments
Type Intent Optional Attributes Name
real(kind=double_k), intent(in) :: val
type(tem_logging_type), intent(in), optional :: logger
Return Value character(len=SolSpecLen)
private function tem_i2str(val, logger) result(str)
Converts an integer to a string according to the format provided in the logger.
Arguments
Type Intent Optional Attributes Name
integer(kind=int_k), intent(in) :: val
type(tem_logging_type), intent(in), optional :: logger
Return Value character(len=SolSpecLen)
private function tem_l2str(val, logger) result(str)
Converts a long to a string according to the format provided in the logger.
Arguments
Type Intent Optional Attributes Name
integer(kind=long_k), intent(in) :: val
type(tem_logging_type), intent(in), optional :: logger
Return Value character(len=SolSpecLen)
private function tem_b2str(val) result(str)
Converts a bool to a string.
Arguments
Type Intent Optional Attributes Name
logical, intent(in) :: val
Return Value character(len=SolSpecLen)
private function tem_r2str_arr(val, sep, logger) result(str)
Converts a real "array" to a single string according to the format provided in the logger.
Arguments
Type Intent Optional Attributes Name
real(kind=single_k), intent(in) :: val(:)
array to convert
character(len=*), intent(in) :: sep
seperator between array elements
type(tem_logging_type), intent(in), optional :: logger
logger type which provides output format
Return Value character(len=SolSpecLen)
output string
private function tem_d2str_arr(val, sep, logger) result(str)
Converts an array of doubles to a string according to the format provided in the logger.
Arguments
Type Intent Optional Attributes Name
real(kind=double_k), intent(in) :: val(:)
character(len=*), intent(in) :: sep
type(tem_logging_type), intent(in), optional :: logger
Return Value character(len=SolSpecLen)
private function tem_i2str_arr(val, sep, logger) result(str)
Converts an array of integers to a string according to the format provided in the logger.
Arguments
Type Intent Optional Attributes Name
integer(kind=int_k), intent(in) :: val(:)
array to convert
character(len=*), intent(in) :: sep
type(tem_logging_type), intent(in), optional :: logger
Return Value character(len=SolSpecLen)
private function tem_l2str_arr(val, sep, logger) result(str)
Converts an array of longs to a string according to the format provided in the logger.
Arguments
Type Intent Optional Attributes Name
integer(kind=long_k), intent(in) :: val(:)
character(len=*), intent(in) :: sep
type(tem_logging_type), intent(in), optional :: logger
Return Value character(len=SolSpecLen)
private function tem_b2str_arr(val, sep) result(str)
Converts an array of booleans to a string.
Arguments
Type Intent Optional Attributes Name
logical, intent(in) :: val(:)
character(len=*), intent(in) :: sep
Return Value character(len=SolSpecLen)
Call graph
tem_tostr calls tem_b2str, tem_b2str_arr, tem_d2str, tem_d2str_arr, tem_i2str, tem_i2str_arr, tem_l2str, tem_l2str_arr, tem_r2str, tem_r2str_arr
identify_lists calls tem_tostr
load_spatial_parabol calls tem_tostr
load_spatial_predefined calls tem_tostr, load_spatial_parabol
tem_comm_dumptype calls tem_tostr
tem_load_onecanonicalnd calls tem_tostr
tem_load_spatial calls tem_tostr, load_spatial_predefined
tem_print_array calls tem_tostr
tem_shape_initbylevels calls tem_tostr
tem_shape_load_level calls tem_tostr
tem_stencilheader_dump calls tem_tostr
tem_load_canonicalnd calls tem_load_onecanonicalnd, tem_load_canonicalnd_vec
tem_stencil_dump calls tem_stencilheader_dump
communicate_elements calls identify_lists, redefine_halos
load_spacetime_predefined calls tem_load_spatial
redefine_halos calls tem_comm_dumptype
tem_find_allelements calls identify_lists, communicate_elements
tem_load_canonicalnd_vec calls tem_load_onecanonicalnd
tem_load_ic calls tem_load_spatial
tem_load_shape_single calls tem_shape_load_level, tem_load_canonicalnd
tem_shape2subtree calls tem_shape_initbylevels
tem_load_shape calls tem_load_shape_single
tem_create_leveldesc calls tem_find_allelements
tem_create_subtree_of calls tem_shape2subtree
tem_dimbydim_construction calls tem_stencil_dump
tem_element_dump calls tem_stencil_dump
tem_load_shapes calls tem_load_shape_single
tem_load_spacetime_single calls load_spacetime_predefined