tem_variable_loadMapping – Treelm
tem_variable_loadMapping Interface
4 statements
Source File
public interface tem_variable_loadMapping
Calls
Called by
Module Procedures
public subroutine tem_variable_loadMapping_vector(possVars, conf, parent, key, varDict, varSys)
Loads the variable mapping from a table defined by given key for the variable names defined in possVars list. A variable mapping is used to link a user defined variable to a variable expected from, e.g., an equation system. These mappings are stored in varDict, which basically is a dictionary, whereas the key contains the name of the expected variable and the value contains the name of the user defined variable in the variable table.
Arguments
Type Intent Optional Attributes Name
type(tem_possible_variable_type), intent(in) :: possVars
Possible variable names expected by the solver
type(flu_State), intent(in) :: conf
lua config file
integer, intent(in), optional :: parent
optional parent handle
character(len=*), intent(in), optional :: key
optional key for the table
type(grw_stringkeyvaluepairarray_type), intent(inout) :: varDict
The dictionary that contains the mapping between expected variables and the actual variables defined by the user.
type(tem_varSys_type), intent(inout) :: varSys
Variable system to append anonymous variables to.
public subroutine tem_variable_loadMapping_single(expectedName, conf, thandle, varDict, varSys, nComp, solverData_evalElem, ErrCode)
Loads the variable mapping from a table for single expected name. A variable mapping is used to link a user defined variable to a variable expected from, e.g., an equation system. These mappings are stored in varDict, which basically is a dictionary, whereas the key contains the name of the expected variable and the value contains the name of the user defined variable in the variable table.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: expectedName
Expected variable name from config file
type(flu_State), intent(in) :: conf
lua config file
integer, intent(in) :: thandle
table handle
type(grw_stringkeyvaluepairarray_type), intent(inout) :: varDict
The dictionary that contains the mapping between expected variables and the actual variables defined by the user.
type(tem_varSys_type), intent(inout) :: varSys
Variable system to append anonymous variables to.
integer, intent(in), optional :: nComp
Number of components we expect for this variable.
type(tem_varSys_solverData_evalElem_type), intent(in), optional :: solverData_evalElem
Routine to convert point information into an element representation.
integer, intent(out), optional :: ErrCode
Error code
Call graph
tem_variable_loadmapping calls tem_variable_loadmapping_single, tem_variable_loadmapping_vector
tem_variable_loadmapping_single calls aot_exists, aot_get_val, append, tem_load_spacetime, tem_varsys_append_stfun, tem_spacetime_hash_id
tem_variable_loadmapping_vector calls tem_variable_loadmapping_single, aot_table_close, aot_table_open
append calls append_ga_stringkeyvaluepair, append_ga_stringkeyvaluepair_vec
tem_load_spacetime calls tem_load_spacetime_single, tem_load_spacetime_table
tem_varsys_append_stfun calls tem_varsys_append_stfun_raw, tem_varsys_append_stfunvar
tem_spacetime_hash_id calls aot_fun_close, aot_fun_id, aot_fun_open
append_ga_stringkeyvaluepair calls expand
append_ga_stringkeyvaluepair_vec calls expand
tem_load_spacetime_single calls aot_exists, aot_get_val, aot_table_open, aot_fun_close, aot_fun_open, tem_load_spacetime_single, aot_reference_for, aot_type_of, tem_load_shape, load_spacetime_asconst, load_spacetime_predefined, tem_abort
tem_load_spacetime_table calls aot_table_close, aot_table_open, tem_load_spacetime_single, aot_table_length
tem_varsys_append_stfun_raw calls append, tem_abort, tem_varsys_append_dervar, tem_varsys_assignevaltype
tem_varsys_append_stfunvar calls append, tem_abort, tem_varsys_append_dervar, tem_varsys_assignevaltype
tem_load_bc_state calls tem_variable_loadmapping