tem_load_shape – Treelm
tem_load_shape Interface
4 statements
Source File
public interface tem_load_shape
Calls
Called by
Module Procedures
private subroutine tem_load_shapes(me, conf, parent, key, iError, reqSegments)
Read in an arbitrary shapes from a lua file defined as multiple tables
Read more…
Arguments
Type Intent Optional Attributes Name
type(tem_shape_type), intent(out), allocatable :: me(:)
array of shape type defined in a lua file
type(flu_State) :: conf
lua config file to load shape from
integer, intent(in), optional :: parent
optional parent handle
character(len=*), intent(in), optional :: key
optional key to load from
integer, intent(out), optional :: iError
error flag
logical, intent(in), optional :: reqSegments
Is true if use_get_point is true in output table
private subroutine tem_load_shape_single(me, conf, key, parent, sub_table, iError, reqSegments)
Read in an arbitrary shape from a lua file defined in a single table
Read more…
Arguments
Type Intent Optional Attributes Name
type(tem_shape_type), intent(out) :: me
shape type defined in a lua file
type(flu_State) :: conf
lua state
character(len=*), intent(in), optional :: key
optional key to load from
integer, intent(in), optional :: parent
optional parent handle
integer, intent(in), optional :: sub_table
shape table handle
integer, intent(out), optional :: iError
error flag
logical, intent(in), optional :: reqSegments
Is true if use_get_point is true in output table
Call graph
tem_load_shape calls tem_load_shape_single, tem_load_shapes
tem_load_shape_single calls aot_get_val, aot_table_close, aot_table_open, tem_load_canonicalnd, tem_abort, tem_load_stl, tem_load_transformation, tem_shape_load_bclabels, tem_shape_load_level, tem_shape_load_proplabel, tem_load_cylinder, tem_load_ellipsoid, tem_load_sphere, tem_load_triangle
tem_load_shapes calls tem_load_shape_single, aot_table_close, aot_table_length, aot_table_open
tem_load_canonicalnd calls tem_load_canonicalnd_vec, tem_load_onecanonicalnd
tem_abort calls mpi_abort
tem_load_stl calls tem_load_stlhead, tem_read_stlfiles
tem_load_transformation calls aot_table_close, aot_table_open, tem_load_deformation, tem_load_translation
tem_shape_load_bclabels calls aot_get_val, aot_table_close, aot_table_length, aot_table_open
tem_shape_load_level calls aot_get_val, aot_table_close, aot_table_length, aot_table_open, tem_log, tem_tostr
tem_shape_load_proplabel calls aot_get_val, aot_table_close, aot_table_length, aot_table_open
load_spatial_parabol calls tem_load_shape
tem_load_convergenceheader calls tem_load_shape
tem_load_spacetime_single calls tem_load_shape, tem_load_spacetime_single
tem_load_trackingconfig calls tem_load_shape
tem_load_spacetime calls tem_load_spacetime_single, tem_load_spacetime_table
load_spatial_predefined calls load_spatial_parabol
tem_convergence_load calls tem_load_convergenceheader
tem_load_spacetime_table calls tem_load_spacetime_single
tem_load_tracking calls tem_load_trackingconfig
tem_abortcriteria_load calls tem_convergence_load
tem_load_spatial calls load_spatial_predefined
tem_variable_load_single calls tem_load_spacetime
tem_variable_loadmapping_single calls tem_load_spacetime
tem_variable_load calls tem_variable_load_single
tem_variable_loadmapping calls tem_variable_loadmapping_single
load_spacetime_predefined calls tem_load_spatial
tem_load_ic calls tem_load_spatial
tem_simcontrol_load calls tem_abortcriteria_load
tem_variable_load_vector calls tem_variable_load_single
tem_variable_loadmapping_vector calls tem_variable_loadmapping_single