tem_spatial_parabol2d_for – Treelm
tem_spatial_parabol2d_for Interface
4 statements
Source File
public interface tem_spatial_parabol2d_for
Calls
Called by
Module Procedures
private function tem_spatial_parabol2d_for_treeIds(me, treeIds, tree, n) result(res)
This function computes 2d parabola profile from treeIds of elements
Read more…
Arguments
Type Intent Optional Attributes Name
type(tem_canonicalND_type) :: me
contains parameters for 2d parabola
integer(kind=long_k), intent(in) :: treeIds(n)
treeIds of elements in given level
type(treelmesh_type), intent(in) :: tree
global treelm mesh
integer, intent(in) :: n
number of return values
Return Value real(kind=rk), (n)
return value of a function
private function tem_spatial_parabol2d_for_coord(me, coord, n) result(res)
This function computes 2d parabola profile from coord of elements
Read more…
Arguments
Type Intent Optional Attributes Name
type(tem_canonicalND_type) :: me
contains line parameters for 2d parabola
real(kind=rk), intent(in) :: coord(n,3)
barycentric Ids of an elements. 1st index goes over number of elements and 2nd index goes over x,y,z coordinates
integer, intent(in) :: n
number of return values
Return Value real(kind=rk), (n)
return value of a function
Call graph
tem_spatial_parabol2d_for calls tem_spatial_parabol2d_for_coord, tem_spatial_parabol2d_for_treeids
tem_spatial_parabol2d_for_treeids calls tem_baryofid
tem_baryofid calls tem_coordofid, tem_elemsizelevel
tem_coordofid calls tem_levelof
tem_spatial_for_coord calls tem_spatial_parabol2d_for
tem_spatial_for_treeids calls tem_spatial_parabol2d_for
tem_spatial_vector_for_coord calls tem_spatial_parabol2d_for
tem_spatial_vector_for_treeids calls tem_spatial_parabol2d_for
tem_spatial_for calls tem_spatial_for_coord, tem_spatial_for_treeids, tem_spatial_vector_for_coord, tem_spatial_vector_for_treeids, tem_spatial_scalar_for_index, tem_spatial_vector_for_index
tem_spatial_scalar_for_index calls tem_spatial_for_coord
tem_spatial_vector_for_index calls tem_spatial_vector_for_coord
tem_spacetime_for_coord calls tem_spatial_for
tem_spacetime_for_treeids calls tem_spatial_for
tem_spacetime_scalar_for_index calls tem_spatial_for, tem_spacetime_for_coord
tem_spacetime_vector_for_coord calls tem_spatial_for
tem_spacetime_vector_for_index calls tem_spatial_for, tem_spacetime_vector_for_coord
tem_spacetime_vector_for_treeids calls tem_spatial_for
tem_spatial_scalar_storeval calls tem_spatial_for
tem_spatial_vector_storeval calls tem_spatial_for
tem_spacetime_for calls tem_spacetime_for_coord, tem_spacetime_for_treeids, tem_spacetime_scalar_for_index, tem_spacetime_vector_for_coord, tem_spacetime_vector_for_index, tem_spacetime_vector_for_treeids
tem_spatial_storeval calls tem_spatial_scalar_storeval, tem_spatial_vector_storeval
tem_spacetime_for_stcoord calls tem_spacetime_for_coord