tem_canonicalND_out – Treelm
tem_canonicalND_out Interface
4 statements
Source File
public interface tem_canonicalND_out
interface to write out canonical shape(s) in lua format to a file
Calls
Called by
Module Procedures
private subroutine tem_canonicalND_out_scal(me, conf)
Write out a canonicalND shape in lua format
Arguments
Type Intent Optional Attributes Name
type(tem_canonicalND_type), intent(in) :: me
canonicalND types to write out
type(aot_out_type), intent(inout) :: conf
Aotus type handling the output to the file in lua format
private subroutine tem_canonicalND_out_vec(me, conf)
Write out an array of canonical shapes in lua format
Arguments
Type Intent Optional Attributes Name
type(tem_canonicalND_type), intent(in) :: me(:)
canonicalND types to write out
type(aot_out_type), intent(inout) :: conf
Aotus type handling the output to the file in lua format
Call graph
tem_canonicalnd_out calls tem_canonicalnd_out_scal, tem_canonicalnd_out_vec
tem_canonicalnd_out_scal calls aot_out_close_table, aot_out_open_table, aot_out_val
tem_canonicalnd_out_vec calls tem_canonicalnd_out_scal, aot_out_close_table, aot_out_open_table
tem_shape_out_scal calls tem_canonicalnd_out
tem_shape_out calls tem_shape_out_scal, tem_shape_out_vec
tem_shape_out_vec calls tem_shape_out_scal
hvs_ascii_write_header calls tem_shape_out
tem_convergence_out_single calls tem_shape_out
tem_convergence_out calls tem_convergence_out_single
hvs_ascii_init calls hvs_ascii_write_header
hvs_asciispatial_init calls hvs_ascii_write_header
tem_convergence_dump_single calls tem_convergence_out_single
tem_convergence_out_vector calls tem_convergence_out_single