tem_transformCanoND – Treelm
tem_transformCanoND Interface
4 statements
Source File
public interface tem_transformCanoND
This routine apply transformations to canonical objects
Calls
Called by
Module Procedures
private subroutine transformCanoND(canoND, transform)
This routine apply transformation to canonical objects.
Arguments
Type Intent Optional Attributes Name
type(tem_canonicalND_type), intent(inout) :: canoND(:)
canonical geometry object type
type(tem_transformation_type), intent(in) :: transform
transformation for spatial object
private subroutine transformCanoND_single(canoND, transform)
This routine apply transformation to canonical objects.
Arguments
Type Intent Optional Attributes Name
type(tem_canonicalND_type), intent(inout) :: canoND
canonical geometry object type
type(tem_transformation_type), intent(in) :: transform
transformation for spatial object
Call graph
tem_transformcanond calls transformcanond, transformcanond_single
transformcanond calls transformcanond_single
tem_load_onecanonicalnd calls tem_transformcanond
tem_load_canonicalnd calls tem_load_onecanonicalnd, tem_load_canonicalnd_vec
tem_load_canonicalnd_vec calls tem_load_onecanonicalnd
tem_load_shape_single calls tem_load_canonicalnd
tem_load_shape calls tem_load_shape_single
tem_load_shapes calls tem_load_shape_single