tem_setEffBoundingBox – Treelm
tem_setEffBoundingBox Interface
4 statements
Source File
public interface tem_setEffBoundingBox
Calls
Called by
Module Procedures
private subroutine tem_setEffBoundingBox_fromTree(tree)
Calculate the real bounding box around the fluid domain
Arguments
Type Intent Optional Attributes Name
type(treelmesh_type), intent(inout) :: tree
Mesh
private subroutine tem_setEffBoundingBox_fromSubTree(subTree, globalTree)
Calculate the real bounding box around the fluid domain
Arguments
Type Intent Optional Attributes Name
type(tem_subTree_type) :: subTree
subTree to get effective bounding cube from
type(treelmesh_type), intent(in) :: globalTree
corresponding global tree
Call graph
tem_seteffboundingbox calls tem_seteffboundingbox_fromsubtree, tem_seteffboundingbox_fromtree
tem_seteffboundingbox_fromsubtree calls tem_getlocalboundingcube, mpi_allreduce
tem_seteffboundingbox_fromtree calls tem_getrealboundingcube
tem_getlocalboundingcube calls tem_getlocalboundingcube_fromsubtree, tem_getlocalboundingcube_fromtree
tem_getrealboundingcube calls tem_getlocalboundingcube, mpi_reduce
tem_getlocalboundingcube_fromsubtree calls tem_vrtxcoordofid
tem_getlocalboundingcube_fromtree calls tem_vrtxcoordofid
tem_create_subtree_of calls tem_seteffboundingbox
tem_create_subtree_of_st_funlist calls tem_create_subtree_of
tem_init_convergence calls tem_create_subtree_of
tem_init_tracker_subtree calls tem_create_subtree_of
tem_write_debugmesh calls tem_create_subtree_of