tem_spatial_lua_for – Treelm
tem_spatial_lua_for Interface
8 statements
Source File
public interface tem_spatial_lua_for
Calls
Called by
Module Procedures
private function tem_spatial_lua_for_treeIds(fun_ref, conf, treeIds, tree, n) result(res)
This function invokes the Lua function, in which the barycentric coordinates are computed from treeIds of an element.
Read more…
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: fun_ref
Lua reference to the function to evaluate.
type(flu_State) :: conf
lua state
integer(kind=long_k), intent(in) :: treeIds(n)
treeIds of elements in given level
type(treelmesh_type), intent(in) :: tree
global treelm mesh
integer, intent(in) :: n
number of return values
Return Value real(kind=rk), (n)
return value
private function tem_spatial_lua_for_coord(fun_ref, conf, coord, n) result(res)
This function invokes the Lua function, which takes barycentric coordinates of an element.
Read more…
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: fun_ref
Lua reference to the function to evaluate.
type(flu_State) :: conf
lua state
real(kind=rk), intent(in) :: coord(n,3)
barycentric Ids of an elements. 1st index goes over number of elements and 2nd index goes over x,y,z coordinates
integer, intent(in) :: n
number of return values
Return Value real(kind=rk), (n)
return value
private function tem_spatial_lua_for_index(fun_ref, conf, grwPnt, idx, nVals) result(res)
This function invokes the Lua function, which takes tem_grwPoints_type and evaluate a function at a point of given idx in grwPnt.
Read more…
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: fun_ref
Lua reference to the function to evaluate.
type(flu_State) :: conf
lua state
type(tem_grwPoints_type), intent(in) :: grwPnt
growing array of all spatial point of a variable
integer, intent(in) :: idx(nVals)
Index position to return a pre-store value or to compute
integer, intent(in) :: nVals
number of return values
Return Value real(kind=rk), (nVals)
return value
private function tem_spatial_lua_vector_for_treeIds(fun_ref, conf, treeIds, tree, n, ncomp) result(res)
This function invokes the vectorial Lua function, in which the barycentric coordinates are computed from treeIds of an element.
Read more…
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: fun_ref
Lua reference to the function to evaluate.
type(flu_State) :: conf
lua state
integer(kind=long_k), intent(in) :: treeIds(n)
treeIds of elements in given level
type(treelmesh_type), intent(in) :: tree
global treelm mesh
integer, intent(in) :: n
number of return values
integer, intent(in) :: ncomp
Number of components in each returned value
Return Value real(kind=rk), (n,ncomp)
return value
private function tem_spatial_lua_vector_for_coord(fun_ref, conf, coord, n, ncomp) result(res)
This function invokes the vectorial Lua function, which takes barycentric coordinates of an element.
Read more…
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: fun_ref
Lua reference to the function to evaluate.
type(flu_State), optional :: conf
lua state
real(kind=rk), intent(in) :: coord(n,3)
barycentric Ids of an elements. 1st index goes over number of elements and 2nd index goes over x,y,z coordinates
integer, intent(in) :: n
number of return values
integer, intent(in) :: ncomp
number of components in the resulting vector
Return Value real(kind=rk), (n,ncomp)
return value
private function tem_spatial_lua_vector_for_index(fun_ref, conf, grwPnt, idx, nVals, nComps) result(res)
This function invokes the vectorial Lua function, which takes tem_grwPoints_type and evaluate a function at a point of given idx in grwPnt.
Read more…
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: fun_ref
Lua reference to the function to evaluate.
type(flu_State) :: conf
lua state
type(tem_grwPoints_type), intent(in) :: grwPnt
growing array of all spatial point of a variable
integer, intent(in) :: idx(nVals)
Index position to return a pre-store value or to compute
integer, intent(in) :: nVals
number of return values
integer, intent(in) :: nComps
number of components per returned value
Return Value real(kind=rk), (nVals,nComps)
return value
Call graph
tem_spatial_lua_for calls tem_spatial_lua_for_coord, tem_spatial_lua_for_index, tem_spatial_lua_for_treeids, tem_spatial_lua_vector_for_coord, tem_spatial_lua_vector_for_index, tem_spatial_lua_vector_for_treeids
tem_spatial_lua_for_coord calls aot_fun_close, aot_fun_do, aot_fun_open, aot_fun_put, aot_top_get_val, tem_abort
tem_spatial_lua_for_index calls aot_fun_close, aot_fun_do, aot_fun_open, aot_fun_put, aot_top_get_val, tem_abort
tem_spatial_lua_for_treeids calls aot_fun_close, aot_fun_do, aot_fun_open, aot_fun_put, aot_top_get_val, tem_abort, tem_baryofid
tem_spatial_lua_vector_for_coord calls aot_fun_close, aot_fun_do, aot_fun_open, aot_fun_put, aot_top_get_val, tem_abort
tem_spatial_lua_vector_for_index calls aot_fun_close, aot_fun_do, aot_fun_open, aot_fun_put, aot_top_get_val, tem_abort
tem_spatial_lua_vector_for_treeids calls aot_fun_close, aot_fun_do, aot_fun_open, aot_fun_put, aot_top_get_val, tem_abort, tem_baryofid
tem_abort calls mpi_abort
tem_baryofid calls tem_coordofid, tem_elemsizelevel
tem_coordofid calls tem_levelof
tem_spatial_for_coord calls tem_spatial_lua_for
tem_spatial_for_treeids calls tem_spatial_lua_for
tem_spatial_scalar_for_index calls tem_spatial_lua_for, tem_spatial_for_coord
tem_spatial_vector_for_coord calls tem_spatial_lua_for
tem_spatial_vector_for_index calls tem_spatial_lua_for, tem_spatial_vector_for_coord
tem_spatial_vector_for_treeids calls tem_spatial_lua_for
tem_spatial_for calls tem_spatial_for_coord, tem_spatial_for_treeids, tem_spatial_scalar_for_index, tem_spatial_vector_for_coord, tem_spatial_vector_for_index, tem_spatial_vector_for_treeids
tem_spacetime_for_coord calls tem_spatial_for
tem_spacetime_for_treeids calls tem_spatial_for
tem_spacetime_scalar_for_index calls tem_spatial_for, tem_spacetime_for_coord
tem_spacetime_vector_for_coord calls tem_spatial_for
tem_spacetime_vector_for_index calls tem_spatial_for, tem_spacetime_vector_for_coord
tem_spacetime_vector_for_treeids calls tem_spatial_for
tem_spatial_scalar_storeval calls tem_spatial_for
tem_spatial_vector_storeval calls tem_spatial_for
tem_spacetime_for calls tem_spacetime_for_coord, tem_spacetime_for_treeids, tem_spacetime_scalar_for_index, tem_spacetime_vector_for_coord, tem_spacetime_vector_for_index, tem_spacetime_vector_for_treeids
tem_spatial_storeval calls tem_spatial_scalar_storeval, tem_spatial_vector_storeval
tem_spacetime_for_stcoord calls tem_spacetime_for_coord