tem_exchange_sparta – Treelm
tem_exchange_sparta Interface
6 statements
Source File
public interface tem_exchange_sparta
Calls
Called by
Module Procedures
private subroutine tem_exchange_long(me, val, nComponents, comm)
Arguments
Type Intent Optional Attributes Name
type(tem_sparta_type), intent(in) :: me
integer(kind=long_k), intent(inout), allocatable :: val(:)
integer, intent(in) :: nComponents
integer, intent(in) :: comm
private subroutine tem_exchange_double(me, val, nComponents, comm)
Arguments
Type Intent Optional Attributes Name
type(tem_sparta_type), intent(in) :: me
real(kind=double_k), intent(inout), allocatable :: val(:)
integer, intent(in) :: nComponents
integer, intent(in) :: comm
private subroutine tem_exchange_long2(me, val, nComponents, comm)
Arguments
Type Intent Optional Attributes Name
type(tem_sparta_type), intent(in) :: me
integer(kind=long_k), intent(inout), allocatable :: val(:,:)
integer, intent(in) :: nComponents
integer, intent(in) :: comm
private subroutine tem_exchange_double2(me, val, nComponents, comm)
Arguments
Type Intent Optional Attributes Name
type(tem_sparta_type), intent(in) :: me
real(kind=double_k), intent(inout), allocatable :: val(:,:)
integer, intent(in) :: nComponents
integer, intent(in) :: comm
Call graph
tem_exchange_sparta calls tem_exchange_double, tem_exchange_double2, tem_exchange_long, tem_exchange_long2
tem_exchange_double calls mpi_alltoallv, tem_abort
tem_exchange_double2 calls mpi_alltoallv
tem_exchange_long calls mpi_alltoallv, tem_abort
tem_exchange_long2 calls mpi_alltoallv
tem_abort calls mpi_abort
exchange_elements calls tem_exchange_sparta
load_tem calls exchange_elements
tem_restart_readheader calls load_tem
tem_load_restart calls tem_restart_readheader