tem_variable_load – Treelm
tem_variable_load Interface
4 statements
Source File
public interface tem_variable_load
Calls
Module Procedures
public subroutine tem_variable_load_vector(me, conf, parent, key, vError, nComp, load_solvervar)
Load an array of variables from the configuration.
Arguments
Type Intent Optional Attributes Name
type(tem_variable_type), intent(out), allocatable :: me(:)
The variable to read from the Lua script(conf) and fill
type(flu_State) :: conf
Lua handle connected to the script to read the table from
integer, intent(in), optional :: parent
A parent table handle in which to look the current variable up
character(len=*), intent(in), optional :: key
key for array of variables
integer, intent(out), allocatable :: vError(:)
if Error .ne. 0 is variable is not loaded successfully.
integer, optional :: nComp
If the variable is expected to have a certain number of components, this can be provided with this argument.
Read more…
procedure(tem_load_solverVar_method), optional :: load_solvervar
A method to load solver specific variables.
public subroutine tem_variable_load_single(me, conf, parent, iError, key, nComp, openTable, load_solvervar)
Reading a single variable from the Lua configuration.
Arguments
Type Intent Optional Attributes Name
type(tem_variable_type), intent(out) :: me
The variable to read from the Lua script(conf) and fill
type(flu_State) :: conf
Lua handle connected to the script to read the table from
integer, intent(in) :: parent
A parent table handle in which to look the current variable up
integer, intent(out) :: iError
if Error .ne. 0 is variable is not loaded successfully.
character(len=*), intent(in), optional :: key
key for a single variable
integer, optional :: nComp
If the variable is expected to have a certain number of components, this can be provided with this argument.
Read more…
logical, intent(in), optional :: openTable
if variable table is already opened, set openTable = .false.
procedure(tem_load_solverVar_method), optional :: load_solvervar
A method to load solver specific variables.
Call graph
tem_variable_load calls tem_variable_load_single, tem_variable_load_vector
tem_variable_load_single calls aot_get_val, aot_table_close, aot_table_open, tem_load_spacetime, load_variable_operation, tem_abort, tem_horizontalspacer, upper_to_lower
tem_variable_load_vector calls tem_variable_load_single, aot_table_close, aot_table_length, aot_table_open, tem_horizontalspacer
tem_load_spacetime calls tem_load_spacetime_single, tem_load_spacetime_table
load_variable_operation calls aot_get_val, aot_table_close, aot_table_open, tem_abort, tem_reduction_transient_load
tem_abort calls mpi_abort
tem_load_spacetime_single calls aot_get_val, aot_table_open, tem_abort, tem_load_spacetime_single, aot_exists, aot_fun_close, aot_fun_open, aot_reference_for, aot_type_of, tem_load_shape, load_spacetime_asconst, load_spacetime_predefined
tem_load_spacetime_table calls aot_table_close, aot_table_length, aot_table_open, tem_load_spacetime_single
tem_reduction_transient_load calls aot_get_val, aot_table_close, aot_table_open, tem_abort