tem_viscSpongeLayer_plane_for – Treelm
tem_viscSpongeLayer_plane_for Interface
4 statements
Source File
public interface tem_viscSpongeLayer_plane_for
Interface for viscous sponge layer plane
Calls
Called by
Module Procedures
private function viscSpongelayer_plane_for_coord(me, coord, n) result(res)
This function calculates the sigma for the planar viscosity spongelayer and multiply with targetState 'viscosity'. This function is currectly used to define viscosity sponge in musubi.
Arguments
Type Intent Optional Attributes Name
type(tem_spongeLayer_plane_type) :: me
Spacetime function to evaluate
real(kind=rk), intent(in) :: coord(n,3)
barycentric Ids of an elements. 1st index goes over number of elements and 2nd index goes over x,y,z coordinates
integer, intent(in) :: n
Number of arrays to return
Return Value real(kind=rk), (n)
return value
private function viscSpongelayer_plane_for_treeIDs(me, treeIds, tree, n) result(res)
This function calculates the sigma for the planar viscosity spongelayer and multiply with targetState 'viscosity' from treeid. This function is currectly used to define viscosity sponge in musubi.
Arguments
Type Intent Optional Attributes Name
type(tem_spongeLayer_plane_type) :: me
Spacetime function to evaluate
integer(kind=long_k), intent(in) :: treeIds(n)
treeIds of elements in given level
type(treelmesh_type), intent(in) :: tree
global treelm mesh
integer, intent(in) :: n
Number of arrays to return
Return Value real(kind=rk), (n)
return value
Call graph
tem_viscspongelayer_plane_for calls viscspongelayer_plane_for_coord, viscspongelayer_plane_for_treeids
viscspongelayer_plane_for_treeids calls tem_baryofid
tem_baryofid calls tem_coordofid, tem_elemsizelevel
tem_coordofid calls tem_levelof
tem_spatial_for_coord calls tem_viscspongelayer_plane_for
tem_spatial_for_treeids calls tem_viscspongelayer_plane_for
tem_spatial_for calls tem_spatial_for_coord, tem_spatial_for_treeids, tem_spatial_scalar_for_index
tem_spatial_scalar_for_index calls tem_spatial_for_coord
tem_spacetime_for_coord calls tem_spatial_for
tem_spacetime_for_treeids calls tem_spatial_for
tem_spacetime_scalar_for_index calls tem_spatial_for, tem_spacetime_for_coord
tem_spacetime_vector_for_coord calls tem_spatial_for
tem_spacetime_vector_for_index calls tem_spatial_for, tem_spacetime_vector_for_coord
tem_spacetime_vector_for_treeids calls tem_spatial_for
tem_spatial_scalar_storeval calls tem_spatial_for
tem_spatial_vector_storeval calls tem_spatial_for
tem_spacetime_for calls tem_spacetime_for_coord, tem_spacetime_for_treeids, tem_spacetime_scalar_for_index, tem_spacetime_vector_for_coord, tem_spacetime_vector_for_index, tem_spacetime_vector_for_treeids
tem_spatial_storeval calls tem_spatial_scalar_storeval, tem_spatial_vector_storeval
tem_spacetime_for_stcoord calls tem_spacetime_for_coord