tem_ParentOf – Treelm
tem_ParentOf Interface
4 statements
Source File
public interface tem_ParentOf
Calls
Called by
Module Procedures
private elemental function tem_directParent(TreeID) result(res)
This function delivers the parent ID of a given TreeID
Arguments
Type Intent Optional Attributes Name
integer(kind=long_k), intent(in) :: TreeID
current treeID
Return Value integer(kind=long_k)
result of function containing parent ID
private function tem_ParentAtLevel(TreeID, level) result(parentID)
This function provides the parent ID of a given tree ID on a given level.
Read more…
Arguments
Type Intent Optional Attributes Name
integer(kind=long_k), intent(in) :: TreeID
treeID of which the pID is requested
integer, intent(in) :: level
the level on which the pID is requested
Return Value integer(kind=long_k)
resulting parent ID
Call graph
tem_parentof calls tem_directparent, tem_parentatlevel
tem_parentatlevel calls tem_levelof
create_allparentneighbors calls tem_parentof, identify_elements, identify_stencilneigh
tem_adddep_up calls tem_parentof
tem_build_verticaldependencies calls tem_parentof
update_childneighborid calls tem_parentof
identify_elements calls create_allparentneighbors, identify_elements, identify_stencilneigh
request_remotehalos calls create_allparentneighbors, identify_stencilneigh
tem_create_leveldesc calls tem_build_verticaldependencies
tem_facedep_verticalup calls tem_adddep_up
tem_find_bcs_fromfiner calls update_childneighborid
add_ghostfromfiner calls tem_find_bcs_fromfiner, add_ghostfromfiner
build_levelelements calls identify_elements, identify_additionalneigh
communicate_elements calls request_remotehalos
identify_additionalneigh calls identify_elements
identify_stencilneigh calls identify_elements
tem_dimbydim_construction calls tem_create_leveldesc
tem_facedep_vertical calls tem_facedep_verticalup
identify_local_element calls add_ghostfromfiner
tem_build_face_info calls tem_dimbydim_construction, tem_facedep_vertical
tem_find_allelements calls build_levelelements, communicate_elements, identify_additionalneigh