tem_triangle_out – Treelm
tem_triangle_out Interface
4 statements
Source File
public interface tem_triangle_out
interface to write out triangles in lua format to a file
Calls
Called by
Module Procedures
private subroutine tem_triangle_out_scal(me, conf)
Write out a triangle shape in lua format
Arguments
Type Intent Optional Attributes Name
type(tem_triangle_type), intent(in) :: me
triangle types to write out
type(aot_out_type), intent(inout) :: conf
Aotus type handling the output to the file in lua format
private subroutine tem_triangle_out_vec(me, conf)
Write out an array of triangles in lua format Only if nTriangles <= 10
Arguments
Type Intent Optional Attributes Name
type(tem_triangle_type), intent(in) :: me(:)
triangle types to write out
type(aot_out_type), intent(inout) :: conf
Aotus type handling the output to the file in lua format
Call graph
tem_triangle_out calls tem_triangle_out_scal, tem_triangle_out_vec
tem_triangle_out_scal calls aot_out_close_table, aot_out_open_table, aot_out_val
tem_triangle_out_vec calls tem_triangle_out_scal, aot_out_close_table, aot_out_open_table, aot_out_val
tem_shape_out_scal calls tem_triangle_out
tem_shape_out calls tem_shape_out_scal, tem_shape_out_vec
tem_shape_out_vec calls tem_shape_out_scal
hvs_ascii_write_header calls tem_shape_out
tem_convergence_out_single calls tem_shape_out
tem_convergence_out calls tem_convergence_out_single
hvs_ascii_init calls hvs_ascii_write_header
hvs_asciispatial_init calls hvs_ascii_write_header
tem_convergence_dump_single calls tem_convergence_out_single
tem_convergence_out_vector calls tem_convergence_out_single