tem_stencil_dump – Treelm
tem_stencil_dump Interface
4 statements
Source File
public interface tem_stencil_dump
Calls
Called by
Module Procedures
private subroutine tem_stencilHeader_dump(me, nUnit)
Write element information to disk
Arguments
Type Intent Optional Attributes Name
type(tem_stencilHeader_type), intent(in) :: me
stencil header to be dumped
integer, intent(in), optional :: nUnit
private subroutine tem_stencilElement_dump(me, nUnit, neighID, tIDonly)
Write element information to disk
Arguments
Type Intent Optional Attributes Name
type(tem_stencilElement_type), intent(in) :: me
stencil element to be dumped
integer, intent(in) :: nUnit
unit to dump to
integer(kind=long_k), intent(in), optional, allocatable :: neighID(:)
neighbor ID
logical, intent(in), optional :: tIDonly
only use tree IDs
Call graph
tem_stencil_dump calls tem_stencilelement_dump, tem_stencilheader_dump
tem_stencilelement_dump calls tem_printarray
tem_stencilheader_dump calls tem_tostr
tem_tostr calls tem_b2str, tem_b2str_arr, tem_d2str, tem_d2str_arr, tem_i2str, tem_i2str_arr, tem_l2str, tem_l2str_arr, tem_r2str, tem_r2str_arr
tem_dimbydim_construction calls tem_stencil_dump
tem_element_dump calls tem_stencil_dump
tem_build_face_info calls tem_dimbydim_construction
tem_elemlist_dump calls tem_element_dump
build_levelelements calls tem_elemlist_dump
communicate_elements calls tem_elemlist_dump
tem_init_elemlevels calls tem_elemlist_dump
tem_create_leveldesc calls tem_init_elemlevels
tem_find_allelements calls build_levelelements, communicate_elements