tem_varSys_out – Treelm
tem_varSys_out Interface
4 statements
Source File
public interface tem_varSys_out
Calls
Called by
Module Procedures
public subroutine tem_varSys_out_vector(me, conf, dumpVarPos)
Allows the output of array of varSys to lua out
Arguments
Type Intent Optional Attributes Name
type(tem_varSys_type), intent(in) :: me(:)
variable to write into the lua file
type(aot_out_type), intent(inout) :: conf
aotus type handling the output to the file in lua format
integer, intent(in), optional :: dumpVarPos(:)
Position of variables to dump
public subroutine tem_varSys_out_single(me, conf, dumpVarPos, level)
Write the system of variables description into a Lua file. use the aotus_out functions for doing so, in order to obtain a neatly formatted lua file
Arguments
Type Intent Optional Attributes Name
type(tem_varSys_type), intent(in) :: me
Variable system to write out
type(aot_out_type), intent(inout) :: conf
Aotus type handling the output to the file in lua format
integer, intent(in), optional :: dumpVarPos(:)
Position of variables to dump
integer, intent(in), optional :: level
to dump varSys with key or without key
Call graph
tem_varsys_out calls tem_varsys_out_single, tem_varsys_out_vector
tem_varsys_out_single calls aot_out_close_table, aot_out_open_table, aot_out_val
tem_varsys_out_vector calls tem_varsys_out_single, aot_out_close_table, aot_out_open_table
hvs_ascii_write_header calls tem_varsys_out
tem_restart_writeheader calls tem_varsys_out
hvs_ascii_init calls hvs_ascii_write_header
hvs_asciispatial_init calls hvs_ascii_write_header
tem_restart_closewrite calls tem_restart_writeheader
tem_restart_openwrite calls tem_restart_writeheader
hvs_output_close calls tem_restart_closewrite
hvs_output_init calls hvs_ascii_init, hvs_asciispatial_init
hvs_output_open calls tem_restart_openwrite
tem_init_tracker calls hvs_output_init
tem_tracker calls hvs_output_close, hvs_output_open