tem_variable_dump – Treelm
tem_variable_dump Interface
4 statements
Source File
public interface tem_variable_dump
Calls
Module Procedures
public subroutine tem_variable_dump_vector(me, outUnit)
Dumps array of variable to given unit
Arguments
Type Intent Optional Attributes Name
type(tem_variable_type), intent(in) :: me(:)
variable to write into the lua file
integer, intent(in) :: outUnit
unit to write to
public subroutine tem_variable_dump_single(me, outUnit)
Dump single variable to given unit
Arguments
Type Intent Optional Attributes Name
type(tem_variable_type), intent(in) :: me
variable to write into the lua file
integer, intent(in) :: outUnit
unit to write to
Call graph
tem_variable_dump calls tem_variable_dump_single, tem_variable_dump_vector
tem_variable_dump_single calls aot_out_close, aot_out_open, tem_variable_out_single
tem_variable_dump_vector calls aot_out_close, aot_out_open, tem_variable_out_vector
tem_variable_out_single calls aot_out_close_table, aot_out_open_table, aot_out_val
tem_variable_out_vector calls tem_variable_out_single, aot_out_close_table, aot_out_open_table