tem_spatial_for – Treelm
tem_spatial_for Interface
8 statements
Source File
public interface tem_spatial_for
Calls
Called by
Module Procedures
private function tem_spatial_for_treeIDs(me, treeIds, tree, n) result(res)
This function invokes different spatial boundary kinds like constant, lua function or predefined Fortran function for given treeIDs
Read more…
Arguments
Type Intent Optional Attributes Name
type(tem_spatial_type) :: me
spatial type for given boundary state
integer(kind=long_k), intent(in) :: treeIds(n)
treeIds of elements in given level
type(treelmesh_type), intent(in) :: tree
global treelm mesh
integer, intent(in) :: n
number of return values
Return Value real(kind=rk), (n)
return value of a function
private function tem_spatial_for_coord(me, coord, n) result(res)
This function invokes different spatial boundary kinds like constant, lua function or predefined Fortran function for given coord
Read more…
Arguments
Type Intent Optional Attributes Name
type(tem_spatial_type), intent(in) :: me
spatial type for given boundary state
real(kind=rk), intent(in) :: coord(n,3)
barycentric Ids of an elements. 1st index goes over number of elements and 2nd index goes over x,y,z coordinates
integer, intent(in) :: n
number of return values
Return Value real(kind=rk), (n)
return value of a function
private function tem_spatial_vector_for_treeIDs(me, treeIds, tree, n, ncomp) result(res)
Arguments
Type Intent Optional Attributes Name
type(tem_spatial_type) :: me
spatial type for given boundary state
integer(kind=long_k), intent(in) :: treeIds(n)
treeIds of elements in given level
type(treelmesh_type), intent(in) :: tree
global treelm mesh
integer, intent(in) :: n
number of return values
integer, intent(in) :: ncomp
number of components in the resulting vector
Return Value real(kind=rk), (n,ncomp)
return value of a function
private function tem_spatial_vector_for_coord(me, coord, n, ncomp) result(res)
This function invokes different spatial boundary kinds like constant, lua function or predefined Fortran function for given coord
Read more…
Arguments
Type Intent Optional Attributes Name
type(tem_spatial_type) :: me
spatial type for given boundary state
real(kind=rk), intent(in) :: coord(n,3)
barycentric Ids of an elements. 1st index goes over number of elements and 2nd index goes over x,y,z coordinates
integer, intent(in) :: n
number of return values
integer, intent(in) :: ncomp
number of components per returned value
Return Value real(kind=rk), (n,ncomp)
return value of a function
private function tem_spatial_scalar_for_index(me, grwPnt, idx, nVals, iLevel) result(res)
This function returns pre-stored value at given idx or evaluate a spatial function for a point at given idx in growing array of points. Return value is a scalar.
Arguments
Type Intent Optional Attributes Name
type(tem_spatial_type), intent(in) :: me
spatial type
type(tem_grwPoints_type), intent(in) :: grwPnt
growing array of all spatial point of a variable
integer, intent(in) :: idx(nVals)
Index position to return a pre-store value or to compute
integer, intent(in) :: nVals
number of return values
integer, intent(in) :: iLevel
Level to which the evaluated values to be returned
Return Value real(kind=rk), (nVals)
return value of a function
private function tem_spatial_vector_for_index(me, grwPnt, idx, nVals, iLevel, nComps) result(res)
This function returns pre-stored value at given idx or evaluate a spatial function for a point at given idx. Return value is a vector.
Arguments
Type Intent Optional Attributes Name
type(tem_spatial_type), intent(in) :: me
spatial type
type(tem_grwPoints_type), intent(in) :: grwPnt
growing array of all spatial point of a variable
integer, intent(in) :: idx(nVals)
Index position to return a pre-store value or to compute
integer, intent(in) :: nVals
number of return values
integer, intent(in) :: iLevel
Level to which the evaluated values to be returned
integer, intent(in) :: nComps
number of components per returned value
Return Value real(kind=rk), (nVals,nComps)
return value of a function
Call graph
tem_spatial_for calls tem_spatial_for_coord, tem_spatial_for_treeids, tem_spatial_scalar_for_index, tem_spatial_vector_for_coord, tem_spatial_vector_for_index, tem_spatial_vector_for_treeids
tem_spacetime_for_coord calls tem_spatial_for
tem_spacetime_for_treeids calls tem_spatial_for
tem_spacetime_scalar_for_index calls tem_spatial_for, tem_spacetime_for_coord
tem_spacetime_vector_for_coord calls tem_spatial_for
tem_spacetime_vector_for_index calls tem_spatial_for, tem_spacetime_vector_for_coord
tem_spacetime_vector_for_treeids calls tem_spatial_for
tem_spatial_scalar_storeval calls tem_spatial_for
tem_spatial_vector_storeval calls tem_spatial_for
tem_spacetime_for calls tem_spacetime_for_coord, tem_spacetime_for_treeids, tem_spacetime_scalar_for_index, tem_spacetime_vector_for_coord, tem_spacetime_vector_for_index, tem_spacetime_vector_for_treeids, tem_spacetime_for_stcoord
tem_spatial_storeval calls tem_spatial_scalar_storeval, tem_spatial_vector_storeval
tem_spacetime_for_stcoord calls tem_spacetime_for_coord
evaluate_add_spacetime_scalarbycoordinate calls tem_spacetime_for
evaluate_add_spacetime_scalarbytreeid calls tem_spacetime_for
evaluate_add_spacetime_vectorbycoordinate calls tem_spacetime_for
evaluate_add_spacetime_vectorbytreeid calls tem_spacetime_for
evaluate_first_spacetime_scalarbycoordinate calls tem_spacetime_for
evaluate_first_spacetime_scalarbytreeid calls tem_spacetime_for
evaluate_first_spacetime_vectorbycoordinate calls tem_spacetime_for
evaluate_first_spacetime_vectorbytreeid calls tem_spacetime_for
evaluate_foag_spacetime_scalarbycoordinate calls tem_spacetime_for
evaluate_foag_spacetime_scalarbytreeid calls tem_spacetime_for
evaluate_foag_spacetime_vectorbycoordinate calls tem_spacetime_for
evaluate_foag_spacetime_vectorbytreeid calls tem_spacetime_for
get_valofindex_add_scalar_spacetime calls tem_spacetime_for
get_valofindex_add_vector_spacetime calls tem_spacetime_for
get_valofindex_first_scalar_spacetime calls tem_spacetime_for
get_valofindex_first_vector_spacetime calls tem_spacetime_for
get_valofindex_foag_scalar_spacetime calls tem_spacetime_for
get_valofindex_foag_vector_spacetime calls tem_spacetime_for
setup_indices_spacetime calls tem_spatial_storeval
tem_update_surfpos calls tem_spacetime_for