tem_load_miescatter_displacementfieldz – Treelm
tem_load_miescatter_displacementfieldz Interface
3 statements
Source File
public interface tem_load_miescatter_displacementfieldz
Calls
Called by
Module Procedures
private subroutine tem_load_miescatter(conf, thandle, me)
load gauss pulse variables to set initial condition
Arguments
Type Intent Optional Attributes Name
type(flu_State) :: conf
lua state type
integer, intent(in) :: thandle
aotus parent handle
type(tem_miescatter_field_type), intent(out) :: me
Global gauss pulse data type
Call graph
tem_load_miescatter_displacementfieldz calls tem_load_miescatter
tem_load_miescatter calls aot_get_val, aot_table_close, aot_table_open, tem_abort, tem_init_data
tem_abort calls mpi_abort
tem_init_data calls bessel_jn_derivative, hankel2_n, hankel2_n_derivative, tem_get_ncoeffs_miescat
hankel2_n_derivative calls hankel2_n
tem_get_ncoeffs_miescat calls aot_get_val, tem_abort
load_spacetime_predefined calls tem_load_miescatter_displacementfieldz, tem_load_spatial
load_spatial_predefined calls tem_load_miescatter_displacementfieldz
tem_load_spacetime_single calls load_spacetime_predefined, tem_load_spacetime_single
tem_load_spatial calls load_spatial_predefined
tem_load_spacetime calls tem_load_spacetime_single, tem_load_spacetime_table
tem_load_ic calls tem_load_spatial
tem_load_spacetime_table calls tem_load_spacetime_single
tem_variable_load_single calls tem_load_spacetime
tem_variable_loadmapping_single calls tem_load_spacetime