tem_varSys_dump – Treelm
tem_varSys_dump Interface
4 statements
Source File
public interface tem_varSys_dump
Calls
Called by
Module Procedures
public subroutine tem_varSys_dump_vector(me, outUnit, dumpVarPos)
Dumps array of varSys to given unit
Arguments
Type Intent Optional Attributes Name
type(tem_varSys_type), intent(in) :: me(:)
variable to write into the lua file
integer, intent(inout) :: outUnit
unit to write to
integer, intent(in), optional :: dumpVarPos(:)
Position of variables to dump
public subroutine tem_varSys_dump_single(me, outUnit, dumpVarPos)
Dump single varSys to given unit
Arguments
Type Intent Optional Attributes Name
type(tem_varSys_type), intent(in) :: me
variable to write into the lua file
integer, intent(inout) :: outUnit
unit to write to
integer, intent(in), optional :: dumpVarPos(:)
Position of variables to dump
Call graph
tem_varsys_dump calls tem_varsys_dump_single, tem_varsys_dump_vector
tem_varsys_dump_single calls aot_out_close, aot_out_open, tem_varsys_out_single
tem_varsys_dump_vector calls aot_out_close, aot_out_open, tem_varsys_out_vector
tem_varsys_out_single calls aot_out_close_table, aot_out_open_table, aot_out_val
tem_varsys_out_vector calls tem_varsys_out_single, aot_out_close_table, aot_out_open_table
tem_restart_readheader calls tem_varsys_dump
tem_load_restart calls tem_restart_readheader