tem_varSys_append_stfun – Treelm
tem_varSys_append_stfun Interface
4 statements
Source File
public interface tem_varSys_append_stfun
Calls
Called by
Module Procedures
private subroutine tem_varSys_append_stFunVar(stFunVar, varSys, st_funList, solverData_evalElem)
subroutine to add the variables from the input lua script to the varsys
Arguments
Type Intent Optional Attributes Name
type(tem_variable_type), intent(in) :: stFunVar
variables defined in the lua file
type(tem_varSys_type), intent(inout) :: varSys
global variable system to which stFunVar to be appended
type(tem_st_fun_linkedList_type), intent(inout) :: st_funList
contains spacetime functions of all variables
type(tem_varSys_solverData_evalElem_type), intent(in), optional :: solverData_evalElem
A setter routine that allows the caller to define routine for the construction of an element representation.
private subroutine tem_varSys_append_stFun_raw(varSys, stFun, varname, nComp, evaltype, st_funList, solverData_evalElem)
subroutine to add the variables from the input lua script to the varsys
Arguments
Type Intent Optional Attributes Name
type(tem_varSys_type), intent(inout) :: varSys
global variable system to which stFunVar to be appended
type(tem_spacetime_fun_type), intent(in), pointer :: stFun(:)
variables defined in the lua file
character(len=*), intent(in) :: varname
integer, intent(in), optional :: nComp
character(len=*), intent(in), optional :: evaltype
type(tem_st_fun_linkedList_type), intent(inout), optional :: st_funList
contains spacetime functions of all variables
type(tem_varSys_solverData_evalElem_type), intent(in), optional :: solverData_evalElem
A setter routine that allows the caller to define routine for the construction of an element representation.
Call graph
tem_varsys_append_stfun calls tem_varsys_append_stfun_raw, tem_varsys_append_stfunvar
tem_varsys_append_stfun_raw calls append, tem_abort, tem_varsys_append_dervar, tem_varsys_assignevaltype
tem_varsys_append_stfunvar calls append, tem_abort, tem_varsys_append_dervar, tem_varsys_assignevaltype
append calls append_da_label, append_da_veclabel
tem_abort calls mpi_abort
tem_varsys_append_dervar calls append, positionofval
positionofval calls posofval_label
append_da_label calls expand, sortedposofval
append_da_veclabel calls expand
tem_variable_loadmapping_single calls tem_varsys_append_stfun
tem_varsys_append_luavar calls tem_varsys_append_stfun
tem_variable_loadmapping calls tem_variable_loadmapping_single, tem_variable_loadmapping_vector
tem_variable_loadmapping_vector calls tem_variable_loadmapping_single
tem_load_bc_state calls tem_variable_loadmapping