tem_spongeLayer_box2d_for – Treelm
tem_spongeLayer_box2d_for Interface
6 statements
Source File
public interface tem_spongeLayer_box2d_for
Interface for sponge layer box 2d
Calls
Called by
Module Procedures
private function spongelayer_box2d_scalar_for_coord(me, coord, n) result(res)
This function returns the sigma for the 2d box shape spongelayer
Arguments
Type Intent Optional Attributes Name
type(tem_spongeLayer_box_type) :: me
Spacetime function to evaluate
real(kind=rk), intent(in) :: coord(n,3)
barycentric Ids of an elements. 1st index goes over number of elements and 2nd index goes over x,y,z coordinates
integer, intent(in) :: n
Number of arrays to return
Return Value real(kind=rk), (n)
return value
private function spongelayer_box2d_scalar_for_treeIDs(me, treeIds, tree, n) result(res)
This function returns the sigma for the spongelayer from treeids
Arguments
Type Intent Optional Attributes Name
type(tem_spongeLayer_box_type) :: me
Spacetime function to evaluate
integer(kind=long_k), intent(in) :: treeIds(n)
treeIds of elements in given level
type(treelmesh_type), intent(in) :: tree
global treelm mesh
integer, intent(in) :: n
Number of arrays to return
Return Value real(kind=rk), (n)
return value
private function spongelayer_box2d_vector_for_coord(me, ncomp, coord, n) result(res)
This function calculates the sigma for the spongelayer and fills up the res with the target state
Arguments
Type Intent Optional Attributes Name
type(tem_spongeLayer_box_type) :: me
Spacetime function to evaluate
integer, intent(in) :: ncomp
Number of entrys in each array
real(kind=rk), intent(in) :: coord(n,3)
barycentric Ids of an elements. 1st index goes over number of elements and 2nd index goes over x,y,z coordinates
integer, intent(in) :: n
Number of arrays to return
Return Value real(kind=rk), (n,ncomp)
return value
private function spongelayer_box2d_vector_for_treeIDs(me, ncomp, treeIds, tree, n) result(res)
This function calculates the sigma for the spongelayer and fills up the res with the target state
Arguments
Type Intent Optional Attributes Name
type(tem_spongeLayer_box_type) :: me
Spacetime function to evaluate
integer, intent(in) :: ncomp
Number of entrys in each array
integer(kind=long_k), intent(in) :: treeIds(n)
treeIds of elements in given level
type(treelmesh_type), intent(in) :: tree
global treelm mesh
integer, intent(in) :: n
Number of arrays to return
Return Value real(kind=rk), (n,ncomp)
return value
Call graph
tem_spongelayer_box2d_for calls spongelayer_box2d_scalar_for_coord, spongelayer_box2d_scalar_for_treeids, spongelayer_box2d_vector_for_coord, spongelayer_box2d_vector_for_treeids
spongelayer_box2d_scalar_for_coord calls spongelayer_box2d_expon_for_coord, spongelayer_box2d_roundcornerpolyn5_for_coord, spongelayer_box2d_roundcornerpolyn6_for_coord, spongelayer_box2d_sharpcornerpolyn5_for_coord, spongelayer_box2d_sharpcornerpolyn6_for_coord
spongelayer_box2d_scalar_for_treeids calls spongelayer_box2d_expon_for_treeids, spongelayer_box2d_roundcornerpolyn5_for_treeids, spongelayer_box2d_roundcornerpolyn6_for_treeids, spongelayer_box2d_sharpcornerpolyn5_for_treeids, spongelayer_box2d_sharpcornerpolyn6_for_treeids
spongelayer_box2d_vector_for_coord calls spongelayer_box2d_scalar_for_coord
spongelayer_box2d_vector_for_treeids calls spongelayer_box2d_scalar_for_treeids
spongelayer_box2d_expon_for_treeids calls spongelayer_box2d_expon_for_coord, tem_baryofid
spongelayer_box2d_roundcornerpolyn5_for_treeids calls spongelayer_box2d_roundcornerpolyn5_for_coord, tem_baryofid
spongelayer_box2d_roundcornerpolyn6_for_treeids calls spongelayer_box2d_roundcornerpolyn6_for_coord, tem_baryofid
spongelayer_box2d_sharpcornerpolyn5_for_treeids calls spongelayer_box2d_sharpcornerpolyn5_for_coord, tem_baryofid
spongelayer_box2d_sharpcornerpolyn6_for_treeids calls spongelayer_box2d_sharpcornerpolyn6_for_coord, tem_baryofid
tem_baryofid calls tem_coordofid, tem_elemsizelevel
tem_spatial_for_coord calls tem_spongelayer_box2d_for
tem_spatial_for_treeids calls tem_spongelayer_box2d_for
tem_spatial_vector_for_coord calls tem_spongelayer_box2d_for
tem_spatial_vector_for_treeids calls tem_spongelayer_box2d_for
tem_spatial_for calls tem_spatial_for_coord, tem_spatial_for_treeids, tem_spatial_vector_for_coord, tem_spatial_vector_for_treeids, tem_spatial_scalar_for_index, tem_spatial_vector_for_index
tem_spatial_scalar_for_index calls tem_spatial_for_coord
tem_spatial_vector_for_index calls tem_spatial_vector_for_coord
tem_spacetime_for_coord calls tem_spatial_for
tem_spacetime_for_treeids calls tem_spatial_for
tem_spacetime_scalar_for_index calls tem_spatial_for, tem_spacetime_for_coord
tem_spacetime_vector_for_coord calls tem_spatial_for
tem_spacetime_vector_for_index calls tem_spatial_for, tem_spacetime_vector_for_coord
tem_spacetime_vector_for_treeids calls tem_spatial_for
tem_spatial_scalar_storeval calls tem_spatial_for
tem_spatial_vector_storeval calls tem_spatial_for
tem_spacetime_for calls tem_spacetime_for_coord, tem_spacetime_for_treeids, tem_spacetime_scalar_for_index, tem_spacetime_vector_for_coord, tem_spacetime_vector_for_index, tem_spacetime_vector_for_treeids
tem_spatial_storeval calls tem_spatial_scalar_storeval, tem_spatial_vector_storeval
tem_spacetime_for_stcoord calls tem_spacetime_for_coord