tem_load_canonicalND – Treelm
tem_load_canonicalND Interface
4 statements
Source File
public interface tem_load_canonicalND
interface to load canonical objects
Calls
Called by
Module Procedures
private subroutine tem_load_oneCanonicalND(me, transform, conf, thandle, reqSegments)
Read one canonical object definition into a tem_canonicalND_type from a lua table.
Arguments
Type Intent Optional Attributes Name
type(tem_canonicalND_type), intent(out) :: me
contains canonicalND data
type(tem_transformation_type), intent(in) :: transform
transformation for spatial object
type(flu_State) :: conf
lua state
integer, intent(in) :: thandle
lua table identification
logical, intent(in), optional :: reqSegments
Is true if use_get_point is true in output table
private subroutine tem_load_canonicalND_vec(me, transform, conf, thandle, reqSegments)
Loading canonicalNDs from the config file valid definitions:
Arguments
Type Intent Optional Attributes Name
type(tem_canonicalND_type), intent(out), allocatable :: me(:)
the array of canonical objects which to read in (and first allocate)
type(tem_transformation_type), intent(in) :: transform
transformation for spatial object
type(flu_State) :: conf
lua config handle
integer, intent(in) :: thandle
table handle from which to read
logical, intent(in), optional :: reqSegments
Is true if use_get_point is true in output table
Call graph
tem_load_canonicalnd calls tem_load_canonicalnd_vec, tem_load_onecanonicalnd
tem_load_canonicalnd_vec calls tem_load_onecanonicalnd, aot_table_close, aot_table_length, aot_table_open, tem_abort
tem_load_onecanonicalnd calls aot_get_val, aot_table_close, aot_table_length, aot_table_open, tem_tostr, tem_transformcanond, tem_abort, tem_createbox, tem_createplane, upper_to_lower
tem_tostr calls tem_b2str, tem_b2str_arr, tem_d2str, tem_d2str_arr, tem_i2str, tem_i2str_arr, tem_l2str, tem_l2str_arr, tem_r2str, tem_r2str_arr
tem_transformcanond calls transformcanond, transformcanond_single
tem_abort calls mpi_abort
tem_createbox calls tem_createplane
tem_createplane calls cross_product3d
transformcanond calls transformcanond_single
tem_load_shape_single calls tem_load_canonicalnd
tem_load_shape calls tem_load_shape_single, tem_load_shapes
tem_load_shapes calls tem_load_shape_single
load_spatial_parabol calls tem_load_shape
tem_load_convergenceheader calls tem_load_shape
tem_load_spacetime_single calls tem_load_shape, tem_load_spacetime_single
tem_load_trackingconfig calls tem_load_shape
tem_load_spacetime calls tem_load_spacetime_single
load_spatial_predefined calls load_spatial_parabol
tem_convergence_load calls tem_load_convergenceheader
tem_load_spacetime_table calls tem_load_spacetime_single
tem_load_tracking calls tem_load_trackingconfig