tem_spatial_storeVal – Treelm
tem_spatial_storeVal Interface
4 statements
Source File
public interface tem_spatial_storeVal
Calls
Called by
Module Procedures
private subroutine tem_spatial_scalar_storeVal(me, coord, nVals, iLevel)
This routine evaluate scalar spatial function and store its value in growing array
Arguments
Type Intent Optional Attributes Name
type(tem_spatial_type), intent(inout) :: me
spatial type for given boundary state
real(kind=rk), intent(in) :: coord(nVals,3)
barycentric Ids of an elements. 1st index goes over number of elements and 2nd index goes over x,y,z coordinates
integer, intent(in) :: nVals
number of return values
integer, intent(in) :: iLevel
Level to which the evaluated values to be stored
private subroutine tem_spatial_vector_storeVal(me, coord, nVals, iLevel, nComps)
This routine evaluate vector spatial function and store its value in growing array with access Array Of Structure pattern (iVal-1)*nComps + iComp
Arguments
Type Intent Optional Attributes Name
type(tem_spatial_type), intent(inout) :: me
spatial type for given boundary state
real(kind=rk), intent(in) :: coord(nVals,3)
barycentric Ids of an elements. 1st index goes over number of elements and 2nd index goes over x,y,z coordinates
integer, intent(in) :: nVals
number of return values
integer, intent(in) :: iLevel
Level to which the evaluated values to be stored
integer, intent(in) :: nComps
number of components per returned value
Call graph
tem_spatial_storeval calls tem_spatial_scalar_storeval, tem_spatial_vector_storeval
tem_spatial_scalar_storeval calls append, tem_spatial_for, truncate
tem_spatial_vector_storeval calls append, tem_spatial_for, truncate
append calls append_arrayga2d_real, append_singlega2d_real
tem_spatial_for calls tem_spatial_for_coord, tem_spatial_for_treeids, tem_spatial_scalar_for_index, tem_spatial_vector_for_coord, tem_spatial_vector_for_index, tem_spatial_vector_for_treeids
truncate calls truncate_ga_char
setup_indices_spacetime calls tem_spatial_storeval