tem_reduction_spatial_out – Treelm
tem_reduction_spatial_out Interface
4 statements
Source File
public interface tem_reduction_spatial_out
Calls
Called by
Module Procedures
private subroutine tem_reduction_spatial_out_vector(me, conf)
Allows the output of array of reduction to lua out
Arguments
Type Intent Optional Attributes Name
type(tem_reduction_spatial_type), intent(in) :: me(:)
reduction to write into the lua file
type(aot_out_type), intent(inout) :: conf
aotus type handling the output to the file in lua format
private subroutine tem_reduction_spatial_out_single(me, conf)
Allows the output of the single reduction to lua out.
Read more…
Arguments
Type Intent Optional Attributes Name
type(tem_reduction_spatial_type), intent(in) :: me
reduction to write into the lua file
type(aot_out_type), intent(inout) :: conf
aotus type handling the output to the file in lua format
Call graph
tem_reduction_spatial_out calls tem_reduction_spatial_out_single, tem_reduction_spatial_out_vector
tem_reduction_spatial_out_single calls aot_out_val
tem_reduction_spatial_out_vector calls aot_out_val
tem_convergence_out_single calls tem_reduction_spatial_out
tem_convergence_out calls tem_convergence_out_single, tem_convergence_out_vector
tem_convergence_dump_single calls tem_convergence_out_single
tem_convergence_out_vector calls tem_convergence_out_single
tem_convergence_dump calls tem_convergence_dump_single, tem_convergence_dump_vector
tem_convergence_dump_vector calls tem_convergence_out_vector