tem_load_miescatter_magneticfieldx – Treelm
tem_load_miescatter_magneticfieldx Interface
3 statements
Source File
public interface tem_load_miescatter_magneticfieldx
Calls
Called by
Module Procedures
private subroutine tem_load_miescatter(conf, thandle, me)
load gauss pulse variables to set initial condition
Arguments
Type Intent Optional Attributes Name
type(flu_State) :: conf
lua state type
integer, intent(in) :: thandle
aotus parent handle
type(tem_miescatter_field_type), intent(out) :: me
Global gauss pulse data type
Call graph
tem_load_miescatter_magneticfieldx calls tem_load_miescatter
tem_load_miescatter calls tem_abort
tem_abort calls mpi_abort
load_spacetime_predefined calls tem_load_miescatter_magneticfieldx, tem_load_spatial
load_spatial_predefined calls tem_load_miescatter_magneticfieldx
tem_load_spacetime_single calls load_spacetime_predefined, tem_load_spacetime_single
tem_load_spatial calls load_spatial_predefined
tem_load_spacetime calls tem_load_spacetime_single, tem_load_spacetime_table
tem_load_ic calls tem_load_spatial
tem_load_spacetime_table calls tem_load_spacetime_single
tem_variable_load_single calls tem_load_spacetime
tem_variable_loadmapping_single calls tem_load_spacetime