tem_spacetime_for – Treelm
tem_spacetime_for Interface
9 statements
Source File
public interface tem_spacetime_for
Calls
Called by
Module Procedures
private function tem_spacetime_for_treeIDs(me, treeIDs, time, tree, n) result(res)
This function compute space time function for given list of treeIDs
Read more…
Arguments
Type Intent Optional Attributes Name
type(tem_spacetime_fun_type) :: me
Spacetime function to evaluate
integer(kind=long_k), intent(in) :: treeIDs(n)
TreeIDs where to evaluate the function
type(tem_time_type), intent(in) :: time
timer object incl. the current time information
type(treelmesh_type), intent(in) :: tree
Global treelmesh to look for positions in
integer, intent(in) :: n
Number of values to return
Return Value real(kind=rk), (n)
return value of the function
private function tem_spacetime_vector_for_treeIDs(me, treeIDs, time, tree, n, ncomp) result(res)
This function compute space time function that give bach a table of results for given list of treeIDs
Read more…
Arguments
Type Intent Optional Attributes Name
type(tem_spacetime_fun_type) :: me
Spacetime function to evaluate
integer(kind=long_k), intent(in) :: treeIDs(n)
TreeIDs where to evaluate the function
type(tem_time_type), intent(in) :: time
timer object incl. the current time information
type(treelmesh_type), intent(in) :: tree
Global treelmesh to look for positions in
integer, intent(in) :: n
Number of tables to return
integer, intent(in) :: ncomp
Number of values in a Table
Return Value real(kind=rk), (n,ncomp)
return value of the function
private function tem_spacetime_for_coord(me, coord, time, n) result(res)
This function computes the space time function for a given list of coordinates
Arguments
Type Intent Optional Attributes Name
type(tem_spacetime_fun_type) :: me
Spacetime function to evaluate
real(kind=rk), intent(in) :: coord(n,3)
barycentric Ids of an elements. 1st index goes over number of elements and 2nd index goes over x,y,z coordinates
type(tem_time_type), intent(in) :: time
timer object incl. the current time information
integer, intent(in) :: n
Number of values to return
Return Value real(kind=rk), (n)
return value of the function
private function tem_spacetime_vector_for_coord(me, coord, time, n, ncomp) result(res)
This function computes the space time function that gives back an array for a given list of coordinates
Arguments
Type Intent Optional Attributes Name
type(tem_spacetime_fun_type) :: me
Spacetime function to evaluate
real(kind=rk), intent(in) :: coord(n,3)
barycentric Ids of an elements. 1st index goes over number of elements and 2nd index goes over x,y,z coordinates
type(tem_time_type), intent(in) :: time
timer object incl. the current time information
integer, intent(in) :: n
Number of arrays to return
integer, intent(in) :: ncomp
Number of entrys in each array
Return Value real(kind=rk), (n,ncomp)
return value of the function
private function tem_spacetime_for_stcoord(me, stCoord, n) result(res)
This function computes the space time function for given list of space-time coordinates.
Read more…
Arguments
Type Intent Optional Attributes Name
type(tem_spacetime_fun_type) :: me
Spacetime function to evaluate
real(kind=rk), intent(in) :: stCoord(n,4)
barycentric Ids of an elements. 1st index goes over number of elements and 2nd index goes over x,y,z,t coordinates
integer, intent(in) :: n
Number of values to return
Return Value real(kind=rk), (n)
return value of the function
private function tem_spacetime_scalar_for_index(me, grwPnt, idx, nVals, iLevel, time) result(res)
This function returns pre-stored value at given idx if spacetime function is predefined apesmate else evaluate a spacetime function for a point at given idx in growing array of points. Return value is a scalar.
Arguments
Type Intent Optional Attributes Name
type(tem_spacetime_fun_type), intent(in) :: me
spacetime type
type(tem_grwPoints_type), intent(in) :: grwPnt
growing array of all spacetime point of a variable
integer, intent(in) :: idx(nVals)
Index position to return a pre-store value or to compute
integer, intent(in) :: nVals
number of return values
integer, intent(in) :: iLevel
Level to access stored value in aps_coupling
type(tem_time_type), intent(in) :: time
timer object incl. the current time information
Return Value real(kind=rk), (nVals)
return value of a function
private function tem_spacetime_vector_for_index(me, grwPnt, idx, nVals, iLevel, time, nComps) result(res)
This function returns pre-stored value at given idx if spacetime function is predefined apesmate else evaluate a spacetime function for a point at given idx in growing array of points. Return value is a vector.
Arguments
Type Intent Optional Attributes Name
type(tem_spacetime_fun_type), intent(in) :: me
spacetime type
type(tem_grwPoints_type), intent(in) :: grwPnt
growing array of all spacetime point of a variable
integer, intent(in) :: idx(nVals)
Index position to return a pre-store value or to compute
integer, intent(in) :: nVals
number of return values
integer, intent(in) :: iLevel
Level to which the evaluated values to be returned
type(tem_time_type), intent(in) :: time
timer object incl. the current time information
integer, intent(in) :: nComps
number of components per returned value
Return Value real(kind=rk), (nVals,nComps)
return value of a function
Call graph
tem_spacetime_for calls tem_spacetime_for_coord, tem_spacetime_for_stcoord, tem_spacetime_for_treeids, tem_spacetime_scalar_for_index, tem_spacetime_vector_for_coord, tem_spacetime_vector_for_index, tem_spacetime_vector_for_treeids
tem_spacetime_for_coord calls tem_spacetime_lua_for, tem_spatial_for, tem_abort, tem_eval_acoustic_pulse, tem_eval_cylindricalwave, tem_eval_miescatter_displz, tem_eval_miescatter_magnx, tem_eval_miescatter_magny, tem_polygon_material_movement_multi, tem_polygon_material_movement_single, tem_temporal_for
tem_spacetime_for_stcoord calls tem_spacetime_for_coord
tem_spacetime_for_treeids calls tem_spacetime_lua_for, tem_spatial_for, tem_abort, tem_temporal_for
tem_spacetime_scalar_for_index calls tem_spacetime_for_coord, ids, tem_spacetime_lua_for, tem_spatial_for, posids, tem_temporal_for, tem_precice_read
tem_spacetime_vector_for_coord calls tem_spacetime_lua_for, tem_spatial_for, tem_abort, tem_temporal_for
tem_spacetime_vector_for_index calls tem_spacetime_vector_for_coord, ids, tem_spacetime_lua_for, tem_spatial_for, posids, tem_temporal_for, tem_precice_read
tem_spacetime_vector_for_treeids calls tem_spacetime_lua_for, tem_spatial_for, tem_abort, tem_temporal_for
evaluate_add_spacetime_scalarbycoordinate calls tem_spacetime_for
evaluate_add_spacetime_scalarbytreeid calls tem_spacetime_for
evaluate_add_spacetime_vectorbycoordinate calls tem_spacetime_for
evaluate_add_spacetime_vectorbytreeid calls tem_spacetime_for
evaluate_first_spacetime_scalarbycoordinate calls tem_spacetime_for
evaluate_first_spacetime_scalarbytreeid calls tem_spacetime_for
evaluate_first_spacetime_vectorbycoordinate calls tem_spacetime_for
evaluate_first_spacetime_vectorbytreeid calls tem_spacetime_for
evaluate_foag_spacetime_scalarbycoordinate calls tem_spacetime_for
evaluate_foag_spacetime_scalarbytreeid calls tem_spacetime_for
evaluate_foag_spacetime_vectorbycoordinate calls tem_spacetime_for
evaluate_foag_spacetime_vectorbytreeid calls tem_spacetime_for
get_valofindex_add_scalar_spacetime calls tem_spacetime_for
get_valofindex_add_vector_spacetime calls tem_spacetime_for
get_valofindex_first_scalar_spacetime calls tem_spacetime_for
get_valofindex_first_vector_spacetime calls tem_spacetime_for
get_valofindex_foag_scalar_spacetime calls tem_spacetime_for
get_valofindex_foag_vector_spacetime calls tem_spacetime_for
tem_update_surfpos calls tem_spacetime_for