truncate – Treelm
truncate Interface
3 statements
Source File
public interface truncate
truncate the array, meaning cut off the trailing empty entries
Calls
Called by
Module Procedures
public subroutine truncate_da_label(me)
truncate the array after the last valid entry and hence cut off the empty trailing empty entries
Arguments
Type Intent Optional Attributes Name
type(dyn_labelarray_type) :: me
Call graph
truncate calls truncate_da_label, truncate_possible_variable
tem_create_varmap calls truncate
truncate_possible_variable calls truncate
hvs_output_init calls tem_create_varmap
tem_init_convergence calls tem_create_varmap
tem_init_depend calls tem_create_varmap
tem_init_tracker calls tem_create_varmap, hvs_output_init
tem_opvar_reduction_transient_init calls tem_create_varmap