truncate – Treelm
truncate Interface
3 statements
Source File
public interface truncate
truncate the array, meaning cut off the trailing empty entries
Calls
Called by
Module Procedures
public subroutine truncate_ga_char(me)
Arguments
Type Intent Optional Attributes Name
type(grw_chararray_type) :: me
Call graph
truncate calls truncate_ga_char, truncate_grwpoints, truncate_intpmatrixlsf
destroy_intpmatrixlsf calls truncate
setup_indices_spacetime calls truncate, tem_spatial_storeval
tem_opvar_fill_inputindex calls truncate
tem_opvar_setupindices calls truncate, tem_opvar_fill_inputindex
tem_spatial_scalar_storeval calls truncate
tem_spatial_vector_storeval calls truncate
truncate_grwpoints calls truncate
truncate_intpmatrixlsf calls truncate
destroy calls destroy_intpmatrixlsf
tem_spatial_storeval calls tem_spatial_scalar_storeval, tem_spatial_vector_storeval